/**
 * Events & Hospitality Form Templates
 *
 * Templates for event registration, RSVPs, venue booking,
 * and hospitality services.
 */

import type { FormTemplate } from '../types';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  dateTimeField,
  numberField,
  currencyField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  addressField,
} from '../helpers';

export const eventsHospitalityTemplates: FormTemplate[] = [
  // 1. Wedding RSVP Form
  createTemplate({
    id: 'wedding-rsvp',
    name: 'Wedding RSVP Form',
    shortDescription: 'RSVP for wedding ceremonies',
    fullDescription: 'A beautiful wedding RSVP form for couples. Captures guest attendance, meal preferences, and plus-one information.',
    category: 'events-hospitality',
    icon: 'Heart',
    complexity: 'simple',
    estimatedTime: 3,
    isFeatured: true,
    displayOrder: 1,
    tags: ['wedding', 'rsvp', 'event', 'celebration'],
    useCases: [
      'Wedding invitations',
      'Engagement parties',
      'Anniversary celebrations',
      'Rehearsal dinners',
    ],
    features: [
      'Guest counting',
      'Meal selection',
      'Plus-one handling',
      'Song requests',
    ],
    fieldConfigs: [
      textField('guestName', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true }),
      selectField('attending', 'Will you be attending?', [
        'Joyfully Accepts',
        'Regretfully Declines',
      ], { required: true }),
      numberField('guestCount', 'Number of Guests in Your Party', {
        required: true,
        validation: { min: 1, max: 5 },
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      textareaField('guestNames', 'Names of All Guests Attending', {
        placeholder: 'Please list the names of everyone in your party',
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      sectionHeader('meals', 'Meal Preferences', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      selectField('meal1', 'Guest 1 Meal Choice', [
        'Beef',
        'Chicken',
        'Fish',
        'Vegetarian',
        'Vegan',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      selectField('meal2', 'Guest 2 Meal Choice', [
        'Beef',
        'Chicken',
        'Fish',
        'Vegetarian',
        'Vegan',
        'N/A - Only 1 Guest',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      textareaField('dietaryRestrictions', 'Dietary Restrictions or Allergies', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'attending', operator: 'equals', value: 'Joyfully Accepts' }],
        },
      }),
      textField('songRequest', 'Song Request for the DJ'),
      textareaField('message', 'A Message for the Happy Couple'),
    ],
  }),

  // 2. Hotel Reservation Request
  createTemplate({
    id: 'hotel-reservation',
    name: 'Hotel Reservation Request',
    shortDescription: 'Request a hotel room reservation',
    fullDescription: 'Hotel booking request form for capturing guest preferences, room types, and special requirements.',
    category: 'events-hospitality',
    icon: 'Building',
    complexity: 'moderate',
    estimatedTime: 5,
    displayOrder: 2,
    tags: ['hotel', 'reservation', 'booking', 'accommodation'],
    useCases: [
      'Hotel bookings',
      'Room reservations',
      'Group accommodations',
      'Corporate travel',
    ],
    features: [
      'Room type selection',
      'Date selection',
      'Special requests',
      'Guest information',
    ],
    fieldConfigs: [
      sectionHeader('guest', 'Guest Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      addressField('address', 'Billing Address'),
      sectionHeader('stay', 'Stay Details'),
      dateField('checkIn', 'Check-in Date', { required: true, fieldWidth: 'half' }),
      dateField('checkOut', 'Check-out Date', { required: true, fieldWidth: 'half' }),
      selectField('roomType', 'Room Type', [
        'Standard King',
        'Standard Double Queen',
        'Deluxe King',
        'Deluxe Double Queen',
        'Suite',
        'Executive Suite',
      ], { required: true }),
      numberField('numRooms', 'Number of Rooms', { required: true, validation: { min: 1 } }),
      numberField('adults', 'Number of Adults', { required: true, fieldWidth: 'half' }),
      numberField('children', 'Number of Children', { fieldWidth: 'half' }),
      sectionHeader('preferences', 'Room Preferences'),
      multiSelectField('bedPreference', 'Bed Preference', [
        'King Bed',
        'Two Queen Beds',
        'No Preference',
      ]),
      selectField('floorPreference', 'Floor Preference', [
        'Lower Floor',
        'Higher Floor',
        'No Preference',
      ]),
      multiSelectField('roomFeatures', 'Desired Features', [
        'City View',
        'Pool View',
        'Ocean View',
        'Balcony',
        'Quiet Location',
        'Near Elevator',
        'Accessible Room',
      ]),
      yesNoField('smoking', 'Smoking Room Required?'),
      sectionHeader('special', 'Special Requests'),
      textareaField('specialRequests', 'Special Requests or Notes', {
        placeholder: 'Anniversary, birthday, accessibility needs, etc.',
      }),
      textField('arrivalTime', 'Estimated Arrival Time'),
      yesNoField('airportTransfer', 'Need Airport Transfer?'),
      textField('flightInfo', 'Flight Information (if transfer needed)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'airportTransfer', operator: 'isTrue' }],
        },
      }),
      sectionHeader('purpose', 'Trip Purpose'),
      selectField('tripPurpose', 'Purpose of Trip', [
        'Leisure',
        'Business',
        'Group/Event',
        'Wedding Block',
        'Other',
      ]),
      textField('companyName', 'Company Name (for business)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'tripPurpose', operator: 'equals', value: 'Business' }],
        },
      }),
    ],
  }),

  // 3. Catering Request Form
  createTemplate({
    id: 'catering-request',
    name: 'Catering Request Form',
    shortDescription: 'Request catering services for events',
    fullDescription: 'Comprehensive catering request form for events. Captures event details, menu preferences, and dietary requirements.',
    category: 'events-hospitality',
    icon: 'UtensilsCrossed',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 3,
    tags: ['catering', 'food', 'event', 'menu'],
    useCases: [
      'Corporate events',
      'Wedding receptions',
      'Party catering',
      'Conference meals',
    ],
    features: [
      'Event details',
      'Menu selection',
      'Dietary accommodations',
      'Budget planning',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('contactName', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      textField('organization', 'Organization/Company'),
      sectionHeader('event', 'Event Details'),
      textField('eventName', 'Event Name', { required: true }),
      selectField('eventType', 'Type of Event', [
        'Corporate Meeting',
        'Conference',
        'Wedding Reception',
        'Birthday Party',
        'Anniversary',
        'Holiday Party',
        'Graduation',
        'Memorial/Funeral',
        'Other',
      ], { required: true }),
      dateField('eventDate', 'Event Date', { required: true }),
      textField('eventTime', 'Event Time (Start - End)', { required: true }),
      numberField('guestCount', 'Expected Guest Count', { required: true }),
      textField('venue', 'Event Venue/Location', { required: true }),
      addressField('venueAddress', 'Venue Address'),
      sectionHeader('service', 'Service Style'),
      selectField('serviceStyle', 'Service Style', [
        'Buffet',
        'Plated/Sit-down',
        'Family Style',
        'Cocktail/Passed Hors d\'oeuvres',
        'Food Stations',
        'Box Lunches',
        'Drop-off Only',
      ], { required: true }),
      multiSelectField('mealType', 'Meal Type (select all needed)', [
        'Breakfast',
        'Brunch',
        'Lunch',
        'Dinner',
        'Appetizers/Hors d\'oeuvres',
        'Dessert',
        'Snacks/Refreshments',
      ], { required: true }),
      sectionHeader('menu', 'Menu Preferences'),
      multiSelectField('cuisinePreference', 'Cuisine Preference', [
        'American',
        'Italian',
        'Mexican',
        'Asian',
        'Mediterranean',
        'BBQ',
        'Seafood',
        'Vegetarian Focus',
        'Open to Suggestions',
      ]),
      textareaField('menuIdeas', 'Specific Menu Ideas or Requests', {
        placeholder: 'Let us know if you have specific dishes in mind...',
      }),
      sectionHeader('dietary', 'Dietary Accommodations'),
      multiSelectField('dietaryNeeds', 'Dietary Needs to Accommodate', [
        'Vegetarian',
        'Vegan',
        'Gluten-Free',
        'Dairy-Free',
        'Nut-Free',
        'Kosher',
        'Halal',
        'Low-Sodium',
        'None/Not Sure Yet',
      ]),
      textareaField('allergyInfo', 'Specific Allergy Information'),
      sectionHeader('beverages', 'Beverage Services'),
      multiSelectField('beverages', 'Beverages Needed', [
        'Coffee/Tea Service',
        'Soft Drinks',
        'Juice/Lemonade',
        'Beer & Wine',
        'Full Bar',
        'Specialty Cocktails',
        'Non-Alcoholic Options',
        'None',
      ]),
      sectionHeader('budget', 'Budget'),
      currencyField('budget', 'Budget Range (total)', { required: true }),
      selectField('budgetFlexibility', 'Budget Flexibility', [
        'Firm budget - cannot exceed',
        'Flexible - can adjust for right menu',
        'Looking for guidance',
      ]),
      sectionHeader('additional', 'Additional Services'),
      multiSelectField('additionalServices', 'Additional Services Needed', [
        'Linens/Table Settings',
        'Floral Arrangements',
        'Service Staff',
        'Bartenders',
        'Cake/Dessert Table',
        'Rental Equipment',
        'Setup/Cleanup',
        'None',
      ]),
      textareaField('additionalNotes', 'Additional Notes or Questions'),
    ],
  }),

  // 4. Venue Booking Inquiry
  createTemplate({
    id: 'venue-booking',
    name: 'Venue Booking Inquiry',
    shortDescription: 'Inquire about venue availability',
    fullDescription: 'Venue inquiry form for event spaces. Captures event details and requirements to match with available spaces.',
    category: 'events-hospitality',
    icon: 'MapPin',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 4,
    tags: ['venue', 'booking', 'event space', 'rental'],
    useCases: [
      'Wedding venues',
      'Conference centers',
      'Party spaces',
      'Meeting rooms',
    ],
    features: [
      'Event requirements',
      'Capacity needs',
      'Date availability',
      'Setup preferences',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone', { required: true, fieldWidth: 'half' }),
      textField('organization', 'Organization (if applicable)'),
      sectionHeader('event', 'Event Information'),
      textField('eventName', 'Event Name', { required: true }),
      selectField('eventType', 'Type of Event', [
        'Wedding Ceremony',
        'Wedding Reception',
        'Corporate Meeting',
        'Conference/Seminar',
        'Birthday Party',
        'Anniversary',
        'Gala/Fundraiser',
        'Holiday Party',
        'Graduation',
        'Reunion',
        'Other',
      ], { required: true }),
      dateField('eventDate', 'Preferred Date', { required: true }),
      dateField('alternateDate', 'Alternate Date'),
      textField('startTime', 'Start Time', { required: true, fieldWidth: 'half' }),
      textField('endTime', 'End Time', { required: true, fieldWidth: 'half' }),
      yesNoField('needSetupTime', 'Need Early Access for Setup?'),
      sectionHeader('requirements', 'Space Requirements'),
      numberField('guestCount', 'Expected Guest Count', { required: true }),
      selectField('roomSetup', 'Preferred Room Setup', [
        'Banquet/Rounds',
        'Theater Style',
        'Classroom Style',
        'U-Shape',
        'Cocktail/Standing',
        'Combination',
        'Flexible',
      ]),
      multiSelectField('spaceFeatures', 'Space Features Needed', [
        'Stage/Podium',
        'Dance Floor',
        'Outdoor Space',
        'Private Entrance',
        'Natural Light',
        'High Ceilings',
        'Kitchen Access',
        'Projector/Screen',
        'Sound System',
        'WiFi',
        'Parking',
      ]),
      yesNoField('accessibilityNeeded', 'Accessibility Requirements?'),
      sectionHeader('services', 'Additional Services'),
      yesNoField('needCatering', 'Need Catering?'),
      selectField('cateringType', 'Catering Preference', [
        'In-house catering required',
        'Bring own caterer',
        'No preference',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'needCatering', operator: 'isTrue' }],
        },
      }),
      yesNoField('needAV', 'Need A/V Equipment?'),
      yesNoField('needDecorations', 'Need Decoration Services?'),
      yesNoField('alcoholServed', 'Will Alcohol Be Served?'),
      sectionHeader('budget', 'Budget'),
      currencyField('budget', 'Budget for Venue Rental'),
      textareaField('additionalInfo', 'Additional Information or Questions'),
    ],
  }),

  // 5. Table Reservation Form
  createTemplate({
    id: 'table-reservation',
    name: 'Table Reservation Form',
    shortDescription: 'Reserve a table at restaurant',
    fullDescription: 'Restaurant table reservation form. Captures party size, date/time preferences, and special occasions.',
    category: 'events-hospitality',
    icon: 'Utensils',
    complexity: 'simple',
    estimatedTime: 2,
    isFeatured: true,
    displayOrder: 5,
    tags: ['restaurant', 'reservation', 'dining', 'table'],
    useCases: [
      'Restaurant reservations',
      'Special dining occasions',
      'Group bookings',
      'Private dining',
    ],
    features: [
      'Party size',
      'Date/time selection',
      'Special occasions',
      'Seating preferences',
    ],
    fieldConfigs: [
      textField('name', 'Name for Reservation', { required: true }),
      emailField('email', 'Email', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      numberField('partySize', 'Party Size', { required: true, validation: { min: 1, max: 20 } }),
      dateField('reservationDate', 'Date', { required: true }),
      selectField('reservationTime', 'Preferred Time', [
        '5:00 PM',
        '5:30 PM',
        '6:00 PM',
        '6:30 PM',
        '7:00 PM',
        '7:30 PM',
        '8:00 PM',
        '8:30 PM',
        '9:00 PM',
        '9:30 PM',
      ], { required: true }),
      selectField('occasion', 'Special Occasion?', [
        'None',
        'Birthday',
        'Anniversary',
        'Date Night',
        'Business Dinner',
        'Celebration',
        'Other',
      ]),
      selectField('seatingPreference', 'Seating Preference', [
        'No Preference',
        'Indoor',
        'Outdoor/Patio',
        'Bar Area',
        'Private Room',
        'Window Seat',
        'Booth',
      ]),
      textareaField('specialRequests', 'Special Requests or Dietary Notes', {
        placeholder: 'Allergies, accessibility needs, high chair needed, etc.',
      }),
      yesNoField('confirmationMethod', 'Confirm via text message?'),
    ],
  }),

  // 6. Event Feedback Form
  createTemplate({
    id: 'event-feedback',
    name: 'Event Feedback Form',
    shortDescription: 'Collect feedback after events',
    fullDescription: 'Post-event feedback form to gather attendee opinions. Helps improve future events and measure satisfaction.',
    category: 'events-hospitality',
    icon: 'MessageSquare',
    complexity: 'simple',
    estimatedTime: 5,
    displayOrder: 6,
    tags: ['feedback', 'survey', 'event', 'review'],
    useCases: [
      'Conference feedback',
      'Workshop evaluations',
      'Party feedback',
      'Venue reviews',
    ],
    features: [
      'Event ratings',
      'Speaker feedback',
      'Venue assessment',
      'Suggestions',
    ],
    fieldConfigs: [
      sectionHeader('event', 'Event Information'),
      textField('eventName', 'Event Attended'),
      dateField('eventDate', 'Event Date'),
      sectionHeader('overall', 'Overall Experience'),
      selectField('overallRating', 'Overall Rating', [
        '5 - Excellent',
        '4 - Very Good',
        '3 - Good',
        '2 - Fair',
        '1 - Poor',
      ], { required: true }),
      selectField('meetExpectations', 'Did the event meet your expectations?', [
        'Exceeded expectations',
        'Met expectations',
        'Partially met expectations',
        'Did not meet expectations',
      ], { required: true }),
      selectField('attendAgain', 'Would you attend this event again?', [
        'Definitely yes',
        'Probably yes',
        'Maybe',
        'Probably not',
        'Definitely not',
      ], { required: true }),
      selectField('recommendEvent', 'Would you recommend this event to others?', [
        'Definitely yes',
        'Probably yes',
        'Maybe',
        'Probably not',
        'Definitely not',
      ], { required: true }),
      sectionHeader('details', 'Detailed Feedback'),
      selectField('contentRating', 'Content/Programming Quality', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      selectField('speakerRating', 'Speakers/Presenters', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      selectField('venueRating', 'Venue/Location', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      selectField('foodRating', 'Food & Beverages', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      selectField('organizationRating', 'Organization/Logistics', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      selectField('valueRating', 'Value for Money/Time', [
        'Excellent', 'Good', 'Average', 'Below Average', 'Poor', 'N/A',
      ]),
      sectionHeader('feedback', 'Open Feedback'),
      textareaField('bestPart', 'What did you enjoy most about the event?'),
      textareaField('improvements', 'What could be improved?'),
      textareaField('futureSuggestions', 'Topics or activities you\'d like to see at future events?'),
      textareaField('additionalComments', 'Any other comments?'),
      sectionHeader('follow', 'Stay Connected'),
      yesNoField('futureEvents', 'Would you like to be notified about future events?'),
      emailField('email', 'Email Address (optional)', { required: false }),
    ],
  }),

  // 7. Tour Booking Form
  createTemplate({
    id: 'tour-booking',
    name: 'Tour Booking Form',
    shortDescription: 'Book tours and experiences',
    fullDescription: 'Tour booking form for travel companies and attractions. Captures participant information, tour preferences, and special requirements.',
    category: 'events-hospitality',
    icon: 'Map',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 7,
    tags: ['tour', 'booking', 'travel', 'experience'],
    useCases: [
      'City tours',
      'Guided experiences',
      'Attractions bookings',
      'Activity reservations',
    ],
    features: [
      'Tour selection',
      'Participant details',
      'Special requirements',
      'Pickup arrangements',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Lead Guest Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone', { required: true, fieldWidth: 'half' }),
      textField('country', 'Country of Residence'),
      sectionHeader('tour', 'Tour Selection'),
      selectField('tourName', 'Select Tour', [
        'City Highlights Tour - 3 hours',
        'Historical Walking Tour - 2 hours',
        'Food & Culture Tour - 4 hours',
        'Adventure Tour - Full Day',
        'Night Tour - 3 hours',
        'Private Custom Tour',
      ], { required: true }),
      dateField('tourDate', 'Preferred Date', { required: true }),
      selectField('tourTime', 'Preferred Start Time', [
        '9:00 AM',
        '10:00 AM',
        '11:00 AM',
        '1:00 PM',
        '2:00 PM',
        '3:00 PM',
        '5:00 PM',
        '6:00 PM',
      ], { required: true }),
      selectField('language', 'Preferred Language', [
        'English',
        'Spanish',
        'French',
        'German',
        'Chinese',
        'Japanese',
      ]),
      sectionHeader('participants', 'Participants'),
      numberField('adults', 'Number of Adults', { required: true, validation: { min: 1 } }),
      numberField('children', 'Number of Children (under 12)'),
      numberField('seniors', 'Number of Seniors (65+)'),
      textareaField('participantNames', 'Names of All Participants'),
      sectionHeader('requirements', 'Special Requirements'),
      textareaField('dietaryRestrictions', 'Dietary Restrictions (for food tours)'),
      yesNoField('mobilityIssues', 'Any mobility concerns?'),
      textareaField('mobilityDetails', 'Please describe mobility needs', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'mobilityIssues', operator: 'isTrue' }],
        },
      }),
      textareaField('specialRequests', 'Other Special Requests'),
      sectionHeader('pickup', 'Pickup Information'),
      selectField('pickupOption', 'Pickup Option', [
        'Hotel pickup (included)',
        'Meeting point',
        'No pickup needed',
      ]),
      textField('hotelName', 'Hotel Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'pickupOption', operator: 'equals', value: 'Hotel pickup (included)' }],
        },
      }),
      textField('hotelAddress', 'Hotel Address', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'pickupOption', operator: 'equals', value: 'Hotel pickup (included)' }],
        },
      }),
    ],
  }),
];
