/**
 * Nonprofit & Community Form Templates
 *
 * Templates for donations, volunteer applications, grant requests,
 * and community engagement.
 */

import type { FormTemplate } from '../types';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  addressField,
  fileField,
} from '../helpers';

export const nonprofitCommunityTemplates: FormTemplate[] = [
  // 1. Donation Form
  createTemplate({
    id: 'donation-form',
    name: 'Donation Form',
    shortDescription: 'Accept charitable donations',
    fullDescription: 'A donation form for nonprofits and charities. Captures donor information, gift amount, and designation preferences. Includes recurring donation options.',
    category: 'nonprofit-community',
    icon: 'Heart',
    complexity: 'moderate',
    estimatedTime: 4,
    isFeatured: true,
    displayOrder: 1,
    tags: ['donation', 'charity', 'nonprofit', 'giving', 'fundraising'],
    useCases: [
      'Online donations',
      'Fundraising campaigns',
      'Annual giving',
      'Memorial gifts',
    ],
    features: [
      'Flexible gift amounts',
      'Recurring donations',
      'Fund designation',
      'Tribute gifts',
    ],
    fieldConfigs: [
      sectionHeader('gift', 'Your Gift'),
      selectField('donationType', 'Donation Type', [
        'One-time Gift',
        'Monthly Recurring',
        'Quarterly Recurring',
        'Annual Recurring',
      ], { required: true }),
      selectField('amount', 'Gift Amount', [
        { value: '25', label: '$25' },
        { value: '50', label: '$50' },
        { value: '100', label: '$100' },
        { value: '250', label: '$250' },
        { value: '500', label: '$500' },
        { value: '1000', label: '$1,000' },
        { value: 'other', label: 'Other Amount' },
      ], { required: true }),
      currencyField('customAmount', 'Enter Amount', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'amount', operator: 'equals', value: 'other' }],
        },
      }),
      selectField('designation', 'Designate My Gift To', [
        'Where Most Needed',
        'Program Support',
        'Education Programs',
        'Community Outreach',
        'Emergency Fund',
        'Capital Campaign',
        'Scholarship Fund',
        'Other',
      ]),
      textField('otherDesignation', 'Specify Other Designation', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'designation', operator: 'equals', value: 'Other' }],
        },
      }),
      sectionHeader('donor', 'Donor Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number'),
      addressField('address', 'Billing Address', { required: true }),
      sectionHeader('tribute', 'Tribute Gift (Optional)'),
      yesNoField('isTribute', 'Is this a tribute gift?'),
      selectField('tributeType', 'Tribute Type', [
        'In Honor Of',
        'In Memory Of',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isTribute', operator: 'isTrue' }],
        },
      }),
      textField('tributeName', 'Honoree/Memorial Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isTribute', operator: 'isTrue' }],
        },
      }),
      yesNoField('notifyTribute', 'Send notification to family?', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isTribute', operator: 'isTrue' }],
        },
      }),
      textField('notifyName', 'Notification Recipient Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [
            { field: 'isTribute', operator: 'isTrue' },
            { field: 'notifyTribute', operator: 'isTrue' },
          ],
        },
      }),
      addressField('notifyAddress', 'Notification Recipient Address', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [
            { field: 'isTribute', operator: 'isTrue' },
            { field: 'notifyTribute', operator: 'isTrue' },
          ],
        },
      }),
      sectionHeader('matching', 'Employer Matching'),
      yesNoField('employerMatch', 'Does your employer match donations?'),
      textField('employerName', 'Employer Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'employerMatch', operator: 'isTrue' }],
        },
      }),
      sectionHeader('preferences', 'Communication Preferences'),
      yesNoField('anonymousDonation', 'Make my donation anonymous'),
      yesNoField('receiveUpdates', 'I\'d like to receive updates about impact'),
      textareaField('comments', 'Comments or Special Instructions'),
    ],
    enhanced: {
      headline: 'Turn Website Visitors into Lifelong Donors',
      subheadline: 'Capture donations with tribute options, recurring giving, and employer matching—building donor relationships that last beyond the first gift.',
      longDescription: {
        opening: 'Most nonprofit websites lose 90% of potential donors at the donation page. Generic payment forms with no context. Clunky interfaces that fail on mobile. No options for tribute gifts or recurring donations. When someone is moved to give, friction kills the moment. And when they do give, you capture a transaction—not a relationship. One-time donors stay one-time donors because you never learned what motivated them.',
        solution: 'This template creates a complete donation experience: flexible gift amounts with suggested levels, recurring options (monthly, quarterly, annual), fund designation so donors direct their impact, tribute gifts for memorials and honors with family notification, employer matching capture to double gifts, anonymous giving options, and communication preferences. Conditional logic shows relevant fields based on donor choices.',
        outcome: 'Increase online donation completion rates by 40%. Convert 25% of one-time donors to recurring givers with easy monthly options. Capture 60% more employer matching gifts. Build donor profiles that inform cultivation. Tribute gift notifications create new donor connections. Transform transactions into relationships that yield lifetime giving.',
      },
      useCases: [
        {
          title: 'Annual Fund Drive',
          icon: '📅',
          industry: 'Nonprofit',
          scenario: 'Your organization runs a $500K annual fund campaign. Direct mail response rates are declining. Online giving is growing but conversion rates lag behind industry benchmarks. Donors who give once rarely give again.',
          painPoint: 'Generic donation form captures no donor preferences. Recurring giving not prominently featured. No employer matching capture. Tribute gift process is separate and manual.',
          keyFields: ['Donation Type', 'Gift Amount', 'Does your employer match donations?', 'Is this a tribute gift?'],
          exampleOrganization: 'A nonprofit with $500K annual fund goal, achieving only 15% donor retention rate versus 45% industry average.',
        },
        {
          title: 'Memorial Gift Program',
          icon: '🕊️',
          industry: 'Nonprofit',
          scenario: 'Families often want to direct funeral donations to your cause. But your current process requires phone calls to set up memorial pages, and notification to families is manual. Meaningful gift moments are lost to friction.',
          painPoint: 'Memorial gifts handled manually. Family notification delayed or forgotten. No tracking of tribute gift relationships. Memorial pages require staff setup.',
          keyFields: ['Tribute Type', 'Honoree/Memorial Name', 'Send notification to family?', 'Notification Recipient Address'],
          exampleOrganization: 'A healthcare nonprofit receiving 200+ memorial gifts annually with no automated tribute program.',
        },
        {
          title: 'Sustainer Program Growth',
          icon: '💳',
          industry: 'Nonprofit',
          scenario: 'Your monthly giving program has 200 sustainers but growth has plateaued. The signup process is buried and complex. Donors don\'t understand the value of monthly giving, and the option isn\'t visible during standard donations.',
          painPoint: 'Recurring options not prominent in donation flow. Monthly giving benefits not communicated. Upgrade path from one-time to recurring unclear. Sustainer retention declining.',
          keyFields: ['Donation Type', 'Gift Amount', 'Designate My Gift To', 'I\'d like to receive updates about impact'],
          exampleOrganization: 'A nonprofit with 200 monthly sustainers seeking to grow to 500 within 18 months.',
        },
        {
          title: 'Corporate Matching Campaigns',
          icon: '🏢',
          industry: 'Nonprofit',
          scenario: 'Millions in matching gift dollars go unclaimed because donors don\'t know their employer matches or the process is complicated. Your donation form doesn\'t capture employer information, leaving money on the table.',
          painPoint: 'Employer matching capture inconsistent. No follow-up on matching gift claims. Can\'t identify donors with matching-eligible employers. Missing millions in potential revenue.',
          keyFields: ['Does your employer match donations?', 'Employer Name', 'Gift Amount'],
          exampleOrganization: 'A nonprofit estimating $100K in unclaimed matching gifts based on donor employer data.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Impact Statements',
          description: 'Show donors what their gift accomplishes at each level: "$25 provides meals for a family for a week." Increases average gift size by 20%.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Matching Gift Integration',
          description: 'Integrate with Double the Donation or 360MatchPro to auto-detect employer matching programs and streamline submission.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Add Fund-Specific Campaigns',
          description: 'Create designated funds with progress thermometers for capital campaigns, emergency appeals, or program-specific giving.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Include Stock Gift Option',
          description: 'For major donors, add appreciated stock transfer instructions. Stock gifts provide tax advantages and typically are larger than cash gifts.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Add Giving Levels with Benefits',
          description: 'Create named giving societies with specific benefits at each level. Recognition motivates increased giving.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'instant-receipt',
          title: 'Send Tax Receipt Immediately',
          description: 'Automatically email IRS-compliant donation receipt with organization EIN, gift amount, date, and any goods/services provided (usually none for straight donations).',
          trigger: 'On form submission',
          benefits: ['Donors have immediate tax documentation', 'Reduces receipt request inquiries', 'Professional donor experience'],
        },
        {
          workflowType: 'tribute-notification',
          title: 'Send Tribute Notifications',
          description: 'For tribute gifts with notification requested, automatically mail or email the family with a beautiful card noting the gift (not amount) in honor/memory of their loved one.',
          trigger: 'On tribute gift submission with notification = yes',
          benefits: ['Families notified promptly', 'Creates new donor touchpoint', 'Professional tribute program'],
        },
        {
          workflowType: 'recurring-welcome',
          title: 'Welcome New Sustainers',
          description: 'For new recurring donors, send special welcome series explaining the impact of their monthly commitment, introducing them to the sustainer community.',
          trigger: 'On recurring donation signup',
          benefits: ['Sustainer retention improved', 'Donors feel valued', 'Reduced recurring cancellation'],
        },
        {
          workflowType: 'donor-crm-sync',
          title: 'Update Donor Record',
          description: 'Automatically update CRM with donation details, preferences, tribute relationships, and employer matching potential. Create new donor records as needed.',
          trigger: 'On form submission',
          benefits: ['Complete donor history in CRM', 'No manual data entry', 'Cultivation data captured'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Amount field supports both preset options and custom entry for flexibility',
          'Conditional logic shows tribute and matching fields only when relevant',
          'Recurring type field enables automated billing schedule setup',
        ],
        integrationHints: [
          'Payment processor (Stripe, PayPal Giving Fund) for transaction handling',
          'Donor CRM (Bloomerang, Little Green Light, Salesforce NPSP) for donor management',
          'Matching gift service (Double the Donation) for employer matching capture',
        ],
        mongoDBConsiderations: [
          'Index on {email: 1} for donor lookup and deduplication',
          'Index on {donationType: 1, createdAt: -1} for recurring vs. one-time reporting',
          'Index on {designation: 1} for fund-specific reporting',
          'Store tribute relationships as embedded documents for notification tracking',
        ],
      },
      seo: {
        metaTitle: 'Donation Form Template | NetPad',
        metaDescription: 'Free nonprofit donation form with recurring giving, tribute gifts, and employer matching. Increase online giving and donor retention.',
        keywords: ['donation form', 'nonprofit donation', 'online giving form', 'recurring donation', 'tribute gift form'],
        ogDescription: 'Convert more donors with a donation form that captures recurring gifts, tributes, and employer matching. Build donor relationships, not just transactions.',
      },
      socialProofAngles: [
        'Higher donation completion rates',
        'Increased recurring giving',
        'More employer matching captured',
        'Better donor retention',
      ],
    },
  }),

  // 2. Volunteer Application Form
  createTemplate({
    id: 'volunteer-application',
    name: 'Volunteer Application Form',
    shortDescription: 'Apply to volunteer with organization',
    fullDescription: 'Recruit and screen volunteers with this comprehensive application. Captures skills, availability, and background information for proper placement.',
    category: 'nonprofit-community',
    icon: 'Users',
    complexity: 'moderate',
    estimatedTime: 10,
    isFeatured: true,
    displayOrder: 2,
    tags: ['volunteer', 'application', 'nonprofit', 'community service'],
    useCases: [
      'Volunteer recruitment',
      'Community service',
      'Event volunteers',
      'Ongoing programs',
    ],
    features: [
      'Skills and interests',
      'Availability scheduling',
      'Reference collection',
      'Background check consent',
    ],
    fieldConfigs: [
      sectionHeader('personal', 'Personal Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number', { required: true }),
      addressField('address', 'Address', { required: true }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('age', 'Age Group', [
        'Under 18 (requires parental consent)',
        '18-25',
        '26-35',
        '36-50',
        '51-65',
        '65+',
      ]),
      sectionHeader('emergency', 'Emergency Contact'),
      textField('emergencyName', 'Emergency Contact Name', { required: true }),
      phoneField('emergencyPhone', 'Emergency Contact Phone', { required: true }),
      textField('emergencyRelation', 'Relationship', { required: true }),
      sectionHeader('interests', 'Volunteer Interests'),
      multiSelectField('interestAreas', 'Areas of Interest (select all that apply)', [
        'Event Support',
        'Administrative/Office',
        'Fundraising',
        'Marketing/Social Media',
        'Education/Tutoring',
        'Mentoring',
        'Direct Service',
        'Building/Maintenance',
        'Food Services',
        'Transportation',
        'Tech Support',
        'Board/Committee',
      ], { required: true }),
      textareaField('whyVolunteer', 'Why do you want to volunteer with us?', {
        required: true,
        validation: { minLength: 50 },
      }),
      sectionHeader('skills', 'Skills & Experience'),
      textareaField('relevantSkills', 'Relevant Skills', {
        placeholder: 'List any skills that might be helpful (languages, certifications, professional skills)...',
      }),
      yesNoField('previousVolunteer', 'Have you volunteered with us before?'),
      textareaField('otherVolunteerExp', 'Other Volunteer Experience'),
      textField('occupation', 'Current Occupation'),
      sectionHeader('availability', 'Availability'),
      selectField('commitmentType', 'Type of Commitment', [
        'Ongoing/Regular',
        'One-time/Event-based',
        'Seasonal',
        'Flexible/As needed',
      ], { required: true }),
      multiSelectField('availableDays', 'Days Available', [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ], { required: true }),
      multiSelectField('availableTimes', 'Times Available', [
        'Morning (8am-12pm)',
        'Afternoon (12pm-5pm)',
        'Evening (5pm-9pm)',
      ]),
      numberField('hoursPerWeek', 'Hours Available Per Week'),
      dateField('availableStart', 'Available to Start'),
      sectionHeader('references', 'References'),
      textField('reference1Name', 'Reference 1 Name', { required: true, fieldWidth: 'half' }),
      phoneField('reference1Phone', 'Reference 1 Phone', { required: true, fieldWidth: 'half' }),
      textField('reference1Relation', 'Reference 1 Relationship', { fieldWidth: 'half' }),
      textField('reference2Name', 'Reference 2 Name', { fieldWidth: 'half' }),
      phoneField('reference2Phone', 'Reference 2 Phone', { fieldWidth: 'half' }),
      textField('reference2Relation', 'Reference 2 Relationship', { fieldWidth: 'half' }),
      sectionHeader('background', 'Background Check'),
      yesNoField('consentBackground', 'I consent to a background check if required', { required: true }),
      yesNoField('felonyHistory', 'Have you been convicted of a felony?'),
      textareaField('felonyExplanation', 'If yes, please explain', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'felonyHistory', operator: 'isTrue' }],
        },
      }),
      sectionHeader('agreement', 'Agreement'),
      yesNoField('agreeTerms', 'I agree to follow organizational policies and procedures', { required: true }),
      yesNoField('agreePhoto', 'I consent to photos/videos being taken during volunteer activities'),
    ],
    enhanced: {
      headline: 'Match Volunteers with Roles They\'ll Love',
      subheadline: 'Screen and place volunteers based on skills, availability, and interests—reducing no-shows and building a committed volunteer corps.',
      longDescription: {
        opening: 'Volunteer programs struggle with the same problems: people sign up but never show. Volunteers are placed in roles that don\'t match their skills. Background checks take weeks because applications are incomplete. Enthusiastic new volunteers wait so long for placement that they lose interest. Meanwhile, critical roles go unfilled while you have volunteers sitting idle. Poor volunteer experiences lead to one-and-done participation instead of long-term commitment.',
        solution: 'This template captures comprehensive volunteer applications: personal and emergency contact information, areas of interest from a curated list, motivation for volunteering, relevant skills and experience, commitment type preferences, detailed availability by day and time, hours per week, references for screening, background check consent with disclosure questions, and policy agreements including photo consent.',
        outcome: 'Place volunteers in roles within days, not weeks. Match skills to opportunities automatically—marketing professionals to communications, teachers to tutoring, retirees to daytime programs. Background check processing accelerated with complete applications. Track volunteer hours and impact. Build a volunteer database that powers rapid event staffing. Increase volunteer retention from 30% to 65% through better matching.',
      },
      useCases: [
        {
          title: 'Hospital Volunteer Services',
          icon: '🏥',
          industry: 'Healthcare',
          scenario: 'Your hospital has 15 volunteer roles from gift shop to patient escort. Applications arrive on paper and sit in a pile. Background checks take 3 weeks because information is incomplete. New volunteers wait so long they volunteer elsewhere.',
          painPoint: 'Paper applications create processing backlog. Background checks delayed by incomplete information. No systematic matching of volunteers to roles. Volunteer onboarding takes too long.',
          keyFields: ['Areas of Interest (select all that apply)', 'Type of Commitment', 'Days Available', 'I consent to a background check if required'],
          exampleOrganization: 'A 400-bed hospital with 200 volunteer positions, experiencing 50% dropout during the 6-week onboarding process.',
        },
        {
          title: 'Youth Mentoring Program',
          icon: '👥',
          industry: 'Nonprofit',
          scenario: 'Your mentoring program matches adults with at-risk youth. Safety screening is critical—background checks, references, and training are required. Incomplete applications delay mentor placement while youth wait for matches.',
          painPoint: 'Safety screening documentation incomplete. Reference contact information missing. Availability doesn\'t match youth schedules. Background check consent missing.',
          keyFields: ['Have you been convicted of a felony?', 'Reference 1 Name', 'Reference 1 Phone', 'Hours Available Per Week'],
          exampleOrganization: 'A youth mentoring nonprofit with 50+ mentors, taking 8+ weeks to onboard new mentors due to screening delays.',
        },
        {
          title: 'Food Bank Operations',
          icon: '🥫',
          industry: 'Nonprofit',
          scenario: 'Your food bank needs volunteers for warehouse sorting, mobile pantry, and client services. Weekend slots fill instantly while weekday shifts go empty. You can\'t easily find volunteers with forklift certification or bilingual skills.',
          painPoint: 'Availability doesn\'t match operational needs. Special skills not captured or searchable. Can\'t fill last-minute shift openings. Volunteer skills underutilized.',
          keyFields: ['Days Available', 'Times Available', 'Relevant Skills', 'Available to Start'],
          exampleOrganization: 'A regional food bank distributing 10M pounds annually, with 40% of weekday volunteer shifts unfilled.',
        },
        {
          title: 'Event Volunteer Coordination',
          icon: '🎪',
          industry: 'Events',
          scenario: 'Your organization runs 20+ events annually requiring 50-200 volunteers each. Event volunteer recruitment is chaotic—mass emails, spreadsheets, and last-minute scrambles. You don\'t know volunteer skills or preferences.',
          painPoint: 'No volunteer database for event staffing. Can\'t target recruitment to volunteer interests. Volunteer skills unknown for role matching. No-show rates high.',
          keyFields: ['Areas of Interest (select all that apply)', 'Days Available', 'Why do you want to volunteer with us?', 'Have you volunteered with us before?'],
          exampleOrganization: 'An event-focused nonprofit with 25% volunteer no-show rate due to poor matching and communication.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Role-Specific Questions',
          description: 'Use conditional logic to show additional questions based on interest area selection—driving record for transportation, food handler certification for kitchen.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Include Skills Assessment',
          description: 'Add specific skill level ratings (beginner/intermediate/expert) for relevant competencies: languages, software, certifications.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Minor Volunteer Path',
          description: 'For volunteers under 18, automatically add parental consent form requirement and restrict available roles.',
          fieldSuggestion: 'file',
          difficulty: 'medium',
        },
        {
          title: 'Add Interview Scheduling',
          description: 'For roles requiring interviews, include calendar integration to let applicants select interview time slots.',
          fieldSuggestion: 'date',
          difficulty: 'advanced',
        },
        {
          title: 'Include Corporate Volunteer Tracking',
          description: 'Add employer field and corporate volunteer program identification for companies with volunteer hours requirements.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'application-acknowledgment',
          title: 'Confirm Application Receipt',
          description: 'Immediately email applicant confirming receipt with expected timeline, next steps, and information about your organization\'s mission.',
          trigger: 'On form submission',
          benefits: ['Applicant knows status', 'Sets expectations', 'Professional first impression'],
        },
        {
          workflowType: 'background-check-initiation',
          title: 'Initiate Background Check',
          description: 'For applications with consent, automatically send background check request to screening provider with applicant information.',
          trigger: 'On submission with background consent = yes',
          benefits: ['Faster screening turnaround', 'No manual data transfer', 'Consistent screening process'],
        },
        {
          workflowType: 'coordinator-notification',
          title: 'Alert Program Coordinators',
          description: 'Notify volunteer coordinators of new applications matching their program areas. Include applicant skills, availability, and interest areas.',
          trigger: 'On form submission based on interest areas',
          benefits: ['Right coordinators see relevant applicants', 'Faster outreach to good matches', 'Distributed volunteer management'],
        },
        {
          workflowType: 'reference-requests',
          title: 'Send Reference Requests',
          description: 'Automatically email references with simple form to provide feedback on applicant. Include deadline and volunteer role context.',
          trigger: 'On form submission',
          benefits: ['Reference collection automated', 'Faster screening completion', 'Consistent reference questions'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Multi-select fields for interests and availability enable sophisticated matching queries',
          'Reference fields structured for automated outreach',
          'Conditional felony explanation shown only when needed for sensitive handling',
        ],
        integrationHints: [
          'Background check providers (Sterling, Checkr) for screening automation',
          'Volunteer management systems (VolunteerHub, Galaxy Digital) for placement tracking',
          'Calendar integration for interview and orientation scheduling',
        ],
        mongoDBConsiderations: [
          'Index on {interestAreas: 1} for program-based volunteer queries',
          'Index on {availableDays: 1, availableTimes: 1} for shift matching',
          'Index on {createdAt: -1} for application queue processing',
          'Text index on relevantSkills and whyVolunteer for keyword search',
        ],
      },
      seo: {
        metaTitle: 'Volunteer Application Form Template | NetPad',
        metaDescription: 'Free volunteer application template with skills matching, availability capture, and background check consent. Build a committed volunteer program.',
        keywords: ['volunteer application form', 'volunteer signup', 'volunteer recruitment', 'volunteer management', 'nonprofit volunteers'],
        ogDescription: 'Stop losing volunteers to slow onboarding. This application captures skills, availability, and consent for faster placement and better matching.',
      },
      socialProofAngles: [
        'Faster volunteer onboarding',
        'Better volunteer-role matching',
        'Higher volunteer retention',
        'Reduced no-show rates',
      ],
    },
  }),

  // 3. Grant Application Form
  createTemplate({
    id: 'grant-application',
    name: 'Grant Application Form',
    shortDescription: 'Apply for grant funding',
    fullDescription: 'Comprehensive grant application form for organizations seeking funding. Captures project details, budgets, and organizational information.',
    category: 'nonprofit-community',
    icon: 'Award',
    complexity: 'advanced',
    estimatedTime: 30,
    displayOrder: 3,
    tags: ['grant', 'funding', 'application', 'nonprofit'],
    useCases: [
      'Foundation grants',
      'Government funding',
      'Corporate grants',
      'Community funds',
    ],
    features: [
      'Organization profile',
      'Project narrative',
      'Budget breakdown',
      'Outcomes/metrics',
    ],
    fieldConfigs: [
      sectionHeader('org', 'Organization Information'),
      textField('orgName', 'Organization Name', { required: true }),
      textField('ein', 'EIN/Tax ID Number', { required: true }),
      addressField('orgAddress', 'Organization Address', { required: true }),
      textField('website', 'Website'),
      textField('execDirector', 'Executive Director Name', { required: true }),
      emailField('execEmail', 'Executive Director Email', { required: true }),
      phoneField('orgPhone', 'Organization Phone', { required: true }),
      selectField('orgType', 'Organization Type', [
        '501(c)(3) Public Charity',
        '501(c)(3) Private Foundation',
        'Government Entity',
        'Religious Organization',
        'Educational Institution',
        'Fiscal Sponsor Arrangement',
      ], { required: true }),
      numberField('yearFounded', 'Year Founded'),
      numberField('annualBudget', 'Annual Operating Budget'),
      numberField('fullTimeStaff', 'Number of Full-time Staff'),
      sectionHeader('contact', 'Grant Contact'),
      textField('contactName', 'Contact Name', { required: true }),
      textField('contactTitle', 'Contact Title', { required: true }),
      emailField('contactEmail', 'Contact Email', { required: true }),
      phoneField('contactPhone', 'Contact Phone', { required: true }),
      sectionHeader('project', 'Project Information'),
      textField('projectTitle', 'Project Title', { required: true }),
      selectField('grantType', 'Type of Support Requested', [
        'Program/Project Support',
        'General Operating Support',
        'Capital Campaign',
        'Capacity Building',
        'Research',
        'Scholarship',
      ], { required: true }),
      currencyField('amountRequested', 'Amount Requested', { required: true }),
      dateField('projectStart', 'Project Start Date', { required: true }),
      dateField('projectEnd', 'Project End Date', { required: true }),
      sectionHeader('narrative', 'Project Narrative'),
      textareaField('orgMission', 'Organization Mission Statement', {
        required: true,
        validation: { maxLength: 500 },
      }),
      textareaField('orgHistory', 'Brief Organization History', {
        required: true,
        validation: { maxLength: 1000 },
      }),
      textareaField('problemStatement', 'Problem/Need Statement', {
        required: true,
        placeholder: 'Describe the problem or need your project addresses...',
        validation: { minLength: 200 },
      }),
      textareaField('projectDescription', 'Project Description', {
        required: true,
        placeholder: 'Describe your project, including goals, activities, and timeline...',
        validation: { minLength: 500 },
      }),
      textareaField('targetPopulation', 'Target Population', {
        required: true,
        placeholder: 'Who will benefit from this project?',
      }),
      numberField('beneficiariesNumber', 'Estimated Number of Beneficiaries'),
      sectionHeader('outcomes', 'Outcomes & Evaluation'),
      textareaField('outcomes', 'Expected Outcomes', {
        required: true,
        placeholder: 'What changes do you expect to see as a result of this project?',
      }),
      textareaField('metrics', 'How Will Success Be Measured?', {
        required: true,
        placeholder: 'Describe the metrics and methods you\'ll use to evaluate success...',
      }),
      sectionHeader('budget', 'Budget'),
      textareaField('budgetNarrative', 'Budget Narrative', {
        required: true,
        placeholder: 'Explain how funds will be used...',
      }),
      fileField('budgetDocument', 'Detailed Budget (upload)', {
        required: true,
        validation: { allowedTypes: ['application/pdf', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] },
      }),
      yesNoField('otherFunding', 'Have you applied for or received other funding for this project?'),
      textareaField('otherFundingSources', 'Other Funding Sources', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'otherFunding', operator: 'isTrue' }],
        },
      }),
      sectionHeader('documents', 'Required Documents'),
      fileField('financialStatements', 'Financial Statements'),
      fileField('annualReport', 'Annual Report'),
      fileField('boardList', 'Board of Directors List'),
      fileField('irsLetter', '501(c)(3) Determination Letter', { required: true }),
      fileField('additionalDocs', 'Additional Supporting Documents', {
        validation: { multiple: true, maxFiles: 5 },
      }),
      sectionHeader('certification', 'Certification'),
      yesNoField('certifyAccurate', 'I certify that the information provided is accurate', { required: true }),
      yesNoField('authorizedSigner', 'I am authorized to submit this application on behalf of the organization', { required: true }),
      textField('signerName', 'Name of Authorized Signer', { required: true }),
      textField('signerTitle', 'Title', { required: true }),
      dateField('signatureDate', 'Date', { required: true }),
    ],
    enhanced: {
      headline: 'Review Complete Grant Applications, Not Fragments',
      subheadline: 'Collect comprehensive grant proposals with budgets, outcomes, and documentation—structured data that enables fair evaluation and faster decisions.',
      longDescription: {
        opening: 'Grant review is painful when applications arrive incomplete. Proposals missing budgets. Organizations without 501(c)(3) documentation. Outcome metrics vague or absent. Reviewers spend hours chasing missing information instead of evaluating proposals. Applicants resubmit multiple times, delaying decisions and frustrating everyone. When you finally have complete applications, comparing them is difficult because each one uses different formats.',
        solution: 'This template captures complete grant applications: organization profile with EIN and 501(c)(3) status, executive leadership and contact information, organization type and history, dedicated grant contact, comprehensive project details with support type and timeline, narrative sections for mission, history, problem statement, project description, and target population with beneficiary estimates, outcome and evaluation methodology, budget narrative with document upload, other funding sources, required documents (financials, annual report, board list, determination letter), and authorized signer certification.',
        outcome: 'Review complete applications, not fragments. Standardized format enables fair comparison across proposals. Required fields ensure nothing is missing. Document uploads collected in one place. Track applications through review pipeline. Reduce review cycle time by 50% with complete submissions. Make better funding decisions with structured, comparable data.',
      },
      useCases: [
        {
          title: 'Community Foundation',
          icon: '🏛️',
          industry: 'Philanthropy',
          scenario: 'Your foundation reviews 200+ grant applications annually across 10 funding areas. Paper applications arrive in different formats, making comparison difficult. Reviewers spend more time organizing materials than evaluating proposals.',
          painPoint: 'Applications arrive in inconsistent formats. Missing documents require follow-up. Can\'t easily compare proposals across applicants. Review process takes months.',
          keyFields: ['Type of Support Requested', 'Amount Requested', 'Budget Narrative', '501(c)(3) Determination Letter'],
          exampleOrganization: 'A community foundation awarding $2M annually across 200+ applications, with 4-month average review cycle.',
        },
        {
          title: 'Corporate Giving Program',
          icon: '🏢',
          industry: 'Corporate',
          scenario: 'Your company funds $500K in community grants annually. Employee volunteers review applications, but they\'re not grant professionals. Inconsistent applications make evaluation difficult and time-consuming for volunteer reviewers.',
          painPoint: 'Volunteer reviewers overwhelmed by inconsistent formats. Can\'t determine organization legitimacy quickly. Budget information insufficient for due diligence. Review takes excessive volunteer time.',
          keyFields: ['EIN/Tax ID Number', 'Organization Type', 'Annual Operating Budget', 'Detailed Budget (upload)'],
          exampleOrganization: 'A corporate foundation with employee-volunteer review committees, spending 200+ hours annually on application processing.',
        },
        {
          title: 'Government Grant Administration',
          icon: '🏛️',
          industry: 'Government',
          scenario: 'Your agency administers federal pass-through grants to community organizations. Compliance requirements are strict—incomplete applications create audit risk. Tracking outcomes across grantees requires standardized reporting.',
          painPoint: 'Compliance documentation incomplete. Outcome metrics not captured consistently. Audit trail difficult to reconstruct. Grantee reporting formats vary.',
          keyFields: ['Expected Outcomes', 'How Will Success Be Measured?', 'Estimated Number of Beneficiaries', 'I certify that the information provided is accurate'],
          exampleOrganization: 'A county government administering $5M in community development grants with federal compliance requirements.',
        },
        {
          title: 'Private Family Foundation',
          icon: '👨‍👩‍👧‍👦',
          industry: 'Philanthropy',
          scenario: 'Your family foundation awards grants in focus areas aligned with family values. Board meetings occur quarterly, and applications must be complete before the meeting packet is assembled. Incomplete applications miss funding cycles.',
          painPoint: 'Incomplete applications delay board review. Mission alignment difficult to assess from varying formats. Family members lack time to chase missing information. Good proposals miss funding deadlines.',
          keyFields: ['Organization Mission Statement', 'Problem/Need Statement', 'Project Description', 'Target Population'],
          exampleOrganization: 'A family foundation with quarterly grant cycles, where 30% of applications are deferred due to incomplete documentation.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Funding Priority Alignment',
          description: 'Include questions asking applicants to indicate which of your funding priorities their project addresses. Enables filtering by strategic focus.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Multi-Stage Review',
          description: 'Create Letter of Inquiry (LOI) as shorter first stage, then full application for invited applicants. Reduces applicant and reviewer burden.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
        {
          title: 'Add Budget Template Upload',
          description: 'Provide downloadable budget template that standardizes financial presentation. Ensures all applicants provide comparable budget information.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Include Logic Model Section',
          description: 'Add inputs/activities/outputs/outcomes framework for sophisticated funders requiring theory of change documentation.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
        {
          title: 'Enable Reviewer Scoring',
          description: 'Add internal scoring rubric that reviewers complete alongside applications. Structured scoring enables fair comparison.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'submission-acknowledgment',
          title: 'Confirm Application Receipt',
          description: 'Immediately email applicant confirming receipt with application ID, review timeline, and next steps. Include contact for questions.',
          trigger: 'On form submission',
          benefits: ['Applicants know submission succeeded', 'Sets timeline expectations', 'Professional funder communication'],
        },
        {
          workflowType: 'completeness-validation',
          title: 'Check Application Completeness',
          description: 'Automatically validate that all required fields are populated and documents uploaded. Flag incomplete applications for follow-up.',
          trigger: 'On form submission',
          benefits: ['Catch incomplete applications immediately', 'Automated follow-up for missing items', 'Complete applications for reviewers'],
        },
        {
          workflowType: 'reviewer-assignment',
          title: 'Route to Reviewers',
          description: 'Based on funding category and amount requested, automatically assign applications to appropriate reviewers. Notify reviewers of new applications.',
          trigger: 'On complete application submission',
          benefits: ['Right reviewers see relevant applications', 'Workload distribution automated', 'Faster review initiation'],
        },
        {
          workflowType: 'eligibility-screening',
          title: 'Verify 501(c)(3) Status',
          description: 'Automatically check IRS database for organization 501(c)(3) status using EIN provided. Flag applications from organizations without valid status.',
          trigger: 'On form submission',
          benefits: ['Eligibility verified automatically', 'Ineligible applications flagged immediately', 'Due diligence streamlined'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Organization type enum enables filtering by eligibility criteria',
          'Amount requested as currency field for budget range filtering',
          'File uploads for required documents enable complete digital dossier',
        ],
        integrationHints: [
          'Grant management systems (Fluxx, Submittable, Foundant) for pipeline tracking',
          'IRS Tax Exempt Organization Search API for 501(c)(3) verification',
          'Document storage (AWS S3, Azure Blob) for secure file management',
        ],
        mongoDBConsiderations: [
          'Index on {orgType: 1, grantType: 1} for eligibility filtering',
          'Index on {amountRequested: 1} for funding range queries',
          'Index on {projectStart: 1, projectEnd: 1} for timeline-based review',
          'Full-text index on narrative fields for keyword search across proposals',
        ],
      },
      seo: {
        metaTitle: 'Grant Application Form Template | NetPad',
        metaDescription: 'Free grant application template for foundations. Collect complete proposals with budgets, outcomes, and documentation for faster review.',
        keywords: ['grant application form', 'grant proposal template', 'foundation grant form', 'nonprofit grant application', 'funding application'],
        ogDescription: 'Review complete grant applications, not fragments. This template captures everything reviewers need for fair, efficient funding decisions.',
      },
      socialProofAngles: [
        'Faster grant review cycles',
        'Complete applications on first submission',
        'Fair proposal comparison',
        'Streamlined due diligence',
      ],
    },
  }),

  // 4. Membership Application Form
  createTemplate({
    id: 'membership-application',
    name: 'Membership Application Form',
    shortDescription: 'Join as a member',
    fullDescription: 'Member registration form for nonprofit organizations, associations, and community groups. Captures member information and membership preferences.',
    category: 'nonprofit-community',
    icon: 'UserPlus',
    complexity: 'simple',
    estimatedTime: 5,
    displayOrder: 4,
    tags: ['membership', 'join', 'member', 'registration'],
    useCases: [
      'Association memberships',
      'Club registrations',
      'Community groups',
      'Professional organizations',
    ],
    features: [
      'Membership level selection',
      'Auto-renewal options',
      'Interest areas',
      'Committee preferences',
    ],
    fieldConfigs: [
      sectionHeader('member', 'Member Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number'),
      addressField('address', 'Mailing Address', { required: true }),
      textField('organization', 'Organization/Company (if applicable)'),
      textField('title', 'Title/Position'),
      sectionHeader('membership', 'Membership Selection'),
      selectField('membershipLevel', 'Membership Level', [
        'Student - $25/year',
        'Individual - $50/year',
        'Family - $75/year',
        'Professional - $100/year',
        'Sponsor - $250/year',
        'Benefactor - $500/year',
        'Lifetime - $1,000',
      ], { required: true }),
      selectField('membershipTerm', 'Membership Term', [
        '1 Year',
        '2 Years',
        '3 Years',
      ], { required: true }),
      yesNoField('autoRenew', 'Enable auto-renewal'),
      sectionHeader('involvement', 'Get Involved'),
      multiSelectField('interestAreas', 'Areas of Interest', [
        'Events & Programs',
        'Advocacy',
        'Education',
        'Networking',
        'Volunteering',
        'Leadership Opportunities',
        'Committee Work',
      ]),
      multiSelectField('committees', 'Committee Interest', [
        'Events Committee',
        'Membership Committee',
        'Communications Committee',
        'Advocacy Committee',
        'Finance Committee',
        'Board of Directors',
        'None at this time',
      ]),
      sectionHeader('communication', 'Communication Preferences'),
      multiSelectField('communicationPrefs', 'I\'d like to receive', [
        'Monthly Newsletter',
        'Event Invitations',
        'Advocacy Alerts',
        'Member Updates',
        'Partner Offers',
      ]),
      selectField('preferredContact', 'Preferred Contact Method', [
        'Email',
        'Phone',
        'Mail',
      ]),
      sectionHeader('referral', 'How Did You Hear About Us?'),
      selectField('referralSource', 'Referral Source', [
        'Friend/Colleague',
        'Search Engine',
        'Social Media',
        'Event',
        'News/Media',
        'Other Organization',
        'Other',
      ]),
      textField('referredBy', 'Referred By (name if applicable)'),
      textareaField('whyJoining', 'Why are you interested in joining?'),
    ],
    enhanced: {
      headline: 'Grow Membership with Frictionless Signup',
      subheadline: 'Convert interested visitors into engaged members—capturing preferences and interests that power personalized communication and committee recruitment.',
      longDescription: {
        opening: 'Membership organizations struggle with the same funnel problem: plenty of interest, but sign-ups stall at the application. Paper forms create barriers. Online forms ask for payment but capture nothing about member interests. New members receive generic welcome emails, then hear nothing relevant for months. Engagement drops before it starts. Meanwhile, committees need volunteers but have no way to identify interested members.',
        solution: 'This template captures complete membership applications: personal and contact information, organization affiliation and title, membership level selection with pricing, term length with auto-renewal option, areas of interest for targeted communication, committee preferences for volunteer recruitment, communication preferences for respectful outreach, referral source for marketing attribution, and motivation for joining to inform engagement strategy.',
        outcome: 'Convert 40% more membership inquiries with streamlined signup. Segment new members by interest area for relevant communication. Recruit committee volunteers from members who expressed interest. Track referral sources to optimize recruitment marketing. Auto-renewal reduces membership lapse. Build member profiles that inform engagement and increase renewal rates by 25%.',
      },
      useCases: [
        {
          title: 'Professional Association',
          icon: '👔',
          industry: 'Associations',
          scenario: 'Your professional association has 5,000 members across multiple tiers. Paper applications and manual processing create a 2-week lag from interest to activation. New members miss the first month of benefits. Can\'t identify members interested in leadership.',
          painPoint: 'Slow application processing delays membership activation. Interest areas not captured for personalized content. Committee recruitment relies on broadcast emails. No attribution for recruitment efforts.',
          keyFields: ['Membership Level', 'Areas of Interest', 'Committee Interest', 'Referral Source'],
          exampleOrganization: 'A professional association with 5,000 members experiencing 30% first-year attrition due to poor onboarding.',
        },
        {
          title: 'Community Organization',
          icon: '🏘️',
          industry: 'Nonprofit',
          scenario: 'Your neighborhood association recruits members through events and word-of-mouth. Paper signup sheets capture names but no contact information. New members receive nothing until the next newsletter. Engaged members slip away.',
          painPoint: 'Paper signups capture incomplete information. No follow-up process for new members. Can\'t track which events drive membership. No way to identify engaged members for leadership.',
          keyFields: ['Email Address', 'Communication Preferences', 'Why are you interested in joining?', 'Referred By (name if applicable)'],
          exampleOrganization: 'A neighborhood association with 40% membership turnover due to poor communication and engagement tracking.',
        },
        {
          title: 'Alumni Association',
          icon: '🎓',
          industry: 'Education',
          scenario: 'Your alumni association wants to grow membership and engagement. Recent graduates don\'t see value in membership. Current members don\'t know about volunteer opportunities. Membership data is siloed from the advancement office.',
          painPoint: 'Value proposition unclear to prospective members. Volunteer opportunities not matched to member interests. No integration with alumni database. Young alumni engagement very low.',
          keyFields: ['Membership Level', 'Membership Term', 'Areas of Interest', 'I\'d like to receive'],
          exampleOrganization: 'A university alumni association with 15% participation rate among alumni under 35.',
        },
        {
          title: 'Trade Association',
          icon: '🏭',
          industry: 'Associations',
          scenario: 'Your trade association represents 200+ companies with tiered membership. Applications require company information and multiple contact people. Paper applications delay board approval and benefit activation.',
          painPoint: 'Company membership requires multiple contacts. Board approval delayed by incomplete applications. Can\'t track which companies are interested in advocacy versus networking. Benefit activation takes weeks.',
          keyFields: ['Organization/Company (if applicable)', 'Title/Position', 'Membership Level', 'Enable auto-renewal'],
          exampleOrganization: 'A trade association with 200+ company members, taking 3 weeks from application to activation.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Membership Benefits Display',
          description: 'Show benefit comparison table when member selects level. Helps members understand value and may encourage upgrades.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Employer Billing',
          description: 'For professional associations, allow members to request employer invoice instead of personal payment.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Add Chapter/Region Selection',
          description: 'For organizations with local chapters, capture geographic preference for local event invitations and networking.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Skills/Expertise Profile',
          description: 'Capture professional skills and expertise areas to power member directory and speaker bureau.',
          fieldSuggestion: 'multiselect',
          difficulty: 'medium',
        },
        {
          title: 'Enable Family Membership',
          description: 'For family membership tiers, capture additional household member names and emails for benefits access.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'welcome-series',
          title: 'Send Welcome Sequence',
          description: 'Immediately start personalized welcome email series: benefits overview, getting started guide, upcoming events matching interests, and introduction to staff.',
          trigger: 'On form submission',
          benefits: ['New members engaged immediately', 'Benefits explained clearly', 'Relevant content from day one'],
        },
        {
          workflowType: 'committee-notification',
          title: 'Alert Committee Chairs',
          description: 'When new member expresses committee interest, automatically notify relevant committee chair with member contact info and background.',
          trigger: 'On submission with committee interest selected',
          benefits: ['Volunteer recruitment automated', 'Committee chairs notified of prospects', 'Members engaged in leadership quickly'],
        },
        {
          workflowType: 'ams-sync',
          title: 'Create Member Record',
          description: 'Automatically create member record in association management system with all application data, preferences, and payment status.',
          trigger: 'On form submission',
          benefits: ['No manual data entry', 'Member record complete from start', 'Benefits access enabled immediately'],
        },
        {
          workflowType: 'renewal-reminder',
          title: 'Schedule Renewal Reminders',
          description: 'For non-auto-renew members, schedule renewal reminders at 60, 30, and 7 days before expiration. Include renewal link and benefits summary.',
          trigger: 'On membership activation',
          benefits: ['Proactive renewal reminders', 'Easy online renewal', 'Reduced membership lapse'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Membership level field includes pricing for automated payment calculation',
          'Multi-select for interests and committees enables sophisticated member segmentation',
          'Auto-renew boolean supports automated billing setup',
        ],
        integrationHints: [
          'Association management systems (MemberClicks, Wild Apricot, YourMembership) for member records',
          'Payment processor with recurring billing (Stripe, PayPal) for auto-renewal',
          'Email marketing (Mailchimp, Constant Contact) for interest-based segmentation',
        ],
        mongoDBConsiderations: [
          'Index on {membershipLevel: 1} for tier-based reporting',
          'Index on {interestAreas: 1} for targeted communication queries',
          'Index on {committees: 1} for volunteer recruitment',
          'Index on {referralSource: 1} for marketing attribution analysis',
        ],
      },
      seo: {
        metaTitle: 'Membership Application Form Template | NetPad',
        metaDescription: 'Free membership application template for associations. Capture member preferences and interests for personalized engagement and higher retention.',
        keywords: ['membership application form', 'member signup', 'association membership', 'member registration', 'nonprofit membership'],
        ogDescription: 'Convert more members with frictionless signup. Capture interests and preferences that power personalized communication and committee recruitment.',
      },
      socialProofAngles: [
        'Higher membership conversion',
        'Better member engagement',
        'Easier committee recruitment',
        'Improved renewal rates',
      ],
    },
  }),

  // 5. Community Event Proposal
  createTemplate({
    id: 'community-event-proposal',
    name: 'Community Event Proposal',
    shortDescription: 'Propose a community event',
    fullDescription: 'Submit proposals for community events. Captures event details, logistics, and resource needs for planning and approval.',
    category: 'nonprofit-community',
    icon: 'Calendar',
    complexity: 'moderate',
    estimatedTime: 12,
    displayOrder: 5,
    tags: ['event', 'proposal', 'community', 'planning'],
    useCases: [
      'Community events',
      'Fundraisers',
      'Awareness campaigns',
      'Educational programs',
    ],
    features: [
      'Event overview',
      'Budget planning',
      'Resource needs',
      'Marketing plan',
    ],
    fieldConfigs: [
      sectionHeader('proposer', 'Proposer Information'),
      textField('proposerName', 'Your Name', { required: true }),
      emailField('proposerEmail', 'Email', { required: true }),
      phoneField('proposerPhone', 'Phone', { required: true }),
      textField('organization', 'Organization (if applicable)'),
      sectionHeader('event', 'Event Overview'),
      textField('eventName', 'Event Name', { required: true }),
      selectField('eventType', 'Type of Event', [
        'Fundraiser/Gala',
        'Community Festival',
        'Educational Workshop',
        'Awareness Campaign',
        'Volunteer Day',
        'Sports/Recreation',
        'Arts/Cultural',
        'Health/Wellness',
        'Other',
      ], { required: true }),
      textareaField('eventDescription', 'Event Description', {
        required: true,
        placeholder: 'Describe the event, its purpose, and what attendees will experience...',
        validation: { minLength: 100 },
      }),
      textareaField('eventGoals', 'Event Goals', {
        required: true,
        placeholder: 'What do you hope to achieve with this event?',
      }),
      sectionHeader('logistics', 'Event Logistics'),
      dateField('proposedDate', 'Proposed Date', { required: true }),
      textField('proposedTime', 'Proposed Time'),
      textField('proposedLocation', 'Proposed Location', { required: true }),
      numberField('expectedAttendance', 'Expected Attendance', { required: true }),
      selectField('targetAudience', 'Target Audience', [
        'General Public',
        'Families',
        'Youth/Students',
        'Seniors',
        'Professionals',
        'Members Only',
        'Specific Community',
      ], { required: true }),
      yesNoField('outdoorEvent', 'Is this an outdoor event?'),
      textareaField('backupPlan', 'Weather/Backup Plan (for outdoor events)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'outdoorEvent', operator: 'isTrue' }],
        },
      }),
      sectionHeader('budget', 'Budget & Resources'),
      currencyField('estimatedBudget', 'Estimated Total Budget', { required: true }),
      currencyField('fundingRequested', 'Funding Requested from Organization'),
      textareaField('budgetBreakdown', 'Budget Breakdown', {
        required: true,
        placeholder: 'Provide a breakdown of expected expenses...',
      }),
      textareaField('fundingSource', 'Other Funding Sources', {
        placeholder: 'List sponsors, ticket sales, other funding...',
      }),
      sectionHeader('support', 'Support Needed'),
      multiSelectField('resourcesNeeded', 'Resources Needed from Organization', [
        'Venue/Space',
        'Staff Support',
        'Volunteer Coordination',
        'Marketing/Promotion',
        'Event Supplies',
        'Audio/Visual Equipment',
        'Insurance/Permits',
        'Catering',
        'None - Just Approval',
      ]),
      numberField('volunteersNeeded', 'Estimated Volunteers Needed'),
      textareaField('specialRequests', 'Special Requests or Considerations'),
      sectionHeader('marketing', 'Marketing & Promotion'),
      textareaField('marketingPlan', 'Marketing Plan', {
        placeholder: 'How will you promote this event?',
      }),
      multiSelectField('promotionChannels', 'Promotion Channels', [
        'Social Media',
        'Email Newsletter',
        'Website',
        'Flyers/Posters',
        'Local Media',
        'Partner Organizations',
        'Word of Mouth',
      ]),
    ],
    enhanced: {
      headline: 'Approve Events with Confidence, Not Chaos',
      subheadline: 'Collect complete event proposals with budgets, logistics, and resource needs—giving decision-makers everything they need to approve or improve.',
      longDescription: {
        opening: 'Community event proposals arrive as vague emails: "I want to do a fundraiser." No dates, no budget, no logistics. Staff spend hours in meetings extracting basic information. Proposals get approved without clear resource commitments, then fail during execution. Events that seemed simple become budget overruns. Meanwhile, great ideas get lost because proposers don\'t know what information you need.',
        solution: 'This template captures comprehensive event proposals: proposer contact information and organizational affiliation, complete event overview with type classification, detailed description and goals, logistics (date, time, location, expected attendance, target audience, outdoor/weather considerations), budget and resource planning with funding breakdown and support needed, volunteer requirements, and marketing plan with promotion channels.',
        outcome: 'Evaluate complete proposals, not fragments. Compare events objectively with standardized budget and attendance data. Make approval decisions with full understanding of resource requirements. Track events from proposal through execution. Reduce event failures by 70% with thorough upfront planning. Enable community members to propose events without back-and-forth.',
      },
      useCases: [
        {
          title: 'Parks and Recreation Department',
          icon: '🌳',
          industry: 'Government',
          scenario: 'Your parks department receives 50+ event permit requests annually. Proposals range from neighborhood picnics to 5,000-person festivals. Email requests lack standard information. Staff can\'t assess impact or resource needs consistently.',
          painPoint: 'No standard proposal format. Resource impact unclear until too late. Can\'t compare events for scheduling conflicts. Insurance and permit requirements discovered late.',
          keyFields: ['Expected Attendance', 'Proposed Location', 'Is this an outdoor event?', 'Resources Needed from Organization'],
          exampleOrganization: 'A city parks department processing 50+ event permits annually with no standardized proposal process.',
        },
        {
          title: 'Nonprofit Program Development',
          icon: '🏛️',
          industry: 'Nonprofit',
          scenario: 'Your nonprofit empowers staff and volunteers to propose community events. Great ideas come from the field, but proposals lack business case. Board can\'t evaluate without budget and outcome projections.',
          painPoint: 'Staff ideas not captured systematically. Budget implications unclear. No ROI tracking for events. Board decisions based on incomplete information.',
          keyFields: ['Event Goals', 'Estimated Total Budget', 'Funding Requested from Organization', 'Budget Breakdown'],
          exampleOrganization: 'A community nonprofit where 40% of approved events exceed budget due to inadequate planning.',
        },
        {
          title: 'University Student Activities',
          icon: '🎓',
          industry: 'Education',
          scenario: 'Your student activities office reviews 200+ event proposals per semester from student organizations. Paper forms and emails create processing backlog. Events get approved without clear risk assessment.',
          painPoint: 'High volume overwhelms manual processing. Risk factors (alcohol, outdoor, large crowd) not systematically captured. Resource conflicts discovered at event time. No post-event outcome tracking.',
          keyFields: ['Type of Event', 'Expected Attendance', 'Target Audience', 'Estimated Volunteers Needed'],
          exampleOrganization: 'A university reviewing 200+ student event proposals per semester with 2-week average approval time.',
        },
        {
          title: 'Community Foundation Events',
          icon: '❤️',
          industry: 'Nonprofit',
          scenario: 'Your foundation hosts and sponsors community events. Proposals come from partner organizations wanting co-sponsorship or venue access. No standard way to evaluate alignment with mission or resource availability.',
          painPoint: 'Mission alignment hard to assess. Resource commitments accumulate without visibility. Staff support requests overlap. Marketing coordination manual.',
          keyFields: ['Event Description', 'Other Funding Sources', 'Marketing Plan', 'Special Requests or Considerations'],
          exampleOrganization: 'A community foundation receiving 30+ event partnership requests annually with no systematic evaluation process.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Risk Assessment Questions',
          description: 'Include questions about alcohol service, physical activities, large crowds, and other risk factors for insurance and safety planning.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Enable Venue Selection',
          description: 'Show available venues with capacity limits based on proposed date. Prevent double-booking and capacity issues.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
        {
          title: 'Add Success Metrics Section',
          description: 'Require proposers to define measurable outcomes: attendance targets, funds raised, participants served. Enables post-event evaluation.',
          fieldSuggestion: 'textarea',
          difficulty: 'easy',
        },
        {
          title: 'Include Sponsor Recognition',
          description: 'For events seeking organizational sponsorship, capture what recognition/benefits the organization will receive.',
          fieldSuggestion: 'textarea',
          difficulty: 'easy',
        },
        {
          title: 'Enable Multi-Stage Approval',
          description: 'For large events, route proposals through multiple approvers (program director, finance, executive) with status tracking.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'proposal-acknowledgment',
          title: 'Confirm Proposal Receipt',
          description: 'Immediately email proposer confirming receipt with proposal ID, review timeline, and contact for questions.',
          trigger: 'On form submission',
          benefits: ['Proposer knows submission succeeded', 'Sets timeline expectations', 'Professional communication'],
        },
        {
          workflowType: 'review-routing',
          title: 'Route to Reviewers',
          description: 'Based on event type, budget size, and resource requests, automatically route proposal to appropriate reviewers. Large events get executive review.',
          trigger: 'On form submission based on event parameters',
          benefits: ['Right reviewers see relevant proposals', 'Large events get appropriate scrutiny', 'Faster review initiation'],
        },
        {
          workflowType: 'resource-check',
          title: 'Check Resource Availability',
          description: 'Automatically check venue availability and staff calendars for proposed date. Flag conflicts before approval.',
          trigger: 'On form submission',
          benefits: ['Conflicts identified immediately', 'No double-booking', 'Resource planning automated'],
        },
        {
          workflowType: 'approval-notification',
          title: 'Send Approval Decision',
          description: 'When proposal is approved or denied, automatically notify proposer with decision, conditions, and next steps for approved events.',
          trigger: 'On approval status change',
          benefits: ['Fast decision communication', 'Clear next steps for approved events', 'Professional process'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Event type classification enables category-specific routing and reporting',
          'Multi-select for resources enables capacity planning across events',
          'Budget fields support ROI tracking when paired with actual spend',
        ],
        integrationHints: [
          'Calendar/venue management for availability checking',
          'Project management (Asana, Monday) for event execution tracking',
          'Finance system for budget tracking and expense reconciliation',
        ],
        mongoDBConsiderations: [
          'Index on {proposedDate: 1} for calendar conflict checking',
          'Index on {eventType: 1} for category-based reporting',
          'Index on {estimatedBudget: 1} for approval routing by size',
          'Compound index on {proposedLocation: 1, proposedDate: 1} for venue conflicts',
        ],
      },
      seo: {
        metaTitle: 'Community Event Proposal Form Template | NetPad',
        metaDescription: 'Free event proposal template for organizations. Collect complete proposals with budgets and logistics for confident approval decisions.',
        keywords: ['event proposal form', 'community event form', 'event request form', 'event planning form', 'event approval'],
        ogDescription: 'Stop approving events without full information. This proposal form captures everything decision-makers need for confident event approval.',
      },
      socialProofAngles: [
        'Faster event approvals',
        'Better resource planning',
        'Reduced event failures',
        'Complete proposal information',
      ],
    },
  }),

  // 6. Fundraising Pledge Form
  createTemplate({
    id: 'fundraising-pledge',
    name: 'Fundraising Pledge Form',
    shortDescription: 'Make a pledge to donate',
    fullDescription: 'Capture pledges for fundraising campaigns. Donors commit to future donations with flexible payment scheduling.',
    category: 'nonprofit-community',
    icon: 'HandHeart',
    complexity: 'simple',
    estimatedTime: 3,
    displayOrder: 6,
    tags: ['pledge', 'fundraising', 'donation', 'campaign'],
    useCases: [
      'Capital campaigns',
      'Annual fund drives',
      'Matching gift campaigns',
      'Planned giving',
    ],
    features: [
      'Pledge amount',
      'Payment schedule',
      'Recognition preferences',
      'Tribute options',
    ],
    fieldConfigs: [
      sectionHeader('donor', 'Donor Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number', { required: true }),
      addressField('address', 'Address', { required: true }),
      sectionHeader('pledge', 'Pledge Details'),
      textField('campaignName', 'Campaign (if specific)'),
      currencyField('totalPledge', 'Total Pledge Amount', { required: true }),
      selectField('paymentSchedule', 'Payment Schedule', [
        'One-time payment',
        'Monthly installments',
        'Quarterly installments',
        'Annual installments',
        'Custom schedule',
      ], { required: true }),
      numberField('numPayments', 'Number of Payments', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'paymentSchedule', operator: 'equals', value: 'Monthly installments' },
            { field: 'paymentSchedule', operator: 'equals', value: 'Quarterly installments' },
            { field: 'paymentSchedule', operator: 'equals', value: 'Annual installments' },
          ],
        },
      }),
      dateField('firstPaymentDate', 'First Payment Date', { required: true }),
      selectField('paymentMethod', 'Preferred Payment Method', [
        'Credit Card',
        'Bank Transfer/ACH',
        'Check',
        'Stock Transfer',
        'IRA Distribution',
        'To Be Determined',
      ], { required: true }),
      sectionHeader('recognition', 'Recognition'),
      yesNoField('allowRecognition', 'May we recognize your gift publicly?'),
      selectField('recognitionName', 'Recognition Name', [
        'Use my name as provided',
        'Anonymous',
        'Use different name',
      ]),
      textField('alternateRecognition', 'Alternate Recognition Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'recognitionName', operator: 'equals', value: 'Use different name' }],
        },
      }),
      sectionHeader('tribute', 'Tribute (Optional)'),
      yesNoField('isTribute', 'Is this a tribute gift?'),
      selectField('tributeType', 'Tribute Type', ['In Honor Of', 'In Memory Of'], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isTribute', operator: 'isTrue' }],
        },
      }),
      textField('tributeeName', 'Honoree Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isTribute', operator: 'isTrue' }],
        },
      }),
      sectionHeader('commitment', 'Commitment'),
      yesNoField('acknowledgePledge', 'I acknowledge this is a pledge commitment', { required: true }),
      textareaField('comments', 'Comments or Special Instructions'),
    ],
    enhanced: {
      headline: 'Secure Commitments That Convert to Cash',
      subheadline: 'Capture multi-year pledges with flexible payment schedules—structured data that powers reminder workflows and pledge fulfillment tracking.',
      longDescription: {
        opening: 'Capital campaigns and major gift fundraising depend on pledges—commitments to future giving. But pledge management is often chaotic. Paper pledge cards with illegible handwriting. Spreadsheets tracking payment schedules that no one updates. Donors forget they pledged, then feel ambushed by reminder calls. Anonymous pledges go unfulfilled because no one follows up. Campaigns report pledged amounts that never materialize as cash.',
        solution: 'This template captures structured pledge commitments: complete donor contact information, campaign designation if applicable, total pledge amount with payment schedule selection, number of payments for installments, first payment date, payment method preference, recognition preferences with alternate naming, tribute gift options, and formal acknowledgment of pledge commitment.',
        outcome: 'Convert 85% of pledges to cash versus 70% industry average. Automated payment reminders at scheduled intervals. Flexible schedules (monthly, quarterly, annual, custom) match donor preferences. Recognition preferences documented upfront. Anonymous pledges tracked internally. Dashboard visibility into pledge pipeline and fulfillment rates. Transform campaign pledges into actual revenue.',
      },
      useCases: [
        {
          title: 'Capital Campaign',
          icon: '🏗️',
          industry: 'Nonprofit',
          scenario: 'Your $10M capital campaign accepts multi-year pledges from major donors. Paper pledge cards create tracking nightmares. Board members want real-time pipeline reports. Some pledged donors have never been invoiced.',
          painPoint: 'Paper pledges hard to track and report. Payment schedules not systematically recorded. No automated reminders to donors. Pledge fulfillment rates below target.',
          keyFields: ['Total Pledge Amount', 'Payment Schedule', 'First Payment Date', 'Preferred Payment Method'],
          exampleOrganization: 'A nonprofit in a $10M capital campaign with 65% pledge fulfillment rate versus 85% target.',
        },
        {
          title: 'Annual Fund Leadership Giving',
          icon: '⭐',
          industry: 'Nonprofit',
          scenario: 'Your annual fund cultivates leadership gifts ($1,000+) with pledge options. Donors want to spread gifts across the year. Current process doesn\'t accommodate flexible payment schedules, losing major gift commitments.',
          painPoint: 'Can\'t accommodate flexible payment schedules. Large gift prospects deterred by lump-sum requirement. No tracking of pledge versus payment. Major gift pipeline unclear.',
          keyFields: ['Total Pledge Amount', 'Payment Schedule', 'Number of Payments', 'Campaign (if specific)'],
          exampleOrganization: 'An annual fund with $100K in leadership giving, losing potential gifts due to inflexible payment options.',
        },
        {
          title: 'Endowment Building',
          icon: '🏛️',
          industry: 'Education',
          scenario: 'Your university raises endowment gifts through planned giving and multi-year pledges. Donors commit to 5-year payment schedules. Tracking legacy pledges alongside immediate gifts is complex.',
          painPoint: 'Multi-year pledge tracking complex. Donor intent documentation insufficient. Payment schedules span staff transitions. Recognition preferences lost over time.',
          keyFields: ['Payment Schedule', 'First Payment Date', 'May we recognize your gift publicly?', 'Recognition Name'],
          exampleOrganization: 'A university endowment with $50M in outstanding pledges and no centralized tracking system.',
        },
        {
          title: 'Gala Event Giving',
          icon: '🎉',
          industry: 'Nonprofit',
          scenario: 'Your annual gala generates $500K in pledges through paddle raises and sponsorships. Event night excitement leads to generous commitments. Post-event follow-up is chaotic, and pledge fulfillment disappoints.',
          painPoint: 'Event pledges captured inconsistently. Post-event follow-up delayed. Can\'t match pledge cards to donor records. Fulfillment tracking manual.',
          keyFields: ['Total Pledge Amount', 'Preferred Payment Method', 'I acknowledge this is a pledge commitment', 'Comments or Special Instructions'],
          exampleOrganization: 'A nonprofit gala raising $500K in pledges annually with 60% same-night fulfillment.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Pledge Motivation',
          description: 'Include question asking why donor is making this commitment. Informs stewardship and helps cultivation of similar prospects.',
          fieldSuggestion: 'textarea',
          difficulty: 'easy',
        },
        {
          title: 'Enable Stock/IRA Gifts',
          description: 'Add options for appreciated stock transfer and IRA charitable rollover, which often yield larger gifts than cash.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Include Legacy Gift Intent',
          description: 'Capture whether donor has included organization in estate plans. Opens planned giving conversation.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Add Matching Gift Eligibility',
          description: 'Capture employer information to identify matching gift opportunities that could double pledge value.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Enable Digital Signature',
          description: 'Add digital signature field for formal pledge documentation. Creates legally binding commitment record.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'pledge-acknowledgment',
          title: 'Send Pledge Confirmation',
          description: 'Immediately email donor confirming pledge details: total amount, payment schedule, recognition preferences, and first payment due date.',
          trigger: 'On form submission',
          benefits: ['Donor has written confirmation', 'Payment expectations clear', 'Professional acknowledgment'],
        },
        {
          workflowType: 'payment-reminders',
          title: 'Schedule Payment Reminders',
          description: 'Based on payment schedule, automatically send reminders 14 and 7 days before each payment is due. Include payment link and outstanding balance.',
          trigger: 'Scheduled based on payment dates',
          benefits: ['Proactive payment reminders', 'Easy payment link included', 'Higher pledge fulfillment'],
        },
        {
          workflowType: 'crm-pledge-tracking',
          title: 'Create Pledge Record',
          description: 'Automatically create pledge record in donor CRM with full payment schedule, expected amounts by date, and recognition preferences.',
          trigger: 'On form submission',
          benefits: ['Complete pledge tracking', 'Payment schedule documented', 'Recognition preferences stored'],
        },
        {
          workflowType: 'overdue-escalation',
          title: 'Alert on Overdue Payments',
          description: 'When scheduled payment is 30 days overdue, alert development staff for personal follow-up. Include donor contact info and pledge history.',
          trigger: 'Payment date + 30 days without payment received',
          benefits: ['Overdue pledges flagged automatically', 'Staff alerted for personal outreach', 'Prevents pledge lapse'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Payment schedule field generates expected payment dates for reminder automation',
          'First payment date anchors payment schedule calculation',
          'Recognition fields support public vs. anonymous giving preferences',
        ],
        integrationHints: [
          'Donor CRM (Bloomerang, Raiser\'s Edge) for pledge tracking and payment recording',
          'Payment processor for recurring payment setup when payment method allows',
          'Email automation for scheduled payment reminders',
        ],
        mongoDBConsiderations: [
          'Index on {firstPaymentDate: 1, paymentSchedule: 1} for reminder scheduling',
          'Store payment schedule as array of {dueDate, amount, status} for fulfillment tracking',
          'Index on {campaignName: 1} for campaign-specific pledge reporting',
          'Aggregation pipeline for pledge-to-cash conversion reporting',
        ],
      },
      seo: {
        metaTitle: 'Fundraising Pledge Form Template | NetPad',
        metaDescription: 'Free pledge form for nonprofits. Capture multi-year commitments with flexible payment schedules for capital campaigns and major gifts.',
        keywords: ['pledge form', 'fundraising pledge', 'capital campaign pledge', 'donation pledge', 'nonprofit pledge'],
        ogDescription: 'Convert more pledges to cash with structured commitment capture and automated payment reminders. Build predictable major gift revenue.',
      },
      socialProofAngles: [
        'Higher pledge fulfillment rates',
        'Automated payment reminders',
        'Flexible payment schedules',
        'Better pledge tracking',
      ],
    },
  }),
];
