/**
 * Sports & Fitness Form Templates
 *
 * Templates for gym memberships, team registration,
 * fitness assessments, and athletic waivers.
 */

import type { FormTemplate } from '../types';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  addressField,
  signatureField,
} from '../helpers';

export const sportsFitnessTemplates: FormTemplate[] = [
  // 1. Gym Membership Application
  createTemplate({
    id: 'gym-membership',
    name: 'Gym Membership Application',
    shortDescription: 'Join a fitness center',
    fullDescription: 'Gym membership application capturing personal information, health screening, emergency contacts, and membership options.',
    category: 'sports-fitness',
    icon: 'Dumbbell',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 1,
    tags: ['gym', 'membership', 'fitness', 'health club'],
    useCases: [
      'Gym signups',
      'Fitness center memberships',
      'Health club registration',
      'Wellness center enrollment',
    ],
    features: [
      'Membership selection',
      'Health screening',
      'Emergency contact',
      'Waiver agreement',
    ],
    fieldConfigs: [
      sectionHeader('personal', 'Personal Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('gender', 'Gender', ['Male', 'Female', 'Non-binary', 'Prefer not to say']),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      addressField('address', 'Home Address', { required: true }),
      sectionHeader('emergency', 'Emergency Contact'),
      textField('emergencyName', 'Emergency Contact Name', { required: true }),
      textField('emergencyRelation', 'Relationship', { required: true }),
      phoneField('emergencyPhone', 'Emergency Phone', { required: true }),
      sectionHeader('membership', 'Membership Options'),
      selectField('membershipType', 'Membership Type', [
        'Individual Monthly - $29.99/mo',
        'Individual Annual - $299/yr',
        'Family Monthly - $49.99/mo',
        'Family Annual - $499/yr',
        'Student Monthly - $19.99/mo',
        'Senior Monthly - $24.99/mo',
        'Day Pass - $15',
      ], { required: true }),
      multiSelectField('addons', 'Add-Ons (Optional)', [
        'Personal Training Sessions',
        'Group Fitness Classes',
        'Locker Rental',
        'Towel Service',
        'Tanning',
        'Childcare',
      ]),
      selectField('startDate', 'Preferred Start Date', [
        'Today',
        'Beginning of Next Month',
        'Specific Date',
      ], { required: true }),
      dateField('specificStartDate', 'Specific Start Date', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'startDate', operator: 'equals', value: 'Specific Date' }],
        },
      }),
      sectionHeader('health', 'Health Screening (PAR-Q)'),
      yesNoField('heartCondition', 'Has a doctor ever said you have a heart condition?', { required: true }),
      yesNoField('chestPain', 'Do you feel pain in your chest during physical activity?', { required: true }),
      yesNoField('loseBalance', 'Do you lose your balance or consciousness?', { required: true }),
      yesNoField('boneJointProblem', 'Do you have a bone or joint problem that could be worsened by exercise?', { required: true }),
      yesNoField('takingMedication', 'Are you taking medication for blood pressure or heart condition?', { required: true }),
      yesNoField('otherReason', 'Any other reason you should not exercise?', { required: true }),
      textareaField('healthDetails', 'If you answered YES to any questions, please explain'),
      textareaField('medicalConditions', 'Please list any medical conditions, injuries, or limitations'),
      sectionHeader('goals', 'Fitness Goals'),
      multiSelectField('fitnessGoals', 'What are your fitness goals?', [
        'Weight Loss',
        'Build Muscle',
        'Improve Cardiovascular Health',
        'Increase Flexibility',
        'Stress Relief',
        'General Fitness',
        'Train for Event/Sport',
        'Rehabilitation',
      ]),
      textareaField('specificGoals', 'Specific Goals or Notes'),
      sectionHeader('waiver', 'Liability Waiver'),
      yesNoField('agreeRules', 'I agree to follow all gym rules and policies', { required: true }),
      yesNoField('agreeRisk', 'I understand and accept the inherent risks of exercise', { required: true }),
      yesNoField('agreeWaiver', 'I release the gym from liability for injuries', { required: true }),
      signatureField('signature', 'Signature', { required: true }),
      dateField('signatureDate', 'Date', { required: true }),
    ],
    enhanced: {
      headline: 'Sign Up Members Without the Clipboard Shuffle',
      subheadline: 'Capture complete memberships with health screening, emergency contacts, and waiver signatures—members walk out ready to work out.',
      longDescription: {
        opening: 'Gym signups are friction-heavy. Prospects tour the facility, get excited, then face a 15-minute paper application at the front desk. The clipboard shuffle kills momentum. Staff manually enter data into the system, making errors along the way. Health screening questions get skipped. Emergency contacts are incomplete. Waivers get filed but are unsearchable when you need them. Members start without complete profiles, creating liability gaps.',
        solution: 'This template captures complete gym memberships: personal information and contact details, emergency contact with relationship, membership type selection with add-ons, preferred start date, comprehensive PAR-Q health screening, fitness goals for trainer matching, and legally-binding waiver acceptance with digital signature. Conditional logic shows follow-up questions only when health concerns are indicated.',
        outcome: 'Sign up members in 5 minutes instead of 15. Complete health profiles before first workout enable safe exercise programming. Emergency contacts on file from day one. Digital waivers searchable and legally sound. Fitness goals captured for trainer consultation upsell. Track add-on attachment rates and membership mix. Reduce dropout by starting members with clear goals.',
      },
      useCases: [
        {
          title: 'Commercial Gym Chain',
          icon: '🏋️',
          industry: 'Fitness',
          scenario: 'Your gym chain has 10+ locations signing up 500+ members monthly. Paper applications create data entry backlog. Membership data inconsistent across locations. Health screening compliance varies. Waivers stored in filing cabinets.',
          painPoint: 'Paper applications slow signup and create errors. Health screening inconsistent across staff. Waiver management manual and non-compliant. Can\'t analyze membership patterns across locations.',
          keyFields: ['Membership Type', 'Has a doctor ever said you have a heart condition?', 'What are your fitness goals?', 'Signature'],
          exampleOrganization: 'A 15-location gym chain signing 500+ members monthly with 20% data entry error rate on paper applications.',
        },
        {
          title: 'Boutique Fitness Studio',
          icon: '🧘',
          industry: 'Fitness',
          scenario: 'Your boutique studio emphasizes personalized service. You want to know members\' goals before their first session. Paper intake doesn\'t capture the information trainers need. Members show up and trainers start cold.',
          painPoint: 'Goals and health history not captured systematically. Trainers meet members without context. Can\'t match members to appropriate classes. Personalized service promise unfulfilled.',
          keyFields: ['What are your fitness goals?', 'Please list any medical conditions, injuries, or limitations', 'Add-Ons (Optional)', 'Preferred Start Date'],
          exampleOrganization: 'A boutique studio with 200 members, where trainers have no pre-session member information.',
        },
        {
          title: 'Corporate Wellness Facility',
          icon: '🏢',
          industry: 'Corporate',
          scenario: 'Your company fitness center serves 1,000+ employees. HR needs health screening documentation for liability. Emergency contacts required for facility use. Current paper process creates compliance gaps and administrative burden.',
          painPoint: 'Health screening documentation incomplete. Emergency contacts not consistently captured. Compliance reporting manual. HR spends hours on data entry.',
          keyFields: ['Emergency Contact Name', 'PAR-Q health questions', 'Medical conditions', 'Waiver agreement'],
          exampleOrganization: 'A corporate fitness facility with 1,000+ employees and incomplete health screening documentation.',
        },
        {
          title: 'Community Recreation Center',
          icon: '🏊',
          industry: 'Recreation',
          scenario: 'Your rec center serves families with diverse programs—pool, gym, courts. Membership categories are complex (individual, family, senior). Paper applications make it hard to track who has access to what.',
          painPoint: 'Complex membership tiers confusing on paper. Family member information not linked. Program access not clear. Can\'t track facility usage by membership type.',
          keyFields: ['Membership Type', 'Add-Ons (Optional)', 'Date of Birth', 'Home Address'],
          exampleOrganization: 'A community rec center with 5,000+ members across 8 membership tiers, struggling with access management.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Photo Capture',
          description: 'Include photo upload for member ID cards. Streamlines check-in and reduces buddy-swiping.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Family Linking',
          description: 'For family memberships, capture additional household members with their own health screening and emergency contacts.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Add Billing Information',
          description: 'Capture payment method for automatic billing setup. Reduces payment failures and manual processing.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Include Referral Tracking',
          description: 'Ask how member heard about you and who referred them. Enables referral reward programs and marketing attribution.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Add Trainer Consultation Scheduling',
          description: 'For members with fitness goals, offer complimentary trainer consultation scheduling during signup.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'welcome-email',
          title: 'Send Welcome Package',
          description: 'Immediately email new member: facility hours, class schedule, trainer bios, gym etiquette guide, and first-visit checklist.',
          trigger: 'On form submission',
          benefits: ['New members prepared for first visit', 'Reduces first-day questions', 'Professional onboarding experience'],
        },
        {
          workflowType: 'health-flag',
          title: 'Alert Staff on Health Concerns',
          description: 'When PAR-Q indicates health concerns (any "yes" answers), alert fitness manager for physician clearance follow-up before workout.',
          trigger: 'On submission with any PAR-Q yes response',
          benefits: ['Health risks identified immediately', 'Liability protection', 'Appropriate exercise programming'],
        },
        {
          workflowType: 'membership-system-sync',
          title: 'Create Member Account',
          description: 'Automatically create member account in gym management software with access credentials, membership level, and payment schedule.',
          trigger: 'On form submission',
          benefits: ['No manual account creation', 'Instant access activation', 'Payment setup automated'],
        },
        {
          workflowType: 'goal-matching',
          title: 'Recommend Classes/Trainers',
          description: 'Based on fitness goals selected, automatically email member with recommended classes, trainers, and programs aligned with their objectives.',
          trigger: 'On form submission based on fitness goals',
          benefits: ['Personalized recommendations', 'Higher class attendance', 'Better goal achievement'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'PAR-Q boolean fields enable health risk flagging and compliance tracking',
          'Multi-select for goals and add-ons supports personalization and upsell analysis',
          'Signature field with date creates legally-binding waiver record',
        ],
        integrationHints: [
          'Gym management software (Mindbody, Zen Planner, ABC Fitness) for member accounts',
          'Payment processor (Stripe, Square) for recurring billing setup',
          'Access control system for key card/check-in activation',
        ],
        mongoDBConsiderations: [
          'Index on {membershipType: 1} for membership mix reporting',
          'Index on {heartCondition: 1, chestPain: 1} to identify members needing clearance',
          'Index on {fitnessGoals: 1} for targeted program marketing',
          'Store signature as reference with timestamp for audit trail',
        ],
      },
      seo: {
        metaTitle: 'Gym Membership Application Template | NetPad',
        metaDescription: 'Free gym membership form with PAR-Q health screening and digital waiver. Sign up members faster with complete profiles from day one.',
        keywords: ['gym membership form', 'fitness center registration', 'health club signup', 'gym waiver form', 'PAR-Q form'],
        ogDescription: 'Stop the clipboard shuffle. This gym membership form captures health screening, emergency contacts, and waivers in one digital flow.',
      },
      socialProofAngles: [
        'Faster member signups',
        'Complete health screening',
        'Digital waiver management',
        'Better member onboarding',
      ],
    },
  }),

  // 2. Sports Team Registration
  createTemplate({
    id: 'sports-team-registration',
    name: 'Sports Team Registration',
    shortDescription: 'Register for sports leagues and teams',
    fullDescription: 'Team/player registration form for recreational and competitive sports leagues. Captures player information, skill level, and team preferences.',
    category: 'sports-fitness',
    icon: 'Users',
    complexity: 'moderate',
    estimatedTime: 6,
    isFeatured: true,
    displayOrder: 2,
    tags: ['sports', 'team', 'league', 'registration'],
    useCases: [
      'League registration',
      'Team signups',
      'Recreational sports',
      'Youth athletics',
    ],
    features: [
      'Player information',
      'Skill assessment',
      'Team preferences',
      'Emergency contact',
    ],
    fieldConfigs: [
      sectionHeader('player', 'Player Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('gender', 'Gender', ['Male', 'Female', 'Non-binary']),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      addressField('address', 'Address'),
      sectionHeader('league', 'League Information'),
      selectField('sport', 'Sport', [
        'Basketball',
        'Soccer',
        'Softball',
        'Volleyball',
        'Flag Football',
        'Tennis',
        'Pickleball',
        'Bowling',
        'Kickball',
        'Other',
      ], { required: true }),
      selectField('season', 'Season', [
        'Spring 2025',
        'Summer 2025',
        'Fall 2025',
        'Winter 2026',
      ], { required: true }),
      selectField('division', 'Division/Level', [
        'Recreational - Beginner',
        'Recreational - Intermediate',
        'Competitive - Intermediate',
        'Competitive - Advanced',
      ], { required: true }),
      selectField('ageGroup', 'Age Group (if applicable)', [
        'Youth (Under 12)',
        'Teen (13-17)',
        'Adult (18-39)',
        'Senior (40+)',
        'Open/All Ages',
      ]),
      sectionHeader('team', 'Team Preferences'),
      selectField('registrationType', 'Registration Type', [
        'Individual (place me on a team)',
        'With Friends (list below)',
        'Team Captain (forming a team)',
        'Existing Team Member',
      ], { required: true }),
      textareaField('friendsList', 'Friends to Play With (names)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'registrationType', operator: 'equals', value: 'With Friends (list below)' }],
        },
      }),
      textField('existingTeam', 'Existing Team Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'registrationType', operator: 'equals', value: 'Team Captain (forming a team)' },
            { field: 'registrationType', operator: 'equals', value: 'Existing Team Member' },
          ],
        },
      }),
      selectField('position', 'Preferred Position (if applicable)', [
        'Any Position',
        'Guard/Defense',
        'Forward/Offense',
        'Center/Midfield',
        'Goalie',
        'Pitcher',
        'Catcher',
        'No Preference',
      ]),
      sectionHeader('experience', 'Experience'),
      selectField('skillLevel', 'Self-Rated Skill Level', [
        'Beginner - New to the sport',
        'Intermediate - Played recreationally',
        'Advanced - Played competitively',
        'Expert - Played at high level',
      ], { required: true }),
      numberField('yearsPlaying', 'Years Playing This Sport'),
      textareaField('experience', 'Relevant Experience'),
      sectionHeader('emergency', 'Emergency Contact'),
      textField('emergencyName', 'Emergency Contact Name', { required: true }),
      phoneField('emergencyPhone', 'Emergency Phone', { required: true }),
      textField('emergencyRelation', 'Relationship', { required: true }),
      sectionHeader('medical', 'Medical Information'),
      textareaField('medicalConditions', 'Medical Conditions or Allergies'),
      textareaField('injuries', 'Current or Recent Injuries'),
      sectionHeader('waiver', 'Waiver & Agreement'),
      yesNoField('agreeRules', 'I agree to abide by league rules and sportsmanship guidelines', { required: true }),
      yesNoField('agreeWaiver', 'I accept responsibility for injury risk and release the league from liability', { required: true }),
      signatureField('signature', 'Signature', { required: true }),
    ],
    enhanced: {
      headline: 'Build Balanced Teams from Scattered Signups',
      subheadline: 'Capture player skills, availability, and team preferences—data that powers fair team formation and competitive balance.',
      longDescription: {
        opening: 'League registration is chaotic. Players email their interest, text their availability, and show up without completing paperwork. Individual registrations pile up with no systematic way to form balanced teams. Skill levels are self-reported inconsistently. Friends want to play together but you don\'t know who knows whom. Draft night becomes guesswork. Teams end up lopsided—one squad dominates while others struggle, and players quit mid-season.',
        solution: 'This template captures structured player registrations: complete contact information, sport and season selection, division and age group for proper placement, team preferences (individual placement, friend groups, team captain, existing team), preferred position, self-rated skill level with years of experience, emergency contact and medical information, and waiver acceptance with digital signature.',
        outcome: 'Form balanced teams using actual skill data. Keep friend groups together when requested. Match captains with free agents needing teams. Reduce mid-season dropouts with proper skill-level placement. Complete emergency and medical information before first game. Digital waivers signed and searchable. Track registration patterns by sport, season, and division for program planning.',
      },
      useCases: [
        {
          title: 'Adult Recreation League',
          icon: '⚽',
          industry: 'Recreation',
          scenario: 'Your rec department runs adult leagues in 6 sports across 4 seasons. 500+ players register annually. Team formation is a nightmare—spreadsheets, emails, and draft night chaos. Competitive balance is hit-or-miss.',
          painPoint: 'Registration data scattered across systems. Skill levels not captured consistently. Friend requests get lost. Team formation takes days of manual work. Unbalanced teams lead to dropouts.',
          keyFields: ['Registration Type', 'Self-Rated Skill Level', 'Friends to Play With (names)', 'Division/Level'],
          exampleOrganization: 'A parks department running adult leagues with 500+ registrations per season, experiencing 25% mid-season dropout due to skill mismatch.',
        },
        {
          title: 'Youth Sports Organization',
          icon: '🏀',
          industry: 'Youth Sports',
          scenario: 'Your youth sports org registers 1,000+ kids annually across age groups. Parents register online but data is incomplete. Coaches need emergency contacts and medical info before practice. Waivers are collected inconsistently.',
          painPoint: 'Parent contact information incomplete. Emergency and medical info not captured before play. Waiver collection inconsistent. Age group verification manual.',
          keyFields: ['Date of Birth', 'Age Group (if applicable)', 'Emergency Contact', 'Medical Conditions or Allergies'],
          exampleOrganization: 'A youth sports organization with 1,000+ players and incomplete emergency information for 30% of participants.',
        },
        {
          title: 'Corporate Sports League',
          icon: '🏢',
          industry: 'Corporate',
          scenario: 'Your company runs inter-departmental sports leagues for employee wellness. Registration is informal—emails and Slack messages. You can\'t track participation, skill levels, or who\'s actually playing. Liability waivers are an afterthought.',
          painPoint: 'Informal registration creates tracking gaps. Waivers not collected systematically. Skill levels unknown for team balancing. Can\'t report on wellness program participation.',
          keyFields: ['Sport', 'Division/Level', 'Waiver agreement', 'Relevant Experience'],
          exampleOrganization: 'A corporate wellness program with 200+ league participants and no systematic registration or waiver collection.',
        },
        {
          title: 'Pickup Sports Coordinator',
          icon: '🎾',
          industry: 'Recreation',
          scenario: 'You organize weekly pickup games and need to manage rotating players. Some weeks you have 30 signups, others 8. Skill levels vary wildly. You need to balance teams on the fly.',
          painPoint: 'Can\'t predict attendance. Skill levels unknown for balancing. No contact list for weekly announcements. Emergency contacts not on file.',
          keyFields: ['Skill Level', 'Sport', 'Email', 'Emergency Contact'],
          exampleOrganization: 'A pickup sports organizer managing 50+ rotating players with no player database or skill tracking.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Availability Calendar',
          description: 'Capture which game nights/times work for the player. Helps with scheduling and ensures players can actually attend.',
          fieldSuggestion: 'multiselect',
          difficulty: 'easy',
        },
        {
          title: 'Enable Coach/Captain Interest',
          description: 'Ask if player is interested in coaching or captaining. Build leadership pipeline for future seasons.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Add Jersey Size',
          description: 'Capture shirt size for team uniforms. Prevents sizing issues and reorders.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Previous Season Data',
          description: 'For returning players, pre-populate contact info and ask about skill changes since last season.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Enable Multi-Sport Registration',
          description: 'Allow players to register for multiple sports/seasons in one submission with different preferences for each.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'registration-confirmation',
          title: 'Confirm Registration',
          description: 'Immediately email player confirming registration with sport, division, and expected team assignment timeline.',
          trigger: 'On form submission',
          benefits: ['Player knows registration succeeded', 'Sets timeline expectations', 'Professional communication'],
        },
        {
          workflowType: 'team-assignment',
          title: 'Notify Team Assignment',
          description: 'When teams are formed, automatically email players with team name, captain contact info, practice schedule, and first game date.',
          trigger: 'On team assignment',
          benefits: ['Players informed of placement', 'Captain contact provided', 'Schedule communicated'],
        },
        {
          workflowType: 'friend-group-matching',
          title: 'Flag Friend Requests',
          description: 'When player lists friends, cross-reference with other registrations to identify friend groups for team placement.',
          trigger: 'On submission with friends listed',
          benefits: ['Friend groups identified automatically', 'Easier team formation', 'Better player experience'],
        },
        {
          workflowType: 'captain-roster',
          title: 'Send Captain Roster',
          description: 'For team captains, automatically email roster with player contact information, skill levels, positions, and any medical notes.',
          trigger: 'On team formation complete',
          benefits: ['Captains have player info', 'Skill levels for lineup decisions', 'Medical info for safety'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Registration type field enables individual placement, friend groups, and team linking',
          'Skill level as structured enum supports algorithmic team balancing',
          'Sport and season fields enable multi-league program management',
        ],
        integrationHints: [
          'League management software (TeamSnap, SportsEngine) for roster and schedule management',
          'Payment processor for registration fees',
          'Communication platform for team messaging',
        ],
        mongoDBConsiderations: [
          'Index on {sport: 1, season: 1, division: 1} for league-specific queries',
          'Index on {skillLevel: 1} for team balancing algorithms',
          'Text index on friendsList for friend group matching',
          'Compound index on {existingTeam: 1, registrationType: 1} for team member linking',
        ],
      },
      seo: {
        metaTitle: 'Sports Team Registration Form Template | NetPad',
        metaDescription: 'Free sports league registration template. Capture player skills, team preferences, and waivers for balanced team formation.',
        keywords: ['sports registration form', 'league registration', 'team signup form', 'player registration', 'rec league form'],
        ogDescription: 'Build balanced teams with structured registration. Capture skills, friend groups, and preferences for fair team formation.',
      },
      socialProofAngles: [
        'Better competitive balance',
        'Friend groups kept together',
        'Complete player information',
        'Faster team formation',
      ],
    },
  }),

  // 3. Personal Training Intake
  createTemplate({
    id: 'personal-training-intake',
    name: 'Personal Training Intake',
    shortDescription: 'New client intake for personal training',
    fullDescription: 'Comprehensive intake form for personal training clients. Captures health history, fitness goals, and lifestyle information.',
    category: 'sports-fitness',
    icon: 'HeartPulse',
    complexity: 'advanced',
    estimatedTime: 15,
    displayOrder: 3,
    tags: ['personal training', 'fitness', 'intake', 'assessment'],
    useCases: [
      'Personal training consultations',
      'Fitness coaching intake',
      'Wellness program enrollment',
      'Athletic training',
    ],
    features: [
      'Health history',
      'Fitness assessment',
      'Lifestyle evaluation',
      'Goal setting',
    ],
    fieldConfigs: [
      sectionHeader('personal', 'Personal Information'),
      textField('name', 'Full Name', { required: true }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('gender', 'Gender', ['Male', 'Female', 'Non-binary', 'Prefer not to say']),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      textField('occupation', 'Occupation'),
      textField('emergencyContact', 'Emergency Contact Name & Phone', { required: true }),
      sectionHeader('measurements', 'Current Measurements'),
      numberField('height', 'Height (inches)', { required: true }),
      numberField('weight', 'Current Weight (lbs)', { required: true }),
      numberField('goalWeight', 'Goal Weight (lbs)'),
      numberField('bodyFat', 'Body Fat % (if known)'),
      textField('waist', 'Waist Measurement'),
      sectionHeader('health', 'Health History'),
      yesNoField('doctorApproval', 'Has a doctor cleared you for exercise?'),
      multiSelectField('medicalConditions', 'Current Medical Conditions', [
        'Heart Disease',
        'High Blood Pressure',
        'Diabetes',
        'Asthma',
        'Arthritis',
        'Back Problems',
        'Joint Issues',
        'Pregnancy',
        'None',
      ]),
      textareaField('medications', 'Current Medications'),
      textareaField('injuries', 'Past or Current Injuries'),
      textareaField('surgeries', 'Past Surgeries'),
      yesNoField('painDuringExercise', 'Do you experience pain during exercise?'),
      textareaField('painDetails', 'If yes, describe', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'painDuringExercise', operator: 'isTrue' }],
        },
      }),
      sectionHeader('lifestyle', 'Lifestyle'),
      selectField('activityLevel', 'Current Activity Level', [
        'Sedentary - Desk job, no exercise',
        'Lightly Active - Light exercise 1-2x/week',
        'Moderately Active - Exercise 3-4x/week',
        'Very Active - Hard exercise 5-6x/week',
        'Extremely Active - Physical job + daily exercise',
      ], { required: true }),
      textareaField('currentExercise', 'Describe Your Current Exercise Routine'),
      selectField('sleepHours', 'Average Sleep Per Night', [
        'Less than 5 hours',
        '5-6 hours',
        '7-8 hours',
        'More than 8 hours',
      ]),
      selectField('stressLevel', 'Stress Level', [
        'Low',
        'Moderate',
        'High',
        'Very High',
      ]),
      selectField('smokingStatus', 'Smoking Status', [
        'Never smoked',
        'Former smoker',
        'Current smoker',
      ]),
      selectField('alcoholConsumption', 'Alcohol Consumption', [
        'None',
        '1-2 drinks/week',
        '3-7 drinks/week',
        'More than 7/week',
      ]),
      sectionHeader('nutrition', 'Nutrition'),
      selectField('mealsPerDay', 'Meals Per Day', [
        '1-2',
        '3',
        '4-5',
        '6+',
      ]),
      selectField('waterIntake', 'Daily Water Intake', [
        'Less than 4 glasses',
        '4-6 glasses',
        '7-8 glasses',
        'More than 8 glasses',
      ]),
      multiSelectField('dietaryRestrictions', 'Dietary Restrictions', [
        'None',
        'Vegetarian',
        'Vegan',
        'Gluten-Free',
        'Dairy-Free',
        'Keto/Low Carb',
        'Religious Restrictions',
        'Other',
      ]),
      textareaField('typicalDiet', 'Describe Your Typical Daily Diet'),
      sectionHeader('goals', 'Fitness Goals'),
      multiSelectField('primaryGoals', 'Primary Goals', [
        'Weight Loss',
        'Build Muscle',
        'Increase Strength',
        'Improve Endurance',
        'Increase Flexibility',
        'Sports Performance',
        'Injury Rehabilitation',
        'General Health',
        'Stress Relief',
      ], { required: true }),
      textareaField('specificGoals', 'Specific Goals with Timeline'),
      textareaField('previousAttempts', 'What Have You Tried Before?'),
      sectionHeader('availability', 'Training Preferences'),
      multiSelectField('preferredDays', 'Preferred Training Days', [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ], { required: true }),
      multiSelectField('preferredTimes', 'Preferred Times', [
        'Early Morning (5-8am)',
        'Morning (8-12pm)',
        'Afternoon (12-5pm)',
        'Evening (5-8pm)',
      ]),
      selectField('sessionFrequency', 'Desired Training Frequency', [
        '1x per week',
        '2x per week',
        '3x per week',
        '4+ per week',
      ]),
    ],
    enhanced: {
      headline: 'Know Your Clients Before the First Session',
      subheadline: 'Capture complete health history, lifestyle factors, and goals—trainers start with context instead of spending sessions gathering information.',
      longDescription: {
        opening: 'First training sessions are wasted on paperwork. Trainers spend 30 minutes asking health questions that could have been captured before. Critical information comes out mid-workout: "Oh, I have a bad knee" or "I\'m on blood pressure medication." Goals are vague—"I want to get fit"—leaving trainers guessing at program design. Nutrition and lifestyle factors go unexplored. Trainers design programs in the dark, leading to poor results and client attrition.',
        solution: 'This template captures comprehensive client profiles: personal information and emergency contact, current measurements (height, weight, body fat, goal weight), complete health history with medical conditions and medications, pain during exercise disclosure, lifestyle assessment (activity level, current routine, sleep, stress, smoking, alcohol), nutrition habits (meals, water, dietary restrictions, typical diet), primary fitness goals with timeline and previous attempts, and training preferences with availability.',
        outcome: 'Trainers review profiles before the first session, arriving prepared with program ideas. Health conditions disclosed upfront enable safe programming. Lifestyle factors inform holistic coaching. Specific goals with timelines enable progress tracking. Reduce first-session dropout by 40% with better-prepared initial consultations. Track client outcomes by goal type to refine training approaches.',
      },
      useCases: [
        {
          title: 'Personal Training Studio',
          icon: '💪',
          industry: 'Fitness',
          scenario: 'Your studio has 5 trainers working with 100+ clients. Each trainer does their own intake differently. Some ask about nutrition, others don\'t. Health information is in paper files somewhere. Client goals are in trainers\' heads.',
          painPoint: 'Inconsistent intake across trainers. Health information not systematically captured. Goals and progress not documented. When trainers leave, client history is lost.',
          keyFields: ['Current Medical Conditions', 'Primary Goals', 'Current Activity Level', 'Preferred Training Days'],
          exampleOrganization: 'A personal training studio with 5 trainers and no standardized intake process, experiencing 35% client dropout within 90 days.',
        },
        {
          title: 'Online Coaching Business',
          icon: '💻',
          industry: 'Fitness',
          scenario: 'Your online coaching business serves 200+ remote clients. You need comprehensive intake before programming can begin. Video calls for intake are expensive in coach time. Written intake through email is inconsistent.',
          painPoint: 'Intake consumes expensive coaching time. Information gathered inconsistently. No standard baseline measurements. Can\'t compare intake to outcomes.',
          keyFields: ['Current Measurements', 'Describe Your Current Exercise Routine', 'Describe Your Typical Daily Diet', 'Specific Goals with Timeline'],
          exampleOrganization: 'An online coaching business spending 45+ minutes per client on intake calls that could be captured in forms.',
        },
        {
          title: 'Corporate Wellness Program',
          icon: '🏢',
          industry: 'Corporate',
          scenario: 'Your corporate wellness program offers personal training to employees. HR needs health screening documentation. Trainers need to know employee fitness levels before programming. Medical limitations must be documented.',
          painPoint: 'Health screening incomplete. Activity levels vary dramatically. Goals not captured for program ROI. Medical limitations discovered during sessions.',
          keyFields: ['Has a doctor cleared you for exercise?', 'Medical Conditions', 'Activity Level', 'Fitness Goals'],
          exampleOrganization: 'A corporate wellness program with 500+ employee participants and no systematic fitness intake.',
        },
        {
          title: 'Rehabilitation-Focused Training',
          icon: '🏥',
          industry: 'Healthcare',
          scenario: 'Your training facility specializes in post-rehab and corrective exercise. Clients come with injuries, surgeries, and chronic conditions. Detailed medical history is essential for safe, effective programming.',
          painPoint: 'Complex medical histories not captured systematically. Pain patterns not documented. Surgical history incomplete. Medication interactions not considered.',
          keyFields: ['Past or Current Injuries', 'Past Surgeries', 'Do you experience pain during exercise?', 'Current Medications'],
          exampleOrganization: 'A corrective exercise specialist working with post-rehab clients, spending 60+ minutes on health history intake.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Baseline Fitness Tests',
          description: 'Include fields for recording baseline assessments: pushups, planks, flexibility tests. Establishes starting point for progress tracking.',
          fieldSuggestion: 'number',
          difficulty: 'easy',
        },
        {
          title: 'Include Photo Upload',
          description: 'Allow clients to upload progress photos at intake. Visual documentation of starting point for before/after comparison.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Add Training History Detail',
          description: 'Capture specific training history: gym experience, exercises familiar with, previous trainers. Helps trainers build on existing knowledge.',
          fieldSuggestion: 'textarea',
          difficulty: 'easy',
        },
        {
          title: 'Enable Physician Clearance Upload',
          description: 'For clients with health concerns, allow upload of physician clearance documentation before training begins.',
          fieldSuggestion: 'file',
          difficulty: 'medium',
        },
        {
          title: 'Add Motivation Assessment',
          description: 'Include questions about motivation drivers, past obstacles, and support system. Informs coaching approach and accountability strategies.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'trainer-assignment',
          title: 'Match to Trainer',
          description: 'Based on goals, schedule, and health considerations, automatically suggest trainer matches and notify assigned trainer with client profile.',
          trigger: 'On form submission',
          benefits: ['Trainer receives complete profile', 'Match based on specialization', 'First session can be productive'],
        },
        {
          workflowType: 'health-flag',
          title: 'Alert on Health Concerns',
          description: 'When health conditions or medications are indicated, alert trainer and suggest physician clearance before high-intensity programming.',
          trigger: 'On submission with medical conditions',
          benefits: ['Health risks flagged automatically', 'Physician clearance prompted', 'Safe programming ensured'],
        },
        {
          workflowType: 'welcome-sequence',
          title: 'Send Preparation Materials',
          description: 'Email client with what to expect in first session, what to bring, pre-session nutrition recommendations, and facility information.',
          trigger: 'On form submission',
          benefits: ['Client prepared for session', 'Expectations set clearly', 'Professional onboarding'],
        },
        {
          workflowType: 'goal-tracking',
          title: 'Create Progress Tracking',
          description: 'Based on goals and measurements, automatically create progress tracking plan with check-in intervals and milestone targets.',
          trigger: 'On form submission',
          benefits: ['Progress tracking from day one', 'Clear milestones established', 'Accountability built in'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Multi-select for medical conditions enables specific health concern flagging',
          'Lifestyle fields as structured selects support wellness pattern analysis',
          'Availability multi-selects enable trainer-client schedule matching',
        ],
        integrationHints: [
          'Training software (Trainerize, TrueCoach, PT Distinction) for client management',
          'Scheduling software for session booking based on availability',
          'Progress tracking apps for measurement updates',
        ],
        mongoDBConsiderations: [
          'Index on {primaryGoals: 1} for goal-based client segmentation',
          'Index on {medicalConditions: 1} for health concern filtering',
          'Index on {preferredDays: 1, preferredTimes: 1} for schedule matching',
          'Store measurements as subdocument with dates for progress tracking',
        ],
      },
      seo: {
        metaTitle: 'Personal Training Intake Form Template | NetPad',
        metaDescription: 'Free personal training client intake form. Capture health history, goals, and lifestyle for effective program design from session one.',
        keywords: ['personal training intake', 'fitness client form', 'trainer intake form', 'fitness assessment form', 'client onboarding'],
        ogDescription: 'Stop wasting first sessions on paperwork. This intake form captures everything trainers need to design effective programs from day one.',
      },
      socialProofAngles: [
        'More productive first sessions',
        'Better client-program matching',
        'Complete health documentation',
        'Improved client retention',
      ],
    },
  }),

  // 4. Race/Event Registration
  createTemplate({
    id: 'race-registration',
    name: 'Race/Event Registration',
    shortDescription: 'Register for races and athletic events',
    fullDescription: 'Registration form for races, marathons, and athletic events. Captures participant information, event selection, and emergency details.',
    category: 'sports-fitness',
    icon: 'Timer',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 4,
    tags: ['race', 'marathon', 'event', 'registration'],
    useCases: [
      '5K/10K races',
      'Marathons',
      'Triathlons',
      'Charity runs',
    ],
    features: [
      'Event selection',
      'T-shirt sizing',
      'Emergency info',
      'Waiver signing',
    ],
    fieldConfigs: [
      sectionHeader('participant', 'Participant Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('gender', 'Gender', ['Male', 'Female', 'Non-binary'], { required: true }),
      addressField('address', 'Address'),
      sectionHeader('event', 'Event Selection'),
      selectField('eventName', 'Event', [
        '5K Run/Walk',
        '10K Run',
        'Half Marathon',
        'Full Marathon',
        'Kids Fun Run',
        'Virtual Option',
      ], { required: true }),
      selectField('tShirtSize', 'T-Shirt Size', [
        'Youth S',
        'Youth M',
        'Youth L',
        'Adult XS',
        'Adult S',
        'Adult M',
        'Adult L',
        'Adult XL',
        'Adult 2XL',
        'Adult 3XL',
      ], { required: true }),
      yesNoField('teamEntry', 'Part of a Team?'),
      textField('teamName', 'Team Name', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'teamEntry', operator: 'isTrue' }],
        },
      }),
      sectionHeader('experience', 'Running Experience'),
      selectField('runningExperience', 'Running Experience', [
        'First Race',
        'A few races',
        'Regular racer',
        'Experienced competitor',
      ]),
      textField('estimatedFinishTime', 'Estimated Finish Time'),
      selectField('corralPreference', 'Starting Corral Preference', [
        'Fast - Sub 7 min/mile',
        'Medium - 7-9 min/mile',
        'Casual - 9-12 min/mile',
        'Walker - 12+ min/mile',
      ]),
      sectionHeader('emergency', 'Emergency Information'),
      textField('emergencyContact', 'Emergency Contact Name', { required: true }),
      phoneField('emergencyPhone', 'Emergency Phone', { required: true }),
      textField('emergencyRelation', 'Relationship', { required: true }),
      textareaField('medicalConditions', 'Medical Conditions/Allergies'),
      sectionHeader('extras', 'Additional Options'),
      multiSelectField('addOns', 'Additional Options', [
        'Race Photos Package - $25',
        'Commemorative Medal Upgrade - $15',
        'Charity Donation - $10',
        'Early Packet Pickup',
        'None',
      ]),
      selectField('referralSource', 'How did you hear about us?', [
        'Social Media',
        'Friend/Family',
        'Running Club',
        'Search Engine',
        'Previous Participant',
        'Other',
      ]),
      sectionHeader('waiver', 'Liability Waiver'),
      yesNoField('agreeWaiver', 'I acknowledge the risks and release the organizers from liability', { required: true }),
      yesNoField('agreeMedia', 'I consent to photos/videos for promotional use', { required: true }),
      yesNoField('agreeRules', 'I agree to follow all event rules', { required: true }),
      signatureField('signature', 'Signature', { required: true }),
    ],
    enhanced: {
      headline: 'Fill Every Starting Corral with Happy Runners',
      subheadline: 'Capture race registrations with emergency info, experience levels, and add-ons—data that powers smooth race day operations and future event marketing.',
      longDescription: {
        opening: 'Race registration is high-stakes for event organizers. Participants register weeks or months in advance, then show up expecting a seamless experience. Incomplete registrations cause race day chaos: missing emergency contacts when someone collapses at mile 8, wrong T-shirt sizes creating frustrated finishers, no corral assignments causing dangerous congestion at the start. Post-race, you can\'t contact participants for future events because contact info was incomplete.',
        solution: 'This template captures complete race registrations: participant contact information, event selection (distance, category), T-shirt sizing, team entry with team name, running experience and estimated finish time for corral assignment, emergency contact and medical information, add-on purchases (photos, medal upgrades, charity donations), referral source for marketing attribution, and comprehensive waiver with digital signature.',
        outcome: 'Smooth race day operations with complete participant data. Corral assignments based on pace reduce congestion. Emergency contacts available instantly when needed. Accurate T-shirt orders eliminate sizing complaints. Add-on attachment rates increase revenue per participant. Post-race marketing reaches all participants. Track registration patterns by distance, experience level, and referral source.',
      },
      useCases: [
        {
          title: 'Community 5K Race',
          icon: '🏃',
          industry: 'Events',
          scenario: 'Your annual community 5K draws 500+ participants including serious runners and first-timers. Registration through email creates chaos. No systematic way to capture T-shirt sizes, emergency contacts, or experience levels for corral placement.',
          painPoint: 'Registration data in spreadsheets and emails. T-shirt sizes collected inconsistently. Emergency contacts missing. Can\'t segment fast runners from walkers.',
          keyFields: ['Event', 'T-Shirt Size', 'Running Experience', 'Starting Corral Preference'],
          exampleOrganization: 'A community 5K with 500+ participants and 15% wrong T-shirt sizes due to inconsistent data collection.',
        },
        {
          title: 'Charity Run Series',
          icon: '❤️',
          industry: 'Nonprofit',
          scenario: 'Your nonprofit runs a 4-race series raising $200K annually. Participants register for individual races or the full series. Team fundraising is core to the model. Current registration doesn\'t capture team affiliations or fundraising commitments.',
          painPoint: 'Team registration not linked to fundraising. Can\'t track series participants across events. Charity donation option buried. No post-race engagement for future events.',
          keyFields: ['Part of a Team?', 'Team Name', 'Additional Options (Charity Donation)', 'How did you hear about us?'],
          exampleOrganization: 'A charity race series raising $200K annually, missing 30% of potential team fundraising due to poor registration linking.',
        },
        {
          title: 'Marathon Event',
          icon: '🏅',
          industry: 'Events',
          scenario: 'Your marathon hosts 5,000+ runners across full marathon, half, and relay categories. Start wave management is critical for runner safety and course timing. Medical information must be accessible for aid station emergencies.',
          painPoint: 'Wave assignment based on incomplete data. Medical conditions discovered during emergencies. Estimated finish times unreliable. Relay team coordination manual.',
          keyFields: ['Event', 'Estimated Finish Time', 'Medical Conditions/Allergies', 'Emergency Contact'],
          exampleOrganization: 'A 5,000-runner marathon with start line congestion issues due to inaccurate pace-based wave assignments.',
        },
        {
          title: 'Virtual Race Platform',
          icon: '🌐',
          industry: 'Events',
          scenario: 'Your platform hosts virtual races where participants run anywhere and submit times. Shipping addresses needed for medals and swag. Experience levels vary wildly. Engagement after registration is challenging.',
          painPoint: 'Shipping addresses incomplete. No way to segment participants by experience. Virtual engagement difficult. Photo packages complicated for virtual events.',
          keyFields: ['Address', 'Running Experience', 'T-Shirt Size', 'I consent to photos/videos for promotional use'],
          exampleOrganization: 'A virtual race platform with 20% shipping failures due to incomplete address data.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Pace Calculator',
          description: 'Based on estimated finish time and distance, calculate and display predicted pace per mile. Helps with corral assignment.',
          fieldSuggestion: 'number',
          difficulty: 'medium',
        },
        {
          title: 'Enable Fundraising Integration',
          description: 'For charity races, capture fundraising commitment and link to fundraising platform. Track registration-to-fundraising conversion.',
          fieldSuggestion: 'currency',
          difficulty: 'advanced',
        },
        {
          title: 'Add Relay Team Management',
          description: 'For relay events, allow captain to register team members with individual emergency contacts and leg assignments.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Include Medical ID Upload',
          description: 'Allow participants to upload photo of medical ID bracelet or emergency information card for aid station access.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Expo Preferences',
          description: 'Capture packet pickup preferences and expo session interests for event planning and sponsor activation.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'registration-confirmation',
          title: 'Send Race Confirmation',
          description: 'Immediately email participant with race details, bib number (if assigned), packet pickup information, course map, and what to expect on race day.',
          trigger: 'On form submission',
          benefits: ['Participant has complete race information', 'Bib number for planning', 'Reduces pre-race inquiries'],
        },
        {
          workflowType: 'corral-assignment',
          title: 'Assign Starting Corral',
          description: 'Based on estimated finish time and experience level, automatically assign starting corral and update participant record.',
          trigger: 'On form submission',
          benefits: ['Pace-based wave assignment', 'Safer race start', 'Better runner experience'],
        },
        {
          workflowType: 'race-week-reminder',
          title: 'Send Race Week Info',
          description: 'Email participants 1 week before race with packet pickup details, weather forecast, parking information, and last-minute tips.',
          trigger: '7 days before event date',
          benefits: ['Participants prepared for race day', 'Packet pickup smoothed', 'Fewer day-of questions'],
        },
        {
          workflowType: 'post-race-engagement',
          title: 'Send Results and Photos',
          description: 'After race, email participants with official results, finisher certificate, race photos, and registration link for next year\'s event.',
          trigger: 'After race completion',
          benefits: ['Complete race experience', 'Photo package upsell', 'Early registration for next year'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Event selection enables multi-distance race management',
          'Experience and pace fields support corral assignment algorithms',
          'Add-on multi-select enables revenue tracking per participant',
        ],
        integrationHints: [
          'Race timing systems (RunScore, ChronoTrack) for bib assignment and results',
          'Photo platform (MarathonFoto, GameFace) for participant photo matching',
          'Email marketing for post-race engagement and future event promotion',
        ],
        mongoDBConsiderations: [
          'Index on {eventName: 1, estimatedFinishTime: 1} for corral assignment queries',
          'Index on {tShirtSize: 1} for merchandise ordering aggregation',
          'Index on {referralSource: 1} for marketing attribution analysis',
          'Store emergency contact as embedded document for quick access',
        ],
      },
      seo: {
        metaTitle: 'Race Registration Form Template | NetPad',
        metaDescription: 'Free race registration template for marathons, 5Ks, and athletic events. Capture participant info, emergency contacts, and waivers in one form.',
        keywords: ['race registration form', 'marathon signup', '5K registration', 'running event form', 'race entry form'],
        ogDescription: 'Smooth race day starts with complete registration. Capture emergency info, experience levels, and add-ons for better event operations.',
      },
      socialProofAngles: [
        'Smoother race day operations',
        'Better corral management',
        'Complete emergency information',
        'Higher add-on revenue',
      ],
    },
  }),

  // 5. Athletic Waiver Form
  createTemplate({
    id: 'athletic-waiver',
    name: 'Athletic Waiver Form',
    shortDescription: 'Liability waiver for athletic activities',
    fullDescription: 'Comprehensive liability waiver for gyms, sports facilities, and athletic programs. Includes assumption of risk and release of liability.',
    category: 'sports-fitness',
    icon: 'ShieldCheck',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 5,
    tags: ['waiver', 'liability', 'athletic', 'legal'],
    useCases: [
      'Gym waivers',
      'Sports league waivers',
      'Activity releases',
      'Event participation',
    ],
    features: [
      'Risk acknowledgment',
      'Liability release',
      'Medical authorization',
      'Digital signature',
    ],
    fieldConfigs: [
      sectionHeader('participant', 'Participant Information'),
      textField('participantName', 'Participant Name', { required: true }),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      addressField('address', 'Address'),
      yesNoField('isMinor', 'Is participant under 18?'),
      sectionHeader('parent', 'Parent/Guardian Information (if minor)'),
      textField('parentName', 'Parent/Guardian Name', {
        required: true,
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isMinor', operator: 'isTrue' }],
        },
      }),
      textField('parentRelation', 'Relationship', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isMinor', operator: 'isTrue' }],
        },
      }),
      phoneField('parentPhone', 'Parent Phone', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'isMinor', operator: 'isTrue' }],
        },
      }),
      sectionHeader('activity', 'Activity'),
      textField('activityName', 'Activity/Program Name', { required: true }),
      textField('facilityName', 'Facility Name'),
      sectionHeader('acknowledgments', 'Acknowledgments'),
      yesNoField('ackRisks', 'I acknowledge that physical activities carry inherent risks including injury, illness, or death', { required: true }),
      yesNoField('ackResponsibility', 'I take full responsibility for my participation and any resulting injuries', { required: true }),
      yesNoField('ackEquipment', 'I agree to use equipment properly and follow all safety instructions', { required: true }),
      yesNoField('ackRules', 'I agree to follow all facility rules and staff instructions', { required: true }),
      yesNoField('ackPhysicalCondition', 'I confirm I am physically capable of participating in these activities', { required: true }),
      sectionHeader('release', 'Release of Liability'),
      yesNoField('releaseOrg', 'I release the organization, its employees, and agents from all claims and liability', { required: true }),
      yesNoField('releaseHeirs', 'I agree this release is binding on my heirs, executors, and assigns', { required: true }),
      sectionHeader('medical', 'Medical Authorization'),
      yesNoField('authMedical', 'I authorize emergency medical treatment if needed', { required: true }),
      textField('insuranceProvider', 'Health Insurance Provider'),
      textField('policyNumber', 'Policy Number'),
      textareaField('medicalConditions', 'Medical Conditions or Allergies to Disclose'),
      sectionHeader('emergency', 'Emergency Contact'),
      textField('emergencyName', 'Emergency Contact Name', { required: true }),
      phoneField('emergencyPhone', 'Emergency Phone', { required: true }),
      textField('emergencyRelation', 'Relationship', { required: true }),
      sectionHeader('signature', 'Signature'),
      yesNoField('readAndUnderstood', 'I have read and understand this waiver', { required: true }),
      signatureField('signature', 'Signature', { required: true }),
      textField('printedName', 'Printed Name', { required: true }),
      dateField('signatureDate', 'Date', { required: true }),
    ],
    enhanced: {
      headline: 'Protect Your Organization with Digital Waivers',
      subheadline: 'Capture legally-binding liability releases with risk acknowledgments, medical authorization, and emergency contacts—searchable and always accessible.',
      longDescription: {
        opening: 'Paper waivers create liability gaps. Participants sign quickly without reading. Papers get filed and forgotten. When an incident occurs, staff scramble to find the waiver—was it signed? What did it cover? Is it legally valid? Minor participants often lack parent signatures. Medical conditions go undisclosed. Insurance providers demand waiver documentation you can\'t produce. One lawsuit from an improperly documented injury can cost more than years of program revenue.',
        solution: 'This template captures comprehensive liability waivers: participant identification with contact information, minor status triggering parent/guardian requirements, activity and facility identification, explicit risk acknowledgments (inherent risks, personal responsibility, equipment use, rule compliance, physical capability), release of liability including heirs clause, medical authorization with insurance information, medical conditions disclosure, emergency contact, and legally-binding digital signature with printed name and date.',
        outcome: 'Every waiver digitally signed, timestamped, and searchable. Minor waivers automatically require parent signature. Risk acknowledgments explicitly documented. Medical conditions disclosed before participation. Emergency contacts available instantly. Insurance information on file. Retrieve any waiver in seconds when needed. Reduce liability exposure with consistent, complete documentation.',
      },
      useCases: [
        {
          title: 'Fitness Facility',
          icon: '🏋️',
          industry: 'Fitness',
          scenario: 'Your gym requires waivers for all members. Paper waivers are filed by date, making retrieval difficult. When a member is injured, finding their waiver takes hours. Some waivers are illegible or incomplete.',
          painPoint: 'Paper waivers hard to retrieve. Completeness inconsistent. Signature validity questionable. Medical conditions not systematically captured.',
          keyFields: ['I acknowledge that physical activities carry inherent risks', 'I release the organization from all claims', 'Medical Conditions or Allergies to Disclose', 'Signature'],
          exampleOrganization: 'A gym with 2,000 members and paper waivers in filing cabinets, spending 2+ hours per incident on waiver retrieval.',
        },
        {
          title: 'Youth Sports League',
          icon: '⚽',
          industry: 'Youth Sports',
          scenario: 'Your youth league requires parent-signed waivers for all participants. Paper waivers circulate with coaches and get lost. When a child is injured, you can\'t confirm waiver status. Some waivers lack required parent signatures.',
          painPoint: 'Parent signatures missing from many waivers. Waivers lost between registration and season. Can\'t verify waiver status at practice/games. Medical authorization incomplete.',
          keyFields: ['Is participant under 18?', 'Parent/Guardian Name', 'I authorize emergency medical treatment if needed', 'Medical Conditions or Allergies to Disclose'],
          exampleOrganization: 'A youth sports league with 500+ players and 25% of waivers missing parent signatures.',
        },
        {
          title: 'Adventure Activity Provider',
          icon: '🧗',
          industry: 'Recreation',
          scenario: 'Your adventure company (climbing, zip-lining, rafting) has high-risk activities requiring comprehensive waivers. Lawyers require specific language. Insurance demands waiver documentation for every participant.',
          painPoint: 'High-risk activities need comprehensive releases. Insurance documentation requirements strict. Multiple activities need separate waivers. Waiver language must be legally precise.',
          keyFields: ['Activity/Program Name', 'I acknowledge inherent risks including injury, illness, or death', 'I take full responsibility for my participation', 'Signature'],
          exampleOrganization: 'An adventure provider with 10,000+ annual participants and insurance requiring 100% waiver documentation.',
        },
        {
          title: 'School Athletic Program',
          icon: '🏫',
          industry: 'Education',
          scenario: 'Your school requires athletic waivers for all sports participants. District policy mandates specific acknowledgments. Parents must authorize medical treatment. Current paper process delays roster clearance.',
          painPoint: 'District-mandated language must be included. Medical authorization critical for school events. Roster clearance delayed by incomplete waivers. Paper filing creates compliance gaps.',
          keyFields: ['Parent/Guardian Name', 'I authorize emergency medical treatment if needed', 'Health Insurance Provider', 'Policy Number'],
          exampleOrganization: 'A school athletic program with 300+ student athletes and 3-week average waiver processing time.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Activity-Specific Risks',
          description: 'Customize risk acknowledgments for specific activities. Swimming includes drowning risk. Climbing includes fall risk. Specificity strengthens legal protection.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Enable Multi-Activity Coverage',
          description: 'Allow participants to sign waiver covering multiple activities with checkboxes for each. One waiver, multiple coverages.',
          fieldSuggestion: 'multiselect',
          difficulty: 'medium',
        },
        {
          title: 'Add Witness Signature',
          description: 'For high-risk activities, add witness signature field to strengthen legal validity.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Include Photo ID Upload',
          description: 'Require upload of government ID photo for identity verification. Prevents waiver disputes.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Annual Renewal',
          description: 'Track waiver expiration dates and automatically prompt participants for annual renewal.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'waiver-confirmation',
          title: 'Send Waiver Copy',
          description: 'Immediately email participant a PDF copy of their signed waiver with timestamp and all acknowledgments for their records.',
          trigger: 'On form submission',
          benefits: ['Participant has copy of signed waiver', 'Timestamp documented', 'Professional communication'],
        },
        {
          workflowType: 'parent-verification',
          title: 'Verify Parent Signature',
          description: 'For minor participants, send verification email to parent email address confirming their authorization.',
          trigger: 'On submission for minor participant',
          benefits: ['Parent signature verified', 'Additional documentation', 'Reduces fraudulent signatures'],
        },
        {
          workflowType: 'medical-flag',
          title: 'Alert Staff on Conditions',
          description: 'When medical conditions are disclosed, notify relevant staff (coaches, instructors) with necessary precautions.',
          trigger: 'On submission with medical conditions',
          benefits: ['Staff aware of participant conditions', 'Appropriate precautions taken', 'Safer activity environment'],
        },
        {
          workflowType: 'expiration-reminder',
          title: 'Send Renewal Reminder',
          description: 'For annual waivers, send renewal reminder 30 days before expiration. Include link to new waiver form.',
          trigger: '30 days before waiver expiration',
          benefits: ['Continuous coverage maintained', 'No participation gaps', 'Proactive compliance'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Boolean acknowledgments create explicit record of each risk acceptance',
          'Minor flag triggers parent/guardian fields via conditional logic',
          'Signature field with timestamp creates legally-binding record',
        ],
        integrationHints: [
          'Document storage with versioning for waiver archive',
          'PDF generation for waiver copies',
          'Identity verification service for high-value protection',
        ],
        mongoDBConsiderations: [
          'Index on {participantName: 1, activityName: 1} for waiver lookup',
          'Index on {signatureDate: 1} for expiration tracking',
          'Store signature with timestamp and IP address for legal validity',
          'Consider separate collection for waiver versions/templates',
        ],
      },
      seo: {
        metaTitle: 'Athletic Waiver Form Template | NetPad',
        metaDescription: 'Free digital waiver template for gyms, sports leagues, and athletic programs. Capture liability releases, medical authorization, and emergency contacts.',
        keywords: ['athletic waiver form', 'liability waiver', 'sports waiver', 'gym waiver template', 'activity release form'],
        ogDescription: 'Protect your organization with digital waivers. Capture risk acknowledgments, medical authorization, and emergency contacts—always searchable.',
      },
      socialProofAngles: [
        'Stronger liability protection',
        'Instant waiver retrieval',
        'Complete documentation',
        'Verified parent signatures',
      ],
    },
  }),

  // 6. Fitness Class Booking
  createTemplate({
    id: 'fitness-class-booking',
    name: 'Fitness Class Booking',
    shortDescription: 'Book group fitness classes',
    fullDescription: 'Simple booking form for group fitness classes like yoga, spinning, or aerobics. Captures class selection and participant info.',
    category: 'sports-fitness',
    icon: 'CalendarCheck',
    complexity: 'simple',
    estimatedTime: 3,
    displayOrder: 6,
    tags: ['fitness', 'class', 'booking', 'yoga', 'group'],
    useCases: [
      'Yoga class signup',
      'Spinning reservations',
      'Group fitness',
      'Aerobics classes',
    ],
    features: [
      'Class selection',
      'Schedule viewing',
      'Equipment needs',
      'Waitlist option',
    ],
    fieldConfigs: [
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone', { fieldWidth: 'half' }),
      textField('membershipId', 'Membership ID (if member)'),
      selectField('classType', 'Class Type', [
        'Yoga - Beginner',
        'Yoga - Intermediate',
        'Yoga - Hot/Power',
        'Spinning/Cycling',
        'HIIT',
        'Pilates',
        'Zumba',
        'Strength Training',
        'Barre',
        'Aqua Aerobics',
        'Boot Camp',
      ], { required: true }),
      selectField('classDate', 'Class Date', [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ], { required: true }),
      selectField('classTime', 'Class Time', [
        '6:00 AM',
        '7:00 AM',
        '8:00 AM',
        '9:00 AM',
        '10:00 AM',
        '12:00 PM',
        '5:30 PM',
        '6:30 PM',
        '7:30 PM',
      ], { required: true }),
      selectField('instructor', 'Preferred Instructor (if any)', [
        'No Preference',
        'Sarah',
        'Mike',
        'Jennifer',
        'David',
      ]),
      yesNoField('needEquipment', 'Do you need to rent equipment (mat, weights, etc.)?'),
      textareaField('equipmentNeeds', 'Equipment Needed', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'needEquipment', operator: 'isTrue' }],
        },
      }),
      yesNoField('addToWaitlist', 'Add me to waitlist if class is full'),
      textareaField('specialNeeds', 'Injuries or modifications needed?'),
    ],
    enhanced: {
      headline: 'Fill Every Class Spot Without Phone Tag',
      subheadline: 'Let members book classes online with instructor preferences and modification requests—instructors arrive knowing who\'s in the room and what they need.',
      longDescription: {
        opening: 'Class booking by phone or front desk creates friction. Members can\'t see availability. Staff spend time taking bookings instead of serving members. Popular classes fill up, but waitlists aren\'t managed. Instructors don\'t know who\'s coming or what modifications members need. The member with a knee injury shows up, and the instructor learns mid-class they can\'t do half the movements. No-shows waste spots that waitlisted members wanted.',
        solution: 'This template captures streamlined class bookings: member identification with contact info and membership ID, class type selection from your schedule, date and time selection, instructor preference if applicable, equipment rental needs with specifics, waitlist opt-in for full classes, and injury/modification disclosure so instructors can prepare alternatives.',
        outcome: 'Fill classes to capacity with self-service booking. Reduce no-shows with confirmation emails and waitlist backfill. Instructors receive pre-class rosters with modification notes. Equipment prepared before class starts. Waitlist management automated—first on list gets the spot. Track class popularity by type, time, and instructor for schedule optimization.',
      },
      useCases: [
        {
          title: 'Yoga Studio',
          icon: '🧘',
          industry: 'Fitness',
          scenario: 'Your yoga studio runs 30+ classes weekly across multiple rooms and instructors. Phone and in-person booking creates scheduling conflicts and staff burden. Popular instructors\' classes fill instantly while others have empty spots.',
          painPoint: 'Can\'t see real-time availability. Staff time wasted on booking calls. Instructor schedules managed manually. No data on class popularity or optimal times.',
          keyFields: ['Class Type', 'Class Date', 'Class Time', 'Preferred Instructor (if any)'],
          exampleOrganization: 'A yoga studio running 30+ weekly classes with front desk spending 15+ hours weekly on class booking calls.',
        },
        {
          title: 'Cycling Studio',
          icon: '🚴',
          industry: 'Fitness',
          scenario: 'Your cycling studio has 25 bikes per class. Every spot matters for revenue. No-shows cost $25+ each. Members complain about full classes but don\'t check until they arrive. Waitlist management is manual.',
          painPoint: 'No-shows waste valuable spots. Waitlist notifications manual. Can\'t fill cancelled spots quickly. Specific bike preferences not captured.',
          keyFields: ['Class Time', 'Add me to waitlist if class is full', 'Do you need to rent equipment?', 'Your Name'],
          exampleOrganization: 'A cycling studio with 15% no-show rate costing $500+ weekly in empty bikes.',
        },
        {
          title: 'Group Fitness Program',
          icon: '💪',
          industry: 'Fitness',
          scenario: 'Your gym offers 50+ group fitness classes weekly. Classes range from low-impact to high-intensity. Members with injuries need modifications but instructors don\'t know until class starts. Equipment availability varies by class.',
          painPoint: 'Instructors don\'t know who needs modifications. Equipment needs unknown until arrival. Capacity varies by class type. No way to measure class utilization.',
          keyFields: ['Class Type', 'Injuries or modifications needed?', 'Do you need to rent equipment?', 'Equipment Needed'],
          exampleOrganization: 'A gym with 50+ weekly group classes and instructors unaware of participant modification needs.',
        },
        {
          title: 'Boutique Fitness Franchise',
          icon: '🏃',
          industry: 'Fitness',
          scenario: 'Your boutique fitness franchise (CrossFit, F45, OrangeTheory) runs class-based workouts with strict capacity limits. Members book across multiple locations. Consistency in booking experience matters for the brand.',
          painPoint: 'Booking experience inconsistent across locations. Can\'t track member preferences across studios. Capacity management manual. Franchise-wide reporting difficult.',
          keyFields: ['Class Type', 'Class Date', 'Class Time', 'Membership ID (if member)'],
          exampleOrganization: 'A multi-location fitness franchise with inconsistent booking processes and no cross-location member data.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Specific Bike/Spot Selection',
          description: 'For cycling or assigned-spot classes, allow members to select their preferred bike or floor position.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Enable Package/Credit Tracking',
          description: 'For class packages, show remaining credits and deduct automatically upon booking.',
          fieldSuggestion: 'number',
          difficulty: 'advanced',
        },
        {
          title: 'Add Late Cancel Fee Warning',
          description: 'Display cancellation policy and late cancel fee. Capture acknowledgment to reduce no-shows.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Include First-Timer Flag',
          description: 'Ask if this is member\'s first time in this class type. Alerts instructor to provide extra guidance.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Enable Recurring Booking',
          description: 'Allow members to book the same class weekly for a set period. Creates routine and reduces booking friction.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'booking-confirmation',
          title: 'Confirm Reservation',
          description: 'Immediately email member with class confirmation: type, date, time, instructor, location, and what to bring.',
          trigger: 'On form submission',
          benefits: ['Member has booking confirmation', 'Class details clear', 'Reduces no-shows'],
        },
        {
          workflowType: 'instructor-roster',
          title: 'Send Class Roster',
          description: 'Before each class, email instructor with roster including member names, first-timers flagged, and modification notes.',
          trigger: '2 hours before class time',
          benefits: ['Instructor prepared for class', 'Modifications known in advance', 'Better member experience'],
        },
        {
          workflowType: 'waitlist-notification',
          title: 'Notify Waitlist on Opening',
          description: 'When spot opens (cancellation or no-show), automatically notify first waitlisted member with limited-time booking link.',
          trigger: 'On cancellation with active waitlist',
          benefits: ['Waitlist members notified instantly', 'Spots filled quickly', 'No manual notification'],
        },
        {
          workflowType: 'reminder',
          title: 'Send Class Reminder',
          description: 'Email or text member 24 hours before class with reminder, cancellation option, and what to bring.',
          trigger: '24 hours before class time',
          benefits: ['Reduces no-shows', 'Easy cancellation if needed', 'Member arrives prepared'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Class type and time fields enable schedule-based availability checking',
          'Waitlist boolean supports automated waitlist management',
          'Modification field supports instructor preparation',
        ],
        integrationHints: [
          'Class management software (Mindbody, Glofox, Mariana Tek) for schedule and booking sync',
          'SMS gateway for class reminders and waitlist notifications',
          'Payment system for class package tracking',
        ],
        mongoDBConsiderations: [
          'Index on {classType: 1, classDate: 1, classTime: 1} for availability queries',
          'Index on {addToWaitlist: 1, classDate: 1} for waitlist management',
          'Index on {instructor: 1, classDate: 1} for instructor roster generation',
          'Consider capped collection for booking analytics',
        ],
      },
      seo: {
        metaTitle: 'Fitness Class Booking Form Template | NetPad',
        metaDescription: 'Free class booking form for gyms and studios. Let members reserve spots online with instructor preferences and modification requests.',
        keywords: ['fitness class booking', 'yoga class signup', 'gym class reservation', 'group fitness booking', 'class registration form'],
        ogDescription: 'Fill every class spot without phone tag. Members book online, instructors get rosters with modification notes, waitlists manage themselves.',
      },
      socialProofAngles: [
        'Higher class utilization',
        'Reduced no-shows',
        'Better instructor preparation',
        'Automated waitlist management',
      ],
    },
  }),
];
