/**
 * Technology & IT Form Templates
 *
 * Templates for bug reports, feature requests, IT service tickets,
 * and technology-related requests.
 */

import type { FormTemplate } from '../types';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  fileField,
  urlField,
} from '../helpers';

export const technologyItTemplates: FormTemplate[] = [
  // 1. Bug Report Form
  createTemplate({
    id: 'bug-report',
    name: 'Bug Report Form',
    shortDescription: 'Report software bugs and issues',
    fullDescription: 'A structured bug report form for software development teams. Captures detailed information about bugs including steps to reproduce, expected vs actual behavior.',
    category: 'technology-it',
    icon: 'Bug',
    complexity: 'moderate',
    estimatedTime: 6,
    isFeatured: true,
    displayOrder: 1,
    tags: ['bug', 'report', 'software', 'issue', 'defect'],
    useCases: [
      'Software bug tracking',
      'QA testing',
      'User-reported issues',
      'Technical support',
    ],
    features: [
      'Severity classification',
      'Steps to reproduce',
      'Environment details',
      'Screenshot uploads',
    ],
    fieldConfigs: [
      sectionHeader('reporter', 'Reporter Information'),
      textField('reporterName', 'Your Name', { required: true }),
      emailField('email', 'Email', { required: true }),
      textField('company', 'Company/Organization'),
      sectionHeader('bug', 'Bug Details'),
      textField('bugTitle', 'Bug Title', {
        required: true,
        placeholder: 'Brief, descriptive title for the bug',
      }),
      selectField('severity', 'Severity', [
        'Critical - System crash, data loss',
        'High - Major feature broken',
        'Medium - Feature partially broken',
        'Low - Minor issue, workaround exists',
        'Cosmetic - Visual/UI issue only',
      ], { required: true }),
      selectField('priority', 'Priority', [
        'Urgent - Needs immediate fix',
        'High - Fix in current sprint',
        'Medium - Fix soon',
        'Low - Fix when possible',
      ]),
      selectField('component', 'Component/Area', [
        'Frontend/UI',
        'Backend/API',
        'Database',
        'Authentication',
        'Payments',
        'Notifications',
        'Reports',
        'Mobile App',
        'Integration',
        'Other',
      ], { required: true }),
      sectionHeader('description', 'Bug Description'),
      textareaField('description', 'Description', {
        required: true,
        placeholder: 'Describe the bug in detail...',
        validation: { minLength: 50 },
      }),
      textareaField('stepsToReproduce', 'Steps to Reproduce', {
        required: true,
        placeholder: '1. Go to...\n2. Click on...\n3. Enter...\n4. See error',
      }),
      textareaField('expectedBehavior', 'Expected Behavior', {
        required: true,
        placeholder: 'What should happen?',
      }),
      textareaField('actualBehavior', 'Actual Behavior', {
        required: true,
        placeholder: 'What actually happens?',
      }),
      sectionHeader('environment', 'Environment'),
      selectField('browser', 'Browser', [
        'Chrome',
        'Firefox',
        'Safari',
        'Edge',
        'Mobile Safari',
        'Mobile Chrome',
        'Other',
        'N/A',
      ]),
      textField('browserVersion', 'Browser Version'),
      selectField('os', 'Operating System', [
        'Windows 11',
        'Windows 10',
        'macOS',
        'Linux',
        'iOS',
        'Android',
        'Other',
      ]),
      textField('deviceModel', 'Device Model (if mobile)'),
      textField('appVersion', 'App/Product Version'),
      sectionHeader('additional', 'Additional Information'),
      urlField('url', 'URL Where Bug Occurred'),
      textareaField('errorMessage', 'Error Message (if any)', {
        placeholder: 'Copy and paste the full error message...',
      }),
      textareaField('consoleErrors', 'Console Errors (if any)'),
      yesNoField('reproducible', 'Is this bug reproducible?', { required: true }),
      selectField('frequency', 'How often does this occur?', [
        'Every time',
        'Most of the time',
        'Sometimes',
        'Rarely',
        'Once',
      ]),
      fileField('screenshots', 'Screenshots/Videos', {
        validation: { multiple: true, maxFiles: 5 },
      }),
      textareaField('workaround', 'Known Workaround (if any)'),
    ],
  }),

  // 2. IT Service Request Form
  createTemplate({
    id: 'it-service-request',
    name: 'IT Service Request Form',
    shortDescription: 'Request IT support and services',
    fullDescription: 'Internal IT service request form for employees. Covers hardware, software, access requests, and technical support needs.',
    category: 'technology-it',
    icon: 'Headphones',
    complexity: 'moderate',
    estimatedTime: 5,
    isFeatured: true,
    displayOrder: 2,
    tags: ['it', 'service', 'support', 'helpdesk', 'ticket'],
    useCases: [
      'IT helpdesk tickets',
      'Equipment requests',
      'Software installation',
      'Access requests',
    ],
    features: [
      'Request categorization',
      'Priority levels',
      'Asset tracking',
      'Approval workflow',
    ],
    fieldConfigs: [
      sectionHeader('requester', 'Requester Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email', { required: true }),
      textField('department', 'Department', { required: true }),
      textField('manager', 'Manager Name'),
      phoneField('phone', 'Phone/Extension'),
      textField('location', 'Office Location/Desk Number'),
      sectionHeader('request', 'Request Details'),
      selectField('requestType', 'Request Type', [
        'Hardware Issue/Request',
        'Software Issue/Request',
        'Network/Connectivity',
        'Email/Communication',
        'Access Request',
        'Password Reset',
        'New Employee Setup',
        'Equipment Return',
        'Other',
      ], { required: true }),
      selectField('priority', 'Priority', [
        'Emergency - Cannot work',
        'High - Significantly impacted',
        'Medium - Moderately impacted',
        'Low - Minor inconvenience',
      ], { required: true }),
      textField('subject', 'Brief Subject/Title', { required: true }),
      textareaField('description', 'Detailed Description', {
        required: true,
        placeholder: 'Describe your request or issue in detail...',
      }),
      sectionHeader('hardware', 'Hardware Details (if applicable)'),
      textField('assetTag', 'Asset Tag Number'),
      selectField('deviceType', 'Device Type', [
        'Desktop Computer',
        'Laptop',
        'Monitor',
        'Keyboard/Mouse',
        'Phone/Headset',
        'Printer',
        'Mobile Device',
        'Other',
        'N/A',
      ]),
      textField('deviceModel', 'Make/Model'),
      sectionHeader('software', 'Software Details (if applicable)'),
      textField('softwareName', 'Software Name'),
      textField('softwareVersion', 'Version'),
      textareaField('errorMessages', 'Error Messages'),
      sectionHeader('access', 'Access Request (if applicable)'),
      textField('systemAccess', 'System/Application Name'),
      selectField('accessType', 'Access Type Needed', [
        'New Access',
        'Modify Existing Access',
        'Remove Access',
        'N/A',
      ]),
      textareaField('accessJustification', 'Business Justification'),
      sectionHeader('availability', 'Availability'),
      selectField('preferredContact', 'Preferred Contact Method', [
        'Email',
        'Phone',
        'Teams/Slack',
        'Any',
      ]),
      textareaField('availability', 'Best Times to Contact/Access Your Workstation'),
      yesNoField('remoteAccess', 'Can IT access your computer remotely?'),
      fileField('attachments', 'Screenshots/Attachments', {
        validation: { multiple: true, maxFiles: 5 },
      }),
    ],
  }),

  // 3. Software Demo Request
  createTemplate({
    id: 'software-demo-request',
    name: 'Software Demo Request',
    shortDescription: 'Request a software product demo',
    fullDescription: 'Capture leads requesting product demonstrations. Includes qualification questions and scheduling preferences.',
    category: 'technology-it',
    icon: 'Monitor',
    complexity: 'simple',
    estimatedTime: 4,
    displayOrder: 3,
    tags: ['demo', 'software', 'sales', 'product'],
    useCases: [
      'SaaS demos',
      'Enterprise software',
      'Product trials',
      'Sales presentations',
    ],
    features: [
      'Lead qualification',
      'Use case capture',
      'Scheduling preferences',
      'Technical requirements',
    ],
    fieldConfigs: [
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Work Email', { required: true }),
      phoneField('phone', 'Phone Number'),
      textField('company', 'Company Name', { required: true, fieldWidth: 'half' }),
      textField('jobTitle', 'Job Title', { required: true, fieldWidth: 'half' }),
      selectField('companySize', 'Company Size', [
        '1-10 employees',
        '11-50 employees',
        '51-200 employees',
        '201-500 employees',
        '501-1000 employees',
        '1000+ employees',
      ], { required: true }),
      selectField('industry', 'Industry', [
        'Technology',
        'Healthcare',
        'Finance',
        'Education',
        'Manufacturing',
        'Retail',
        'Government',
        'Other',
      ]),
      selectField('role', 'Your Role', [
        'Individual Contributor',
        'Team Lead',
        'Manager',
        'Director',
        'VP',
        'C-Level',
        'Consultant',
      ]),
      multiSelectField('interests', 'Features of Interest', [
        'Core Platform',
        'Analytics & Reporting',
        'Integrations',
        'API Access',
        'Security & Compliance',
        'Mobile App',
        'Custom Development',
      ]),
      textareaField('useCase', 'Describe Your Use Case', {
        required: true,
        placeholder: 'What problem are you trying to solve?',
      }),
      selectField('timeline', 'Purchase Timeline', [
        'Immediate - Ready to buy',
        '1-3 months',
        '3-6 months',
        'Just evaluating',
      ]),
      selectField('currentSolution', 'Current Solution', [
        'None - This is new',
        'Competitor product',
        'In-house solution',
        'Manual/Spreadsheets',
        'Other',
      ]),
      selectField('demoType', 'Preferred Demo Type', [
        'Live 1-on-1 demo',
        'Group demo/webinar',
        'Self-guided trial',
        'Recorded demo video',
      ]),
      textareaField('questions', 'Questions for the Demo'),
    ],
  }),

  // 4. System Access Request
  createTemplate({
    id: 'system-access-request',
    name: 'System Access Request',
    shortDescription: 'Request access to systems and applications',
    fullDescription: 'Formal access request form with approval workflow. Captures access justification and required permissions.',
    category: 'technology-it',
    icon: 'Key',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 4,
    tags: ['access', 'permissions', 'security', 'request'],
    useCases: [
      'New employee access',
      'Role changes',
      'Project access',
      'Temporary access',
    ],
    features: [
      'Multi-system requests',
      'Permission levels',
      'Business justification',
      'Approval tracking',
    ],
    fieldConfigs: [
      sectionHeader('requester', 'Requester Information'),
      textField('requesterName', 'Your Name', { required: true }),
      emailField('requesterEmail', 'Your Email', { required: true }),
      textField('department', 'Department', { required: true }),
      textField('employeeId', 'Employee ID'),
      textField('managerName', 'Manager Name', { required: true }),
      emailField('managerEmail', 'Manager Email', { required: true }),
      sectionHeader('forWhom', 'Access For'),
      selectField('requestFor', 'Requesting Access For', [
        'Myself',
        'Another Employee',
        'Contractor/Vendor',
        'Multiple Users',
      ], { required: true }),
      textField('targetUserName', 'User Name (if different)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'requestFor', operator: 'equals', value: 'Another Employee' },
            { field: 'requestFor', operator: 'equals', value: 'Contractor/Vendor' },
          ],
        },
      }),
      emailField('targetUserEmail', 'User Email (if different)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'requestFor', operator: 'equals', value: 'Another Employee' },
            { field: 'requestFor', operator: 'equals', value: 'Contractor/Vendor' },
          ],
        },
      }),
      sectionHeader('access', 'Access Request'),
      multiSelectField('systems', 'Systems/Applications', [
        'Active Directory',
        'Email/Office 365',
        'VPN',
        'CRM (Salesforce)',
        'ERP System',
        'HR System',
        'Finance System',
        'Development Tools',
        'Source Control (Git)',
        'Production Servers',
        'Database Access',
        'Cloud Console (AWS/Azure/GCP)',
        'Other',
      ], { required: true }),
      textField('otherSystems', 'Specify Other Systems'),
      selectField('accessLevel', 'Access Level Needed', [
        'Read Only',
        'Read/Write',
        'Admin',
        'Custom',
      ], { required: true }),
      textareaField('specificPermissions', 'Specific Permissions Needed', {
        placeholder: 'Describe the specific access rights required...',
      }),
      sectionHeader('duration', 'Access Duration'),
      selectField('accessType', 'Access Type', [
        'Permanent',
        'Temporary',
        'Project-Based',
      ], { required: true }),
      dateField('startDate', 'Start Date', { required: true }),
      dateField('endDate', 'End Date (if temporary)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'accessType', operator: 'equals', value: 'Temporary' },
            { field: 'accessType', operator: 'equals', value: 'Project-Based' },
          ],
        },
      }),
      sectionHeader('justification', 'Business Justification'),
      textareaField('justification', 'Business Justification', {
        required: true,
        placeholder: 'Explain why this access is needed for job duties...',
        validation: { minLength: 50 },
      }),
      textField('projectName', 'Project Name (if applicable)'),
      yesNoField('sensitiveData', 'Will you access sensitive/PII data?', { required: true }),
      yesNoField('completedTraining', 'Have you completed required security training?', { required: true }),
    ],
  }),

  // 5. Security Incident Report
  createTemplate({
    id: 'security-incident-report',
    name: 'Security Incident Report',
    shortDescription: 'Report security incidents and concerns',
    fullDescription: 'Report potential security incidents, breaches, or suspicious activities. Enables rapid response and proper documentation.',
    category: 'technology-it',
    icon: 'ShieldAlert',
    complexity: 'moderate',
    estimatedTime: 8,
    displayOrder: 5,
    tags: ['security', 'incident', 'breach', 'report'],
    useCases: [
      'Security breaches',
      'Phishing attempts',
      'Suspicious activity',
      'Policy violations',
    ],
    features: [
      'Incident classification',
      'Impact assessment',
      'Timeline documentation',
      'Evidence collection',
    ],
    fieldConfigs: [
      sectionHeader('reporter', 'Reporter Information'),
      textField('reporterName', 'Your Name', { required: true }),
      emailField('reporterEmail', 'Email', { required: true }),
      textField('reporterDept', 'Department', { required: true }),
      phoneField('reporterPhone', 'Phone', { required: true }),
      sectionHeader('incident', 'Incident Details'),
      selectField('incidentType', 'Type of Incident', [
        'Phishing/Social Engineering',
        'Malware/Virus',
        'Unauthorized Access',
        'Data Breach/Leak',
        'Lost/Stolen Device',
        'Password Compromise',
        'Suspicious Email',
        'Physical Security',
        'Policy Violation',
        'Other',
      ], { required: true }),
      selectField('severity', 'Severity', [
        'Critical - Active breach, immediate action required',
        'High - Potential breach, urgent response needed',
        'Medium - Suspicious activity, investigation needed',
        'Low - Possible incident, monitoring needed',
        'Unknown - Need assessment',
      ], { required: true }),
      dateField('incidentDate', 'When Did This Occur?', { required: true }),
      textField('incidentTime', 'Approximate Time'),
      dateField('discoveryDate', 'When Was It Discovered?', { required: true }),
      sectionHeader('description', 'Description'),
      textareaField('description', 'Describe What Happened', {
        required: true,
        placeholder: 'Provide a detailed description of the incident...',
        validation: { minLength: 100 },
      }),
      textareaField('actionsTaken', 'Actions Already Taken', {
        placeholder: 'What have you done so far in response?',
      }),
      sectionHeader('impact', 'Potential Impact'),
      yesNoField('dataInvolved', 'Was data potentially accessed/exposed?', { required: true }),
      multiSelectField('dataTypes', 'Types of Data Involved', [
        'Personal/PII data',
        'Financial data',
        'Credentials/Passwords',
        'Business confidential',
        'Customer data',
        'Employee data',
        'Source code',
        'Unknown',
        'No data involved',
      ]),
      multiSelectField('systemsAffected', 'Systems Potentially Affected', [
        'Workstation',
        'Server',
        'Network',
        'Cloud services',
        'Mobile device',
        'Email',
        'Database',
        'Unknown',
      ]),
      textareaField('affectedUsers', 'Users/Accounts Potentially Affected'),
      sectionHeader('evidence', 'Evidence'),
      textareaField('indicators', 'Indicators of Compromise', {
        placeholder: 'IP addresses, email addresses, file names, etc.',
      }),
      fileField('evidence', 'Screenshots/Evidence', {
        validation: { multiple: true, maxFiles: 10 },
      }),
      yesNoField('preserved', 'Has evidence been preserved?'),
      sectionHeader('containment', 'Containment'),
      yesNoField('ongoing', 'Is the incident still ongoing?', { required: true }),
      yesNoField('contained', 'Has the incident been contained?'),
      textareaField('containmentActions', 'Containment Actions Needed/Taken'),
    ],
  }),

  // 6. Beta Tester Signup
  createTemplate({
    id: 'beta-tester-signup',
    name: 'Beta Tester Signup',
    shortDescription: 'Sign up to beta test software',
    fullDescription: 'Recruit and screen beta testers for new software features. Captures technical profile and testing availability.',
    category: 'technology-it',
    icon: 'FlaskConical',
    complexity: 'simple',
    estimatedTime: 5,
    displayOrder: 6,
    tags: ['beta', 'testing', 'feedback', 'early access'],
    useCases: [
      'Product beta programs',
      'Feature testing',
      'Early access programs',
      'User feedback collection',
    ],
    features: [
      'Technical profile',
      'Device information',
      'Testing availability',
      'Experience level',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('name', 'Full Name', { required: true }),
      emailField('email', 'Email Address', { required: true }),
      textField('company', 'Company/Organization'),
      selectField('country', 'Country', [
        'United States',
        'Canada',
        'United Kingdom',
        'Germany',
        'France',
        'Australia',
        'India',
        'Other',
      ]),
      sectionHeader('profile', 'Technical Profile'),
      selectField('techLevel', 'Technical Experience Level', [
        'Beginner - Basic computer user',
        'Intermediate - Comfortable with technology',
        'Advanced - Power user',
        'Expert - Developer/IT professional',
      ], { required: true }),
      selectField('primaryRole', 'Primary Role', [
        'End User',
        'System Administrator',
        'Developer',
        'Designer',
        'Product Manager',
        'QA/Tester',
        'Other',
      ]),
      multiSelectField('devices', 'Devices Available for Testing', [
        'Windows PC',
        'Mac',
        'Linux',
        'iPhone',
        'Android Phone',
        'iPad',
        'Android Tablet',
      ], { required: true }),
      multiSelectField('browsers', 'Browsers Used', [
        'Chrome',
        'Firefox',
        'Safari',
        'Edge',
        'Other',
      ]),
      sectionHeader('experience', 'Testing Experience'),
      yesNoField('previousBeta', 'Have you participated in beta programs before?'),
      textareaField('betaExperience', 'Describe your beta testing experience', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'previousBeta', operator: 'isTrue' }],
        },
      }),
      selectField('feedbackStyle', 'How do you prefer to provide feedback?', [
        'Written reports',
        'Video recordings',
        'Screenshots with annotations',
        'Live feedback sessions',
        'Any method',
      ]),
      sectionHeader('availability', 'Availability'),
      selectField('timeCommitment', 'Time Available for Testing (weekly)', [
        '1-2 hours',
        '3-5 hours',
        '5-10 hours',
        '10+ hours',
      ], { required: true }),
      multiSelectField('availability', 'Best Days for Testing', [
        'Weekdays',
        'Weekends',
        'Any day',
      ]),
      selectField('responseTime', 'Typical Response Time for Feedback', [
        'Same day',
        'Within 2-3 days',
        'Within a week',
      ]),
      sectionHeader('interest', 'Areas of Interest'),
      multiSelectField('interests', 'Features You\'re Most Interested In', [
        'Core functionality',
        'Mobile experience',
        'Performance',
        'Integrations',
        'Security features',
        'UI/UX',
        'All features',
      ]),
      textareaField('expectations', 'What do you hope to gain from beta testing?'),
      yesNoField('nda', 'Are you willing to sign an NDA?', { required: true }),
      yesNoField('interviews', 'Would you participate in feedback interviews?'),
    ],
  }),
];
