import type { FormTemplate } from '../types';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  fileField,
  sectionHeader,
  addressField,
} from '../helpers';

export const travelTourismTemplates: FormTemplate[] = [
  createTemplate({
    id: 'travel-booking-inquiry',
    name: 'Travel Booking Inquiry',
    description: 'Capture travel requests and preferences for booking assistance',
    category: 'travel-tourism',
    icon: '✈️',
    complexity: 'intermediate',
    estimatedTime: '5-7 min',
    formType: 'both',
    featured: true,
    fields: [
      sectionHeader('Traveler Information'),
      textField('full_name', 'Full Name (as on ID)', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      dateField('date_of_birth', 'Date of Birth', true),
      textField('passport_number', 'Passport Number', false),
      selectField('nationality', 'Nationality', [
        'United States', 'Canada', 'United Kingdom', 'Australia', 'Germany',
        'France', 'Japan', 'China', 'India', 'Brazil', 'Other'
      ], true),
      sectionHeader('Trip Details'),
      selectField('trip_type', 'Trip Type', [
        'Round Trip', 'One Way', 'Multi-City'
      ], true),
      textField('departure_city', 'Departure City', true),
      textField('destination', 'Destination(s)', true),
      dateField('departure_date', 'Departure Date', true),
      dateField('return_date', 'Return Date', false),
      selectField('travel_class', 'Preferred Travel Class', [
        'Economy', 'Premium Economy', 'Business', 'First Class', 'Flexible'
      ], true),
      numberField('num_travelers', 'Number of Travelers', true, 1, 20),
      sectionHeader('Accommodation Preferences'),
      yesNoField('need_hotel', 'Do you need hotel accommodation?', true),
      selectField('hotel_type', 'Hotel Type Preference', [
        'Budget', 'Mid-Range', 'Luxury', 'Resort', 'Boutique', 'No Preference'
      ], false),
      selectField('room_type', 'Room Type', [
        'Single', 'Double', 'Twin', 'Suite', 'Family Room'
      ], false),
      sectionHeader('Additional Services'),
      yesNoField('need_car_rental', 'Do you need car rental?', false),
      yesNoField('need_travel_insurance', 'Interested in travel insurance?', false),
      yesNoField('need_airport_transfer', 'Need airport transfer?', false),
      currencyField('budget', 'Total Budget (USD)', false),
      textareaField('special_requests', 'Special Requests or Notes', false),
    ],
    tags: ['travel', 'booking', 'vacation', 'flights', 'hotels'],
    useCases: ['Travel agencies', 'Tour operators', 'Corporate travel desks'],
    enhanced: {
      headline: 'Turn Travel Inquiries into Booked Trips',
      subheadline: 'Capture complete travel requests with preferences, budgets, and timelines—giving your agents everything they need to book faster and upsell smarter.',
      longDescription: {
        opening: 'Travel inquiries arrive through email, phone, WhatsApp, and your website—each in different formats with incomplete information. Agents spend 30 minutes per inquiry asking follow-up questions: "What dates?" "How many travelers?" "Do you need a hotel?" By the time you have complete information, the client has already booked through Expedia. Competitors with instant online quotes are eating your margins.',
        solution: 'This template captures complete travel requests in one submission: traveler details with passport information, trip type and routing, travel class preferences, number of travelers, accommodation needs with hotel type preferences, and add-on services like car rental, insurance, and airport transfers. Budget fields help agents find options within range. Special requests capture dietary needs, accessibility requirements, and anniversary celebrations.',
        outcome: 'Quote trips in 2 hours instead of 2 days with complete requirements upfront. Increase average booking value by 25% with systematic upselling of transfers, insurance, and room upgrades. Reduce back-and-forth emails by 80%. Track conversion rates by trip type, destination, and lead source. Build a preference database for repeat travelers that makes rebooking instant.',
      },
      useCases: [
        {
          title: 'Boutique Travel Agency',
          icon: '✈️',
          industry: 'Travel',
          scenario: 'Your travel agency handles 50+ inquiries per week across honeymoon trips, family vacations, and adventure travel. Email inquiries range from one-sentence requests to detailed itineraries. Agents waste hours qualifying leads and gathering missing information.',
          painPoint: 'Inconsistent inquiry formats make quoting slow. No systematic capture of preferences and budget. Agents ask the same questions repeatedly. Can\'t track which trip types generate the most revenue.',
          keyFields: ['Trip Type', 'Destination(s)', 'Preferred Travel Class', 'Total Budget (USD)'],
          exampleOrganization: 'A boutique travel agency booking $2M annually, losing 40% of inquiries to slow response times.',
        },
        {
          title: 'Corporate Travel Management',
          icon: '💼',
          industry: 'Corporate',
          scenario: 'Your company books 200+ business trips monthly. Employees email travel requests with varying detail—some specify exact flights, others just say "NYC next week." Travel coordinators chase down details while executives wait for confirmations. Policy compliance is inconsistent.',
          painPoint: 'Incomplete trip requests delay booking. No standardized capture of travel preferences and approvals. Can\'t enforce travel policy at request stage. Reporting on travel spend requires manual data compilation.',
          keyFields: ['Departure City', 'Destination(s)', 'Departure Date', 'Preferred Travel Class'],
          exampleOrganization: 'A 500-employee company spending $1.5M annually on travel, with 30% of bookings requiring rebooking due to incomplete initial requests.',
        },
        {
          title: 'Destination Wedding Planner',
          icon: '💒',
          industry: 'Events',
          scenario: 'You plan destination weddings and need to coordinate travel for 50-150 guests per event. Guest travel preferences vary wildly—some want luxury resorts, others need budget options. Coordinating group flights and room blocks requires detailed preference capture.',
          painPoint: 'Guest preferences collected inconsistently. Can\'t coordinate group bookings without standardized data. Room block management is chaotic. No way to track which guests have booked.',
          keyFields: ['Number of Travelers', 'Hotel Type Preference', 'Do you need hotel accommodation?', 'Special Requests or Notes'],
          exampleOrganization: 'A destination wedding planner coordinating 20+ weddings annually, spending 10+ hours per wedding on travel coordination.',
        },
        {
          title: 'Adventure Tour Operator',
          icon: '🏔️',
          industry: 'Tourism',
          scenario: 'Your adventure tour company runs trips to 15+ destinations. Travelers have specific fitness levels, dietary restrictions, and gear requirements. Incomplete intake leads to mismatched expectations and bad reviews when travelers aren\'t prepared.',
          painPoint: 'Critical health and fitness information collected inconsistently. Dietary needs missed until arrival. Gear requirements communicated poorly. Emergency contact information incomplete.',
          keyFields: ['Number of Travelers', 'Need travel insurance?', 'Special Requests or Notes', 'Date of Birth'],
          exampleOrganization: 'An adventure tour operator running 100+ trips annually, with 15% of travelers arriving unprepared due to incomplete intake.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Loyalty Program Integration',
          description: 'Capture frequent flyer numbers, hotel loyalty memberships, and TSA PreCheck status to book with preferred programs and expedite travel.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Enable Multi-Traveler Capture',
          description: 'Add repeating fields for additional travelers with name (as on passport), date of birth, and passport number for each party member.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Connect Flight Search API',
          description: 'Integrate with Amadeus or Sabre GDS API to show real-time flight options and pricing based on submitted preferences.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
        {
          title: 'Add Travel Document Checklist',
          description: 'Based on destination and nationality, automatically generate required document checklist (visa, vaccination, travel insurance requirements).',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Include Previous Trip History',
          description: 'For returning clients, pre-populate preferences from previous bookings to speed up the request process.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'instant-notification',
          title: 'Alert Agent for Hot Leads',
          description: 'Notify assigned travel consultant immediately when inquiry is submitted. Include trip summary, budget, and travel dates. High-budget trips ($10K+) get SMS alerts for priority response.',
          trigger: 'On form submission',
          benefits: ['Respond within 1 hour instead of 24 hours', 'High-value leads prioritized automatically', 'Complete trip details in notification'],
        },
        {
          workflowType: 'auto-response',
          title: 'Send Inquiry Confirmation',
          description: 'Immediately email traveler confirming receipt with summary of their request. Include destination highlights, travel tips, and expected quote timeline.',
          trigger: 'On form submission',
          benefits: ['Traveler knows inquiry was received', 'Reduces "did you get my email?" calls', 'Professional first impression'],
        },
        {
          workflowType: 'crm-sync',
          title: 'Create Traveler Profile',
          description: 'Automatically create or update traveler profile in your CRM/booking system with preferences, passport details, and trip history for faster future bookings.',
          trigger: 'On form submission',
          benefits: ['No duplicate data entry', 'Preferences available for future trips', 'Complete traveler history in one place'],
        },
        {
          workflowType: 'conditional-routing',
          title: 'Route by Destination Specialist',
          description: 'Automatically route inquiries to agents based on expertise: Caribbean specialist for beach vacations, adventure team for trekking trips, luxury consultant for premium requests.',
          trigger: 'On submission based on destination and trip type',
          benefits: ['Inquiries handled by specialists', 'Faster, more accurate quotes', 'Better conversion from expertise match'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Date fields for departure/return enable calendar-based availability checking',
          'Budget stored as currency for price range filtering and revenue forecasting',
          'Boolean add-on fields (car rental, insurance, transfers) support upsell tracking',
        ],
        integrationHints: [
          'GDS API (Amadeus, Sabre, Travelport) for real-time flight and hotel inventory',
          'Travel CRM (ClientBase, Travefy) for traveler profile management',
          'SMS gateway for high-priority inquiry alerts',
        ],
        mongoDBConsiderations: [
          'Index on {departure_date: 1, destination: 1} for trip availability queries',
          'Index on {budget: 1, travel_class: 1} for pricing segment analysis',
          'Text index on destination and special_requests for search functionality',
          'Consider geospatial index if storing destination coordinates for distance calculations',
        ],
      },
      seo: {
        metaTitle: 'Travel Booking Inquiry Form Template | NetPad',
        metaDescription: 'Free travel booking form template for agencies. Capture trip details, preferences, and budget to quote faster and book more trips.',
        keywords: ['travel booking form', 'trip inquiry form', 'travel agency form', 'vacation request form', 'travel consultation'],
        ogDescription: 'Stop chasing travel details through email. This inquiry form captures complete trip requirements for faster quoting and higher booking rates.',
      },
      socialProofAngles: [
        'Faster quote turnaround time',
        'Higher booking conversion rates',
        'Increased upsell revenue from add-ons',
        'Better client preference tracking',
      ],
    },
  }),

  createTemplate({
    id: 'tour-package-booking',
    name: 'Tour Package Booking',
    description: 'Book guided tours and travel packages with all details',
    category: 'travel-tourism',
    icon: '🗺️',
    complexity: 'advanced',
    estimatedTime: '8-12 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Lead Traveler Details'),
      textField('lead_name', 'Lead Traveler Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      addressField('address', 'Billing Address', true),
      sectionHeader('Tour Selection'),
      selectField('tour_package', 'Select Tour Package', [
        'City Explorer (3 days)', 'Cultural Heritage (5 days)', 'Adventure Trek (7 days)',
        'Beach Paradise (5 days)', 'Mountain Escape (4 days)', 'Custom Package'
      ], true),
      dateField('preferred_start_date', 'Preferred Start Date', true),
      dateField('alternate_date', 'Alternate Date', false),
      sectionHeader('Group Details'),
      numberField('adults', 'Number of Adults', true, 1, 20),
      numberField('children', 'Number of Children (2-12 years)', false, 0, 10),
      numberField('infants', 'Number of Infants (under 2)', false, 0, 5),
      sectionHeader('Room Preferences'),
      selectField('room_config', 'Room Configuration', [
        'Single Rooms', 'Double/Twin Sharing', 'Triple Sharing', 'Family Rooms'
      ], true),
      selectField('meal_plan', 'Meal Plan', [
        'Breakfast Only', 'Half Board (B+D)', 'Full Board (B+L+D)', 'All Inclusive'
      ], true),
      sectionHeader('Dietary & Accessibility'),
      selectField('dietary_requirements', 'Dietary Requirements', [
        'None', 'Vegetarian', 'Vegan', 'Halal', 'Kosher', 'Gluten-Free', 'Other'
      ], false),
      textareaField('dietary_notes', 'Specific Dietary Notes', false),
      yesNoField('accessibility_needs', 'Any accessibility requirements?', true),
      textareaField('accessibility_details', 'Accessibility Details', false),
      sectionHeader('Add-ons & Extras'),
      yesNoField('travel_insurance', 'Add Travel Insurance', false),
      yesNoField('airport_transfers', 'Include Airport Transfers', false),
      yesNoField('photography_package', 'Add Photography Package', false),
      textareaField('special_occasions', 'Special Occasions to Celebrate', false),
      sectionHeader('Payment'),
      selectField('payment_method', 'Payment Method', [
        'Credit Card', 'Bank Transfer', 'PayPal', 'Pay in Installments'
      ], true),
      textareaField('additional_notes', 'Additional Notes or Questions', false),
    ],
    tags: ['tour', 'package', 'group travel', 'vacation', 'guided tour'],
    useCases: ['Tour operators', 'Travel agencies', 'Resort packages'],
    enhanced: {
      headline: 'Book Tour Groups Without the Spreadsheet Chaos',
      subheadline: 'Capture every detail for guided tours—from dietary restrictions to room configurations—so your operations team can deliver flawless experiences.',
      longDescription: {
        opening: 'Tour packages involve dozens of moving parts per booking: room configurations for families and couples, dietary requirements for every meal, accessibility needs, airport transfers, and add-on excursions. One missed detail ruins the experience. When a vegetarian gets served meat, when a mobility-impaired guest arrives at a property without an elevator, when the honeymoon couple ends up in twin beds—you get 1-star reviews. Coordinating this through email threads and spreadsheets is a recipe for errors.',
        solution: 'This template captures comprehensive tour bookings: lead traveler contact and billing information, package selection with preferred dates, complete group composition (adults, children, infants), room configuration preferences, meal plan selection, dietary requirements for each traveler, accessibility needs with detailed descriptions, add-on services (insurance, transfers, photography), special occasions to celebrate, and payment preferences including installment options.',
        outcome: 'Deliver seamless tour experiences with zero-error operations. Dietary requirements automatically forwarded to hotel and restaurant partners. Accessibility needs flagged for property verification before confirmation. Room configurations matched to group composition. Special occasions (anniversaries, birthdays) noted for surprise touches. Reduce post-booking modifications by 70% with complete upfront capture.',
      },
      useCases: [
        {
          title: 'Multi-Day Tour Operator',
          icon: '🗺️',
          industry: 'Tourism',
          scenario: 'Your company runs 7-14 day guided tours across Europe. Each tour group has 20-40 travelers with complex requirements: couples wanting king beds, solo travelers needing single supplements, vegetarians, guests with mobility limitations. Operations coordinates with 10+ hotels and restaurants per tour.',
          painPoint: 'Guest requirements scattered across emails and booking notes. Hotel manifests created manually with frequent errors. Dietary needs communicated inconsistently to restaurants. Accessibility mismatches discovered at check-in.',
          keyFields: ['Room Configuration', 'Meal Plan', 'Dietary Requirements', 'Any accessibility requirements?'],
          exampleOrganization: 'A tour operator running 50+ multi-country tours annually, experiencing 15% of travelers with unmet special requirements.',
        },
        {
          title: 'Destination Resort Packages',
          icon: '🏝️',
          industry: 'Hospitality',
          scenario: 'Your all-inclusive resort sells 5-night packages direct to consumers. Guests book packages that include room, meals, and activities. You need complete guest information before arrival for room assignment, restaurant reservations, and activity scheduling.',
          painPoint: 'Incomplete guest profiles lead to wrong room assignments. Dietary needs discovered at dinner. Activity preferences unknown until arrival. Special occasions missed.',
          keyFields: ['Number of Adults', 'Number of Children (2-12 years)', 'Dietary Requirements', 'Special Occasions to Celebrate'],
          exampleOrganization: 'A 200-room all-inclusive resort with 80% package bookings, spending 5+ hours daily on pre-arrival guest coordination.',
        },
        {
          title: 'Adventure Travel Company',
          icon: '🥾',
          industry: 'Adventure Tourism',
          scenario: 'Your adventure company runs trekking, safari, and expedition tours. Participants need varying fitness levels, specific gear, and medical clearance. Incomplete intake leads to unprepared travelers, safety incidents, and negative experiences.',
          painPoint: 'Fitness levels self-reported inaccurately. Medical conditions discovered mid-trek. Gear requirements not communicated. Emergency contact information incomplete.',
          keyFields: ['Lead Traveler Name', 'Any accessibility requirements?', 'Accessibility Details', 'Add Travel Insurance'],
          exampleOrganization: 'An adventure tour company with 30% of trips requiring participant support due to inadequate pre-trip screening.',
        },
        {
          title: 'Group Travel Coordinator',
          icon: '👥',
          industry: 'Travel',
          scenario: 'You organize group trips for alumni associations, professional groups, and affinity organizations. Groups of 30-100 travelers need coordinated bookings with individual preferences, payment tracking, and roster management.',
          painPoint: 'Individual preferences collected through multiple email threads. Payment status tracked manually in spreadsheets. Roster changes create coordination nightmares. Group leaders overwhelmed with logistics.',
          keyFields: ['Number of Adults', 'Payment Method', 'Additional Notes or Questions', 'Include Airport Transfers'],
          exampleOrganization: 'A group travel coordinator managing 15+ group trips annually with 50+ participants each, spending 20+ hours per trip on data coordination.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Per-Traveler Details',
          description: 'Create repeating fields for each traveler in the group: name, DOB, passport number, dietary requirements, and emergency contact.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Enable Package Customization',
          description: 'Allow guests to select optional excursions, room upgrades, and meal enhancements as add-ons to base packages.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Add Deposit Calculator',
          description: 'Calculate required deposit based on package price, number of travelers, and selected add-ons. Show total and payment schedule.',
          fieldSuggestion: 'currency',
          difficulty: 'advanced',
        },
        {
          title: 'Include Medical Questionnaire',
          description: 'For adventure tours, add health screening questions to assess fitness levels and identify conditions requiring accommodation.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Enable Group Roster Management',
          description: 'For group bookings, allow lead traveler to add/edit participant details and track individual payment status.',
          fieldSuggestion: 'textarea',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'booking-confirmation',
          title: 'Send Detailed Confirmation',
          description: 'Immediately email comprehensive booking confirmation: package details, dates, room configuration, included meals and activities, special requests acknowledged, payment schedule, and cancellation policy.',
          trigger: 'On form submission',
          benefits: ['Guests have complete booking reference', 'Reduces confirmation-related inquiries', 'Sets clear expectations'],
        },
        {
          workflowType: 'operations-sync',
          title: 'Create Operations Manifest',
          description: 'Automatically generate guest manifest for operations team: room list with configurations, dietary requirements summary, accessibility needs, transfer schedules, and special occasions.',
          trigger: 'On booking confirmation',
          benefits: ['Operations team has complete guest data', 'No manual manifest creation', 'Dietary and accessibility requirements flagged'],
        },
        {
          workflowType: 'payment-reminder',
          title: 'Balance Payment Reminders',
          description: 'For installment payments, automatically send balance reminders at 60, 30, and 14 days before departure with payment link and outstanding amount.',
          trigger: 'Scheduled based on departure date and payment plan',
          benefits: ['Reduces late payments and cancellations', 'Automatic reminder sequence', 'Payment link for easy completion'],
        },
        {
          workflowType: 'pre-departure',
          title: 'Send Pre-Departure Information',
          description: 'Automatically send packing list, weather forecast, visa requirements, emergency contacts, and day-by-day itinerary 14 days before departure.',
          trigger: '14 days before departure date',
          benefits: ['Guests arrive prepared', 'Reduces pre-departure inquiries', 'Professional pre-trip communication'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Group composition stored as separate adult/child/infant counts for accurate pricing',
          'Dietary requirements as select with "Other" option plus free-text notes field',
          'Payment method includes installment option requiring balance tracking',
        ],
        integrationHints: [
          'Tour operator software (Tourwriter, Rezdy) for inventory and operations management',
          'Payment gateway with installment plan support (Stripe, PayPal)',
          'Hotel/supplier APIs for real-time availability and manifest distribution',
        ],
        mongoDBConsiderations: [
          'Index on {tour_package: 1, preferred_start_date: 1} for package availability queries',
          'Index on {dietary_requirements: 1} for meal planning aggregation',
          'Store payment schedule as array of {due_date, amount, status} for balance tracking',
          'Consider embedded documents for additional passenger details to maintain booking atomicity',
        ],
      },
      seo: {
        metaTitle: 'Tour Package Booking Form Template | NetPad',
        metaDescription: 'Free tour booking template for operators. Capture group details, dietary needs, and accessibility requirements for seamless tour operations.',
        keywords: ['tour booking form', 'package booking form', 'group travel form', 'guided tour booking', 'tour operator form'],
        ogDescription: 'Stop losing tour details in email threads. This booking form captures everything operations needs for flawless tour delivery.',
      },
      socialProofAngles: [
        'Zero-error tour operations',
        'Complete guest requirements upfront',
        'Streamlined operations manifests',
        'Reduced pre-departure inquiries',
      ],
    },
  }),

  createTemplate({
    id: 'visa-application-form',
    name: 'Visa Application Assistance',
    description: 'Collect information for visa application processing',
    category: 'travel-tourism',
    icon: '🛂',
    complexity: 'advanced',
    estimatedTime: '15-20 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Personal Information'),
      textField('surname', 'Surname (Family Name)', true),
      textField('given_names', 'Given Names', true),
      dateField('dob', 'Date of Birth', true),
      textField('place_of_birth', 'Place of Birth', true),
      selectField('gender', 'Gender', ['Male', 'Female', 'Other'], true),
      selectField('marital_status', 'Marital Status', [
        'Single', 'Married', 'Divorced', 'Widowed', 'Separated'
      ], true),
      selectField('nationality', 'Current Nationality', [
        'United States', 'Canada', 'United Kingdom', 'Australia', 'Germany',
        'France', 'Japan', 'China', 'India', 'Brazil', 'Mexico', 'Other'
      ], true),
      sectionHeader('Passport Details'),
      textField('passport_number', 'Passport Number', true),
      dateField('passport_issue_date', 'Issue Date', true),
      dateField('passport_expiry_date', 'Expiry Date', true),
      textField('issuing_authority', 'Issuing Authority', true),
      sectionHeader('Contact Information'),
      addressField('current_address', 'Current Residential Address', true),
      phoneField('phone', 'Phone Number', true),
      emailField('email', 'Email Address', true),
      sectionHeader('Travel Details'),
      selectField('visa_type', 'Visa Type Requested', [
        'Tourist', 'Business', 'Student', 'Work', 'Transit', 'Medical'
      ], true),
      textField('destination_country', 'Destination Country', true),
      dateField('intended_arrival', 'Intended Arrival Date', true),
      dateField('intended_departure', 'Intended Departure Date', true),
      textField('accommodation_address', 'Accommodation Address at Destination', true),
      sectionHeader('Employment Information'),
      selectField('employment_status', 'Employment Status', [
        'Employed', 'Self-Employed', 'Student', 'Retired', 'Unemployed', 'Other'
      ], true),
      textField('employer_name', 'Employer/School Name', false),
      textField('employer_address', 'Employer/School Address', false),
      textField('job_title', 'Job Title/Course of Study', false),
      sectionHeader('Financial Information'),
      selectField('trip_funding', 'Who is funding this trip?', [
        'Self', 'Employer', 'Family Member', 'Sponsor', 'Scholarship', 'Other'
      ], true),
      currencyField('monthly_income', 'Monthly Income (USD)', false),
      sectionHeader('Travel History'),
      yesNoField('previous_visa', 'Have you previously held a visa for this country?', true),
      textareaField('previous_visa_details', 'Previous Visa Details', false),
      yesNoField('visa_denied', 'Has a visa ever been denied?', true),
      textareaField('denial_details', 'Denial Details (if applicable)', false),
      sectionHeader('Documents'),
      fileField('passport_copy', 'Passport Bio Page Copy', true, '.pdf,.jpg,.png'),
      fileField('photo', 'Passport Photo', true, '.jpg,.png'),
      fileField('bank_statement', 'Bank Statement (last 3 months)', false, '.pdf'),
      fileField('employment_letter', 'Employment/Enrollment Letter', false, '.pdf'),
      fileField('travel_itinerary', 'Travel Itinerary', false, '.pdf'),
    ],
    tags: ['visa', 'immigration', 'travel documents', 'passport'],
    useCases: ['Visa agencies', 'Immigration services', 'Travel agencies'],
    enhanced: {
      headline: 'Process Visa Applications Without Missing Documents',
      subheadline: 'Collect complete visa application data with document uploads and validation—reducing rejections and processing delays caused by incomplete submissions.',
      longDescription: {
        opening: 'Visa applications are rejected for preventable reasons: missing passport pages, incorrect photo specifications, incomplete employment history, undisclosed travel records. Each rejection costs your client weeks of delay and potentially hundreds in resubmission fees. Your agency spends hours chasing missing documents through email, only to discover another gap when you assemble the package. Consulates have zero tolerance for incomplete applications.',
        solution: 'This template captures everything consulates require: complete personal information matching passport exactly, passport details with validity verification, current address and contact information, visa type and travel dates, detailed employment or student status, financial sponsorship information, complete travel history including previous visas and denials, and document uploads for passport bio page, photos, bank statements, employment letters, and itineraries.',
        outcome: 'Submit complete visa packages on first attempt. Required fields ensure no critical information is missing. Document upload checklist with format specifications prevents photo rejections. Previous denial disclosure allows proper explanation letters. Reduce rejection rates by 80% and processing time by 50%. Build a client document repository for future applications.',
      },
      useCases: [
        {
          title: 'Visa Processing Agency',
          icon: '🛂',
          industry: 'Immigration Services',
          scenario: 'Your visa agency processes 200+ applications monthly across 30+ countries. Each country has different requirements. Clients submit information piecemeal—passport scan today, employment letter next week, bank statement after reminder. Staff chase documents instead of processing applications.',
          painPoint: 'Country-specific requirements not captured systematically. Document collection takes 3-4 rounds of follow-up. Applications assembled with missing pieces. Staff time wasted on document chasing instead of processing.',
          keyFields: ['Visa Type Requested', 'Passport Bio Page Copy', 'Bank Statement (last 3 months)', 'Employment/Enrollment Letter'],
          exampleOrganization: 'A visa agency processing 200+ applications monthly with 25% rejection rate due to incomplete documentation.',
        },
        {
          title: 'Corporate Travel Department',
          icon: '💼',
          industry: 'Corporate',
          scenario: 'Your company sends employees on international assignments requiring work visas. HR coordinates with immigration attorneys but employees provide incomplete information. Visa delays impact project timelines and cost thousands in delayed starts.',
          painPoint: 'Employee information collected inconsistently. Previous travel history incomplete. Document gathering delays visa processing. No centralized tracking of employee visa status.',
          keyFields: ['Employment Status', 'Employer/School Name', 'Have you previously held a visa for this country?', 'Has a visa ever been denied?'],
          exampleOrganization: 'A multinational company with 50+ international assignments annually, experiencing 30% visa delays due to incomplete employee documentation.',
        },
        {
          title: 'Education Abroad Office',
          icon: '🎓',
          industry: 'Education',
          scenario: 'Your university sends 500+ students abroad annually for study abroad, internships, and research. Student visa applications require academic enrollment verification, financial proof, and health insurance. Incomplete applications delay departure or prevent travel entirely.',
          painPoint: 'Students underestimate visa complexity and timeline. Financial documentation requirements vary by country. Health and insurance requirements often missed. Incomplete applications discovered too late.',
          keyFields: ['Visa Type Requested', 'Employment Status', 'Who is funding this trip?', 'Travel Itinerary'],
          exampleOrganization: 'A university study abroad office processing 500+ student visas annually, with 20% requiring emergency expedited processing due to delays.',
        },
        {
          title: 'Immigration Law Firm',
          icon: '⚖️',
          industry: 'Legal',
          scenario: 'Your immigration practice handles complex visa cases: H-1B petitions, investor visas, asylum applications. Each case requires extensive documentation and precise information. Client intake through email creates disorganized case files and missed deadlines.',
          painPoint: 'Complex documentation requirements tracked manually. Client information scattered across emails. Previous immigration history incomplete. Deadline tracking is manual and error-prone.',
          keyFields: ['Current Nationality', 'Have you previously held a visa for this country?', 'Has a visa ever been denied?', 'Denial Details (if applicable)'],
          exampleOrganization: 'An immigration law firm handling 100+ complex visa cases annually, spending 5+ hours per case on document organization.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Country-Specific Requirements',
          description: 'Use conditional logic to show additional fields based on destination country: Schengen insurance requirements, US DS-160 supplement questions, UK financial thresholds.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
        {
          title: 'Include Photo Specification Guide',
          description: 'Add photo requirements (size, background color, recency) based on destination country. Include sample acceptable/unacceptable photos.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Family Application Grouping',
          description: 'For family visa applications, allow adding spouse and dependent information in a single submission with linked case tracking.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Add Document Expiration Tracking',
          description: 'Capture document expiration dates (passport, bank statements) to flag applications where documents will expire before visa issuance.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
        {
          title: 'Include Appointment Scheduling',
          description: 'For countries requiring biometrics appointments, integrate appointment booking based on application submission.',
          fieldSuggestion: 'date',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'document-checklist',
          title: 'Send Document Requirements',
          description: 'Based on visa type and destination, automatically email applicant with complete document checklist, specification requirements (photo size, statement date range), and submission deadline.',
          trigger: 'On form submission',
          benefits: ['Applicants know exactly what to provide', 'Reduces back-and-forth clarification', 'Country-specific requirements automated'],
        },
        {
          workflowType: 'completeness-check',
          title: 'Validate Application Completeness',
          description: 'Automatically check submission for completeness: all required fields populated, documents uploaded, passport validity sufficient. Flag incomplete applications before processing begins.',
          trigger: 'On form submission',
          benefits: ['Catch incomplete applications immediately', 'Reduce processing of incomplete files', 'Instant feedback to applicants'],
        },
        {
          workflowType: 'case-tracking',
          title: 'Create Case File',
          description: 'Automatically create case file in immigration case management system with all application data, uploaded documents, and processing timeline based on visa type.',
          trigger: 'On form submission',
          benefits: ['No manual case file creation', 'Documents organized automatically', 'Processing timeline established'],
        },
        {
          workflowType: 'status-updates',
          title: 'Send Processing Updates',
          description: 'Automatically notify applicants at key milestones: application received, documents verified, submitted to consulate, interview scheduled, decision received.',
          trigger: 'On case status change',
          benefits: ['Applicants informed throughout process', 'Reduces status inquiry calls', 'Professional communication sequence'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Personal information fields match passport data requirements exactly (surname/given names split)',
          'Date fields for passport validity enable automatic expiration checking',
          'Boolean fields for previous visas and denials support disclosure compliance',
        ],
        integrationHints: [
          'Immigration case management systems (INSZoom, Docketwise) for case tracking',
          'Document storage (AWS S3, Azure Blob) with encryption for sensitive files',
          'Calendar/scheduling API for biometrics appointment booking',
        ],
        mongoDBConsiderations: [
          'Index on {destination_country: 1, visa_type: 1} for requirement matching',
          'Index on {passport_expiry_date: 1} for validity alerts',
          'Store documents as references to encrypted blob storage, not embedded',
          'Consider field-level encryption for SSN equivalent fields (passport number)',
        ],
      },
      seo: {
        metaTitle: 'Visa Application Form Template | NetPad',
        metaDescription: 'Free visa application template with document uploads. Collect complete applicant information to reduce rejections and processing delays.',
        keywords: ['visa application form', 'immigration form', 'visa assistance form', 'travel visa form', 'visa document collection'],
        ogDescription: 'Stop visa rejections from incomplete applications. This template captures everything consulates require with document validation.',
      },
      socialProofAngles: [
        'Reduced visa rejection rates',
        'Faster application processing',
        'Complete documentation on first submission',
        'Professional client experience',
      ],
    },
  }),

  createTemplate({
    id: 'hotel-guest-registration',
    name: 'Hotel Guest Registration',
    description: 'Digital check-in form for hotel guests',
    category: 'travel-tourism',
    icon: '🏨',
    complexity: 'simple',
    estimatedTime: '3-5 min',
    formType: 'both',
    featured: true,
    fields: [
      sectionHeader('Guest Information'),
      textField('full_name', 'Full Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      dateField('dob', 'Date of Birth', true),
      selectField('id_type', 'ID Type', [
        'Passport', 'Driver\'s License', 'National ID', 'Other'
      ], true),
      textField('id_number', 'ID Number', true),
      selectField('nationality', 'Nationality', [
        'United States', 'Canada', 'United Kingdom', 'Australia', 'Germany',
        'France', 'Japan', 'China', 'India', 'Brazil', 'Other'
      ], true),
      addressField('home_address', 'Home Address', true),
      sectionHeader('Reservation Details'),
      textField('confirmation_number', 'Reservation Confirmation Number', false),
      dateField('check_in_date', 'Check-in Date', true),
      dateField('check_out_date', 'Check-out Date', true),
      numberField('num_guests', 'Number of Guests', true, 1, 10),
      sectionHeader('Preferences & Requests'),
      selectField('bed_preference', 'Bed Preference', [
        'King', 'Queen', 'Two Double', 'Two Twin', 'No Preference'
      ], false),
      selectField('floor_preference', 'Floor Preference', [
        'Low Floor', 'High Floor', 'No Preference'
      ], false),
      yesNoField('smoking_room', 'Smoking Room?', true),
      yesNoField('late_checkout', 'Request Late Checkout?', false),
      textareaField('special_requests', 'Special Requests', false),
      sectionHeader('Vehicle Information (if applicable)'),
      yesNoField('has_vehicle', 'Arriving with vehicle?', false),
      textField('vehicle_make', 'Vehicle Make/Model', false),
      textField('license_plate', 'License Plate Number', false),
      sectionHeader('Emergency Contact'),
      textField('emergency_name', 'Emergency Contact Name', true),
      phoneField('emergency_phone', 'Emergency Contact Phone', true),
    ],
    tags: ['hotel', 'check-in', 'guest registration', 'hospitality'],
    useCases: ['Hotels', 'Resorts', 'Vacation rentals', 'B&Bs'],
    enhanced: {
      headline: 'Check In Guests Before They Arrive',
      subheadline: 'Replace paper registration cards with digital pre-arrival check-in—guests walk in, get their keys, and head to their rooms in under 2 minutes.',
      longDescription: {
        opening: 'Front desk check-in is a bottleneck. Guests arrive tired from travel, wait in line, then spend 5-10 minutes filling out paper registration cards with information you already have from their reservation. Staff manually enter data into the PMS, make transcription errors, and file paper cards that are impossible to search. During peak check-in hours (3-6 PM), lines stretch across the lobby while guests grow frustrated.',
        solution: 'This template enables digital pre-arrival registration: guest identification with ID type and number for compliance, nationality for reporting, home address, reservation confirmation linking, check-in/out dates, number of guests, room and floor preferences, special requests, vehicle information for parking, and emergency contacts. Guests complete registration on their phone before arrival.',
        outcome: 'Reduce check-in time from 8 minutes to 90 seconds. Eliminate paper registration cards and manual data entry. Guest preferences pre-loaded in PMS for room assignment. Vehicle information enables valet efficiency. Emergency contacts on file before arrival. Achieve 70%+ pre-arrival registration rates with email/SMS reminders. Improve TripAdvisor scores with smooth arrivals.',
      },
      useCases: [
        {
          title: 'Full-Service Hotel',
          icon: '🏨',
          industry: 'Hospitality',
          scenario: 'Your 300-room hotel handles 200+ check-ins daily. Peak hours create 15-minute waits. Guest complaints mention slow check-in as top friction point. Front desk staff overtime costs $40K annually just to handle peak periods.',
          painPoint: 'Paper registration slows every check-in. Data entry errors cause billing issues. Guest preferences not captured systematically. Peak hour staffing is expensive.',
          keyFields: ['Full Name', 'ID Type', 'ID Number', 'Reservation Confirmation Number'],
          exampleOrganization: 'A 300-room full-service hotel with 15-minute average check-in wait times during peak hours.',
        },
        {
          title: 'Boutique Property',
          icon: '🏡',
          industry: 'Hospitality',
          scenario: 'Your 25-room boutique hotel prides itself on personalized service. But staff spend check-in time on paperwork instead of welcoming guests. Special requests noted on reservations get lost between OTA and front desk.',
          painPoint: 'Staff time wasted on administrative tasks. Guest preferences from booking not transferred to registration. Can\'t deliver personalized welcome when focused on paperwork. No time for property orientation.',
          keyFields: ['Special Requests', 'Bed Preference', 'Floor Preference', 'Request Late Checkout?'],
          exampleOrganization: 'A boutique hotel focused on personalized experiences, unable to deliver memorable arrivals due to check-in paperwork.',
        },
        {
          title: 'Resort Property',
          icon: '🌴',
          industry: 'Hospitality',
          scenario: 'Your 500-room resort handles family arrivals with multiple guests, cribs, rollaway beds, and dining reservations. Paper registration for a family of 5 takes 15+ minutes. Activities desk is backed up because check-in took too long.',
          painPoint: 'Multi-guest registrations are time-consuming. Resort amenity preferences not captured at check-in. Families miss orientation due to long registration. Dining and activity bookings delayed.',
          keyFields: ['Number of Guests', 'Special Requests', 'Arriving with vehicle?', 'Vehicle Make/Model'],
          exampleOrganization: 'A family resort where average check-in takes 12 minutes, causing 40% of guests to skip property orientation.',
        },
        {
          title: 'Extended Stay Property',
          icon: '🏢',
          industry: 'Hospitality',
          scenario: 'Your extended stay property hosts business travelers for weeks or months. Compliance requires complete guest registration with ID verification. Manual processes mean repeat guests fill out the same forms every stay.',
          painPoint: 'Compliance documentation time-consuming. Repeat guest information not retained. Long-term guest preferences not tracked. Vehicle parking management manual.',
          keyFields: ['ID Type', 'ID Number', 'Nationality', 'License Plate Number'],
          exampleOrganization: 'An extended stay property with 60% repeat guests, each filling out identical registration forms on every visit.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Loyalty Program Integration',
          description: 'Pre-populate fields for loyalty members from their profile. Capture loyalty number for point accrual and tier recognition.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Enable ID Document Upload',
          description: 'Allow guests to upload passport or ID photo for verification, reducing front desk ID handling time.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Add Resort Amenity Preferences',
          description: 'For resort properties, capture pool towel needs, spa appointment interests, dining reservation preferences, and activity bookings.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Include Upsell Opportunities',
          description: 'Offer room upgrades, early check-in, late checkout, and amenity packages during digital registration.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Connect Mobile Key',
          description: 'For properties with mobile key, complete registration enables direct-to-room arrival bypassing front desk entirely.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'pre-arrival-email',
          title: 'Send Registration Link',
          description: 'Automatically email guests 48 hours before arrival with digital registration link. Include property directions, parking instructions, and check-in time reminder.',
          trigger: '48 hours before check-in date',
          benefits: ['High pre-arrival completion rates', 'Guests prepared before arrival', 'Reduces day-of registration'],
        },
        {
          workflowType: 'pms-sync',
          title: 'Update PMS Guest Profile',
          description: 'Automatically sync registration data to property management system: guest details, preferences, vehicle information, emergency contacts. Room assignment ready before arrival.',
          trigger: 'On form submission',
          benefits: ['No manual data entry', 'Preferences available for room assignment', 'Guest profile complete in PMS'],
        },
        {
          workflowType: 'arrival-notification',
          title: 'Alert Front Desk',
          description: 'When pre-registered guest arrives (detected via reservation lookup), notify front desk with guest name, room assignment, and any special requests or VIP notes.',
          trigger: 'On reservation lookup at arrival',
          benefits: ['Staff prepared for guest', 'Personalized greeting possible', 'Special requests ready'],
        },
        {
          workflowType: 'parking-management',
          title: 'Update Parking System',
          description: 'For guests arriving with vehicles, automatically add license plate to parking system for garage access and valet identification.',
          trigger: 'On form submission with vehicle information',
          benefits: ['Seamless parking access', 'Valet can identify guest vehicles', 'Parking compliance automated'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'ID type and number fields support compliance reporting requirements',
          'Confirmation number links to existing reservation in PMS',
          'Boolean preference fields enable quick room matching algorithms',
        ],
        integrationHints: [
          'PMS API (Opera, Mews, Cloudbeds) for guest profile sync and room assignment',
          'Mobile key provider (ASSA ABLOY, OpenKey) for direct-to-room arrivals',
          'Parking management system for vehicle access and valet coordination',
        ],
        mongoDBConsiderations: [
          'Index on {confirmation_number: 1} for reservation lookup',
          'Index on {check_in_date: 1, check_out_date: 1} for occupancy queries',
          'Index on {license_plate: 1} for parking system lookups',
          'Consider TTL index on completed registrations for data retention compliance',
        ],
      },
      seo: {
        metaTitle: 'Hotel Guest Registration Form Template | NetPad',
        metaDescription: 'Free digital check-in form for hotels. Enable pre-arrival registration to reduce front desk wait times and improve guest satisfaction.',
        keywords: ['hotel registration form', 'guest check-in form', 'digital registration', 'hotel check-in', 'pre-arrival registration'],
        ogDescription: 'Eliminate check-in lines with digital pre-arrival registration. Guests complete paperwork before arrival and walk straight to their room.',
      },
      socialProofAngles: [
        'Faster guest check-in times',
        'Reduced front desk workload',
        'Higher guest satisfaction scores',
        'Eliminated paper registration cards',
      ],
    },
  }),

  createTemplate({
    id: 'vacation-rental-application',
    name: 'Vacation Rental Application',
    description: 'Application form for short-term vacation rental bookings',
    category: 'travel-tourism',
    icon: '🏡',
    complexity: 'intermediate',
    estimatedTime: '6-8 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Primary Guest Information'),
      textField('full_name', 'Full Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      dateField('dob', 'Date of Birth', true),
      addressField('home_address', 'Home Address', true),
      sectionHeader('Booking Details'),
      textField('property_name', 'Property Name/ID', true),
      dateField('check_in', 'Check-in Date', true),
      dateField('check_out', 'Check-out Date', true),
      numberField('num_adults', 'Number of Adults', true, 1, 20),
      numberField('num_children', 'Number of Children', false, 0, 10),
      selectField('purpose', 'Purpose of Stay', [
        'Vacation', 'Family Gathering', 'Remote Work', 'Special Event', 'Other'
      ], true),
      sectionHeader('Guest Details'),
      textareaField('guest_names', 'Names of All Guests', true),
      yesNoField('bringing_pets', 'Bringing any pets?', true),
      textField('pet_details', 'Pet Details (type, size, breed)', false),
      sectionHeader('Travel Information'),
      selectField('arrival_time', 'Estimated Arrival Time', [
        'Before 12 PM', '12 PM - 3 PM', '3 PM - 6 PM', '6 PM - 9 PM', 'After 9 PM'
      ], true),
      selectField('transportation', 'Mode of Transportation', [
        'Personal Vehicle', 'Rental Car', 'Taxi/Rideshare', 'Other'
      ], false),
      numberField('num_vehicles', 'Number of Vehicles', false, 0, 5),
      sectionHeader('House Rules Acknowledgment'),
      yesNoField('no_smoking', 'I agree to no smoking inside the property', true),
      yesNoField('no_parties', 'I agree to no parties or events without approval', true),
      yesNoField('quiet_hours', 'I agree to observe quiet hours (10 PM - 8 AM)', true),
      yesNoField('max_occupancy', 'I agree not to exceed max occupancy', true),
      sectionHeader('Payment & Agreement'),
      selectField('payment_method', 'Preferred Payment Method', [
        'Credit Card', 'Bank Transfer', 'PayPal', 'Venmo'
      ], true),
      yesNoField('terms_accepted', 'I accept the rental terms and conditions', true),
      textareaField('questions', 'Questions for the Host', false),
    ],
    tags: ['vacation rental', 'airbnb', 'vrbo', 'short-term rental'],
    useCases: ['Vacation rental owners', 'Property managers', 'Rental platforms'],
    enhanced: {
      headline: 'Screen Vacation Rental Guests Before They Book',
      subheadline: 'Collect guest details, house rules acknowledgment, and trip purpose—protect your property while delivering five-star guest experiences.',
      longDescription: {
        opening: 'Vacation rentals face unique risks: parties that damage property, guests who exceed occupancy limits, unauthorized pets, and noise complaints that get you fined or delisted. OTA bookings provide minimal guest information—just a name and payment method. You discover problems during or after the stay: the "couple\'s getaway" turns out to be 12 people, the "quiet retreat" becomes a graduation party. One bad guest can cost thousands in damage and lost future bookings.',
        solution: 'This template captures comprehensive guest applications: primary guest details and identification, complete booking information, all guest names for occupancy verification, pet disclosure with details, arrival logistics, explicit house rules acknowledgments (no smoking, no parties, quiet hours, occupancy limits), payment preferences, and open questions for hosts. Required acknowledgment fields create documented agreement to rules.',
        outcome: 'Screen guests before confirming bookings. House rules acknowledgments create legal protection and set clear expectations. Guest list enables accurate headcount. Pet disclosure prevents surprise damage. Purpose of stay field flags potential party bookings for extra scrutiny. Reduce property damage incidents by 75% and neighbor complaints by 90%. Build guest history for repeat booking decisions.',
      },
      useCases: [
        {
          title: 'Multi-Property Vacation Rental Manager',
          icon: '🏘️',
          industry: 'Property Management',
          scenario: 'You manage 25+ vacation rentals across a beach community. OTA bookings come with minimal information. Problematic guests damage one property and book another before you can flag them. HOA complaints threaten your rental permits.',
          painPoint: 'No systematic guest screening across properties. Party bookings slip through. Guest damage at one property not flagged for others. HOA complaints increasing.',
          keyFields: ['Names of All Guests', 'Purpose of Stay', 'I agree to no parties or events without approval', 'I agree to observe quiet hours (10 PM - 8 AM)'],
          exampleOrganization: 'A vacation rental manager with 25+ properties experiencing $50K+ annual damage from inadequate guest screening.',
        },
        {
          title: 'Individual Property Owner',
          icon: '🏡',
          industry: 'Real Estate',
          scenario: 'Your vacation home generates $60K annually but you\'ve had two damaging incidents in the past year. One party resulted in $8K in repairs. OTA messaging doesn\'t capture enough information to screen effectively.',
          painPoint: 'Limited visibility into who\'s actually staying. House rules communicated but not acknowledged. No documentation when disputes arise. Can\'t identify party-risk bookings.',
          keyFields: ['Number of Adults', 'Number of Children', 'Bringing any pets?', 'I agree to no smoking inside the property'],
          exampleOrganization: 'A vacation rental owner with one property, having experienced $12K in damage from two problematic bookings.',
        },
        {
          title: 'Luxury Villa Rental',
          icon: '💎',
          industry: 'Hospitality',
          scenario: 'Your luxury villa rents for $2,000+ per night. Guests expect concierge-level service. You need arrival details for stocking, transportation coordination, and personalized welcome. Current booking process doesn\'t capture these details.',
          painPoint: 'Guest preferences unknown before arrival. Can\'t coordinate luxury touches (champagne, flowers, grocery stocking). Transportation and arrival time unclear. Missing opportunity for premium experience.',
          keyFields: ['Estimated Arrival Time', 'Mode of Transportation', 'Questions for the Host', 'Special Requests'],
          exampleOrganization: 'A luxury villa with $150K annual revenue, receiving 3-star reviews for lack of personalized arrival experience.',
        },
        {
          title: 'Pet-Friendly Rental',
          icon: '🐕',
          industry: 'Hospitality',
          scenario: 'Your pet-friendly rental charges pet fees and has breed/size restrictions. Guests book without disclosing pets, then show up with animals. Pet damage and cleaning costs exceed collected fees. Restricted breeds create liability concerns.',
          painPoint: 'Pet disclosure inconsistent. Breed and size restrictions violated. Pet fees not collected before arrival. No documentation of pet policy agreement.',
          keyFields: ['Bringing any pets?', 'Pet Details (type, size, breed)', 'I accept the rental terms and conditions'],
          exampleOrganization: 'A pet-friendly rental losing $5K annually to undisclosed pets and inadequate pet fee collection.',
        },
      ],
      customizationTips: [
        {
          title: 'Add ID Verification',
          description: 'Require primary guest to upload government ID for verification. Matches name to booking and creates accountability.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Include Damage Deposit Authorization',
          description: 'Capture payment method authorization for security deposit hold. Document agreement to damage responsibility.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Add Property-Specific Rules',
          description: 'Customize house rules section for each property: pool rules, boat dock usage, golf cart policies, etc.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Enable Guest Screening Service',
          description: 'Integrate with guest screening services (Autohost, Superhog) to automatically flag high-risk bookings.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Capture Grocery/Concierge Preferences',
          description: 'For premium rentals, collect grocery stocking requests, restaurant reservation preferences, and activity interests.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'application-review',
          title: 'Flag High-Risk Bookings',
          description: 'Automatically flag bookings for manual review based on risk signals: large groups, special events mentioned, local addresses, last-minute bookings with cash payment preference.',
          trigger: 'On form submission with risk indicators',
          benefits: ['Party bookings caught before confirmation', 'Risk assessment automated', 'Owner approval on flagged bookings'],
        },
        {
          workflowType: 'confirmation-email',
          title: 'Send Booking Confirmation',
          description: 'After application approval, send comprehensive confirmation: property address, access instructions, check-in time, house rules summary, local recommendations, and host contact information.',
          trigger: 'On application approval',
          benefits: ['Guests have all arrival information', 'House rules reinforced', 'Professional guest communication'],
        },
        {
          workflowType: 'arrival-prep',
          title: 'Generate Arrival Checklist',
          description: 'Create property preparation checklist based on guest details: number of beds to make, pet preparation needed, grocery stocking requests, special occasion setup.',
          trigger: '48 hours before check-in',
          benefits: ['Property prepared for specific guests', 'Special requests not forgotten', 'Consistent preparation quality'],
        },
        {
          workflowType: 'guest-database',
          title: 'Update Guest History',
          description: 'Store guest information in database for future reference: booking history, rule compliance, damage incidents, review ratings. Flag problematic guests for future bookings.',
          trigger: 'On checkout',
          benefits: ['Guest history for repeat bookings', 'Problem guests flagged', 'Loyalty recognition for great guests'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Guest names stored as textarea for flexible group capture',
          'Boolean acknowledgment fields create documented rule agreement',
          'Purpose of stay helps identify party-risk bookings',
        ],
        integrationHints: [
          'Guest screening API (Autohost, Superhog) for risk assessment',
          'Property management software (Guesty, Hostaway) for booking sync',
          'Smart lock API for access code generation based on booking dates',
        ],
        mongoDBConsiderations: [
          'Index on {property_name: 1, check_in: 1} for availability conflict checking',
          'Index on {email: 1} for guest history lookup across properties',
          'Store rule acknowledgments with timestamps for legal documentation',
          'Consider separate collection for guest reputation scoring across bookings',
        ],
      },
      seo: {
        metaTitle: 'Vacation Rental Application Form Template | NetPad',
        metaDescription: 'Free vacation rental guest application with house rules acknowledgment. Screen guests and protect your property from problem bookings.',
        keywords: ['vacation rental application', 'airbnb guest form', 'rental guest screening', 'short-term rental form', 'vrbo application'],
        ogDescription: 'Stop problem guests before they book. This application captures guest details, occupancy verification, and house rules acknowledgment.',
      },
      socialProofAngles: [
        'Reduced property damage incidents',
        'Better guest communication',
        'Documented house rules agreement',
        'Fewer neighbor complaints',
      ],
    },
  }),

  createTemplate({
    id: 'travel-feedback-survey',
    name: 'Travel Experience Survey',
    description: 'Gather feedback from travelers about their trip experience',
    category: 'travel-tourism',
    icon: '📝',
    complexity: 'simple',
    estimatedTime: '4-6 min',
    formType: 'conversational',
    fields: [
      sectionHeader('Trip Information'),
      textField('destination', 'Destination Visited', true),
      dateField('travel_date', 'Travel Date', true),
      textField('booking_reference', 'Booking Reference (optional)', false),
      sectionHeader('Overall Experience'),
      selectField('overall_rating', 'Overall Trip Rating', [
        '5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor'
      ], true),
      selectField('value_rating', 'Value for Money', [
        '5 - Excellent Value', '4 - Good Value', '3 - Fair Value', '2 - Below Expectations', '1 - Poor Value'
      ], true),
      yesNoField('recommend', 'Would you recommend us to others?', true),
      sectionHeader('Service Ratings'),
      selectField('booking_experience', 'Booking Process', [
        '5 - Very Easy', '4 - Easy', '3 - Neutral', '2 - Difficult', '1 - Very Difficult'
      ], true),
      selectField('customer_service', 'Customer Service Quality', [
        '5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor'
      ], true),
      selectField('accommodation', 'Accommodation Quality', [
        '5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor', 'N/A'
      ], false),
      selectField('transportation', 'Transportation Quality', [
        '5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor', 'N/A'
      ], false),
      selectField('tour_guide', 'Tour Guide (if applicable)', [
        '5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor', 'N/A'
      ], false),
      sectionHeader('Detailed Feedback'),
      textareaField('highlights', 'What were the highlights of your trip?', false),
      textareaField('improvements', 'What could we improve?', false),
      textareaField('issues', 'Did you experience any issues?', false),
      sectionHeader('Future Travel'),
      yesNoField('book_again', 'Would you book with us again?', true),
      selectField('next_destination', 'Interested in future destinations?', [
        'Europe', 'Asia', 'Americas', 'Africa', 'Australia/Pacific', 'Middle East', 'Not Sure'
      ], false),
      yesNoField('newsletter', 'Subscribe to travel deals newsletter?', false),
      sectionHeader('Contact (Optional)'),
      textField('name', 'Your Name', false),
      emailField('email', 'Email for Follow-up', false),
    ],
    tags: ['survey', 'feedback', 'travel review', 'customer satisfaction'],
    useCases: ['Travel agencies', 'Tour operators', 'Hotels', 'Airlines'],
    enhanced: {
      headline: 'Turn Trip Feedback into Repeat Bookings',
      subheadline: 'Capture detailed travel experience feedback while it\'s fresh—identify promoters for testimonials and detractors for service recovery before they post negative reviews.',
      longDescription: {
        opening: 'Travelers share experiences publicly—on TripAdvisor, Google, and social media. By the time you see a negative review, it\'s too late for service recovery and the damage is done. Meanwhile, your happiest travelers never leave reviews because you didn\'t ask. Post-trip emails with generic "How was your trip?" get ignored. You lose the feedback that would improve operations and the testimonials that would drive bookings.',
        solution: 'This template captures structured travel feedback: trip details for context, overall and value ratings with NPS-style recommend question, service-specific ratings (booking, customer service, accommodation, transportation, guides), detailed open-ended feedback on highlights and improvements, issue reporting, future travel interests, and optional contact for follow-up. Conversational format increases completion rates.',
        outcome: 'Achieve 40%+ survey completion rates with conversational forms sent within 24 hours of return. Identify promoters (9-10 rating) for testimonial requests and referral programs. Catch detractors (1-6 rating) for immediate service recovery before public reviews. Track satisfaction trends by destination, guide, and service component. Build feedback database that drives continuous improvement.',
      },
      useCases: [
        {
          title: 'Tour Operator Quality Management',
          icon: '🗺️',
          industry: 'Tourism',
          scenario: 'Your tour company runs 200+ trips annually across 15 destinations. Quality varies by guide, hotel partner, and season. Occasional issues surface in TripAdvisor reviews months later. No systematic way to track satisfaction trends or identify problem areas.',
          painPoint: 'Quality issues discovered through public reviews. Can\'t compare satisfaction across destinations or guides. Service recovery happens too late. No data to hold suppliers accountable.',
          keyFields: ['Overall Trip Rating', 'Tour Guide (if applicable)', 'What could we improve?', 'Did you experience any issues?'],
          exampleOrganization: 'A tour operator with 4.2 TripAdvisor rating, losing bookings to competitors with 4.7+ ratings.',
        },
        {
          title: 'Travel Agency Client Retention',
          icon: '✈️',
          industry: 'Travel',
          scenario: 'Your travel agency books complex itineraries with multiple suppliers. Client satisfaction depends on factors beyond your control: flight delays, hotel quality, weather. Without feedback, you can\'t identify which clients are promoters and which are at risk of churning.',
          painPoint: 'Client satisfaction unknown until rebooking (or non-rebooking). Can\'t identify promoters for referrals. Issues with suppliers not systematically tracked. No testimonials for marketing.',
          keyFields: ['Value for Money', 'Would you recommend us to others?', 'Would you book with us again?', 'What were the highlights of your trip?'],
          exampleOrganization: 'A travel agency with 35% client retention rate, compared to industry best-in-class of 55%.',
        },
        {
          title: 'Hotel Experience Improvement',
          icon: '🏨',
          industry: 'Hospitality',
          scenario: 'Your hotel receives 500+ guests monthly. OTA reviews are sporadic and don\'t cover operational details. You suspect housekeeping quality varies by shift, but have no data. Guest complaints at checkout come too late for service recovery.',
          painPoint: 'Limited visibility into guest experience details. Can\'t identify department-specific issues. Service recovery reactive, not proactive. Staff performance not measurable.',
          keyFields: ['Accommodation Quality', 'Customer Service Quality', 'What could we improve?', 'Email for Follow-up'],
          exampleOrganization: 'A 150-room hotel with inconsistent reviews, unable to identify root causes of guest dissatisfaction.',
        },
        {
          title: 'Cruise Line Quality Tracking',
          icon: '🚢',
          industry: 'Cruise',
          scenario: 'Your cruise line runs 7-14 day voyages with complex operations: dining, entertainment, shore excursions, cabin service. Post-cruise surveys are long and completion rates are under 15%. You lack the granular feedback needed to improve specific touchpoints.',
          painPoint: 'Low survey completion rates with lengthy forms. Can\'t pinpoint specific improvement areas. Shore excursion quality varies wildly. Entertainment feedback not captured.',
          keyFields: ['Overall Trip Rating', 'Booking Process', 'Interested in future destinations?', 'Subscribe to travel deals newsletter?'],
          exampleOrganization: 'A cruise line with 12% survey completion rate, unable to systematically improve guest experience.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Photo Upload',
          description: 'Allow travelers to share trip photos with permission for marketing use. Authentic traveler photos outperform stock imagery.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Service Recovery Trigger',
          description: 'Automatically alert manager when overall rating is below 3 or issues field is populated. Enable immediate follow-up call.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Add Net Promoter Score Calculation',
          description: 'Calculate NPS from recommend question and track trends over time. Segment feedback by promoter/passive/detractor.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Supplier Rating',
          description: 'Add ratings for specific suppliers (hotels, guides, transport) to build performance data for partner management.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Connect Review Platform',
          description: 'For promoters, include direct link to leave TripAdvisor/Google review. Capture positive sentiment on public platforms.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'survey-trigger',
          title: 'Send Survey Post-Trip',
          description: 'Automatically email survey 24 hours after trip return date. Include trip summary and personalized greeting. Send reminder after 3 days if not completed.',
          trigger: '24 hours after return date',
          benefits: ['Feedback captured while fresh', 'High completion rates', 'Automated reminder sequence'],
        },
        {
          workflowType: 'service-recovery',
          title: 'Alert on Low Scores',
          description: 'Immediately notify manager when survey submitted with overall rating below 3 or issues reported. Include guest contact information for follow-up call.',
          trigger: 'On submission with low rating or issues',
          benefits: ['Immediate service recovery opportunity', 'Prevent negative public reviews', 'Show guests you care'],
        },
        {
          workflowType: 'testimonial-request',
          title: 'Request Testimonials from Promoters',
          description: 'For guests rating 5 and willing to recommend, automatically send follow-up requesting testimonial and permission to use feedback in marketing.',
          trigger: 'On submission with rating 5 AND recommend = yes',
          benefits: ['Capture testimonials from happiest guests', 'Build social proof library', 'Automated testimonial collection'],
        },
        {
          workflowType: 'newsletter-sync',
          title: 'Add to Marketing List',
          description: 'For guests who opt in to newsletter, add to email marketing platform with destination interests and trip history for targeted campaigns.',
          trigger: 'On submission with newsletter = yes',
          benefits: ['Grow email list from travelers', 'Segment by destination interest', 'Enable targeted re-marketing'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Rating fields use consistent 5-point scale for trend analysis',
          'Boolean recommend field enables NPS calculation',
          'Optional contact fields allow anonymous feedback option',
        ],
        integrationHints: [
          'Email marketing (Mailchimp, Klaviyo) for newsletter signup sync',
          'Review platform APIs for directing promoters to public review sites',
          'CRM sync for updating customer profiles with satisfaction data',
        ],
        mongoDBConsiderations: [
          'Index on {destination: 1, travel_date: 1} for destination satisfaction analysis',
          'Index on {overall_rating: 1} for promoter/detractor filtering',
          'Aggregation pipeline for NPS calculation: (promoters - detractors) / total * 100',
          'Time-series analysis on ratings for trend detection',
        ],
      },
      seo: {
        metaTitle: 'Travel Feedback Survey Template | NetPad',
        metaDescription: 'Free travel survey template for agencies and operators. Capture trip feedback, identify promoters, and enable service recovery.',
        keywords: ['travel feedback form', 'trip survey template', 'customer satisfaction survey', 'travel review form', 'post-trip survey'],
        ogDescription: 'Get actionable travel feedback before guests post public reviews. Identify promoters and fix issues while they can still be resolved.',
      },
      socialProofAngles: [
        'Higher survey completion rates',
        'Faster service recovery',
        'More testimonials collected',
        'Improved satisfaction scores',
      ],
    },
  }),

  createTemplate({
    id: 'cruise-booking-form',
    name: 'Cruise Booking Form',
    description: 'Comprehensive cruise vacation booking and preferences form',
    category: 'travel-tourism',
    icon: '🚢',
    complexity: 'advanced',
    estimatedTime: '10-15 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Lead Passenger Information'),
      textField('full_name', 'Full Name (as on passport)', true),
      dateField('dob', 'Date of Birth', true),
      selectField('gender', 'Gender', ['Male', 'Female', 'Other'], true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      addressField('address', 'Home Address', true),
      textField('passport_number', 'Passport Number', true),
      dateField('passport_expiry', 'Passport Expiry Date', true),
      selectField('nationality', 'Nationality', [
        'United States', 'Canada', 'United Kingdom', 'Australia', 'Germany', 'Other'
      ], true),
      sectionHeader('Cruise Selection'),
      selectField('cruise_line', 'Preferred Cruise Line', [
        'Royal Caribbean', 'Carnival', 'Norwegian', 'Princess', 'MSC', 'Celebrity', 'No Preference'
      ], true),
      selectField('destination', 'Cruise Destination', [
        'Caribbean', 'Mediterranean', 'Alaska', 'Bahamas', 'Europe', 'Asia', 'Other'
      ], true),
      selectField('cruise_length', 'Cruise Length', [
        '3-4 Nights', '5-6 Nights', '7 Nights', '10-14 Nights', '15+ Nights'
      ], true),
      dateField('preferred_date', 'Preferred Departure Date', true),
      textField('departure_port', 'Preferred Departure Port', false),
      sectionHeader('Cabin Preferences'),
      selectField('cabin_type', 'Cabin Type', [
        'Interior', 'Ocean View', 'Balcony', 'Suite', 'No Preference'
      ], true),
      selectField('deck_preference', 'Deck Preference', [
        'Lower Deck', 'Mid Deck', 'Upper Deck', 'No Preference'
      ], false),
      selectField('bed_config', 'Bed Configuration', [
        'King/Queen', 'Twin Beds', 'No Preference'
      ], false),
      numberField('num_cabins', 'Number of Cabins Needed', true, 1, 10),
      sectionHeader('Passenger Details'),
      numberField('adults', 'Number of Adults', true, 1, 20),
      numberField('children', 'Number of Children (2-17)', false, 0, 10),
      numberField('infants', 'Number of Infants (under 2)', false, 0, 5),
      textareaField('additional_passengers', 'Additional Passenger Names & DOBs', false),
      sectionHeader('Dining & Special Needs'),
      selectField('dining_time', 'Dining Time Preference', [
        'Early Seating', 'Late Seating', 'My Time Dining', 'No Preference'
      ], true),
      selectField('dietary_needs', 'Dietary Requirements', [
        'None', 'Vegetarian', 'Vegan', 'Gluten-Free', 'Kosher', 'Halal', 'Other'
      ], false),
      yesNoField('mobility_needs', 'Any mobility/accessibility needs?', true),
      textareaField('medical_conditions', 'Medical Conditions to Note', false),
      sectionHeader('Add-Ons & Packages'),
      yesNoField('beverage_package', 'Add Beverage Package?', false),
      yesNoField('wifi_package', 'Add WiFi Package?', false),
      yesNoField('excursion_package', 'Interested in Shore Excursion Package?', false),
      yesNoField('travel_insurance', 'Add Travel Insurance?', false),
      yesNoField('pre_cruise_hotel', 'Need Pre-Cruise Hotel?', false),
      yesNoField('flights', 'Need Flight Arrangements?', false),
      sectionHeader('Budget & Payment'),
      currencyField('budget_per_person', 'Budget Per Person (USD)', false),
      selectField('payment_plan', 'Payment Preference', [
        'Pay in Full', 'Deposit Now, Balance Later', 'Payment Plan'
      ], true),
      textareaField('special_requests', 'Special Requests or Celebrations', false),
    ],
    tags: ['cruise', 'vacation', 'ocean voyage', 'ship travel'],
    useCases: ['Travel agencies', 'Cruise specialists', 'Vacation planners'],
    enhanced: {
      headline: 'Book Cruises Without the Back-and-Forth',
      subheadline: 'Capture every cruise preference in one form—cabin type, dining time, dietary needs, and add-ons—so you can quote accurately and book faster.',
      longDescription: {
        opening: 'Cruise bookings are complex: cabin categories across multiple decks, dining preferences, dietary restrictions, accessibility needs, shore excursion interests, beverage packages, WiFi plans, spa reservations, and special occasions. One booking involves 20+ decisions. Agents spend 30-45 minutes on phone calls gathering preferences, then another round when the client discusses with their travel partner. Incomplete information leads to wrong cabin assignments, missed dining preferences, and disappointed cruisers.',
        solution: 'This template captures comprehensive cruise requirements: lead passenger details with passport information, cruise line and destination preferences, cruise length and departure preferences, cabin type and deck preferences, bed configuration needs, complete passenger manifest with ages, dining time and dietary requirements, mobility and accessibility needs, add-on packages (beverage, WiFi, excursions, insurance), pre-cruise hotel and flight needs, budget parameters, and payment preferences including installment plans.',
        outcome: 'Quote cruises in hours instead of days with complete preferences upfront. Cabin assignment matches passenger needs (mobility requirements on lower decks, families near kids\' clubs). Dining accommodations correct from embarkation. Add-on package recommendations increase booking value by 30%. Reduce booking modifications by 60% with thorough upfront capture. Deliver the cruise vacation clients actually want.',
      },
      useCases: [
        {
          title: 'Cruise Specialist Agency',
          icon: '🚢',
          industry: 'Travel',
          scenario: 'Your agency specializes in cruise vacations with 500+ bookings annually. Each booking requires extensive consultation to match clients with the right ship, cabin, and add-ons. Phone consultations take 45+ minutes, and clients often need to "check with spouse" before confirming preferences.',
          painPoint: 'Lengthy phone consultations for preference gathering. Clients provide incomplete information, requiring follow-up. Cabin selection based on incomplete mobility and preference data. Add-on packages undersold due to rushed consultations.',
          keyFields: ['Cabin Type', 'Dining Time Preference', 'Any mobility/accessibility needs?', 'Add Beverage Package?'],
          exampleOrganization: 'A cruise specialist agency with 45-minute average consultation time, looking to reduce to 15 minutes.',
        },
        {
          title: 'Group Cruise Coordinator',
          icon: '👥',
          industry: 'Travel',
          scenario: 'You organize group cruises for family reunions, corporate incentives, and affinity groups. Groups of 20-100 passengers need coordinated cabin assignments, dining arrangements, and shore excursions. Collecting preferences from each passenger through email is chaotic.',
          painPoint: 'Individual preferences scattered across emails. Dining table assignments require manual coordination. Shore excursion booking uncoordinated. Group photo and event planning data incomplete.',
          keyFields: ['Number of Adults', 'Number of Children (2-17)', 'Additional Passenger Names & DOBs', 'Interested in Shore Excursion Package?'],
          exampleOrganization: 'A group cruise coordinator managing 10+ group sailings annually, spending 20+ hours per group on data collection.',
        },
        {
          title: 'Luxury Cruise Concierge',
          icon: '💎',
          industry: 'Travel',
          scenario: 'Your agency books luxury and expedition cruises at $500+ per person per day. Clients expect personalized service and attention to detail. Suite bookings require butler preference coordination. Expedition cruises need fitness and medical screening.',
          painPoint: 'High-touch service requires extensive preference capture. Suite amenities customization data not collected. Expedition fitness requirements discovered late. Special occasion arrangements missed.',
          keyFields: ['Cabin Type', 'Deck Preference', 'Medical Conditions to Note', 'Special Requests or Celebrations'],
          exampleOrganization: 'A luxury cruise concierge with $2M+ in annual bookings, losing suite upgrades due to incomplete preference capture.',
        },
        {
          title: 'Corporate Incentive Planner',
          icon: '🏆',
          industry: 'Events',
          scenario: 'You plan corporate incentive cruises rewarding top performers. Companies need consistent cabin categories, branded events, and complete passenger documentation. HR provides employee lists, but detailed preferences and passport information must be collected individually.',
          painPoint: 'Employee preference collection time-consuming. Passport information gathered piecemeal. Dietary and accessibility needs discovered at embarkation. Room assignment conflicts between award tiers.',
          keyFields: ['Passport Number', 'Passport Expiry Date', 'Dietary Requirements', 'Need Flight Arrangements?'],
          exampleOrganization: 'A corporate planner organizing 5+ incentive cruises annually with 50-200 passengers each.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Cabin Category Pricing',
          description: 'Display cabin category options with price ranges to help clients self-select appropriate price points before consultation.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Enable Shore Excursion Selection',
          description: 'Based on cruise destination, show available shore excursions at each port for pre-booking interest capture.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
        {
          title: 'Add Past Cruise History',
          description: 'Capture previous cruise experience, loyalty program membership, and past cabin preferences to inform recommendations.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Include Health Questionnaire',
          description: 'For expedition cruises and passengers with medical conditions, add health screening questions required by cruise lines.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Enable Travel Companion Linking',
          description: 'For groups traveling together, allow linking of booking forms for coordinated cabin assignments and dining tables.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'quote-generation',
          title: 'Generate Cruise Quote',
          description: 'Based on submitted preferences, automatically generate personalized quote with cabin options, add-on packages, and total pricing. Include comparison of recommended cabin categories.',
          trigger: 'On form submission',
          benefits: ['Instant quote generation', 'Multiple cabin options presented', 'Complete pricing with add-ons'],
        },
        {
          workflowType: 'booking-confirmation',
          title: 'Send Comprehensive Confirmation',
          description: 'After booking confirmed, send detailed confirmation: cruise details, cabin assignment, dining time, add-ons purchased, passport requirements, embarkation instructions, and payment schedule.',
          trigger: 'On booking confirmation',
          benefits: ['Complete booking reference', 'All preferences documented', 'Clear next steps'],
        },
        {
          workflowType: 'document-reminder',
          title: 'Passport Verification Alert',
          description: 'If passport expiry is within 6 months of cruise return date, alert agent and client. Many countries require 6-month passport validity.',
          trigger: 'On submission with passport expiry < cruise date + 6 months',
          benefits: ['Prevent embarkation issues', 'Early passport renewal reminder', 'Compliance with cruise line requirements'],
        },
        {
          workflowType: 'pre-cruise',
          title: 'Send Pre-Cruise Information',
          description: 'Automatically send packing list, port arrival instructions, check-in information, and shore excursion final booking deadline 30 days before sailing.',
          trigger: '30 days before cruise date',
          benefits: ['Guests prepared for cruise', 'Reduces pre-cruise inquiries', 'Final booking deadlines communicated'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Passenger counts separated by age category for accurate pricing',
          'Passport expiry date enables validity checking workflow',
          'Add-on boolean fields support package bundling and upsell tracking',
        ],
        integrationHints: [
          'Cruise line booking APIs (if available) for real-time pricing and availability',
          'Payment gateway with installment support for cruise payment plans',
          'Document collection system for passport copies and travel insurance',
        ],
        mongoDBConsiderations: [
          'Index on {cruise_line: 1, destination: 1, preferred_date: 1} for inventory matching',
          'Index on {passport_expiry: 1} for validity alert queries',
          'Store additional passengers as embedded array with required fields for manifest',
          'Consider separate collection for shore excursion preferences per booking',
        ],
      },
      seo: {
        metaTitle: 'Cruise Booking Form Template | NetPad',
        metaDescription: 'Free cruise booking template for travel agencies. Capture cabin preferences, dining needs, and add-ons for faster cruise quoting.',
        keywords: ['cruise booking form', 'cruise vacation form', 'cruise inquiry form', 'cruise agent form', 'cruise preferences'],
        ogDescription: 'Stop losing cruise details in phone calls. This form captures every preference for accurate quotes and seamless bookings.',
      },
      socialProofAngles: [
        'Faster cruise quoting',
        'Higher add-on package sales',
        'Fewer booking modifications',
        'Better cabin matching',
      ],
    },
  }),
];
