'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Box,
  Container,
  Paper,
  Typography,
  CircularProgress,
  Alert,
  Button,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Radio,
  Divider,
  alpha,
  Chip,
  Skeleton,
} from '@mui/material';
import {
  CloudDownload,
  Folder,
  Add,
  CheckCircle,
  Error as ErrorIcon,
  Timer,
  AccountTree,
  SmartToy,
  Terminal,
  Share,
  Api,
  Chat,
} from '@mui/icons-material';
import { useAuth } from '@/contexts/AuthContext';
import { useOrganization } from '@/contexts/OrganizationContext';
import type { WorkflowImportConfig } from '@/lib/platform/workflowImportsDbOps';

interface Project {
  projectId: string;
  name: string;
  slug: string;
  description?: string;
}

interface WorkflowImportData {
  importId: string;
  config: WorkflowImportConfig;
  projectId?: string;
  source: string;
  expiresAt: string;
  claimed: boolean;
}

/**
 * Get icon for import source
 */
function getSourceIcon(source: string) {
  switch (source) {
    case 'claude-mcp':
      return <SmartToy />;
    case 'chatgpt':
      return <Chat />;
    case 'cli':
      return <Terminal />;
    case 'share':
      return <Share />;
    default:
      return <Api />;
  }
}

/**
 * Get label for import source
 */
function getSourceLabel(source: string): string {
  switch (source) {
    case 'claude-mcp':
      return 'Claude MCP';
    case 'chatgpt':
      return 'ChatGPT';
    case 'cli':
      return 'NetPad CLI';
    case 'share':
      return 'Shared Link';
    default:
      return 'API';
  }
}

/**
 * Workflow Import Page
 *
 * Allows users to import a workflow configuration generated by ChatGPT, Claude MCP, or other sources.
 * Displays workflow preview and project selection.
 */
export default function WorkflowImportPage() {
  const params = useParams();
  const router = useRouter();
  const importId = params.importId as string;

  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const { organization, isLoading: orgLoading } = useOrganization();

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [importData, setImportData] = useState<WorkflowImportData | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null);
  const [importing, setImporting] = useState(false);

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      const returnUrl = encodeURIComponent(`/import/workflow/${importId}`);
      router.push(`/auth/login?redirect=${returnUrl}`);
    }
  }, [authLoading, isAuthenticated, router, importId]);

  // Fetch import data
  const fetchImportData = useCallback(async () => {
    try {
      const response = await fetch(`/api/workflows/import/${importId}`);
      const data = await response.json();

      if (!response.ok) {
        if (response.status === 404) {
          setError('This import link was not found or has expired.');
        } else if (response.status === 410) {
          setError('This import has already been used to create a workflow.');
        } else {
          setError(data.error || 'Failed to load import');
        }
        setLoading(false);
        return;
      }

      setImportData(data);

      // If projectId is already specified, pre-select it
      if (data.projectId) {
        setSelectedProjectId(data.projectId);
      }
    } catch (err) {
      setError('Failed to connect to the server');
    } finally {
      setLoading(false);
    }
  }, [importId]);

  // Fetch projects when organization is available
  const fetchProjects = useCallback(async () => {
    if (!organization?.orgId) return;

    try {
      const response = await fetch(`/api/projects?orgId=${organization.orgId}`);
      const data = await response.json();

      if (data.projects && Array.isArray(data.projects)) {
        setProjects(data.projects);

        // Auto-select if only one project or if there's a default
        if (!selectedProjectId && data.projects.length > 0) {
          const defaultProject = data.projects.find((p: Project) => p.slug === 'general') || data.projects[0];
          setSelectedProjectId(defaultProject.projectId);
        }
      }
    } catch (err) {
      console.error('Failed to fetch projects:', err);
    }
  }, [organization?.orgId, selectedProjectId]);

  useEffect(() => {
    if (isAuthenticated && !authLoading) {
      fetchImportData();
    }
  }, [isAuthenticated, authLoading, fetchImportData]);

  useEffect(() => {
    if (organization?.orgId) {
      fetchProjects();
    }
  }, [organization?.orgId, fetchProjects]);

  // Handle import
  const handleImport = async () => {
    if (!selectedProjectId || !importData || !organization) {
      return;
    }

    setImporting(true);

    try {
      // Store the import config in sessionStorage for the workflow editor to pick up
      sessionStorage.setItem(
        'netpad_workflow_import',
        JSON.stringify({
          importId: importData.importId,
          config: importData.config,
          source: importData.source,
        })
      );

      // Navigate to the workflow editor with import flag
      const selectedProject = projects.find((p) => p.projectId === selectedProjectId);
      if (selectedProject) {
        router.push(
          `/orgs/${organization.orgId}/projects/${selectedProjectId}/workflows?imported=${importData.importId}`
        );
      }
    } catch (err) {
      setError('Failed to start import');
      setImporting(false);
    }
  };

  // Loading state
  if (authLoading || loading) {
    return (
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '100vh',
          bgcolor: '#f5f5f5',
        }}
      >
        <CircularProgress />
      </Box>
    );
  }

  // Error state
  if (error) {
    return (
      <Box
        sx={{
          minHeight: '100vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          bgcolor: '#f5f5f5',
        }}
      >
        <Container maxWidth="sm">
          <Paper sx={{ p: 4, textAlign: 'center' }}>
            <ErrorIcon sx={{ fontSize: 64, color: 'error.main', mb: 2 }} />
            <Typography variant="h5" sx={{ mb: 2 }}>
              Import Unavailable
            </Typography>
            <Alert severity="error" sx={{ mb: 3 }}>
              {error}
            </Alert>
            <Button variant="contained" onClick={() => router.push('/workflows')}>
              Go to Workflows
            </Button>
          </Paper>
        </Container>
      </Box>
    );
  }

  if (!importData) {
    return null;
  }

  const config = importData.config;
  const nodeCount = config.canvas?.nodes?.length || 0;
  const edgeCount = config.canvas?.edges?.length || 0;
  const expiresAt = new Date(importData.expiresAt);
  const timeLeft = Math.max(0, Math.floor((expiresAt.getTime() - Date.now()) / 1000 / 60));

  return (
    <Box
      sx={{
        minHeight: '100vh',
        bgcolor: '#f5f5f5',
        py: 4,
      }}
    >
      <Container maxWidth="sm">
        {/* Header */}
        <Paper sx={{ p: 4, mb: 3, textAlign: 'center' }}>
          <CloudDownload sx={{ fontSize: 48, color: 'primary.main', mb: 2 }} />
          <Typography variant="h5" sx={{ fontWeight: 600, mb: 1 }}>
            Import Workflow from {getSourceLabel(importData.source)}
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Review the workflow details below and select a project to import into
          </Typography>
        </Paper>

        {/* Workflow Preview */}
        <Paper sx={{ p: 3, mb: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2, mb: 2 }}>
            <AccountTree sx={{ color: 'text.secondary', mt: 0.5 }} />
            <Box sx={{ flex: 1 }}>
              <Typography variant="h6" sx={{ fontWeight: 600 }}>
                {config.name || 'Untitled Workflow'}
              </Typography>
              {config.description && (
                <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                  {config.description}
                </Typography>
              )}
            </Box>
          </Box>

          <Divider sx={{ my: 2 }} />

          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
            <Chip
              size="small"
              icon={getSourceIcon(importData.source)}
              label={getSourceLabel(importData.source)}
              sx={{ bgcolor: alpha('#2196F3', 0.1) }}
            />
            {nodeCount > 0 && (
              <Chip
                size="small"
                label={`${nodeCount} node${nodeCount !== 1 ? 's' : ''}`}
                variant="outlined"
              />
            )}
            {edgeCount > 0 && (
              <Chip
                size="small"
                label={`${edgeCount} connection${edgeCount !== 1 ? 's' : ''}`}
                variant="outlined"
              />
            )}
            {config.tags && config.tags.length > 0 && (
              config.tags.slice(0, 3).map((tag) => (
                <Chip
                  key={tag}
                  size="small"
                  label={tag}
                  variant="outlined"
                  sx={{ bgcolor: alpha('#9C27B0', 0.05) }}
                />
              ))
            )}
          </Box>

          {/* Expiry warning */}
          {timeLeft < 60 && (
            <Alert
              severity="warning"
              icon={<Timer />}
              sx={{ mt: 2 }}
            >
              This import link expires in {timeLeft} minute{timeLeft !== 1 ? 's' : ''}
            </Alert>
          )}
        </Paper>

        {/* Project Selection */}
        <Paper sx={{ p: 3, mb: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600, mb: 2 }}>
            Select a Project
          </Typography>

          {orgLoading ? (
            <Box>
              <Skeleton variant="rectangular" height={56} sx={{ mb: 1, borderRadius: 1 }} />
              <Skeleton variant="rectangular" height={56} sx={{ mb: 1, borderRadius: 1 }} />
            </Box>
          ) : projects.length === 0 ? (
            <Alert severity="info">
              No projects found. Create a project first to import this workflow.
            </Alert>
          ) : (
            <List sx={{ bgcolor: 'background.default', borderRadius: 1 }}>
              {projects.map((project) => (
                <ListItemButton
                  key={project.projectId}
                  selected={selectedProjectId === project.projectId}
                  onClick={() => setSelectedProjectId(project.projectId)}
                  sx={{
                    borderRadius: 1,
                    mb: 0.5,
                    border: '1px solid',
                    borderColor: selectedProjectId === project.projectId
                      ? 'primary.main'
                      : 'transparent',
                  }}
                >
                  <ListItemIcon>
                    <Radio
                      checked={selectedProjectId === project.projectId}
                      tabIndex={-1}
                    />
                  </ListItemIcon>
                  <ListItemIcon sx={{ minWidth: 40 }}>
                    <Folder color={selectedProjectId === project.projectId ? 'primary' : 'action'} />
                  </ListItemIcon>
                  <ListItemText
                    primary={project.name}
                    secondary={project.description || project.slug}
                  />
                </ListItemButton>
              ))}

              {/* Create new project option */}
              <ListItemButton
                onClick={() => router.push(`/orgs/${organization?.orgId}/projects?action=create`)}
                sx={{ borderRadius: 1, color: 'primary.main' }}
              >
                <ListItemIcon>
                  <Add color="primary" />
                </ListItemIcon>
                <ListItemText primary="Create New Project" />
              </ListItemButton>
            </List>
          )}
        </Paper>

        {/* Actions */}
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button
            variant="outlined"
            onClick={() => router.push('/workflows')}
            disabled={importing}
            sx={{ flex: 1 }}
          >
            Cancel
          </Button>
          <Button
            variant="contained"
            onClick={handleImport}
            disabled={!selectedProjectId || importing}
            startIcon={importing ? <CircularProgress size={20} /> : <CheckCircle />}
            sx={{ flex: 2 }}
          >
            {importing ? 'Importing...' : 'Import to Project'}
          </Button>
        </Box>

        {/* Footer */}
        <Box sx={{ mt: 4, textAlign: 'center' }}>
          <Typography variant="caption" color="text.secondary">
            After import, you can edit the workflow before saving.
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
