/**
 * Customer Service Form Templates
 *
 * Templates for support tickets, customer feedback, product returns,
 * and service-related interactions.
 */

import { FormTemplate, EnhancedTemplateContent } from '@/types/formTemplate';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  fileField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  ratingField,
  scaleField,
  urlField,
} from '../helpers';

export const customerServiceTemplates: FormTemplate[] = [
  // 1. Customer Satisfaction Survey
  createTemplate({
    id: 'customer-satisfaction-survey',
    name: 'Customer Satisfaction Survey',
    shortDescription: 'Measure customer satisfaction with your service',
    fullDescription: 'A comprehensive customer satisfaction survey to gather feedback on products, services, and overall customer experience. Includes NPS score and detailed feedback sections.',
    category: 'customer-service',
    icon: 'Star',
    complexity: 'moderate',
    estimatedTime: 5,
    isFeatured: true,
    displayOrder: 1,
    tags: ['csat', 'satisfaction', 'survey', 'feedback', 'nps'],
    useCases: [
      'Post-purchase surveys',
      'Service quality measurement',
      'Customer experience tracking',
      'Quarterly satisfaction surveys',
    ],
    features: [
      'NPS score calculation',
      'Multi-dimensional ratings',
      'Open-ended feedback',
      'Improvement suggestions',
    ],
    fieldConfigs: [
      sectionHeader('about', 'About Your Experience'),
      selectField('productService', 'Which product/service did you use?', [
        'Product A',
        'Product B',
        'Service Plan - Basic',
        'Service Plan - Premium',
        'Support Services',
        'Other',
      ], { required: true }),
      dateField('interactionDate', 'When did you interact with us?'),
      sectionHeader('ratings', 'Rate Your Experience'),
      scaleField('npsScore', 'How likely are you to recommend us to a friend or colleague?', {
        required: true,
        validation: { min: 0, max: 10, lowLabel: 'Not at all likely', highLabel: 'Extremely likely' },
      }),
      ratingField('overallSatisfaction', 'Overall Satisfaction', { required: true }),
      ratingField('productQuality', 'Product/Service Quality'),
      ratingField('valueForMoney', 'Value for Money'),
      ratingField('easeOfUse', 'Ease of Use'),
      ratingField('customerSupport', 'Customer Support (if applicable)'),
      sectionHeader('feedback', 'Detailed Feedback'),
      textareaField('whatWentWell', 'What did we do well?', {
        placeholder: 'Tell us what you liked about your experience...',
      }),
      textareaField('whatToImprove', 'What could we improve?', {
        placeholder: 'Share suggestions for how we can do better...',
      }),
      yesNoField('hadIssues', 'Did you experience any issues?'),
      textareaField('issueDescription', 'Please describe the issue(s)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hadIssues', operator: 'isTrue' }],
        },
      }),
      selectField('issueResolution', 'Was your issue resolved?', [
        'Yes, completely',
        'Yes, partially',
        'No, still unresolved',
        'Did not contact support',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hadIssues', operator: 'isTrue' }],
        },
      }),
      sectionHeader('future', 'Looking Forward'),
      yesNoField('wouldBuyAgain', 'Would you purchase from us again?'),
      multiSelectField('interestedIn', 'What other products/services interest you?', [
        'Product A',
        'Product B',
        'Product C',
        'Premium Support',
        'Training/Education',
        'Not interested in anything else',
      ]),
      yesNoField('canContact', 'May we contact you for follow-up?'),
      emailField('email', 'Email Address (optional)', { required: false }),
    ],
    enhanced: {
      headline: 'Measure What Matters: Real Customer Sentiment',
      subheadline: 'Capture NPS scores, detailed satisfaction ratings, and actionable feedback—so you can identify promoters, address detractors, and continuously improve.',
      longDescription: {
        opening: 'Most companies guess at customer satisfaction. They rely on anecdotes, support ticket volumes, or worse—silence. By the time they realize customers are unhappy, the churn has already started.',
        solution: 'This template implements a complete CSAT framework: NPS score (0-10) for benchmarking, multi-dimensional ratings for product quality, support, and value, plus open-ended feedback that reveals the "why" behind the numbers. Conditional logic surfaces issue details only when needed.',
        outcome: 'Track customer sentiment over time with measurable metrics. Identify at-risk accounts before they churn. Discover your biggest promoters for testimonials and referrals. Turn detractors into satisfied customers by addressing their specific concerns.',
      },
      useCases: [
        {
          title: 'Post-Purchase Feedback',
          icon: '🛍️',
          industry: 'E-commerce / Retail',
          scenario: 'After customers receive their orders, you want to understand their experience with the product, shipping, and overall service.',
          painPoint: 'Returns and negative reviews come as surprises; no early warning system for dissatisfaction.',
          keyFields: ['NPS Score', 'Overall Satisfaction', 'Product/Service Quality', 'Value for Money'],
          exampleOrganization: 'An e-commerce company sending post-purchase surveys to 10,000+ monthly customers.',
        },
        {
          title: 'B2B Account Health',
          icon: '📊',
          industry: 'SaaS / Technology',
          scenario: 'Customer Success teams need to monitor account health and identify expansion or churn risk before renewal.',
          painPoint: 'Renewal surprises occur because CSMs don\'t have systematic satisfaction data.',
          keyFields: ['NPS Score', 'What could we improve?', 'Would you purchase again?', 'May we contact you?'],
          exampleOrganization: 'A B2B SaaS company with $5M ARR monitoring satisfaction across 200 accounts.',
        },
        {
          title: 'Service Quality Monitoring',
          icon: '🎧',
          industry: 'Professional Services',
          scenario: 'Service businesses need feedback after each engagement to maintain quality standards and identify coaching opportunities.',
          painPoint: 'Service quality varies by provider; no systematic way to identify and replicate excellence.',
          keyFields: ['Customer Support', 'What did we do well?', 'What could we improve?', 'Had Issues'],
          exampleOrganization: 'A consulting firm surveying clients after each project engagement.',
        },
        {
          title: 'Quarterly Relationship Check-ins',
          icon: '📅',
          industry: 'Any B2B',
          scenario: 'Scheduled quarterly surveys provide trending data on account health and flag issues before they escalate.',
          painPoint: 'Annual surveys miss problems until it\'s too late; no trend data to show improvement.',
          keyFields: ['Overall Satisfaction', 'NPS Score', 'What other products interest you?', 'Would buy again'],
          exampleOrganization: 'An enterprise company running quarterly NPS surveys across all strategic accounts.',
        },
      ],
      customizationTips: [
        {
          title: 'Segment by Customer Type',
          description: 'Add a hidden field to capture customer segment (enterprise, SMB, trial) for cohort analysis in reporting.',
          fieldSuggestion: 'hidden',
          difficulty: 'easy',
        },
        {
          title: 'Add Transaction Reference',
          description: 'Include order ID or ticket number to correlate feedback with specific interactions.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Enable Anonymous Option',
          description: 'Add a checkbox allowing anonymous submission for more candid feedback on sensitive issues.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Build NPS Trend Dashboard',
          description: 'Create a reporting view that tracks NPS over time, segmented by product, region, or customer type.',
          difficulty: 'advanced',
        },
        {
          title: 'Implement Closed-Loop Follow-up',
          description: 'Trigger personalized follow-up based on NPS score: thank promoters, address detractor concerns.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'conditional-notification',
          title: 'Alert on Detractor Scores',
          description: 'Immediately notify account managers when NPS score is 0-6 (detractor). Include full survey response.',
          trigger: 'On form submission where npsScore <= 6',
          benefits: ['Rapid response to unhappy customers', 'Churn prevention'],
        },
        {
          workflowType: 'email-sequence',
          title: 'Thank Promoters',
          description: 'Send personalized thank-you to customers scoring 9-10 with invitation to leave public review or referral.',
          trigger: 'On form submission where npsScore >= 9',
          benefits: ['Testimonial collection', 'Referral generation'],
        },
        {
          workflowType: 'crm-update',
          title: 'Update Account Health Score',
          description: 'Push NPS score and satisfaction ratings to CRM for account health monitoring and renewal forecasting.',
          trigger: 'On form submission',
          benefits: ['Account health visibility', 'Better renewal forecasting'],
        },
        {
          workflowType: 'data-aggregation',
          title: 'Weekly NPS Report',
          description: 'Compile weekly summary of NPS scores, trends, and notable feedback for leadership review.',
          trigger: 'Scheduled weekly',
          benefits: ['Executive visibility', 'Trend monitoring'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'NPS stored as integer (0-10) enables accurate mathematical calculations and benchmarking',
          'Rating fields use consistent 1-5 scale for cross-metric comparison',
          'Conditional fields (issue details, resolution) only populate when relevant',
        ],
        integrationHints: [
          'Webhook to analytics platform (Mixpanel, Amplitude) for NPS tracking dashboards',
          'POST to CRM to update contact record with latest satisfaction scores',
          'Connect to review platform (G2, Trustpilot) to invite promoters to leave reviews',
        ],
        mongoDBConsiderations: [
          'Index on {npsScore: 1, createdAt: -1} for NPS trend analysis queries',
          'Index on {productService: 1} for product-specific satisfaction reporting',
          'Aggregation pipeline for calculating NPS percentages (promoters - detractors)',
        ],
      },
      seo: {
        metaTitle: 'Customer Satisfaction Survey Template | NetPad',
        metaDescription: 'Free CSAT and NPS survey template with multi-dimensional ratings, open-ended feedback, and issue tracking. Measure customer satisfaction effectively.',
        keywords: [
          'customer satisfaction survey',
          'CSAT survey template',
          'NPS survey form',
          'customer feedback form',
          'satisfaction measurement',
          'customer experience survey',
          'net promoter score',
        ],
        ogDescription: 'Stop guessing at customer satisfaction. This survey captures NPS, detailed ratings, and actionable feedback—so you can improve what matters.',
      },
      socialProofAngles: [
        'Improved NPS scores over time',
        'Reduced churn through early intervention',
        'More testimonials from identified promoters',
        'Better product decisions from feedback data',
      ],
    },
  }),

  // 2. Support Ticket Form
  createTemplate({
    id: 'support-ticket',
    name: 'Support Ticket Form',
    shortDescription: 'Submit a customer support request',
    fullDescription: 'A structured support ticket form for customers to report issues and request assistance. Includes priority levels, category selection, and file attachment support.',
    category: 'customer-service',
    icon: 'TicketPlus',
    complexity: 'simple',
    estimatedTime: 4,
    isFeatured: true,
    displayOrder: 2,
    tags: ['support', 'ticket', 'help', 'issue', 'request'],
    useCases: [
      'Technical support requests',
      'Account assistance',
      'Billing inquiries',
      'General help requests',
    ],
    features: [
      'Priority level selection',
      'Category routing',
      'Screenshot/file attachments',
      'Contact preference options',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { fieldWidth: 'half' }),
      textField('accountId', 'Account ID / Order Number (if applicable)'),
      sectionHeader('issue', 'Issue Details'),
      selectField('category', 'Issue Category', [
        'Technical Issue',
        'Account Access',
        'Billing/Payment',
        'Product Question',
        'Feature Request',
        'Order Status',
        'Returns/Refunds',
        'Other',
      ], { required: true }),
      selectField('priority', 'Priority Level', [
        'Low - General question',
        'Medium - Issue affecting my work',
        'High - Significant impact',
        'Urgent - Complete blocker',
      ], { required: true }),
      textField('subject', 'Brief Subject/Title', { required: true }),
      textareaField('description', 'Detailed Description', {
        required: true,
        placeholder: 'Please describe your issue in detail. Include any error messages you see...',
        validation: { minLength: 50 },
      }),
      sectionHeader('context', 'Additional Context'),
      textField('browser', 'Browser/Device (if technical issue)'),
      textField('stepsToReproduce', 'Steps to Reproduce (if applicable)'),
      fileField('attachments', 'Screenshots or Files', {
        validation: { multiple: true, maxFiles: 5 },
      }),
      sectionHeader('preferences', 'Contact Preferences'),
      selectField('preferredContact', 'Preferred Contact Method', [
        'Email',
        'Phone',
        'Either',
      ]),
      selectField('bestTime', 'Best Time to Reach You', [
        'Morning (9am-12pm)',
        'Afternoon (12pm-5pm)',
        'Evening (5pm-8pm)',
        'Any time',
      ]),
    ],
    enhanced: {
      headline: 'Resolve Customer Issues Before They Escalate',
      subheadline: 'A structured support ticket form that captures issue details, priority, and context upfront—so your team can solve problems faster with fewer back-and-forth exchanges.',
      longDescription: {
        opening: 'Vague support requests waste everyone\'s time. "It\'s broken" tells you nothing. Support agents spend hours asking for basic information before they can even start troubleshooting. Customers grow frustrated repeating themselves across channels.',
        solution: 'This template captures everything agents need upfront: Issue Category routes tickets correctly, Priority Level sets expectations, Detailed Description with minimum length ensures sufficient context, and file attachments let customers show rather than describe. Contact preferences ensure follow-up happens on their terms.',
        outcome: 'First-response resolution rates improve because agents have context from the start. Average handle time drops when troubleshooting begins immediately. Customer satisfaction increases when issues are resolved without endless clarification requests.',
      },
      useCases: [
        {
          title: 'SaaS Technical Support',
          icon: '💻',
          industry: 'Technology / SaaS',
          scenario: 'Customers experience bugs, performance issues, or need help with features. Technical issues require detailed reproduction steps and environment information.',
          painPoint: 'Support agents can\'t reproduce issues without browser, device, and step-by-step context.',
          keyFields: ['Issue Category', 'Priority Level', 'Detailed Description', 'Browser/Device', 'Steps to Reproduce'],
          exampleOrganization: 'A B2B SaaS company handling 500+ support tickets monthly.',
        },
        {
          title: 'E-commerce Customer Service',
          icon: '🛒',
          industry: 'E-commerce / Retail',
          scenario: 'Customers need help with orders, returns, payments, or product questions. Speed matters for order-related issues.',
          painPoint: 'Order issues require account lookup that wastes time when customers don\'t provide order numbers.',
          keyFields: ['Account ID / Order Number', 'Issue Category', 'Priority Level', 'Detailed Description'],
          exampleOrganization: 'An online retailer processing 10,000+ monthly orders with a dedicated support team.',
        },
        {
          title: 'IT Help Desk',
          icon: '🎫',
          industry: 'Any / Internal',
          scenario: 'Employees submit IT tickets for hardware, software, access, or network issues. Priority routing ensures critical issues get immediate attention.',
          painPoint: 'All tickets look the same priority; critical issues get buried in the queue.',
          keyFields: ['Issue Category', 'Priority Level', 'Subject', 'Detailed Description', 'Screenshots'],
          exampleOrganization: 'An enterprise IT department supporting 1,000+ employees.',
        },
        {
          title: 'Financial Services Support',
          icon: '💳',
          industry: 'Finance / Banking',
          scenario: 'Account holders need help with transactions, access, or billing. Security and urgency vary widely by issue type.',
          painPoint: 'Security-sensitive issues mixed with routine questions; no way to prioritize urgent matters.',
          keyFields: ['Account Number', 'Issue Category', 'Priority Level', 'Detailed Description'],
          exampleOrganization: 'A fintech company with 50,000+ active accounts and 24/7 support coverage.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Product/Plan Selection',
          description: 'If you have multiple products, add a field to identify which product the issue relates to for specialized routing.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Self-Service Links',
          description: 'Display relevant help articles based on category selection before submission to deflect common questions.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Screen Recording Upload',
          description: 'Add a file field accepting video files so customers can record their screen showing the issue.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Build SLA-Based Routing',
          description: 'Route urgent tickets to senior agents; auto-assign based on category to specialized team members.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Expected Response Time',
          description: 'Show estimated response time on the confirmation page based on priority and queue depth.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'auto-response',
          title: 'Send Ticket Confirmation',
          description: 'Immediately email the customer with ticket number, expected response time, and relevant self-help resources.',
          trigger: 'On form submission',
          benefits: ['Professional acknowledgment', 'Sets expectations'],
        },
        {
          workflowType: 'priority-routing',
          title: 'Route by Priority',
          description: 'Urgent tickets page on-call agent immediately; High priority goes to senior support; normal enters queue.',
          trigger: 'On form submission based on priority',
          benefits: ['Critical issues get immediate attention', 'Efficient triage'],
        },
        {
          workflowType: 'slack-notification',
          title: 'Alert Team Channel',
          description: 'Post new tickets to #support-tickets with summary for team visibility and quick claiming.',
          trigger: 'On form submission',
          benefits: ['Team visibility', 'Faster response'],
        },
        {
          workflowType: 'helpdesk-integration',
          title: 'Create Ticket in Help Desk',
          description: 'Automatically create ticket in Zendesk, Freshdesk, or Intercom with all form data mapped.',
          trigger: 'On form submission',
          benefits: ['No manual data entry', 'Unified ticket management'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Category and priority as enums enable clean routing and SLA logic',
          'Description field has minLength validation ensuring actionable detail',
          'Attachments stored as array of file references for flexible access',
        ],
        integrationHints: [
          'Webhook to help desk (Zendesk, Freshdesk) for ticket creation',
          'POST to Slack for real-time team notifications',
          'Connect to knowledge base API to suggest relevant articles based on category',
        ],
        mongoDBConsiderations: [
          'Compound index on {priority: 1, createdAt: -1} for SLA monitoring',
          'Index on {category: 1} for category-based queue management',
          'Index on {email: 1} for customer ticket history lookup',
        ],
      },
      seo: {
        metaTitle: 'Support Ticket Form Template | NetPad',
        metaDescription: 'Free support ticket form with priority levels, category routing, and file attachments. Resolve customer issues faster with structured requests.',
        keywords: [
          'support ticket form',
          'help desk form',
          'customer support form',
          'IT ticket form',
          'issue reporting form',
          'support request template',
          'help request form',
        ],
        ogDescription: 'Stop the back-and-forth. This support ticket form captures issue details, priority, and context upfront—so your team can resolve issues faster.',
      },
      socialProofAngles: [
        'Faster first-response times',
        'Higher first-contact resolution',
        'Improved customer satisfaction',
        'Reduced average handle time',
      ],
    },
  }),

  // 3. Product Return Form
  createTemplate({
    id: 'product-return',
    name: 'Product Return Form',
    shortDescription: 'Request a product return or exchange',
    fullDescription: 'Enable customers to initiate product returns or exchanges. Captures order details, return reasons, and preferred resolution for efficient processing.',
    category: 'customer-service',
    icon: 'PackageX',
    complexity: 'simple',
    estimatedTime: 4,
    displayOrder: 3,
    tags: ['return', 'exchange', 'refund', 'rma'],
    useCases: [
      'Product returns',
      'Exchanges',
      'Refund requests',
      'RMA processing',
    ],
    features: [
      'Order lookup',
      'Return reason categorization',
      'Condition assessment',
      'Resolution preference',
    ],
    fieldConfigs: [
      sectionHeader('customer', 'Customer Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { fieldWidth: 'half' }),
      sectionHeader('order', 'Order Information'),
      textField('orderNumber', 'Order Number', { required: true }),
      dateField('purchaseDate', 'Purchase Date', { required: true }),
      textField('productName', 'Product Name', { required: true }),
      numberField('quantity', 'Quantity to Return', { required: true, validation: { min: 1 } }),
      sectionHeader('return', 'Return Details'),
      selectField('returnReason', 'Reason for Return', [
        'Wrong item received',
        'Item damaged/defective',
        'Item not as described',
        'No longer needed',
        'Better price found elsewhere',
        'Arrived too late',
        'Ordered wrong size/color',
        'Other',
      ], { required: true }),
      textareaField('reasonDetails', 'Please provide more details', {
        required: true,
        placeholder: 'Help us understand the issue...',
      }),
      selectField('productCondition', 'Product Condition', [
        'Unopened/Sealed',
        'Opened but unused',
        'Lightly used',
        'Defective/Damaged',
      ], { required: true }),
      fileField('photos', 'Photos of Product (if damaged)', {
        validation: { multiple: true, maxFiles: 3, allowedTypes: ['image/*'] },
      }),
      sectionHeader('resolution', 'Preferred Resolution'),
      selectField('resolution', 'Preferred Resolution', [
        'Full refund',
        'Exchange for same item',
        'Exchange for different item',
        'Store credit',
      ], { required: true }),
      textField('exchangeItem', 'Exchange Item Details (if applicable)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'resolution', operator: 'equals', value: 'Exchange for different item' },
          ],
        },
      }),
    ],
    enhanced: {
      headline: 'Process Returns That Protect Your Bottom Line',
      subheadline: 'Capture order details, return reasons, and resolution preferences upfront—so you can process returns efficiently while minimizing fraud and unnecessary costs.',
      longDescription: {
        opening: 'Returns are expensive. Every return involves shipping costs, restocking time, and potential product loss. Without structured capture, returns staff waste time chasing order numbers, verifying purchases, and determining appropriate resolutions.',
        solution: 'This template streamlines the return process: Order Number and Purchase Date enable quick verification, Return Reason categorization identifies patterns, Product Condition assessment determines restocking eligibility, and Preferred Resolution captures customer expectations upfront. Photo uploads document condition for damaged item claims.',
        outcome: 'Process returns faster with complete information from the start. Reduce fraud by requiring verifiable order details. Identify product quality issues through reason pattern analysis. Improve customer satisfaction by setting clear expectations about resolution options.',
      },
      useCases: [
        {
          title: 'E-commerce Returns',
          icon: '📦',
          industry: 'E-commerce / Retail',
          scenario: 'Online shoppers request returns for various reasons. Without structure, processing each return requires multiple emails to gather basic information.',
          painPoint: 'Returns take 3-5 days to process because staff chase order numbers and photos repeatedly.',
          keyFields: ['Order Number', 'Reason for Return', 'Product Condition', 'Preferred Resolution'],
          exampleOrganization: 'An e-commerce retailer processing 500+ returns monthly.',
        },
        {
          title: 'Brick-and-Mortar Returns',
          icon: '🏪',
          industry: 'Retail',
          scenario: 'Customers return in-store purchases by mail or at different locations. Receipt and purchase verification are essential.',
          painPoint: 'Without purchase verification, fraudulent returns increase costs significantly.',
          keyFields: ['Order Number', 'Purchase Date', 'Product Name', 'Reason for Return'],
          exampleOrganization: 'A retail chain with 50+ locations processing returns at any store.',
        },
        {
          title: 'Subscription Box Returns',
          icon: '📬',
          industry: 'Subscription Commerce',
          scenario: 'Subscribers return items from their boxes. Tracking which items from which shipment requires clear identification.',
          painPoint: 'Subscription items are hard to trace when customers don\'t specify which box the item came from.',
          keyFields: ['Order Number', 'Product Name', 'Quantity to Return', 'Preferred Resolution'],
          exampleOrganization: 'A subscription box company with 20,000 active subscribers.',
        },
        {
          title: 'B2B Equipment Returns',
          icon: '🔧',
          industry: 'B2B / Manufacturing',
          scenario: 'Business customers return equipment or supplies. Higher value items require more detailed documentation and condition assessment.',
          painPoint: 'High-value returns disputed over condition; no photographic evidence at time of return.',
          keyFields: ['Order Number', 'Product Condition', 'Photos of Product', 'Reason Details'],
          exampleOrganization: 'A B2B distributor handling $100K+ in monthly returns.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Return Eligibility Check',
          description: 'Display return policy based on purchase date. Auto-reject requests outside the return window.',
          difficulty: 'medium',
        },
        {
          title: 'Include Prepaid Label Option',
          description: 'Add a checkbox to request prepaid return shipping label. Calculate shipping cost for deduction from refund.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Enable Store Credit Incentive',
          description: 'Offer bonus store credit (10-15%) for choosing store credit over refund. Reduces cash outflow.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Build RMA Number Generation',
          description: 'Auto-generate unique RMA numbers on submission. Email RMA with return instructions.',
          difficulty: 'medium',
        },
        {
          title: 'Add Product Quality Tracking',
          description: 'Track return reasons by SKU to identify products with quality issues or misleading descriptions.',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-confirmation',
          title: 'Send RMA Confirmation',
          description: 'Email customer with RMA number, return shipping instructions, and expected refund timeline.',
          trigger: 'On form submission',
          benefits: ['Clear instructions', 'Reduced support questions'],
        },
        {
          workflowType: 'order-validation',
          title: 'Verify Order Details',
          description: 'Cross-reference submitted order number with order system to validate purchase and return eligibility.',
          trigger: 'On form submission',
          benefits: ['Fraud prevention', 'Automated eligibility check'],
        },
        {
          workflowType: 'inventory-update',
          title: 'Create Receiving Record',
          description: 'Create expected inventory receipt in warehouse system so staff are prepared for return arrival.',
          trigger: 'On form submission',
          benefits: ['Prepared warehouse staff', 'Faster processing'],
        },
        {
          workflowType: 'refund-processing',
          title: 'Auto-Process Refund',
          description: 'For sealed/unopened returns, automatically process refund once tracking shows delivery to warehouse.',
          trigger: 'On return receipt + condition = sealed',
          benefits: ['Faster refunds', 'Happy customers'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Order number enables join with order system for validation and history',
          'Return reason as enum enables pattern analysis across products',
          'Product condition determines refund amount and restocking eligibility',
        ],
        integrationHints: [
          'Webhook to order management (Shopify, WooCommerce) to validate order details',
          'POST to shipping API (ShipStation, EasyPost) to generate prepaid labels',
          'Connect to payment processor to initiate refunds on approval',
        ],
        mongoDBConsiderations: [
          'Index on {orderNumber: 1} for order lookup and duplicate detection',
          'Index on {returnReason: 1, productName: 1} for quality pattern analysis',
          'Index on {createdAt: -1, status: 1} for returns dashboard queries',
        ],
      },
      seo: {
        metaTitle: 'Product Return Form Template | NetPad',
        metaDescription: 'Free product return and RMA form with order verification, condition tracking, and resolution preferences. Process returns efficiently.',
        keywords: [
          'product return form',
          'RMA form template',
          'return request form',
          'exchange form',
          'refund request form',
          'return authorization',
          'ecommerce return form',
        ],
        ogDescription: 'Stop chasing order numbers for every return. This form captures everything needed to process returns fast—order details, photos, and resolution preference.',
      },
      socialProofAngles: [
        'Faster return processing time',
        'Reduced return fraud',
        'Better product quality insights',
        'Improved customer satisfaction',
      ],
    },
  }),

  // 4. Warranty Claim Form
  createTemplate({
    id: 'warranty-claim',
    name: 'Warranty Claim Form',
    shortDescription: 'Submit a product warranty claim',
    fullDescription: 'File warranty claims for defective or malfunctioning products. Captures product details, proof of purchase, and detailed issue description.',
    category: 'customer-service',
    icon: 'ShieldCheck',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 4,
    tags: ['warranty', 'claim', 'defect', 'guarantee'],
    useCases: [
      'Warranty claims',
      'Manufacturer defects',
      'Product repairs',
      'Replacement requests',
    ],
    features: [
      'Product registration verification',
      'Proof of purchase upload',
      'Issue documentation',
      'Service preference selection',
    ],
    fieldConfigs: [
      sectionHeader('customer', 'Customer Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      textField('address', 'Shipping Address (for replacements)', { required: true }),
      sectionHeader('product', 'Product Information'),
      textField('productName', 'Product Name', { required: true }),
      textField('modelNumber', 'Model Number', { required: true, fieldWidth: 'half' }),
      textField('serialNumber', 'Serial Number', { required: true, fieldWidth: 'half' }),
      dateField('purchaseDate', 'Purchase Date', { required: true }),
      textField('purchaseLocation', 'Where was it purchased?'),
      fileField('proofOfPurchase', 'Proof of Purchase (receipt or invoice)', {
        required: true,
        validation: { allowedTypes: ['image/*', 'application/pdf'] },
      }),
      sectionHeader('issue', 'Issue Description'),
      selectField('issueType', 'Type of Issue', [
        'Complete failure - Does not work',
        'Partial malfunction',
        'Physical defect',
        'Safety concern',
        'Performance degradation',
        'Other',
      ], { required: true }),
      dateField('issueStartDate', 'When did the issue start?', { required: true }),
      textareaField('issueDescription', 'Detailed Description of the Issue', {
        required: true,
        placeholder: 'Describe what is happening, any error messages, and what you\'ve tried...',
        validation: { minLength: 100 },
      }),
      fileField('issuePhotos', 'Photos/Videos of the Issue', {
        validation: { multiple: true, maxFiles: 5 },
      }),
      sectionHeader('resolution', 'Service Options'),
      selectField('preferredResolution', 'Preferred Resolution', [
        'Repair',
        'Replacement',
        'Refund',
        'No preference - recommend best option',
      ], { required: true }),
      yesNoField('originalPackaging', 'Do you have original packaging?'),
    ],
    enhanced: {
      headline: 'Validate Claims Quickly, Honor Warranties Fairly',
      subheadline: 'Collect proof of purchase, product details, and issue documentation in one submission—so warranty claims get resolved accurately without endless back-and-forth.',
      longDescription: {
        opening: 'Warranty claims are a minefield. Customers submit claims without receipts, can\'t provide serial numbers, or describe issues vaguely. Processing teams waste hours chasing documentation while customers grow frustrated waiting for resolution.',
        solution: 'This template captures everything needed for claim validation: Model and Serial Number for product identification, Proof of Purchase upload for warranty verification, detailed Issue Description with minimum length for clear understanding, and photo/video documentation for visual confirmation. Issue type categorization enables quick routing to appropriate specialists.',
        outcome: 'Claims are processed in days instead of weeks. Warranty verification happens instantly with uploaded receipts. Service teams understand issues clearly from the first submission. Customers receive fair, consistent resolutions based on documented evidence.',
      },
      useCases: [
        {
          title: 'Consumer Electronics',
          icon: '📱',
          industry: 'Electronics / Appliances',
          scenario: 'Customers submit warranty claims for phones, laptops, appliances, and electronics. Serial number verification and purchase date determine warranty status.',
          painPoint: 'Customers lose receipts; warranty status disputes delay claim processing.',
          keyFields: ['Model Number', 'Serial Number', 'Purchase Date', 'Proof of Purchase', 'Issue Description'],
          exampleOrganization: 'A consumer electronics brand processing 1,000+ warranty claims monthly.',
        },
        {
          title: 'Home Appliance Warranties',
          icon: '🏠',
          industry: 'Appliances',
          scenario: 'Major appliances fail within warranty period. Service calls are expensive; accurate diagnosis before dispatch saves money.',
          painPoint: 'Technicians arrive unprepared because the issue wasn\'t clearly documented beforehand.',
          keyFields: ['Product Name', 'Type of Issue', 'Issue Description', 'Photos/Videos of the Issue'],
          exampleOrganization: 'An appliance manufacturer with 5-year warranty on major appliances.',
        },
        {
          title: 'Automotive Parts Warranty',
          icon: '🚗',
          industry: 'Automotive',
          scenario: 'Aftermarket and OEM parts fail prematurely. Proof of purchase and installation documentation are critical for claims.',
          painPoint: 'Parts claims disputed over installation practices; no documentation of original defect.',
          keyFields: ['Product Name', 'Serial Number', 'Purchase Location', 'Issue Description', 'Issue Photos'],
          exampleOrganization: 'An auto parts retailer with manufacturer-backed warranty programs.',
        },
        {
          title: 'Software/Hardware Extended Warranty',
          icon: '💻',
          industry: 'Technology',
          scenario: 'Business equipment fails under extended warranty or service contract. Response time and replacement speed matter.',
          painPoint: 'Enterprise claims require faster resolution; standard processes are too slow.',
          keyFields: ['Model Number', 'Serial Number', 'Preferred Resolution', 'Issue Type', 'When did the issue start?'],
          exampleOrganization: 'An enterprise hardware vendor with premium support contracts.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Product Registration Lookup',
          description: 'If customers registered products, auto-populate details from serial number lookup.',
          difficulty: 'advanced',
        },
        {
          title: 'Include Video Upload',
          description: 'For intermittent issues, allow customers to upload video demonstrating the problem.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Add Service Location Selection',
          description: 'For in-person service, let customers choose from authorized service centers based on location.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Enable Warranty Status Check',
          description: 'Validate warranty status from serial number before accepting claim submission.',
          difficulty: 'advanced',
        },
        {
          title: 'Build Claim Status Portal',
          description: 'Create a customer-facing page where claimants can check status with their claim number.',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-confirmation',
          title: 'Send Claim Receipt',
          description: 'Confirm claim submission with unique claim number, expected processing timeline, and next steps.',
          trigger: 'On form submission',
          benefits: ['Clear expectations', 'Claim tracking reference'],
        },
        {
          workflowType: 'warranty-validation',
          title: 'Verify Warranty Status',
          description: 'Cross-reference serial number and purchase date against product registration database for instant validation.',
          trigger: 'On form submission',
          benefits: ['Automated validation', 'Faster processing'],
        },
        {
          workflowType: 'service-dispatch',
          title: 'Schedule Service Call',
          description: 'For repair requests, automatically schedule service appointment or generate service ticket for dispatch.',
          trigger: 'On form submission where preferredResolution = Repair',
          benefits: ['Faster resolution', 'Streamlined scheduling'],
        },
        {
          workflowType: 'replacement-fulfillment',
          title: 'Process Replacement Shipment',
          description: 'For approved replacements, trigger fulfillment system to ship replacement unit immediately.',
          trigger: 'On claim approval where preferredResolution = Replacement',
          benefits: ['Fast replacement delivery', 'Automated fulfillment'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Serial number stored for product lookup and duplicate claim prevention',
          'Issue type as enum enables routing to appropriate service specialists',
          'File fields accept images and PDFs for flexible documentation',
        ],
        integrationHints: [
          'Webhook to product registration system for warranty status verification',
          'POST to service management system (ServiceNow, Salesforce Service Cloud) for case creation',
          'Connect to fulfillment system for replacement unit dispatch',
        ],
        mongoDBConsiderations: [
          'Unique index on {serialNumber: 1} for duplicate claim detection',
          'Index on {issueType: 1, createdAt: -1} for issue pattern analysis',
          'Index on {purchaseDate: 1} for warranty period validation',
        ],
      },
      seo: {
        metaTitle: 'Warranty Claim Form Template | NetPad',
        metaDescription: 'Free warranty claim form with proof of purchase upload, serial number capture, and issue documentation. Process claims accurately and efficiently.',
        keywords: [
          'warranty claim form',
          'product warranty form',
          'warranty request',
          'claim submission form',
          'guarantee claim',
          'product defect form',
          'warranty service request',
        ],
        ogDescription: 'Stop the warranty claim chaos. This form captures serial numbers, proof of purchase, and issue details—so claims get resolved fairly and quickly.',
      },
      socialProofAngles: [
        'Faster claim resolution',
        'Reduced fraudulent claims',
        'Better customer experience',
        'Lower service costs',
      ],
    },
  }),

  // 5. Customer Complaint Form
  createTemplate({
    id: 'customer-complaint',
    name: 'Customer Complaint Form',
    shortDescription: 'File a formal customer complaint',
    fullDescription: 'A structured form for customers to file formal complaints. Enables detailed documentation and ensures complaints are properly routed for resolution.',
    category: 'customer-service',
    icon: 'MessageSquareWarning',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 5,
    tags: ['complaint', 'grievance', 'issue', 'escalation'],
    useCases: [
      'Formal complaints',
      'Service issues',
      'Product problems',
      'Staff conduct issues',
    ],
    features: [
      'Detailed incident documentation',
      'Impact assessment',
      'Resolution tracking',
      'Follow-up scheduling',
    ],
    fieldConfigs: [
      sectionHeader('customer', 'Your Information'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      textField('accountNumber', 'Account/Customer Number (if applicable)'),
      sectionHeader('incident', 'Incident Details'),
      selectField('complaintType', 'Type of Complaint', [
        'Product Quality',
        'Service Quality',
        'Billing/Pricing',
        'Delivery/Shipping',
        'Staff Conduct',
        'Policy Issue',
        'Safety Concern',
        'Other',
      ], { required: true }),
      dateField('incidentDate', 'Date of Incident', { required: true }),
      textField('incidentLocation', 'Location (if applicable)'),
      textField('staffInvolved', 'Staff Member(s) Involved (if known)'),
      textareaField('complaintDescription', 'Detailed Description of Complaint', {
        required: true,
        placeholder: 'Please provide a complete description of what happened...',
        validation: { minLength: 100 },
      }),
      sectionHeader('impact', 'Impact'),
      textareaField('impactDescription', 'How did this affect you?', {
        required: true,
        placeholder: 'Describe any inconvenience, loss, or harm you experienced...',
      }),
      yesNoField('financialLoss', 'Did you experience financial loss?'),
      textareaField('financialDetails', 'Financial Loss Details', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'financialLoss', operator: 'isTrue' }],
        },
      }),
      sectionHeader('resolution', 'Desired Resolution'),
      textareaField('desiredResolution', 'What resolution would you like?', {
        required: true,
        placeholder: 'Tell us what would make this right...',
      }),
      yesNoField('previousContact', 'Have you contacted us about this before?'),
      textareaField('previousContactDetails', 'Previous Contact Details', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'previousContact', operator: 'isTrue' }],
        },
      }),
      fileField('supportingDocs', 'Supporting Documentation', {
        validation: { multiple: true, maxFiles: 5 },
      }),
    ],
    enhanced: {
      headline: 'Handle Complaints Before They Become Crises',
      subheadline: 'Document complaints thoroughly with incident details, impact assessment, and resolution tracking—so issues get resolved fairly and learning happens systematically.',
      longDescription: {
        opening: 'Mishandled complaints become viral social media posts, legal action, and churn. When complaints arrive via email, phone, and chat without structure, details get lost, escalations surprise leadership, and the same problems recur because patterns aren\'t tracked.',
        solution: 'This template creates a formal complaint record: Complaint Type enables pattern analysis, Incident Date and Location provide context, detailed Description with minimum length ensures complete documentation, Impact Assessment captures customer harm, and Previous Contact tracking identifies escalations. File attachments support claims with evidence.',
        outcome: 'Every complaint becomes a trackable case with complete documentation. Patterns emerge from categorized data, enabling root cause fixes. Escalations are identified early through previous contact tracking. Resolution tracking ensures follow-through and customer recovery.',
      },
      useCases: [
        {
          title: 'Service Recovery',
          icon: '🔄',
          industry: 'Any',
          scenario: 'Customers experience service failures and need formal resolution. Without structure, complaints become he-said-she-said disputes.',
          painPoint: 'Staff involved in incidents aren\'t notified; customer has to repeat story multiple times.',
          keyFields: ['Type of Complaint', 'Date of Incident', 'Detailed Description', 'Desired Resolution'],
          exampleOrganization: 'A service business committed to formal complaint resolution within 48 hours.',
        },
        {
          title: 'Regulated Industries',
          icon: '⚖️',
          industry: 'Financial Services / Healthcare',
          scenario: 'Compliance requires formal complaint documentation, tracking, and resolution. Regulators audit complaint handling processes.',
          painPoint: 'Complaints not documented properly create regulatory risk and audit failures.',
          keyFields: ['Account Number', 'Type of Complaint', 'Detailed Description', 'Financial Loss', 'Supporting Documentation'],
          exampleOrganization: 'A financial services firm required to respond to complaints within regulatory timeframes.',
        },
        {
          title: 'Staff Conduct Issues',
          icon: '👥',
          industry: 'Retail / Hospitality',
          scenario: 'Customers report negative interactions with staff. HR needs documentation to address performance issues fairly.',
          painPoint: 'Staff conduct complaints lack specific details; can\'t determine if patterns exist.',
          keyFields: ['Type of Complaint', 'Staff Member(s) Involved', 'Location', 'Incident Description', 'Desired Resolution'],
          exampleOrganization: 'A hospitality company with 500+ front-line staff across multiple locations.',
        },
        {
          title: 'Product Liability Documentation',
          icon: '⚠️',
          industry: 'Manufacturing / Consumer Products',
          scenario: 'Customers report safety concerns or injuries. Legal and product safety teams need complete documentation.',
          painPoint: 'Safety complaints not identified as such; product issues not flagged for safety team.',
          keyFields: ['Type of Complaint', 'How did this affect you?', 'Financial Loss Details', 'Supporting Documentation'],
          exampleOrganization: 'A consumer products company with strict product safety monitoring requirements.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Escalation Triggers',
          description: 'Flag complaints mentioning "safety", "legal", or "injury" for immediate escalation to specialized teams.',
          difficulty: 'medium',
        },
        {
          title: 'Include Resolution Timeline',
          description: 'Set expected resolution dates based on complaint type. Track SLA compliance automatically.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
        {
          title: 'Enable Anonymous Complaints',
          description: 'Add option for anonymous submission for sensitive issues like staff conduct or discrimination.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Build Complaint Dashboard',
          description: 'Create a reporting view showing complaint trends by type, location, resolution time, and outcome.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Follow-Up Survey',
          description: 'Send satisfaction survey after complaint resolution to confirm issue is resolved to customer\'s satisfaction.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'case-creation',
          title: 'Create Complaint Case',
          description: 'Generate unique case number, assign to appropriate team based on complaint type, set resolution deadline.',
          trigger: 'On form submission',
          benefits: ['Trackable cases', 'Clear ownership'],
        },
        {
          workflowType: 'escalation-routing',
          title: 'Route High-Impact Complaints',
          description: 'Complaints involving financial loss, safety, or legal mention go to management immediately.',
          trigger: 'On form submission with specific keywords or fields',
          benefits: ['Early escalation', 'Risk mitigation'],
        },
        {
          workflowType: 'acknowledgment-email',
          title: 'Send Complaint Acknowledgment',
          description: 'Confirm receipt with case number, assigned handler name, and expected resolution timeline.',
          trigger: 'On form submission',
          benefits: ['Professional response', 'Transparency'],
        },
        {
          workflowType: 'resolution-tracking',
          title: 'Track Resolution Progress',
          description: 'Monitor open complaints against SLA. Alert managers on approaching deadlines.',
          trigger: 'Scheduled daily',
          benefits: ['SLA compliance', 'No forgotten complaints'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Complaint type as enum enables trend analysis and team routing',
          'Financial loss fields (boolean + details) enable liability assessment',
          'Previous contact tracking identifies escalated vs. first-time complaints',
        ],
        integrationHints: [
          'Webhook to case management system (Salesforce Service Cloud, Zendesk) for tracking',
          'POST to legal/compliance system when safety or legal keywords detected',
          'Connect to CRM to update customer health score on complaint submission',
        ],
        mongoDBConsiderations: [
          'Index on {complaintType: 1, incidentDate: -1} for complaint trend analysis',
          'Index on {accountNumber: 1} for customer complaint history lookup',
          'Text index on complaintDescription for keyword search (safety, legal terms)',
        ],
      },
      seo: {
        metaTitle: 'Customer Complaint Form Template | NetPad',
        metaDescription: 'Free complaint form with incident documentation, impact tracking, and resolution management. Handle complaints professionally and systematically.',
        keywords: [
          'customer complaint form',
          'complaint submission form',
          'grievance form',
          'service complaint form',
          'formal complaint template',
          'complaint tracking',
          'issue resolution form',
        ],
        ogDescription: 'Turn complaints into improvements. This form documents incidents, tracks impact, and ensures resolution—so problems get fixed and customers are recovered.',
      },
      socialProofAngles: [
        'Faster complaint resolution',
        'Better pattern identification',
        'Improved customer recovery',
        'Reduced escalations to social media',
      ],
    },
  }),

  // 6. Feature Request Form
  createTemplate({
    id: 'feature-request',
    name: 'Feature Request Form',
    shortDescription: 'Suggest new features or improvements',
    fullDescription: 'Collect feature requests and product improvement ideas from customers. Helps product teams understand user needs and prioritize development.',
    category: 'customer-service',
    icon: 'Lightbulb',
    complexity: 'simple',
    estimatedTime: 4,
    displayOrder: 6,
    tags: ['feature', 'request', 'suggestion', 'improvement', 'feedback'],
    useCases: [
      'Product feedback',
      'Feature suggestions',
      'Enhancement requests',
      'User research',
    ],
    features: [
      'Feature description',
      'Use case capture',
      'Priority indication',
      'Similar product references',
    ],
    fieldConfigs: [
      sectionHeader('about', 'About You'),
      textField('name', 'Your Name', { required: true }),
      emailField('email', 'Email Address', { required: true }),
      textField('company', 'Company (if applicable)'),
      selectField('userType', 'What type of user are you?', [
        'Free User',
        'Paid Customer',
        'Trial User',
        'Potential Customer',
        'Partner',
      ]),
      sectionHeader('feature', 'Feature Request'),
      textField('featureTitle', 'Feature Title', {
        required: true,
        placeholder: 'Give your feature request a short, descriptive title',
      }),
      selectField('featureType', 'Type of Request', [
        'New Feature',
        'Enhancement to Existing Feature',
        'Integration Request',
        'Performance Improvement',
        'UI/UX Improvement',
        'Other',
      ], { required: true }),
      textareaField('featureDescription', 'Describe the Feature', {
        required: true,
        placeholder: 'Provide as much detail as possible about what you\'d like...',
        validation: { minLength: 50 },
      }),
      textareaField('useCase', 'What problem would this solve?', {
        required: true,
        placeholder: 'Describe the problem or use case this feature would address...',
      }),
      selectField('frequency', 'How often would you use this feature?', [
        'Daily',
        'Weekly',
        'Monthly',
        'Occasionally',
      ]),
      scaleField('importance', 'How important is this feature to you?', {
        validation: { min: 1, max: 5, lowLabel: 'Nice to have', highLabel: 'Critical' },
      }),
      sectionHeader('alternatives', 'Current Alternatives'),
      textareaField('currentWorkaround', 'How do you currently handle this?', {
        placeholder: 'Describe any workarounds you currently use...',
      }),
      textField('competitorReference', 'Does a competitor offer this?', {
        placeholder: 'Name any competitors who have this feature',
      }),
      yesNoField('willingToTest', 'Would you be willing to test a beta version?'),
    ],
    enhanced: {
      headline: 'Channel Customer Ideas Into Product Decisions',
      subheadline: 'Collect structured feature requests with use case context, frequency indicators, and workaround details—so product teams can prioritize what customers actually need.',
      longDescription: {
        opening: 'Feature requests come from everywhere: support tickets, sales calls, social media, NPS surveys. Without structure, they pile up in spreadsheets, lose context, and never make it to roadmap discussions. Good ideas die because no one can quantify demand.',
        solution: 'This template captures what product teams need to prioritize: Feature Type categorizes requests, Use Case explains the problem being solved, Frequency and Importance indicate demand intensity, Current Workaround reveals pain severity, and Competitor Reference adds competitive context. User type helps weight enterprise vs. free user requests.',
        outcome: 'Feature requests become actionable data. Product managers see patterns across requests, quantify demand, and make evidence-based prioritization decisions. Customer-reported workarounds reveal the severity of gaps. Beta testing volunteers accelerate validation cycles.',
      },
      useCases: [
        {
          title: 'SaaS Product Development',
          icon: '💡',
          industry: 'Technology / SaaS',
          scenario: 'Your product team receives 50+ feature requests monthly from customers, support, and sales. Without structure, prioritization is based on who shouts loudest.',
          painPoint: 'Feature requests lack context; product team can\'t assess actual demand or urgency.',
          keyFields: ['Feature Title', 'What problem would this solve?', 'How important is this feature to you?', 'How often would you use this?'],
          exampleOrganization: 'A B2B SaaS company with 500 customers and a 10-person product team.',
        },
        {
          title: 'Customer-Driven Roadmap',
          icon: '🗺️',
          industry: 'Any Product Company',
          scenario: 'Your roadmap planning needs customer input. You want to build what customers will actually use, not what internal stakeholders assume.',
          painPoint: 'Roadmap decisions made on gut instinct; features ship that customers don\'t use.',
          keyFields: ['Type of Request', 'Feature Description', 'Current Workaround', 'Competitor Reference'],
          exampleOrganization: 'A product-led company using customer input to inform quarterly roadmap.',
        },
        {
          title: 'Enterprise Customer Advisory',
          icon: '🏢',
          industry: 'Enterprise Software',
          scenario: 'Enterprise customers have specific needs that drive large deals. You need to track their requests separately for prioritization.',
          painPoint: 'Enterprise feature requests get lost with free user wishes; revenue-impacting needs not prioritized.',
          keyFields: ['What type of user are you?', 'Company', 'Feature Title', 'Feature Description', 'How important is this feature?'],
          exampleOrganization: 'An enterprise software vendor where top 20 accounts drive 60% of revenue.',
        },
        {
          title: 'Beta Program Recruitment',
          icon: '🧪',
          industry: 'Technology',
          scenario: 'When building requested features, you want customers who asked for them to test early versions. This form identifies willing beta testers.',
          painPoint: 'Beta programs have low participation because volunteers aren\'t tracked.',
          keyFields: ['Feature Title', 'Would you be willing to test a beta version?', 'Email Address'],
          exampleOrganization: 'A company running continuous beta programs with customer advisors.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Product Area Selection',
          description: 'If you have multiple products or modules, let requesters specify which area the feature relates to.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Request Voting',
          description: 'Create a public page where customers can see existing requests and upvote. Reduces duplicate submissions.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Revenue Association',
          description: 'For enterprise users, capture account name to associate requests with customer revenue data.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Build Status Updates',
          description: 'Notify requesters when their feature is added to roadmap, in development, or shipped.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Screenshot/Mockup Upload',
          description: 'Let customers upload sketches or screenshots showing what they want. Visual context helps product teams.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-confirmation',
          title: 'Acknowledge Request',
          description: 'Confirm receipt with unique request ID and link to public roadmap or status page.',
          trigger: 'On form submission',
          benefits: ['Customer feels heard', 'Trackable reference'],
        },
        {
          workflowType: 'product-board-integration',
          title: 'Create Product Board Item',
          description: 'Push request to ProductBoard, Aha!, or Jira with all context for product team review.',
          trigger: 'On form submission',
          benefits: ['Centralized request tracking', 'No manual entry'],
        },
        {
          workflowType: 'duplicate-detection',
          title: 'Check for Similar Requests',
          description: 'Search existing requests for similar feature titles. Link or merge duplicates automatically.',
          trigger: 'On form submission',
          benefits: ['Consolidated demand signals', 'Cleaner backlog'],
        },
        {
          workflowType: 'beta-recruitment',
          title: 'Add to Beta List',
          description: 'When "willing to test" is yes, add to beta tester list tagged with the feature they\'re interested in.',
          trigger: 'On form submission where willingToTest = true',
          benefits: ['Ready beta testers', 'Relevant participants'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Feature type and importance as enums enable aggregation and prioritization queries',
          'Use case and current workaround as text enable full-text search for similar requests',
          'User type enables weighted scoring (paid > free)',
        ],
        integrationHints: [
          'Webhook to product management tool (ProductBoard, Aha!, Jira) for request tracking',
          'POST to CRM to associate feature requests with account records',
          'Connect to email service to send status updates when request progresses',
        ],
        mongoDBConsiderations: [
          'Index on {featureType: 1, importance: 1} for prioritization queries',
          'Text index on featureTitle, featureDescription for duplicate detection',
          'Aggregation pipeline for counting requests by type and calculating demand scores',
        ],
      },
      seo: {
        metaTitle: 'Feature Request Form Template | NetPad',
        metaDescription: 'Free feature request form with use case capture, priority indicators, and beta tester recruitment. Build what customers actually want.',
        keywords: [
          'feature request form',
          'product feedback form',
          'enhancement request',
          'feature suggestion form',
          'product improvement form',
          'customer idea submission',
          'roadmap input form',
        ],
        ogDescription: 'Stop guessing what customers want. This form captures feature requests with use case context—so product teams can prioritize based on real demand.',
      },
      socialProofAngles: [
        'Better product decisions from customer data',
        'Higher feature adoption rates',
        'Improved customer retention',
        'More engaged beta testers',
      ],
    },
  }),

  // 7. Service Cancellation Form
  createTemplate({
    id: 'service-cancellation',
    name: 'Service Cancellation Form',
    shortDescription: 'Request to cancel service or subscription',
    fullDescription: 'Process service cancellation requests while capturing valuable feedback about reasons for leaving. Includes retention offers and handoff details.',
    category: 'customer-service',
    icon: 'XCircle',
    complexity: 'simple',
    estimatedTime: 4,
    displayOrder: 7,
    tags: ['cancellation', 'cancel', 'subscription', 'churn'],
    useCases: [
      'Subscription cancellations',
      'Service termination',
      'Membership cancellation',
      'Contract termination',
    ],
    features: [
      'Cancellation reason capture',
      'Retention offers',
      'Feedback collection',
      'Exit process guidance',
    ],
    fieldConfigs: [
      sectionHeader('account', 'Account Information'),
      textField('name', 'Account Holder Name', { required: true }),
      emailField('email', 'Account Email', { required: true }),
      textField('accountId', 'Account ID', { required: true }),
      phoneField('phone', 'Phone Number'),
      sectionHeader('cancellation', 'Cancellation Details'),
      selectField('serviceType', 'Service/Plan to Cancel', [
        'Basic Plan',
        'Pro Plan',
        'Enterprise Plan',
        'All Services',
        'Specific Feature',
      ], { required: true }),
      selectField('cancellationReason', 'Primary Reason for Cancellation', [
        'Too expensive',
        'Not using it enough',
        'Missing features I need',
        'Found a better alternative',
        'Poor customer service',
        'Technical issues',
        'Business closing',
        'Temporary - will return',
        'Other',
      ], { required: true }),
      textareaField('reasonDetails', 'Please tell us more', {
        required: true,
        placeholder: 'We\'d love to understand better so we can improve...',
      }),
      selectField('effectiveDate', 'When would you like cancellation effective?', [
        'Immediately',
        'End of current billing period',
        'Specific date',
      ], { required: true }),
      dateField('specificDate', 'Specific Cancellation Date', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'effectiveDate', operator: 'equals', value: 'Specific date' }],
        },
      }),
      sectionHeader('feedback', 'Help Us Improve'),
      ratingField('overallExperience', 'Rate your overall experience with us'),
      textareaField('whatCouldChange', 'What could we have done differently to keep you?'),
      yesNoField('considerReturn', 'Would you consider returning in the future?'),
      yesNoField('referOthers', 'Would you still refer others to us?'),
      sectionHeader('final', 'Final Steps'),
      yesNoField('dataExport', 'Would you like to export your data before cancellation?'),
      yesNoField('confirmCancellation', 'I confirm I want to cancel my service', { required: true }),
    ],
    enhanced: {
      headline: 'Reduce Churn by Understanding Why Customers Leave',
      subheadline: 'Capture cancellation reasons, offer targeted retention, and collect feedback that helps you keep future customers longer.',
      longDescription: {
        opening: 'Every cancellation is a lost opportunity. Customers click "cancel" and disappear without explanation. You never learn why they left, can\'t try to save them, and keep making the same mistakes that drive churn.',
        solution: 'This template turns cancellations into conversations: Cancellation Reason with detailed options reveals patterns, detailed feedback captures actionable insights, retention questions ("would you consider returning?") identify salvageable relationships, and data export options create a positive final experience. The confirmation step prevents accidental cancellations.',
        outcome: 'Understand why customers leave and reduce future churn. Identify at-risk segments before they cancel. Recover saveable customers with targeted retention offers. Part on good terms with proper data export, increasing the chance of return and referral.',
      },
      useCases: [
        {
          title: 'SaaS Subscription Churn',
          icon: '📉',
          industry: 'Technology / SaaS',
          scenario: 'Customers cancel monthly or annual subscriptions. Without understanding why, you can\'t improve retention.',
          painPoint: 'Churn reasons are guessed from support tickets; no systematic feedback from churned customers.',
          keyFields: ['Primary Reason for Cancellation', 'Please tell us more', 'What could we have done differently?'],
          exampleOrganization: 'A B2B SaaS company with 5% monthly churn needing to understand patterns.',
        },
        {
          title: 'Gym/Fitness Memberships',
          icon: '💪',
          industry: 'Fitness / Wellness',
          scenario: 'Members cancel gym memberships for various reasons. Some can be saved with freezes or modified plans.',
          painPoint: 'Good members leave without anyone offering alternatives; missed save opportunities.',
          keyFields: ['Service/Plan to Cancel', 'Cancellation Reason', 'When would you like cancellation effective?', 'Would you consider returning?'],
          exampleOrganization: 'A fitness chain with 50,000 members and seasonal churn patterns.',
        },
        {
          title: 'Streaming/Media Subscriptions',
          icon: '📺',
          industry: 'Media / Entertainment',
          scenario: 'Subscribers cancel after binge-watching specific content. Understanding content preferences improves acquisition.',
          painPoint: 'Content investment decisions made without knowing what actually retains subscribers.',
          keyFields: ['Cancellation Reason', 'Please tell us more', 'Would you consider returning?', 'Would you still refer others?'],
          exampleOrganization: 'A streaming service analyzing churn patterns against content release schedules.',
        },
        {
          title: 'Professional Service Contracts',
          icon: '📋',
          industry: 'Professional Services',
          scenario: 'Clients end ongoing service agreements. Exit feedback improves service delivery for remaining clients.',
          painPoint: 'Service quality issues not discovered until clients leave; patterns not identified.',
          keyFields: ['Service to Cancel', 'Cancellation Reason', 'Rate your overall experience', 'What could we have done differently?'],
          exampleOrganization: 'A managed services provider with $2M in recurring contract revenue.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Retention Offer',
          description: 'Based on cancellation reason, display targeted retention offers: discounts, plan downgrades, or pause options.',
          difficulty: 'medium',
        },
        {
          title: 'Include Pause/Freeze Option',
          description: 'Add alternatives to full cancellation: pause for 1-3 months, downgrade to free tier, or seasonal freeze.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Callback Request',
          description: 'Add option for customers to request a call from retention team before final cancellation.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Build Churn Analysis Dashboard',
          description: 'Track cancellation reasons over time, segment by plan/tenure, and correlate with product changes.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Win-Back Sequence',
          description: 'Trigger re-engagement emails at 30, 60, 90 days post-cancellation with personalized offers.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'retention-offer',
          title: 'Present Save Offer',
          description: 'Based on reason and tenure, present discount, plan change, or pause option before processing cancellation.',
          trigger: 'On form submission before confirmation',
          benefits: ['Immediate save opportunity', 'Reduced churn'],
        },
        {
          workflowType: 'data-export',
          title: 'Process Data Export',
          description: 'When customer requests data export, generate and email archive within 24 hours.',
          trigger: 'On form submission where dataExport = true',
          benefits: ['GDPR compliance', 'Positive last impression'],
        },
        {
          workflowType: 'cancellation-confirmation',
          title: 'Send Cancellation Confirmation',
          description: 'Confirm cancellation with effective date, any remaining obligations, and "we\'d love you back" messaging.',
          trigger: 'On cancellation processed',
          benefits: ['Clear closure', 'Door open for return'],
        },
        {
          workflowType: 'win-back-sequence',
          title: 'Trigger Win-Back Campaign',
          description: 'Add to win-back email sequence with personalized messaging based on cancellation reason.',
          trigger: '30 days after cancellation effective date',
          benefits: ['Re-engagement opportunity', 'Win-back revenue'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Cancellation reason as enum enables churn pattern analysis',
          'Effective date options support different cancellation timing needs',
          'Boolean fields (considerReturn, referOthers) enable segmented win-back campaigns',
        ],
        integrationHints: [
          'Webhook to billing system (Stripe, Chargebee) to process actual cancellation',
          'POST to CRM to update account status and trigger win-back campaign',
          'Connect to data export pipeline for GDPR-compliant data package generation',
        ],
        mongoDBConsiderations: [
          'Index on {cancellationReason: 1, createdAt: -1} for churn pattern analysis',
          'Index on {serviceType: 1} for plan-specific churn reporting',
          'Aggregation pipeline for calculating churn reasons by cohort/tenure',
        ],
      },
      seo: {
        metaTitle: 'Service Cancellation Form Template | NetPad',
        metaDescription: 'Free cancellation form with reason capture, retention offers, and feedback collection. Reduce churn by understanding why customers leave.',
        keywords: [
          'cancellation form',
          'subscription cancellation',
          'churn form',
          'service termination form',
          'cancel subscription form',
          'membership cancellation',
          'offboarding form',
        ],
        ogDescription: 'Every cancellation is a learning opportunity. This form captures reasons, offers retention alternatives, and collects feedback—so you can keep future customers longer.',
      },
      socialProofAngles: [
        'Reduced churn through retention offers',
        'Better understanding of why customers leave',
        'Higher win-back rates from churned customers',
        'Improved product from exit feedback',
      ],
    },
  }),

  // 8. Testimonial Submission Form
  createTemplate({
    id: 'testimonial-submission',
    name: 'Testimonial Submission Form',
    shortDescription: 'Submit a customer testimonial',
    fullDescription: 'Collect customer testimonials and success stories for marketing use. Captures detailed feedback along with permission for public use.',
    category: 'customer-service',
    icon: 'Quote',
    complexity: 'simple',
    estimatedTime: 5,
    displayOrder: 8,
    tags: ['testimonial', 'review', 'success story', 'marketing'],
    useCases: [
      'Marketing testimonials',
      'Case study collection',
      'Social proof gathering',
      'Customer advocacy',
    ],
    features: [
      'Testimonial capture',
      'Photo/video upload',
      'Permission management',
      'Use case selection',
    ],
    fieldConfigs: [
      sectionHeader('about', 'About You'),
      textField('name', 'Your Name', { required: true }),
      textField('title', 'Your Title/Role'),
      textField('company', 'Company Name'),
      textField('industry', 'Industry'),
      emailField('email', 'Email Address', { required: true }),
      urlField('website', 'Company Website'),
      sectionHeader('testimonial', 'Your Testimonial'),
      textareaField('testimonial', 'Your Testimonial', {
        required: true,
        placeholder: 'Share your experience with our product/service...',
        validation: { minLength: 50, maxLength: 1000 },
      }),
      ratingField('rating', 'Overall Rating', { required: true }),
      multiSelectField('benefitsExperienced', 'Key Benefits You Experienced', [
        'Saved time',
        'Saved money',
        'Improved efficiency',
        'Better results',
        'Easy to use',
        'Great support',
        'Reliable',
        'Innovative features',
      ]),
      textareaField('specificResults', 'Specific Results/Metrics (if any)', {
        placeholder: 'E.g., "Increased sales by 25%" or "Saved 10 hours per week"',
      }),
      selectField('productUsed', 'Which product/service are you reviewing?', [
        'Product A',
        'Product B',
        'All Products',
        'Services',
      ]),
      textField('timeAsCustomer', 'How long have you been a customer?'),
      sectionHeader('media', 'Photo/Video (Optional)'),
      fileField('headshot', 'Your Photo/Headshot', {
        validation: { allowedTypes: ['image/*'] },
      }),
      fileField('videoTestimonial', 'Video Testimonial', {
        validation: { allowedTypes: ['video/*'], maxSize: 100 },
      }),
      sectionHeader('permissions', 'Usage Permissions'),
      yesNoField('allowPublicUse', 'May we use this testimonial on our website and marketing materials?', { required: true }),
      yesNoField('allowNameUse', 'May we include your name?', { required: true }),
      yesNoField('allowCompanyUse', 'May we include your company name?'),
      yesNoField('allowSocialMedia', 'May we share on social media?'),
    ],
    enhanced: {
      headline: 'Collect Social Proof That Actually Converts',
      subheadline: 'Gather customer testimonials with specific results, usage permissions, and media options—so your marketing team has the social proof they need.',
      longDescription: {
        opening: 'Great customer quotes exist in scattered emails, call recordings, and NPS responses. Marketing hunts for usable testimonials, legal worries about permissions, and the best success stories never make it to your website.',
        solution: 'This template captures marketing-ready testimonials: structured feedback with Benefits Experienced for consistent messaging, Specific Results for quantifiable proof, Photo/Video upload for visual impact, and granular Usage Permissions for legal clarity. Product selection enables testimonial matching to features.',
        outcome: 'Build a testimonial library that marketing can actually use. Legal has documented permissions for every quote. Sales has industry-specific proof points for objection handling. Your website showcases real customer results with real names and faces.',
      },
      useCases: [
        {
          title: 'Marketing Testimonial Collection',
          icon: '📝',
          industry: 'Any',
          scenario: 'Marketing needs fresh testimonials for campaigns, but collecting them is ad-hoc and permissions are unclear.',
          painPoint: 'Great quotes exist but can\'t be used because legal permissions weren\'t documented.',
          keyFields: ['Your Testimonial', 'Overall Rating', 'May we use this testimonial?', 'May we include your name?'],
          exampleOrganization: 'A B2B company needing testimonials for website, sales decks, and campaigns.',
        },
        {
          title: 'Case Study Development',
          icon: '📊',
          industry: 'Technology / Professional Services',
          scenario: 'You\'re building case studies and need customer stories with specific results and metrics.',
          painPoint: 'Case study development stalls because customers won\'t share specific numbers or allow company name use.',
          keyFields: ['Specific Results/Metrics', 'Key Benefits', 'May we include your company name?', 'How long have you been a customer?'],
          exampleOrganization: 'A software company building industry-specific case studies for sales enablement.',
        },
        {
          title: 'Video Testimonial Program',
          icon: '🎥',
          industry: 'Any',
          scenario: 'You want video testimonials for social media and your website but need a way to collect and manage them.',
          painPoint: 'Video collection is unstructured; quality varies and permissions aren\'t consistent.',
          keyFields: ['Video Testimonial', 'Your Photo/Headshot', 'May we share on social media?'],
          exampleOrganization: 'A brand building a library of customer video testimonials for social campaigns.',
        },
        {
          title: 'Review Platform Seeding',
          icon: '⭐',
          industry: 'SaaS / Technology',
          scenario: 'You need reviews on G2, Capterra, or Trustpilot but want to collect internal testimonials first.',
          painPoint: 'Happy customers don\'t leave reviews; no system to identify and prompt advocates.',
          keyFields: ['Overall Rating', 'Your Testimonial', 'Key Benefits', 'Email Address'],
          exampleOrganization: 'A SaaS company building presence on software review platforms.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Incentive Offer',
          description: 'Offer gift cards or discounts for completed testimonials. Track incentive fulfillment.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Include Interview Request',
          description: 'Add option to request a recorded interview for more detailed case study development.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Enable Industry Tagging',
          description: 'Capture customer industry to organize testimonials for industry-specific marketing.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Build Testimonial Gallery',
          description: 'Create a public-facing page showcasing approved testimonials with filtering by industry/product.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Review Platform Redirect',
          description: 'After submission, offer to help them post the same testimonial to G2, Trustpilot, etc.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'thank-you-email',
          title: 'Send Thank You',
          description: 'Immediately thank the customer for their testimonial with any promised incentive or next steps.',
          trigger: 'On form submission',
          benefits: ['Customer appreciation', 'Incentive fulfillment'],
        },
        {
          workflowType: 'marketing-notification',
          title: 'Alert Marketing Team',
          description: 'Notify marketing when new testimonials arrive, especially those with video or specific metrics.',
          trigger: 'On form submission',
          benefits: ['Immediate marketing use', 'No lost testimonials'],
        },
        {
          workflowType: 'testimonial-library',
          title: 'Add to Testimonial Library',
          description: 'Organize approved testimonials by industry, product, and benefit for easy retrieval.',
          trigger: 'On approval',
          benefits: ['Organized assets', 'Easy access for sales'],
        },
        {
          workflowType: 'review-redirect',
          title: 'Request Review Platform Post',
          description: 'For highly positive testimonials, follow up asking if they\'d post to G2, Capterra, or Trustpilot.',
          trigger: 'On form submission where rating >= 4',
          benefits: ['Third-party reviews', 'Expanded social proof'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Benefits as multi-select enables testimonial matching to feature marketing',
          'Permission fields (name, company, social) provide granular usage rights',
          'File fields for photo and video support rich testimonial formats',
        ],
        integrationHints: [
          'Webhook to DAM (digital asset management) for testimonial photo/video storage',
          'POST to CRM to update customer record with testimonial flag',
          'Connect to review platforms API to facilitate cross-posting',
        ],
        mongoDBConsiderations: [
          'Index on {rating: 1, allowPublicUse: 1} for testimonial quality filtering',
          'Index on {benefitsExperienced: 1} for benefit-specific testimonial queries',
          'Text index on testimonial field for keyword search',
        ],
      },
      seo: {
        metaTitle: 'Testimonial Submission Form Template | NetPad',
        metaDescription: 'Free testimonial form with rating capture, media upload, and permission management. Build social proof that marketing can actually use.',
        keywords: [
          'testimonial form',
          'customer testimonial form',
          'review submission form',
          'success story form',
          'customer feedback collection',
          'case study intake',
          'social proof collection',
        ],
        ogDescription: 'Stop hunting for customer quotes. This form collects testimonials with specific results, photos, and usage permissions—ready for marketing.',
      },
      socialProofAngles: [
        'More usable testimonials for marketing',
        'Clear legal permissions for all quotes',
        'Quantifiable customer results',
        'Video testimonial library growth',
      ],
    },
  }),
];
