/**
 * Finance & Accounting Form Templates
 *
 * Templates for expense reports, invoices, credit applications,
 * and financial requests.
 */

import { FormTemplate } from '@/types/formTemplate';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  addressField,
  fileField,
} from '../helpers';

export const financeAccountingTemplates: FormTemplate[] = [
  // 1. Expense Reimbursement Form
  createTemplate({
    id: 'expense-reimbursement',
    name: 'Expense Reimbursement Form',
    shortDescription: 'Submit expenses for reimbursement',
    fullDescription: 'Employee expense reimbursement form with receipt upload and approval workflow. Captures expense details, categories, and supporting documentation.',
    category: 'finance-accounting',
    icon: 'Receipt',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 1,
    tags: ['expense', 'reimbursement', 'finance', 'receipt'],
    useCases: [
      'Travel expenses',
      'Business meals',
      'Office supplies',
      'Client entertainment',
    ],
    features: [
      'Multiple expense entries',
      'Receipt upload',
      'Category classification',
      'Manager approval',
    ],
    fieldConfigs: [
      sectionHeader('employee', 'Employee Information'),
      textField('employeeName', 'Employee Name', { required: true }),
      textField('employeeId', 'Employee ID', { required: true }),
      textField('department', 'Department', { required: true }),
      emailField('email', 'Email', { required: true }),
      textField('manager', 'Manager Name', { required: true }),
      sectionHeader('expense', 'Expense Details'),
      dateField('expenseDate', 'Expense Date', { required: true }),
      selectField('expenseCategory', 'Expense Category', [
        'Travel - Airfare',
        'Travel - Lodging',
        'Travel - Ground Transportation',
        'Travel - Meals',
        'Travel - Other',
        'Client Entertainment',
        'Office Supplies',
        'Training/Education',
        'Equipment',
        'Software/Subscriptions',
        'Communication',
        'Other',
      ], { required: true }),
      textField('vendor', 'Vendor/Merchant', { required: true }),
      textareaField('description', 'Description/Purpose', {
        required: true,
        placeholder: 'Describe the business purpose of this expense...',
      }),
      currencyField('amount', 'Amount', { required: true }),
      selectField('currency', 'Currency', [
        'USD',
        'EUR',
        'GBP',
        'CAD',
        'AUD',
        'Other',
      ], { fieldWidth: 'half' }),
      selectField('paymentMethod', 'Payment Method', [
        'Personal Credit Card',
        'Company Credit Card',
        'Cash',
        'Debit Card',
        'Other',
      ], { required: true }),
      sectionHeader('project', 'Project/Client (if applicable)'),
      textField('projectCode', 'Project Code'),
      textField('clientName', 'Client Name'),
      yesNoField('clientBillable', 'Is this client billable?'),
      sectionHeader('travel', 'Travel Details (if applicable)'),
      textField('tripDestination', 'Trip Destination'),
      dateField('tripStartDate', 'Trip Start Date'),
      dateField('tripEndDate', 'Trip End Date'),
      textareaField('tripPurpose', 'Trip Purpose'),
      sectionHeader('receipts', 'Supporting Documentation'),
      fileField('receipts', 'Upload Receipt(s)', {
        required: true,
        validation: { multiple: true, maxFiles: 10, allowedTypes: ['image/*', 'application/pdf'] },
      }),
      textareaField('missingReceiptExplanation', 'Missing Receipt Explanation (if any)', {
        placeholder: 'Explain why receipt is unavailable...',
      }),
      sectionHeader('additional', 'Additional Information'),
      textareaField('additionalNotes', 'Additional Notes'),
      yesNoField('certifyAccurate', 'I certify this expense report is accurate and complies with company policy', { required: true }),
    ],
  }),

  // 2. Invoice Submission Form
  createTemplate({
    id: 'invoice-submission',
    name: 'Invoice Submission Form',
    shortDescription: 'Submit invoices for payment',
    fullDescription: 'Vendor invoice submission form for accounts payable. Captures invoice details, line items, and payment preferences.',
    category: 'finance-accounting',
    icon: 'FileText',
    complexity: 'moderate',
    estimatedTime: 8,
    displayOrder: 2,
    tags: ['invoice', 'payment', 'vendor', 'accounts payable'],
    useCases: [
      'Vendor invoices',
      'Contractor payments',
      'Service billing',
      'Purchase orders',
    ],
    features: [
      'Invoice details',
      'Line item support',
      'Payment terms',
      'PO matching',
    ],
    fieldConfigs: [
      sectionHeader('vendor', 'Vendor Information'),
      textField('vendorName', 'Vendor/Company Name', { required: true }),
      textField('vendorId', 'Vendor ID (if known)'),
      addressField('vendorAddress', 'Vendor Address', { required: true }),
      textField('contactName', 'Contact Name', { required: true }),
      emailField('contactEmail', 'Contact Email', { required: true }),
      phoneField('contactPhone', 'Contact Phone'),
      sectionHeader('invoice', 'Invoice Details'),
      textField('invoiceNumber', 'Invoice Number', { required: true }),
      dateField('invoiceDate', 'Invoice Date', { required: true }),
      dateField('dueDate', 'Due Date', { required: true }),
      currencyField('invoiceAmount', 'Total Invoice Amount', { required: true }),
      selectField('currency', 'Currency', [
        'USD',
        'EUR',
        'GBP',
        'CAD',
        'Other',
      ]),
      selectField('paymentTerms', 'Payment Terms', [
        'Net 30',
        'Net 45',
        'Net 60',
        'Due on Receipt',
        '2/10 Net 30',
        'Other',
      ]),
      sectionHeader('po', 'Purchase Order'),
      yesNoField('hasPO', 'Is this related to a Purchase Order?'),
      textField('poNumber', 'PO Number', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hasPO', operator: 'isTrue' }],
        },
      }),
      sectionHeader('services', 'Services/Products'),
      textareaField('description', 'Description of Services/Products', {
        required: true,
        placeholder: 'Describe what this invoice is for...',
      }),
      textField('department', 'Department to Charge'),
      textField('glCode', 'GL Code (if known)'),
      textField('costCenter', 'Cost Center'),
      sectionHeader('payment', 'Payment Information'),
      selectField('paymentMethod', 'Preferred Payment Method', [
        'ACH/Direct Deposit',
        'Check',
        'Wire Transfer',
        'Credit Card',
      ], { required: true }),
      textField('bankName', 'Bank Name (for ACH)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit' }],
        },
      }),
      textField('routingNumber', 'Routing Number', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit' }],
        },
      }),
      textField('accountNumber', 'Account Number', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit' }],
        },
      }),
      sectionHeader('documents', 'Supporting Documents'),
      fileField('invoiceDocument', 'Invoice Document', {
        required: true,
        validation: { allowedTypes: ['application/pdf', 'image/*'] },
      }),
      fileField('supportingDocs', 'Supporting Documents (contracts, receipts, etc.)', {
        validation: { multiple: true, maxFiles: 5 },
      }),
      textareaField('notes', 'Additional Notes'),
    ],
  }),

  // 3. Credit Application Form
  createTemplate({
    id: 'credit-application',
    name: 'Credit Application Form',
    shortDescription: 'Apply for business credit/terms',
    fullDescription: 'Business credit application for establishing credit terms. Collects company information, financial references, and credit history.',
    category: 'finance-accounting',
    icon: 'CreditCard',
    complexity: 'advanced',
    estimatedTime: 15,
    isFeatured: true,
    displayOrder: 3,
    tags: ['credit', 'application', 'terms', 'finance'],
    useCases: [
      'New customer credit',
      'Vendor credit terms',
      'Trade credit',
      'Net terms applications',
    ],
    features: [
      'Company profile',
      'Financial information',
      'Trade references',
      'Bank references',
    ],
    fieldConfigs: [
      sectionHeader('company', 'Company Information'),
      textField('legalName', 'Legal Company Name', { required: true }),
      textField('dba', 'DBA/Trade Name'),
      addressField('businessAddress', 'Business Address', { required: true }),
      addressField('billingAddress', 'Billing Address (if different)'),
      phoneField('phone', 'Phone', { required: true }),
      phoneField('fax', 'Fax'),
      emailField('email', 'Email', { required: true }),
      urlField('website', 'Website'),
      textField('taxId', 'Federal Tax ID / EIN', { required: true }),
      textField('dunsNumber', 'DUNS Number'),
      sectionHeader('business', 'Business Details'),
      selectField('businessType', 'Type of Business', [
        'Corporation',
        'LLC',
        'Partnership',
        'Sole Proprietorship',
        'Non-Profit',
        'Government',
      ], { required: true }),
      textField('stateOfIncorporation', 'State of Incorporation'),
      numberField('yearsInBusiness', 'Years in Business', { required: true }),
      textField('industry', 'Industry/Type of Business'),
      numberField('numEmployees', 'Number of Employees'),
      currencyField('annualRevenue', 'Annual Revenue'),
      sectionHeader('credit', 'Credit Request'),
      currencyField('creditRequested', 'Credit Amount Requested', { required: true }),
      selectField('paymentTerms', 'Desired Payment Terms', [
        'Net 30',
        'Net 45',
        'Net 60',
        'Other',
      ], { required: true }),
      sectionHeader('principals', 'Principals/Owners'),
      textField('principal1Name', 'Principal 1 - Full Name', { required: true }),
      textField('principal1Title', 'Principal 1 - Title', { required: true }),
      textField('principal1SSN', 'Principal 1 - SSN (last 4 digits)'),
      numberField('principal1Ownership', 'Principal 1 - % Ownership'),
      textField('principal2Name', 'Principal 2 - Full Name'),
      textField('principal2Title', 'Principal 2 - Title'),
      sectionHeader('bank', 'Bank Reference'),
      textField('bankName', 'Bank Name', { required: true }),
      textField('bankAddress', 'Bank Address'),
      textField('bankContact', 'Bank Contact Name'),
      phoneField('bankPhone', 'Bank Phone', { required: true }),
      textField('accountNumber', 'Account Number (last 4 digits)'),
      sectionHeader('trade1', 'Trade Reference 1'),
      textField('trade1Name', 'Company Name', { required: true }),
      textField('trade1Contact', 'Contact Name'),
      phoneField('trade1Phone', 'Phone', { required: true }),
      emailField('trade1Email', 'Email'),
      textField('trade1Account', 'Account Number'),
      sectionHeader('trade2', 'Trade Reference 2'),
      textField('trade2Name', 'Company Name', { required: true }),
      textField('trade2Contact', 'Contact Name'),
      phoneField('trade2Phone', 'Phone', { required: true }),
      emailField('trade2Email', 'Email'),
      sectionHeader('trade3', 'Trade Reference 3'),
      textField('trade3Name', 'Company Name'),
      textField('trade3Contact', 'Contact Name'),
      phoneField('trade3Phone', 'Phone'),
      emailField('trade3Email', 'Email'),
      sectionHeader('auth', 'Authorization'),
      yesNoField('authBackground', 'I authorize credit/background check', { required: true }),
      yesNoField('certifyAccurate', 'I certify all information is accurate', { required: true }),
      textField('signerName', 'Authorized Signer Name', { required: true }),
      textField('signerTitle', 'Title', { required: true }),
      dateField('signatureDate', 'Date', { required: true }),
    ],
  }),

  // 4. Purchase Order Request
  createTemplate({
    id: 'purchase-order-request',
    name: 'Purchase Order Request',
    shortDescription: 'Request approval for purchases',
    fullDescription: 'Internal purchase order request form. Captures item details, vendor information, and budget justification for procurement approval.',
    category: 'finance-accounting',
    icon: 'ShoppingCart',
    complexity: 'moderate',
    estimatedTime: 8,
    displayOrder: 4,
    tags: ['purchase', 'order', 'procurement', 'approval'],
    useCases: [
      'Equipment purchases',
      'Software purchases',
      'Service contracts',
      'Supply orders',
    ],
    features: [
      'Item details',
      'Vendor selection',
      'Budget allocation',
      'Approval workflow',
    ],
    fieldConfigs: [
      sectionHeader('requester', 'Requester Information'),
      textField('requesterName', 'Your Name', { required: true }),
      textField('department', 'Department', { required: true }),
      emailField('email', 'Email', { required: true }),
      textField('manager', 'Manager Name', { required: true }),
      dateField('neededBy', 'Date Needed By', { required: true }),
      sectionHeader('vendor', 'Vendor Information'),
      textField('vendorName', 'Vendor Name', { required: true }),
      textField('vendorContact', 'Vendor Contact'),
      emailField('vendorEmail', 'Vendor Email'),
      phoneField('vendorPhone', 'Vendor Phone'),
      addressField('vendorAddress', 'Vendor Address'),
      sectionHeader('items', 'Item Details'),
      textField('item1Desc', 'Item 1 - Description', { required: true }),
      numberField('item1Qty', 'Item 1 - Quantity', { required: true, fieldWidth: 'half' }),
      currencyField('item1Price', 'Item 1 - Unit Price', { required: true, fieldWidth: 'half' }),
      textField('item2Desc', 'Item 2 - Description'),
      numberField('item2Qty', 'Item 2 - Quantity', { fieldWidth: 'half' }),
      currencyField('item2Price', 'Item 2 - Unit Price', { fieldWidth: 'half' }),
      textField('item3Desc', 'Item 3 - Description'),
      numberField('item3Qty', 'Item 3 - Quantity', { fieldWidth: 'half' }),
      currencyField('item3Price', 'Item 3 - Unit Price', { fieldWidth: 'half' }),
      currencyField('subtotal', 'Subtotal'),
      currencyField('taxShipping', 'Tax/Shipping'),
      currencyField('totalAmount', 'Total Amount', { required: true }),
      sectionHeader('budget', 'Budget Information'),
      textField('budgetCode', 'Budget Code/Cost Center', { required: true }),
      textField('glCode', 'GL Code'),
      textField('projectCode', 'Project Code (if applicable)'),
      selectField('budgetApproved', 'Is this in the approved budget?', [
        'Yes - In budget',
        'Partially - Over budget',
        'No - Unbudgeted expense',
      ], { required: true }),
      sectionHeader('justification', 'Business Justification'),
      textareaField('justification', 'Business Justification', {
        required: true,
        placeholder: 'Explain why this purchase is needed...',
      }),
      yesNoField('urgentPurchase', 'Is this an urgent purchase?'),
      textareaField('urgencyReason', 'Reason for Urgency', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'urgentPurchase', operator: 'isTrue' }],
        },
      }),
      sectionHeader('quotes', 'Competitive Quotes'),
      yesNoField('hasCompetitiveQuotes', 'Have competitive quotes been obtained?'),
      fileField('quotes', 'Upload Quotes', {
        validation: { multiple: true, maxFiles: 3 },
      }),
      textareaField('singleSourceJustification', 'Single Source Justification (if no quotes)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hasCompetitiveQuotes', operator: 'isFalse' }],
        },
      }),
    ],
  }),

  // 5. Budget Request Form
  createTemplate({
    id: 'budget-request',
    name: 'Budget Request Form',
    shortDescription: 'Request budget allocation or increase',
    fullDescription: 'Form for requesting budget allocations or increases. Captures detailed justification and expected ROI.',
    category: 'finance-accounting',
    icon: 'PiggyBank',
    complexity: 'moderate',
    estimatedTime: 10,
    displayOrder: 5,
    tags: ['budget', 'request', 'finance', 'allocation'],
    useCases: [
      'New initiative funding',
      'Budget increases',
      'Capital requests',
      'Project funding',
    ],
    features: [
      'Budget breakdown',
      'ROI projection',
      'Multi-year planning',
      'Approval workflow',
    ],
    fieldConfigs: [
      sectionHeader('requester', 'Requester Information'),
      textField('requesterName', 'Your Name', { required: true }),
      textField('department', 'Department', { required: true }),
      emailField('email', 'Email', { required: true }),
      textField('manager', 'Manager/VP Name', { required: true }),
      sectionHeader('request', 'Budget Request Details'),
      textField('requestTitle', 'Request Title', { required: true }),
      selectField('requestType', 'Type of Request', [
        'New Initiative/Project',
        'Budget Increase',
        'Reallocation',
        'Capital Expenditure',
        'Emergency Funding',
      ], { required: true }),
      selectField('fiscalYear', 'Fiscal Year', [
        'Current Year',
        'Next Fiscal Year',
        'Multi-Year',
      ], { required: true }),
      currencyField('totalAmountRequested', 'Total Amount Requested', { required: true }),
      sectionHeader('breakdown', 'Budget Breakdown'),
      currencyField('personnel', 'Personnel Costs'),
      currencyField('equipment', 'Equipment/Hardware'),
      currencyField('software', 'Software/Licenses'),
      currencyField('services', 'Professional Services'),
      currencyField('travel', 'Travel'),
      currencyField('other', 'Other Costs'),
      textareaField('breakdownDetails', 'Detailed Cost Breakdown', {
        placeholder: 'Provide line-item details for the budget...',
      }),
      sectionHeader('justification', 'Business Justification'),
      textareaField('businessNeed', 'Business Need/Problem Statement', {
        required: true,
        placeholder: 'Describe the business need this budget addresses...',
      }),
      textareaField('objectives', 'Objectives and Expected Outcomes', {
        required: true,
      }),
      textareaField('alternatives', 'Alternatives Considered'),
      textareaField('riskIfNotApproved', 'Risk If Not Approved'),
      sectionHeader('roi', 'Return on Investment'),
      yesNoField('hasFinancialBenefit', 'Does this have quantifiable financial benefits?'),
      currencyField('expectedRevenue', 'Expected Revenue/Savings (Annual)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hasFinancialBenefit', operator: 'isTrue' }],
        },
      }),
      textField('paybackPeriod', 'Payback Period', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'hasFinancialBenefit', operator: 'isTrue' }],
        },
      }),
      textareaField('roiCalculation', 'ROI Calculation/Methodology'),
      sectionHeader('timeline', 'Implementation Timeline'),
      dateField('startDate', 'Proposed Start Date', { required: true }),
      dateField('endDate', 'Proposed End Date'),
      textareaField('milestones', 'Key Milestones'),
      fileField('supportingDocs', 'Supporting Documents', {
        validation: { multiple: true, maxFiles: 5 },
      }),
    ],
  }),

  // 6. Vendor/Supplier Registration
  createTemplate({
    id: 'vendor-registration-finance',
    name: 'New Vendor Setup Form',
    shortDescription: 'Register new vendors for payment',
    fullDescription: 'Accounts payable vendor setup form. Collects payment information, tax forms, and banking details for new vendors.',
    category: 'finance-accounting',
    icon: 'Building2',
    complexity: 'moderate',
    estimatedTime: 10,
    displayOrder: 6,
    tags: ['vendor', 'supplier', 'setup', 'accounts payable'],
    useCases: [
      'New vendor setup',
      'Payment information update',
      'Vendor management',
      'Supplier onboarding',
    ],
    features: [
      'Tax documentation',
      'Banking details',
      'Payment preferences',
      'Compliance info',
    ],
    fieldConfigs: [
      sectionHeader('vendor', 'Vendor Information'),
      textField('vendorName', 'Legal Business Name', { required: true }),
      textField('dba', 'DBA/Trade Name'),
      addressField('address', 'Business Address', { required: true }),
      phoneField('phone', 'Phone', { required: true }),
      phoneField('fax', 'Fax'),
      emailField('email', 'Email', { required: true }),
      urlField('website', 'Website'),
      sectionHeader('contacts', 'Contact Information'),
      textField('primaryContact', 'Primary Contact Name', { required: true }),
      textField('primaryTitle', 'Title'),
      emailField('primaryEmail', 'Email', { required: true }),
      phoneField('primaryPhone', 'Phone', { required: true }),
      textField('apContact', 'A/P Contact Name'),
      emailField('apEmail', 'A/P Email'),
      phoneField('apPhone', 'A/P Phone'),
      sectionHeader('tax', 'Tax Information'),
      selectField('taxClassification', 'Tax Classification', [
        'Individual/Sole Proprietor',
        'C Corporation',
        'S Corporation',
        'Partnership',
        'LLC - C',
        'LLC - S',
        'LLC - Partnership',
        'Trust/Estate',
        'Other',
      ], { required: true }),
      textField('taxId', 'Tax ID/EIN', { required: true }),
      yesNoField('usBased', 'Is this a US-based company?', { required: true }),
      fileField('w9', 'W-9 Form (US vendors)', {
        validation: { allowedTypes: ['application/pdf'] },
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'usBased', operator: 'isTrue' }],
        },
      }),
      fileField('w8', 'W-8 Form (Non-US vendors)', {
        validation: { allowedTypes: ['application/pdf'] },
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'usBased', operator: 'isFalse' }],
        },
      }),
      sectionHeader('payment', 'Payment Information'),
      selectField('paymentMethod', 'Preferred Payment Method', [
        'ACH/Direct Deposit (preferred)',
        'Check',
        'Wire Transfer',
      ], { required: true }),
      textField('bankName', 'Bank Name', {
        required: true,
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit (preferred)' },
            { field: 'paymentMethod', operator: 'equals', value: 'Wire Transfer' },
          ],
        },
      }),
      textField('routingNumber', 'Routing/ABA Number', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit (preferred)' },
            { field: 'paymentMethod', operator: 'equals', value: 'Wire Transfer' },
          ],
        },
      }),
      textField('accountNumber', 'Account Number', {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit (preferred)' },
            { field: 'paymentMethod', operator: 'equals', value: 'Wire Transfer' },
          ],
        },
      }),
      selectField('accountType', 'Account Type', [
        'Checking',
        'Savings',
      ], {
        conditionalLogic: {
          action: 'show',
          logicType: 'any',
          conditions: [
            { field: 'paymentMethod', operator: 'equals', value: 'ACH/Direct Deposit (preferred)' },
          ],
        },
      }),
      addressField('remitAddress', 'Remit To Address (if different)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'paymentMethod', operator: 'equals', value: 'Check' }],
        },
      }),
      sectionHeader('internal', 'Internal Use'),
      textField('requestedBy', 'Requested By (employee name)', { required: true }),
      textField('requestorDept', 'Requestor Department', { required: true }),
      textareaField('productsServices', 'Products/Services Provided', { required: true }),
    ],
  }),
];

// Helper for URL field
function urlField(path: string, label: string, options: any = {}) {
  return {
    path,
    label,
    type: 'url',
    included: true,
    required: options.required ?? false,
    placeholder: options.placeholder ?? 'https://...',
    fieldWidth: options.fieldWidth ?? 'full',
    validation: options.validation,
    conditionalLogic: options.conditionalLogic,
  };
}
