import { FormTemplate } from '@/types/formTemplate';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  fileField,
  sectionHeader,
  addressField,
  signatureField,
} from '../helpers';

export const governmentPublicTemplates: FormTemplate[] = [
  createTemplate({
    id: 'public-records-request',
    name: 'Public Records Request',
    description: 'Freedom of Information Act (FOIA) style records request form',
    category: 'government-public',
    icon: '📄',
    complexity: 'intermediate',
    estimatedTime: '5-7 min',
    formType: 'both',
    featured: true,
    fields: [
      sectionHeader('Requester Information'),
      textField('full_name', 'Full Name', true),
      selectField('requester_type', 'Requester Type', [
        'Individual', 'Media/Press', 'Business', 'Attorney/Legal',
        'Academic/Research', 'Non-Profit Organization', 'Government Entity'
      ], true),
      textField('organization', 'Organization Name (if applicable)', false),
      addressField('address', 'Mailing Address', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      sectionHeader('Records Request Details'),
      textareaField('records_description', 'Description of Records Requested', true),
      textField('date_range', 'Date Range of Records (if known)', false),
      textField('department', 'Department/Agency (if known)', false),
      textField('reference_numbers', 'Any Reference Numbers or Case IDs', false),
      sectionHeader('Delivery Preferences'),
      selectField('format_preference', 'Preferred Format', [
        'Electronic (Email/Download)', 'Paper Copies', 'CD/USB Drive', 'Inspection Only'
      ], true),
      selectField('delivery_method', 'Delivery Method', [
        'Email', 'Mail', 'Pick Up', 'Fax'
      ], true),
      sectionHeader('Fee Acknowledgment'),
      yesNoField('fee_waiver', 'Are you requesting a fee waiver?', true),
      textareaField('fee_waiver_reason', 'Reason for Fee Waiver Request', false),
      currencyField('max_fee', 'Maximum Amount Willing to Pay (USD)', false),
      sectionHeader('Certification'),
      yesNoField('accurate_info', 'I certify that the information provided is accurate', true),
      yesNoField('understand_fees', 'I understand fees may apply for search and copying', true),
      textareaField('additional_info', 'Additional Information', false),
    ],
    tags: ['FOIA', 'public records', 'government', 'transparency'],
    useCases: ['Government agencies', 'Municipal offices', 'Public institutions'],
    enhanced: {
      headline: 'Process FOIA Requests Without the Filing Cabinet Chaos',
      subheadline: 'Standardize public records requests with clear descriptions, format preferences, and fee acknowledgments—track every request from submission to fulfillment.',
      longDescription: {
        opening: 'Public records requests are a compliance obligation that agencies can\'t ignore. But managing them is chaos. Requests arrive via email, mail, fax, and walk-ins with varying levels of clarity. "I want all the emails" isn\'t actionable. Staff spend hours clarifying requests before beginning searches. Deadlines get missed. Requesters file complaints. And when journalists publish stories about government "stonewalling," it\'s because nobody could find the request in the pile.',
        solution: 'This template standardizes FOIA/public records requests: requester identification (type: individual, media, legal, academic), detailed records description with date ranges and department references, format and delivery preferences, fee waiver requests with justification, and acknowledgment checkboxes. Structured fields ensure actionable requests. Requester type enables appropriate routing (media requests to communications, legal requests to counsel).',
        outcome: 'Respond to requests within statutory deadlines. Reduce clarification cycles with clear request descriptions. Track all requests from submission through fulfillment. Generate compliance reports showing response times and outcomes. Handle fee waivers consistently with documented justifications. Demonstrate transparency with complete audit trails.',
      },
      useCases: [
        {
          title: 'Municipal Clerk\'s Office',
          icon: '🏛️',
          industry: 'Local Government',
          scenario: 'Your city clerk processes 500+ public records requests annually. Requests arrive via email, mail, and in person with wildly varying specificity. Some take 5 minutes to fulfill; others require weeks of searching across departments. Statutory deadlines create constant pressure.',
          painPoint: 'No standardized intake process. Vague requests require multiple clarification cycles. Manual tracking in spreadsheets misses deadlines. No visibility into request backlog or response times.',
          keyFields: ['Description of Records Requested', 'Date Range of Records', 'Department/Agency', 'Preferred Format'],
          exampleOrganization: 'A city clerk\'s office processing 500+ annual FOIA requests with 15% deadline violation rate due to clarification delays.',
        },
        {
          title: 'State Agency Compliance',
          icon: '📋',
          industry: 'State Government',
          scenario: 'Your state agency receives records requests from journalists, attorneys, researchers, and citizens. Media requests require communications office review. Legal requests need counsel sign-off. Some requests seek thousands of pages requiring fee estimates. Current process doesn\'t differentiate.',
          painPoint: 'No routing based on requester type. Media requests not flagged for communications review. Fee estimates calculated manually. No tracking of appeal status or litigation holds.',
          keyFields: ['Requester Type', 'Organization Name', 'Maximum Amount Willing to Pay', 'Are you requesting a fee waiver?'],
          exampleOrganization: 'A state agency receiving 2,000+ annual records requests, with media requests often escalating due to missed communications review.',
        },
        {
          title: 'School District Transparency',
          icon: '🏫',
          industry: 'Education',
          scenario: 'Your school district receives records requests for contracts, personnel files, student data, and board meeting minutes. FERPA intersects with FOIA. Staff aren\'t sure what\'s releasable. Requests for student records require careful redaction. One wrong release creates legal exposure.',
          painPoint: 'Complex intersection of FOIA and FERPA requirements. Staff untrained on redaction requirements. No tracking of what\'s been released vs. withheld. Parent requests confused with FOIA requests.',
          keyFields: ['Records Description', 'Reference Numbers or Case IDs', 'Fee Waiver Request', 'I understand fees may apply'],
          exampleOrganization: 'A school district with 50 schools receiving 200+ annual records requests, uncertain about FERPA/FOIA boundaries.',
        },
        {
          title: 'Law Enforcement Records',
          icon: '🚔',
          industry: 'Public Safety',
          scenario: 'Your police department receives requests for incident reports, body camera footage, arrest records, and 911 calls. Some records are public; others are exempt. Media deadlines are tight. Attorneys request discovery. Processing body camera footage takes hours.',
          painPoint: 'Complex exemptions for ongoing investigations, personnel, juveniles. Body camera processing time-intensive. Media expects fast turnaround. No tracking of exemption justifications for appeals.',
          keyFields: ['Requester Type', 'Date Range of Records', 'Preferred Format', 'Reason for Fee Waiver Request'],
          exampleOrganization: 'A police department receiving 1,000+ annual records requests, with 40% requiring exemption determinations.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Request Category Routing',
          description: 'Based on requester type and subject matter, automatically route to appropriate department: media to communications, legal to counsel, personnel to HR.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Enable Fee Estimation',
          description: 'Based on date range and estimated document volume, automatically calculate fee estimate. Send estimate to requester for approval before beginning search.',
          fieldSuggestion: 'currency',
          difficulty: 'advanced',
        },
        {
          title: 'Add Exemption Tracking',
          description: 'When records are withheld, document exemption basis and provide requester with appeal rights. Track exemption usage for compliance reporting.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Include Status Portal',
          description: 'Provide requesters with unique tracking number and status portal to check request progress. Reduce "where\'s my request?" inquiries.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Enable Recurring Requests',
          description: 'For requesters who want ongoing access (e.g., weekly arrest reports), set up recurring fulfillment without repeated request submissions.',
          fieldSuggestion: 'yesno',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'request-acknowledgment',
          title: 'Acknowledge Request Receipt',
          description: 'Immediately email requester confirming receipt with tracking number, estimated response date based on statutory deadline, and contact for questions.',
          trigger: 'On form submission',
          benefits: ['Requester knows request received', 'Tracking number for follow-up', 'Statutory deadline communicated'],
        },
        {
          workflowType: 'deadline-tracking',
          title: 'Track Statutory Deadlines',
          description: 'Calculate response deadline from submission date. Alert assigned staff at 50%, 75%, and 90% of deadline. Escalate overdue requests to supervisor.',
          trigger: 'On submission and scheduled reminders',
          benefits: ['Never miss statutory deadlines', 'Early warning for complex requests', 'Supervisor visibility into backlog'],
        },
        {
          workflowType: 'fee-approval',
          title: 'Request Fee Approval',
          description: 'When estimated fees exceed threshold, automatically email requester with fee estimate and request approval before proceeding. Track approval status.',
          trigger: 'On fee estimate generation',
          benefits: ['No wasted search time if requester won\'t pay', 'Clear fee agreement before work begins', 'Documented fee acknowledgment'],
        },
        {
          workflowType: 'fulfillment-notification',
          title: 'Notify on Fulfillment',
          description: 'When records are ready, email requester with pickup/download instructions, any exemption explanations, and appeal rights information.',
          trigger: 'On request completion',
          benefits: ['Requester notified immediately', 'Exemption basis documented', 'Appeal rights communicated'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Requester type enables routing and priority logic (media vs. citizen)',
          'Fee waiver boolean with conditional justification text supports policy compliance',
          'Date range and department fields narrow search scope for faster fulfillment',
        ],
        integrationHints: [
          'Document management system for records search and retrieval',
          'Payment processor for fee collection on pickup',
          'Email service for status notifications and document delivery',
        ],
        mongoDBConsiderations: [
          'Index on {submittedDate: 1, status: 1} for deadline tracking queries',
          'Index on {requesterType: 1} for routing and reporting by requester category',
          'Index on {department: 1} for workload distribution analysis',
          'Store fulfillment documents as GridFS or blob storage references',
        ],
      },
      seo: {
        metaTitle: 'Public Records Request Form Template | NetPad',
        metaDescription: 'Free FOIA request template for government agencies. Standardize public records requests with tracking, fee management, and deadline compliance.',
        keywords: ['public records request form', 'FOIA form', 'freedom of information', 'records request', 'government transparency'],
        ogDescription: 'Stop missing FOIA deadlines. This template standardizes public records requests with tracking and fee management for compliance.',
      },
      socialProofAngles: [
        'Meet statutory response deadlines',
        'Reduce clarification cycles',
        'Track all requests from start to finish',
        'Demonstrate government transparency',
      ],
    },
  }),

  createTemplate({
    id: 'permit-application',
    name: 'General Permit Application',
    description: 'Multi-purpose permit application for various government permits',
    category: 'government-public',
    icon: '📋',
    complexity: 'advanced',
    estimatedTime: '10-15 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Applicant Information'),
      textField('full_name', 'Applicant Full Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      addressField('mailing_address', 'Mailing Address', true),
      textField('id_number', 'Government ID Number', true),
      sectionHeader('Permit Details'),
      selectField('permit_type', 'Permit Type', [
        'Building/Construction', 'Business License', 'Special Event', 'Street Closure',
        'Noise/Sound', 'Sidewalk Use', 'Food Vendor', 'Parking', 'Sign/Banner', 'Other'
      ], true),
      textField('permit_type_other', 'If Other, Please Specify', false),
      textareaField('permit_purpose', 'Purpose/Description of Permit Request', true),
      sectionHeader('Location Information'),
      addressField('permit_location', 'Permit Location Address', true),
      textField('parcel_number', 'Parcel/Lot Number (if applicable)', false),
      selectField('property_type', 'Property Type', [
        'Residential', 'Commercial', 'Industrial', 'Public/Government', 'Mixed Use'
      ], false),
      yesNoField('is_owner', 'Are you the property owner?', true),
      textField('owner_name', 'Property Owner Name (if different)', false),
      sectionHeader('Project/Activity Details'),
      dateField('start_date', 'Proposed Start Date', true),
      dateField('end_date', 'Proposed End Date', false),
      textField('project_value', 'Estimated Project Value', false),
      textField('contractor_name', 'Contractor/Company Name', false),
      textField('contractor_license', 'Contractor License Number', false),
      sectionHeader('Supporting Documents'),
      fileField('site_plan', 'Site Plan/Map', false, '.pdf,.jpg,.png'),
      fileField('project_plans', 'Project Plans/Drawings', false, '.pdf'),
      fileField('proof_of_ownership', 'Proof of Ownership/Authorization', false, '.pdf'),
      fileField('insurance_certificate', 'Insurance Certificate', false, '.pdf'),
      fileField('additional_docs', 'Additional Supporting Documents', false, '.pdf,.jpg,.png'),
      sectionHeader('Declarations'),
      yesNoField('comply_codes', 'I agree to comply with all applicable codes and regulations', true),
      yesNoField('accurate_info', 'I certify that all information provided is true and accurate', true),
      yesNoField('inspection_consent', 'I consent to inspections as required', true),
      signatureField('applicant_signature', 'Applicant Signature', true),
      dateField('signature_date', 'Date', true),
    ],
    tags: ['permit', 'license', 'government', 'construction', 'business'],
    useCases: ['City/County offices', 'Building departments', 'Licensing agencies'],
    enhanced: {
      headline: 'Approve Permits Faster with Complete Applications',
      subheadline: 'Collect all required information upfront—applicant details, project scope, documents, and declarations—so reviews can begin immediately instead of chasing missing items.',
      longDescription: {
        opening: 'Permit processing is a bottleneck that frustrates everyone. Contractors submit incomplete applications and wonder why approval takes weeks. Staff spend more time requesting missing documents than actually reviewing projects. Paper applications get lost between departments. Inspectors can\'t find project details in the field. Citizens complain to elected officials about how long permits take. But most delays aren\'t review time—they\'re administrative chaos.',
        solution: 'This template captures complete permit applications in one submission: applicant identification, permit type and purpose, location with parcel information, property ownership verification, project timeline and value, contractor credentials, required documents (site plans, project drawings, insurance), and signed declarations. Permit type selection triggers appropriate document requirements. File uploads ensure supporting materials arrive with the application.',
        outcome: 'Begin reviews on day one with complete applications. Reduce "application incomplete" responses by 70%. Track all permits from submission through final inspection. Know exactly what\'s pending, approved, and ready for inspection. Inspectors access project details on mobile devices in the field. Generate reports showing permit volume, processing time, and revenue by type.',
      },
      useCases: [
        {
          title: 'Building Department Permits',
          icon: '🏗️',
          industry: 'Local Government',
          scenario: 'Your building department processes 2,000+ permits annually: new construction, remodels, electrical, plumbing, HVAC. Each type has different requirements. Contractors submit incomplete applications. Plans review waits while staff chase missing documents. Inspectors show up to sites without project information.',
          painPoint: '60% of applications require follow-up for missing items. No differentiation of requirements by permit type. Paper-based system creates review bottlenecks. Inspectors can\'t access permit details in the field.',
          keyFields: ['Permit Type', 'Permit Location Address', 'Site Plan/Map', 'Contractor License Number'],
          exampleOrganization: 'A city building department processing 2,000+ annual permits with 45-day average approval time, 60% due to incomplete applications.',
        },
        {
          title: 'Special Event Permits',
          icon: '🎪',
          industry: 'Local Government',
          scenario: 'Your city issues permits for festivals, parades, street fairs, and concerts. Event organizers submit requests without required insurance certificates, site maps, or noise mitigation plans. Multiple departments (police, fire, public works) need to review. Coordination happens via email chains.',
          painPoint: 'Insurance and site plans submitted separately, delaying review. Multi-department coordination done via email. No tracking of which departments have approved. Event organizers uncertain of permit status.',
          keyFields: ['Permit Type', 'Proposed Start Date', 'Proposed End Date', 'Insurance Certificate'],
          exampleOrganization: 'A city events office managing 200+ annual special event permits, with average 30-day approval cycle.',
        },
        {
          title: 'Business License Applications',
          icon: '🏪',
          industry: 'Local Government',
          scenario: 'Your licensing office issues business licenses for new and renewing businesses. Applications require proof of zoning compliance, lease agreements, and sometimes health or fire inspections. Different business types have different requirements. Applicants don\'t know what they need.',
          painPoint: 'Requirements vary by business type but aren\'t communicated clearly. Applicants missing zoning approval or health permits. No integration with inspection scheduling. License renewals tracked manually.',
          keyFields: ['Permit Type', 'Property Type', 'Are you the property owner?', 'I agree to comply with all applicable codes'],
          exampleOrganization: 'A city licensing office issuing 5,000 annual business licenses with 15% rejection rate due to zoning/inspection issues.',
        },
        {
          title: 'County Planning Permits',
          icon: '🗺️',
          industry: 'County Government',
          scenario: 'Your county planning department handles land use permits: subdivisions, variances, conditional uses, environmental reviews. Applications require detailed site plans, environmental studies, and neighbor notifications. Review involves planning commission meetings. Process takes months.',
          painPoint: 'Complex applications arrive incomplete. Environmental studies submitted after initial review. Public hearing scheduling disconnected from permit status. No tracking of review timelines for compliance.',
          keyFields: ['Permit Type', 'Parcel/Lot Number', 'Project Plans/Drawings', 'Proof of Ownership/Authorization'],
          exampleOrganization: 'A county planning department with 6-month average approval time for land use permits, citizen complaints about transparency.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Permit Type Requirements',
          description: 'Use conditional logic to show different required documents based on permit type. Building permits need plans; events need insurance; food vendors need health permits.',
          fieldSuggestion: 'file',
          difficulty: 'medium',
        },
        {
          title: 'Enable Fee Calculation',
          description: 'Based on permit type, project value, and square footage, automatically calculate permit fees. Display fee to applicant before submission.',
          fieldSuggestion: 'currency',
          difficulty: 'advanced',
        },
        {
          title: 'Add Completeness Check',
          description: 'Before submission, validate that all required documents are attached based on permit type. Prevent incomplete submissions.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Include Multi-Department Routing',
          description: 'Route permit to appropriate departments for review (building, fire, health, planning). Track approval status from each.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
        {
          title: 'Enable Online Payment',
          description: 'Integrate payment processing to collect permit fees at submission. Track payment status alongside permit status.',
          fieldSuggestion: 'currency',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'application-receipt',
          title: 'Confirm Application Receipt',
          description: 'Immediately email applicant confirming submission with permit number, list of attached documents, estimated review timeline, and contact for questions.',
          trigger: 'On form submission',
          benefits: ['Applicant has permit number immediately', 'Confirmation of documents received', 'Clear expectations for timeline'],
        },
        {
          workflowType: 'completeness-review',
          title: 'Flag Incomplete Applications',
          description: 'Automatically check submitted application against required fields and documents for permit type. Flag missing items and notify applicant within 24 hours.',
          trigger: 'On form submission',
          benefits: ['Incomplete applications identified immediately', 'Staff focus on reviews, not chasing documents', 'Faster time-to-complete submission'],
        },
        {
          workflowType: 'department-routing',
          title: 'Route to Review Departments',
          description: 'Based on permit type, automatically route to required departments (building, fire, planning, health). Each department marks approval in system.',
          trigger: 'On application completeness verification',
          benefits: ['No manual routing between departments', 'Parallel reviews where allowed', 'Clear visibility into which departments have approved'],
        },
        {
          workflowType: 'approval-notification',
          title: 'Notify on Permit Approval',
          description: 'When all required approvals complete, email applicant with approved permit, conditions, inspection requirements, and fee payment instructions.',
          trigger: 'On final approval',
          benefits: ['Immediate notification of approval', 'Permit available for download', 'Clear next steps for inspections'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Permit type as select enables conditional document requirements and fee calculation',
          'Date range fields support project timeline tracking and permit duration',
          'File fields with type restrictions ensure proper document formats',
          'Boolean declarations create audit trail of applicant acknowledgments',
        ],
        integrationHints: [
          'Payment processor for permit fee collection at submission or approval',
          'GIS system for parcel/location verification and zoning lookup',
          'Inspection scheduling system for post-approval inspection coordination',
        ],
        mongoDBConsiderations: [
          'Index on {permitType: 1, status: 1} for permit pipeline by type',
          'Index on {permitLocation: 1} for geographic queries and parcel lookup',
          'Index on {submittedDate: 1} for processing time analysis',
          'Store documents as references to blob storage, not inline',
        ],
      },
      seo: {
        metaTitle: 'Permit Application Form Template | NetPad',
        metaDescription: 'Free permit application template for government agencies. Collect complete applications with documents, fees, and declarations for faster processing.',
        keywords: ['permit application form', 'building permit', 'business license', 'government permit', 'permit online'],
        ogDescription: 'Stop chasing missing documents. This permit template collects complete applications with all required materials for immediate review.',
      },
      socialProofAngles: [
        'Faster permit processing times',
        'Fewer incomplete applications',
        'Better applicant communication',
        'Complete audit trail for compliance',
      ],
    },
  }),

  createTemplate({
    id: 'citizen-complaint-form',
    name: 'Citizen Complaint Form',
    description: 'Report issues, complaints, or concerns to local government',
    category: 'government-public',
    icon: '📢',
    complexity: 'simple',
    estimatedTime: '4-6 min',
    formType: 'both',
    featured: true,
    fields: [
      sectionHeader('Contact Information'),
      textField('full_name', 'Your Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      addressField('address', 'Your Address', false),
      sectionHeader('Complaint Details'),
      selectField('complaint_category', 'Complaint Category', [
        'Road/Street Issue', 'Water/Sewer', 'Trash/Sanitation', 'Noise',
        'Code Violation', 'Parks/Recreation', 'Public Safety', 'Streetlights',
        'Traffic/Parking', 'Animal Control', 'Building/Zoning', 'Other'
      ], true),
      addressField('incident_location', 'Location of Issue', true),
      dateField('incident_date', 'Date Issue First Noticed', true),
      textareaField('description', 'Detailed Description of Complaint', true),
      sectionHeader('Additional Information'),
      yesNoField('ongoing_issue', 'Is this an ongoing issue?', true),
      yesNoField('safety_hazard', 'Is this a safety hazard?', true),
      yesNoField('previous_report', 'Have you reported this before?', true),
      textField('previous_case_number', 'Previous Case/Reference Number', false),
      sectionHeader('Evidence (Optional)'),
      fileField('photos', 'Photos of Issue', false, '.jpg,.png,.heic'),
      fileField('documents', 'Supporting Documents', false, '.pdf,.doc,.docx'),
      sectionHeader('Follow-up Preferences'),
      selectField('contact_preference', 'Preferred Contact Method', [
        'Email', 'Phone', 'Mail', 'No Contact Needed'
      ], true),
      yesNoField('public_record', 'I understand this may become a public record', true),
      textareaField('additional_notes', 'Additional Notes', false),
    ],
    tags: ['complaint', 'citizen services', 'municipal', 'report issue'],
    useCases: ['City/Town halls', 'County offices', '311 services'],
    enhanced: {
      headline: 'Respond to Citizen Concerns Before They Escalate',
      subheadline: 'Give residents an easy way to report issues with automatic routing to the right department—track resolution from report to closure.',
      longDescription: {
        opening: 'Citizens don\'t know who to call. The pothole has been there for months. The streetlight has been out for weeks. They call the main number, get transferred three times, and eventually give up. Some send emails that sit in inboxes. Others show up at city council meetings frustrated that their basic concerns go unaddressed. Elected officials get blindsided by complaints they never heard about. Small issues become political problems because nobody tracked them.',
        solution: 'This template creates a single intake point for citizen concerns: contact information, complaint category (roads, water, trash, noise, code violations, parks, safety, etc.), specific location, date first noticed, detailed description, safety hazard flag, previous report reference, and photo uploads. Category routing sends issues to the right department immediately. Safety flags trigger priority response. Photo evidence helps crews understand issues before arriving.',
        outcome: 'Route complaints to the right department in seconds, not days. Track every issue from report to resolution. Identify chronic problems by location or category. Demonstrate responsiveness to elected officials with resolution metrics. Close the loop with citizens when their issue is addressed. Build trust through transparency and follow-through.',
      },
      useCases: [
        {
          title: 'Municipal 311 Services',
          icon: '📞',
          industry: 'Local Government',
          scenario: 'Your city operates a 311 service for non-emergency requests. Call center staff manually route calls to departments. Email requests sit in shared inboxes. Some issues get addressed; others disappear. Citizens call back asking for status and nobody knows where their request went.',
          painPoint: 'No unified tracking of requests across channels. Manual routing slow and error-prone. No status visibility for citizens. Department workloads invisible to management.',
          keyFields: ['Complaint Category', 'Location of Issue', 'Detailed Description of Complaint', 'Photos of Issue'],
          exampleOrganization: 'A city 311 service handling 50,000+ annual requests with no unified tracking and 40% resolution rate.',
        },
        {
          title: 'County Code Enforcement',
          icon: '⚖️',
          industry: 'County Government',
          scenario: 'Your county receives code violation complaints: overgrown properties, illegal dumping, unpermitted construction, noise violations. Complaints arrive via mail, email, and walk-ins. Some complainants want anonymity. Inspectors need location details and photos to prioritize site visits.',
          painPoint: 'Complaints scattered across mail, email, phone. Anonymous reporting not clearly supported. No photos mean inspectors arrive unprepared. No tracking of repeat violations at same address.',
          keyFields: ['Complaint Category', 'Location of Issue', 'Is this an ongoing issue?', 'Photos of Issue'],
          exampleOrganization: 'A county code enforcement office receiving 3,000+ annual complaints with 60-day average response time.',
        },
        {
          title: 'Public Works Requests',
          icon: '🛠️',
          industry: 'Local Government',
          scenario: 'Your public works department handles road repairs, streetlights, water issues, and trash collection complaints. Crews need location details and problem descriptions to dispatch efficiently. Some issues are safety hazards requiring immediate response. No way to prioritize.',
          painPoint: 'No prioritization of safety hazards vs. routine issues. Crews dispatched without complete information. Repeat requests for same issue not identified. No communication back to reporter on resolution.',
          keyFields: ['Complaint Category', 'Location of Issue', 'Is this a safety hazard?', 'Date Issue First Noticed'],
          exampleOrganization: 'A public works department with 10 crews handling 5,000+ annual requests, unable to prioritize or track resolution.',
        },
        {
          title: 'Neighborhood Services',
          icon: '🏘️',
          industry: 'Local Government',
          scenario: 'Your neighborhood services team handles quality-of-life issues: noise complaints, neighbor disputes, abandoned vehicles, graffiti. Issues are sensitive—complainants may fear retaliation. Some complaints require mediation, not enforcement. Staff need context to handle appropriately.',
          painPoint: 'Sensitive complaints require confidentiality. Some issues need mediation, not enforcement. No tracking of neighborhood-level trends. Resolution communication back to citizens inconsistent.',
          keyFields: ['Your Name', 'Complaint Category', 'Detailed Description', 'Preferred Contact Method'],
          exampleOrganization: 'A city neighborhood services team handling 2,000+ annual quality-of-life complaints with inconsistent response.',
        },
      ],
      customizationTips: [
        {
          title: 'Enable Anonymous Reporting',
          description: 'Allow citizens to submit complaints without providing contact information. Track anonymous vs. identified for response patterns.',
          fieldSuggestion: 'yesno',
          difficulty: 'easy',
        },
        {
          title: 'Add Geolocation',
          description: 'Integrate map-based location selection. Citizens drop a pin instead of typing addresses. Improves accuracy for issues in parks, alleys, or unmarked areas.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Include SLA Tracking',
          description: 'Based on category and safety flag, set resolution deadline. Track time-to-resolution and alert supervisors on overdue issues.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
        {
          title: 'Enable Duplicate Detection',
          description: 'When new complaint is submitted, check for existing open complaints at same location. Link duplicates instead of creating separate work orders.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Add Resolution Feedback',
          description: 'After issue is marked resolved, email citizen asking to confirm resolution. Reopen if citizen reports issue persists.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'receipt-confirmation',
          title: 'Confirm Complaint Receipt',
          description: 'Immediately email/text citizen confirming receipt with case number, assigned department, and estimated response time based on category.',
          trigger: 'On form submission',
          benefits: ['Citizen knows complaint received', 'Case number for follow-up', 'Clear expectations for response'],
        },
        {
          workflowType: 'department-routing',
          title: 'Route to Department',
          description: 'Based on complaint category, automatically assign to responsible department. Safety hazards flagged as priority. Create work order in department\'s system.',
          trigger: 'On form submission',
          benefits: ['Instant routing to correct department', 'Safety issues prioritized', 'No manual triage required'],
        },
        {
          workflowType: 'status-updates',
          title: 'Send Status Updates',
          description: 'When complaint status changes (assigned, in progress, completed), automatically notify citizen with update and next expected action.',
          trigger: 'On status change',
          benefits: ['Citizens informed throughout process', 'Reduces "where\'s my request?" calls', 'Builds trust in government responsiveness'],
        },
        {
          workflowType: 'resolution-notification',
          title: 'Notify on Resolution',
          description: 'When issue is marked resolved, email citizen with resolution description, close case, and invite feedback on satisfaction with response.',
          trigger: 'On completion',
          benefits: ['Closure communication to citizen', 'Satisfaction feedback collected', 'Complete audit trail of resolution'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Complaint category enables automatic department routing',
          'Safety hazard boolean triggers priority processing',
          'Previous report boolean and case number link related complaints',
          'File uploads support photo evidence for field crews',
        ],
        integrationHints: [
          'Work order system (Cityworks, Cartegraph) for dispatch to field crews',
          'GIS system for location mapping and duplicate detection',
          'SMS gateway for status notifications to citizens',
        ],
        mongoDBConsiderations: [
          'Index on {category: 1, status: 1} for department workload queries',
          'Geospatial index on {location: "2dsphere"} for map-based queries and duplicate detection',
          'Index on {submittedDate: 1, resolvedDate: 1} for SLA tracking',
          'Aggregation pipeline for complaint trends by category, location, and time',
        ],
      },
      seo: {
        metaTitle: 'Citizen Complaint Form Template | NetPad',
        metaDescription: 'Free citizen complaint template for government agencies. Route issues to the right department, track resolution, and close the loop with citizens.',
        keywords: ['citizen complaint form', '311 form', 'report issue', 'city complaint', 'municipal services'],
        ogDescription: 'Turn citizen complaints into resolved issues. This template routes reports to the right department and tracks resolution to completion.',
      },
      socialProofAngles: [
        'Faster issue resolution',
        'Better citizen communication',
        'Complete complaint tracking',
        'Improved government responsiveness',
      ],
    },
  }),

  createTemplate({
    id: 'public-meeting-registration',
    name: 'Public Meeting Registration',
    description: 'Register to attend or speak at public government meetings',
    category: 'government-public',
    icon: '🏛️',
    complexity: 'simple',
    estimatedTime: '3-4 min',
    formType: 'conversational',
    fields: [
      sectionHeader('Attendee Information'),
      textField('full_name', 'Full Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', false),
      textField('organization', 'Organization/Affiliation (optional)', false),
      sectionHeader('Meeting Details'),
      selectField('meeting_type', 'Meeting Type', [
        'City Council', 'Planning Commission', 'School Board', 'Town Hall',
        'Budget Hearing', 'Zoning Board', 'Public Hearing', 'Other'
      ], true),
      dateField('meeting_date', 'Meeting Date', true),
      selectField('attendance_type', 'Attendance Type', [
        'In-Person', 'Virtual/Online', 'Phone/Audio Only'
      ], true),
      sectionHeader('Public Comment'),
      yesNoField('wishes_to_speak', 'Do you wish to speak during public comment?', true),
      selectField('agenda_item', 'Regarding Agenda Item', [
        'General Public Comment', 'Specific Agenda Item', 'Multiple Items'
      ], false),
      textField('agenda_item_number', 'Agenda Item Number (if specific)', false),
      textareaField('comment_topic', 'Brief Description of Comment Topic', false),
      selectField('estimated_time', 'Estimated Speaking Time Needed', [
        '1-2 minutes', '3-5 minutes', '5-10 minutes', 'Extended Presentation'
      ], false),
      sectionHeader('Accessibility'),
      yesNoField('accessibility_needs', 'Do you require accessibility accommodations?', false),
      textareaField('accessibility_details', 'Please describe accommodations needed', false),
      yesNoField('interpreter_needed', 'Do you need language interpretation?', false),
      selectField('language', 'If yes, what language?', [
        'Spanish', 'Mandarin', 'Vietnamese', 'Korean', 'ASL', 'Other'
      ], false),
      sectionHeader('Materials'),
      yesNoField('submitting_materials', 'Will you be submitting written materials?', false),
      fileField('presentation', 'Presentation/Materials to Share', false, '.pdf,.ppt,.pptx'),
    ],
    tags: ['public meeting', 'town hall', 'civic engagement', 'city council'],
    useCases: ['City/County government', 'School districts', 'Public agencies'],
    enhanced: {
      headline: 'Run Smoother Public Meetings with Advance Registration',
      subheadline: 'Know who\'s coming, who wants to speak, and what accommodations they need—before the meeting starts.',
      longDescription: {
        opening: 'Public meetings are logistical puzzles. How many chairs do you need? How long will public comment take? Who needs an ASL interpreter? Which agenda items will draw speakers? Without advance registration, you\'re guessing. Meetings run over time because too many people signed up to speak. Non-English speakers arrive without interpretation. Accessibility accommodations aren\'t ready. Citizens feel unheard because the speaking queue was full before they signed up.',
        solution: 'This template captures meeting registration with everything staff need to plan: attendee identification and organization affiliation, meeting and date selection, attendance type (in-person, virtual, audio), intent to speak during public comment, agenda item specifics, speaking time estimate, accessibility accommodation requests, language interpretation needs, and materials to be submitted. Conditional fields show relevant questions based on choices.',
        outcome: 'Plan room setup based on confirmed attendance. Estimate public comment duration from speaker count and time requests. Arrange interpreters and accessibility accommodations in advance. Stream meetings to virtual attendees seamlessly. Manage speaking queues fairly with advance sign-up. Document civic engagement for transparency reporting.',
      },
      useCases: [
        {
          title: 'City Council Meetings',
          icon: '🏛️',
          industry: 'Local Government',
          scenario: 'Your city council meets twice monthly with public comment periods. Controversial agenda items draw crowds; routine meetings are sparse. Without registration, you can\'t predict attendance. Speaking queues form at the door, creating chaos. Some citizens wait hours to speak and don\'t get called.',
          painPoint: 'Can\'t predict attendance for room setup. Speaker sign-up at door creates chaos. Public comment runs overtime. No advance notice of accessibility needs.',
          keyFields: ['Meeting Type', 'Meeting Date', 'Do you wish to speak during public comment?', 'Estimated Speaking Time Needed'],
          exampleOrganization: 'A city council with 15 annual meetings ranging from 20 to 200 attendees, unable to plan for variable turnout.',
        },
        {
          title: 'School Board Meetings',
          icon: '🏫',
          industry: 'Education',
          scenario: 'Your school board meetings draw parents, teachers, students, and community members. Hot-button issues (redistricting, curriculum changes) generate packed rooms. Parents need childcare to attend evening meetings. Non-English speaking families want to participate but need interpretation.',
          painPoint: 'Parents can\'t attend without knowing childcare is available. Interpretation arranged last-minute or not at all. Speaker time dominates meetings without management. Student speakers intimidated by chaotic process.',
          keyFields: ['Organization/Affiliation', 'Attendance Type', 'Do you need language interpretation?', 'If yes, what language?'],
          exampleOrganization: 'A school board with diverse community, 30% non-English speaking families, with interpretation arranged inconsistently.',
        },
        {
          title: 'Planning Commission Hearings',
          icon: '🗺️',
          industry: 'Local Government',
          scenario: 'Your planning commission holds hearings on development projects. Applicants present, neighbors object, and commissioners deliberate. Some cases require 30+ minutes of public testimony. Applicants bring consultants and attorneys. Neighbors organize to oppose. Meeting length is unpredictable.',
          painPoint: 'Can\'t estimate hearing duration. Applicant presentations not coordinated in advance. Neighbor testimony unorganized and repetitive. No record of who spoke on which case.',
          keyFields: ['Regarding Agenda Item', 'Agenda Item Number', 'Brief Description of Comment Topic', 'Will you be submitting written materials?'],
          exampleOrganization: 'A planning commission with monthly hearings running 2-6 hours, no way to estimate duration in advance.',
        },
        {
          title: 'Town Hall Meetings',
          icon: '🎤',
          industry: 'Local Government',
          scenario: 'Your elected officials hold town halls on specific topics: budget, public safety, infrastructure. These are listening sessions, not formal meetings. You want maximum participation. Virtual options expand access. But you don\'t know who\'s coming or how to reach them with updates.',
          painPoint: 'No contact list for attendees. Can\'t send updates or follow-up. Virtual attendance requires technical setup but demand unknown. No record of constituent engagement.',
          keyFields: ['Full Name', 'Email Address', 'Attendance Type', 'Do you require accessibility accommodations?'],
          exampleOrganization: 'A city council holding quarterly town halls with 50-300 variable attendance, no contact capture for follow-up.',
        },
      ],
      customizationTips: [
        {
          title: 'Enable Speaker Queue Management',
          description: 'When multiple speakers register for same agenda item, assign order and send queue position. Allow speakers to track their position in real-time.',
          fieldSuggestion: 'number',
          difficulty: 'advanced',
        },
        {
          title: 'Add Virtual Meeting Links',
          description: 'For virtual attendees, automatically send Zoom/Teams link on registration confirmation. Include dial-in numbers for phone attendees.',
          fieldSuggestion: 'text',
          difficulty: 'easy',
        },
        {
          title: 'Enable Materials Pre-Submission',
          description: 'Allow speakers to submit presentations and written testimony in advance. Share materials with commissioners/board members before meeting.',
          fieldSuggestion: 'file',
          difficulty: 'medium',
        },
        {
          title: 'Add Capacity Limits',
          description: 'When in-person capacity is reached, automatically offer virtual attendance option. Track capacity for fire code compliance.',
          fieldSuggestion: 'number',
          difficulty: 'medium',
        },
        {
          title: 'Include Post-Meeting Survey',
          description: 'After meeting, automatically send satisfaction survey to registrants. Capture feedback on meeting process and civic engagement.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'registration-confirmation',
          title: 'Confirm Registration',
          description: 'Immediately email registrant confirming attendance with meeting details, agenda link, virtual meeting link (if applicable), and speaker queue position (if speaking).',
          trigger: 'On form submission',
          benefits: ['Registrant has all meeting details', 'Virtual attendees have login info', 'Speakers know their queue position'],
        },
        {
          workflowType: 'accommodation-alert',
          title: 'Alert on Accommodation Requests',
          description: 'When accessibility accommodation or language interpretation is requested, immediately notify meeting coordinator to arrange services before meeting.',
          trigger: 'On submission with accommodation = true',
          benefits: ['Accommodation requests caught early', 'Time to arrange interpreters', 'Accessible setup confirmed before meeting'],
        },
        {
          workflowType: 'meeting-reminder',
          title: 'Send Meeting Reminder',
          description: 'One day before meeting, email all registrants with reminder, updated agenda, parking/access info, and final speaker queue.',
          trigger: 'Scheduled - 1 day before meeting',
          benefits: ['Reduces no-shows', 'Registrants have updated agenda', 'Speakers know their final position'],
        },
        {
          workflowType: 'speaker-management',
          title: 'Manage Speaking Queue',
          description: 'Compile speaker list by agenda item for meeting chair. Display estimated public comment duration. Track actual speaking time for future estimates.',
          trigger: 'Day of meeting',
          benefits: ['Chair has organized speaker list', 'Realistic time estimates', 'Fair queue management'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Meeting type and date enable aggregation of registrations by specific meeting',
          'Wishes to speak boolean with conditional time estimate supports queue planning',
          'Accessibility and interpreter fields enable advance accommodation arrangement',
          'Organization field tracks stakeholder engagement patterns',
        ],
        integrationHints: [
          'Video conferencing API (Zoom, Teams) for virtual meeting link generation',
          'Calendar API for meeting reminders and calendar invites',
          'Agenda management system for agenda item linking',
        ],
        mongoDBConsiderations: [
          'Index on {meetingDate: 1, meetingType: 1} for per-meeting queries',
          'Index on {wishesToSpeak: 1, agendaItem: 1} for speaker queue generation',
          'Aggregation pipeline for attendance estimates by meeting type',
          'Consider separate collection for accommodation requests with notification tracking',
        ],
      },
      seo: {
        metaTitle: 'Public Meeting Registration Template | NetPad',
        metaDescription: 'Free public meeting registration for government agencies. Capture attendance, speaker requests, and accommodation needs before meetings.',
        keywords: ['public meeting registration', 'city council signup', 'town hall registration', 'public comment', 'civic engagement'],
        ogDescription: 'Run smoother public meetings with advance registration. Know who\'s coming, who\'s speaking, and what accommodations they need.',
      },
      socialProofAngles: [
        'Better meeting preparation',
        'Fair speaker queue management',
        'Accessibility accommodations arranged in advance',
        'Increased civic participation',
      ],
    },
  }),

  createTemplate({
    id: 'voter-registration-assistance',
    name: 'Voter Registration Assistance',
    description: 'Collect information to assist with voter registration',
    category: 'government-public',
    icon: '🗳️',
    complexity: 'intermediate',
    estimatedTime: '5-7 min',
    formType: 'both',
    fields: [
      sectionHeader('Eligibility Verification'),
      yesNoField('us_citizen', 'Are you a United States citizen?', true),
      yesNoField('age_eligible', 'Will you be 18 years old on or before Election Day?', true),
      yesNoField('state_resident', 'Are you a resident of this state?', true),
      sectionHeader('Personal Information'),
      textField('first_name', 'First Name', true),
      textField('middle_name', 'Middle Name', false),
      textField('last_name', 'Last Name', true),
      textField('suffix', 'Suffix (Jr., Sr., III, etc.)', false),
      dateField('dob', 'Date of Birth', true),
      selectField('gender', 'Gender', ['Male', 'Female', 'Other', 'Prefer not to say'], false),
      sectionHeader('Identification'),
      textField('drivers_license', 'Driver\'s License Number', false),
      textField('ssn_last_four', 'Last 4 Digits of SSN', false),
      sectionHeader('Address Information'),
      addressField('residential_address', 'Residential Address (where you live)', true),
      yesNoField('same_mailing', 'Is your mailing address the same?', true),
      addressField('mailing_address', 'Mailing Address (if different)', false),
      sectionHeader('Previous Registration'),
      yesNoField('previously_registered', 'Have you registered to vote before?', true),
      textField('previous_name', 'Previous Name (if changed)', false),
      textField('previous_address', 'Previous Registration Address', false),
      textField('previous_county', 'Previous County/State', false),
      sectionHeader('Party Affiliation'),
      selectField('party', 'Party Affiliation', [
        'Democratic', 'Republican', 'Independent', 'Libertarian',
        'Green', 'Other', 'No Party Preference'
      ], false),
      sectionHeader('Voting Preferences'),
      yesNoField('mail_ballot', 'Would you like to receive a mail-in ballot?', false),
      yesNoField('poll_worker', 'Interested in being an election poll worker?', false),
      sectionHeader('Assistance'),
      yesNoField('assistance_needed', 'Did someone help you complete this form?', true),
      textField('assistant_name', 'Assistant\'s Name', false),
      textField('assistant_address', 'Assistant\'s Address', false),
      sectionHeader('Declaration'),
      yesNoField('affirm_citizen', 'I affirm I am a U.S. citizen', true),
      yesNoField('affirm_eligible', 'I affirm I meet all eligibility requirements', true),
      yesNoField('affirm_accurate', 'I affirm all information is true and accurate', true),
      signatureField('signature', 'Signature', true),
      dateField('signature_date', 'Date', true),
    ],
    tags: ['voter registration', 'elections', 'civic', 'voting'],
    useCases: ['Election offices', 'Civic organizations', 'Voter registration drives'],
    enhanced: {
      headline: 'Register Every Eligible Voter Accurately',
      subheadline: 'Capture complete voter registration information with eligibility verification, ID collection, and party affiliation—compliant with state requirements.',
      longDescription: {
        opening: 'Voter registration should be simple, but the process is fraught with errors. Paper forms have illegible handwriting. Address changes aren\'t captured. Eligibility questions get skipped. Registration drives collect forms that get rejected because fields are incomplete. Voters show up on Election Day and discover they\'re not registered—or registered at an old address. Every rejected registration is a citizen denied their voice.',
        solution: 'This template collects complete voter registration data: eligibility verification (citizenship, age, residency), personal identification (name, DOB, SSN last four or driver\'s license), residential and mailing addresses with change tracking, previous registration information for record updates, party affiliation, voting preferences (mail ballot, poll worker interest), and assistance documentation with signature capture. Required field validation ensures complete submissions.',
        outcome: 'Submit registration applications that won\'t be rejected for incompleteness. Capture address changes properly for registration updates. Track registrations from drives through confirmation. Meet state compliance requirements with complete data capture. Enable same-day confirmation for voters in states that allow it. Increase civic participation through accessible registration.',
      },
      useCases: [
        {
          title: 'County Elections Office',
          icon: '🗳️',
          industry: 'Government',
          scenario: 'Your county elections office processes voter registrations year-round. Paper applications arrive with incomplete information—missing signatures, illegible addresses, unchecked eligibility boxes. Staff spend hours following up before entering into voter rolls. Some applications never get resolved before registration deadlines.',
          painPoint: '25% of paper applications require follow-up for missing info. Data entry from paper creates errors. No tracking of application status. Deadline pressure causes backlogs.',
          keyFields: ['Are you a United States citizen?', 'Residential Address', 'Driver\'s License Number', 'Signature'],
          exampleOrganization: 'A county elections office processing 50,000+ voter registrations annually with 25% requiring manual follow-up.',
        },
        {
          title: 'Voter Registration Drives',
          icon: '📋',
          industry: 'Civic Organizations',
          scenario: 'Your civic organization runs voter registration drives at community events, college campuses, and high schools. Volunteers collect paper forms that must be submitted within deadlines. Incomplete forms get rejected. Volunteers aren\'t trained to catch errors. Registrations don\'t get confirmed.',
          painPoint: 'Volunteers don\'t catch incomplete forms. Paper forms lost or damaged before submission. No confirmation that registrations were processed. Can\'t track which drives were successful.',
          keyFields: ['First Name', 'Last Name', 'Date of Birth', 'I affirm I am a U.S. citizen'],
          exampleOrganization: 'A civic organization running 50+ annual registration drives with 20% of collected forms rejected for errors.',
        },
        {
          title: 'High School Civic Education',
          icon: '🏫',
          industry: 'Education',
          scenario: 'Your high school civics program includes voter pre-registration for 16-17 year olds. Students complete registration in class. Paper forms require parental awareness for minors in some states. No way to track which students actually get registered when they turn 18.',
          painPoint: 'Pre-registration process confusing for students. No tracking from classroom to registration rolls. Some states require parental notification. Students don\'t know if registration went through.',
          keyFields: ['Will you be 18 years old on or before Election Day?', 'Date of Birth', 'Residential Address', 'Party Affiliation'],
          exampleOrganization: 'A high school civics program pre-registering 500+ students annually with no confirmation of successful registration.',
        },
        {
          title: 'Naturalization Event Registration',
          icon: '🇺🇸',
          industry: 'Government/Civic',
          scenario: 'Your organization partners with USCIS to register new citizens at naturalization ceremonies. Hundreds of new citizens complete registration immediately after taking the oath. Volunteers assist non-native English speakers. High-volume processing requires efficiency without sacrificing accuracy.',
          painPoint: 'High-volume events require fast processing. Language barriers create errors. New citizens unfamiliar with registration process. No confirmation of successful registration.',
          keyFields: ['Are you a United States citizen?', 'Did someone help you complete this form?', 'Assistant\'s Name', 'Signature'],
          exampleOrganization: 'A civic organization registering 2,000+ new citizens annually at naturalization ceremonies with 15% error rate.',
        },
      ],
      customizationTips: [
        {
          title: 'Add State-Specific Fields',
          description: 'Different states require different information. Customize form based on state requirements: some require full SSN, others driver\'s license, some require party registration.',
          fieldSuggestion: 'select',
          difficulty: 'medium',
        },
        {
          title: 'Enable Pre-Registration',
          description: 'For states allowing pre-registration at 16-17, add age-based logic to capture pre-registrations and track until voter turns 18.',
          fieldSuggestion: 'date',
          difficulty: 'medium',
        },
        {
          title: 'Add Address Validation',
          description: 'Validate residential address against USPS database to ensure mail delivery and proper precinct assignment.',
          fieldSuggestion: 'text',
          difficulty: 'advanced',
        },
        {
          title: 'Include Confirmation Tracking',
          description: 'After submission, track registration status with elections office. Notify voter when registration is confirmed or if issues arise.',
          fieldSuggestion: 'yesno',
          difficulty: 'advanced',
        },
        {
          title: 'Enable Multi-Language Support',
          description: 'Provide form in multiple languages as required by Voting Rights Act. Capture preferred language for voter materials.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'submission-confirmation',
          title: 'Confirm Registration Submission',
          description: 'Immediately email/text applicant confirming registration submission with next steps, expected timeline for processing, and how to verify registration status.',
          trigger: 'On form submission',
          benefits: ['Voter knows registration was submitted', 'Clear expectations for confirmation', 'Instructions for verification'],
        },
        {
          workflowType: 'completeness-check',
          title: 'Validate Before Submission',
          description: 'Before allowing submission, validate all required fields are complete and properly formatted. Check age eligibility based on next election date.',
          trigger: 'On form submission attempt',
          benefits: ['Prevent incomplete submissions', 'Catch eligibility issues early', 'Higher acceptance rate at elections office'],
        },
        {
          workflowType: 'elections-integration',
          title: 'Submit to Elections Office',
          description: 'If integrated with state voter registration system, automatically submit registration. If not, generate print-ready form for mailing to elections office.',
          trigger: 'On form submission',
          benefits: ['Direct submission where available', 'Print-ready forms where not', 'Faster processing time'],
        },
        {
          workflowType: 'status-notification',
          title: 'Notify on Registration Status',
          description: 'When registration is confirmed (or rejected), notify applicant with status, precinct assignment (if approved), and next election date.',
          trigger: 'On registration status update',
          benefits: ['Voter knows registration status', 'Precinct and polling place provided', 'Engaged voter before election'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Eligibility questions as required booleans ensure compliance verification',
          'Previous registration fields enable record updates vs. new registrations',
          'Party affiliation as select enables proper ballot assignment in closed primary states',
          'Signature field with timestamp creates legally valid registration record',
        ],
        integrationHints: [
          'State voter registration API (where available) for direct submission',
          'USPS address validation API for address verification',
          'SMS gateway for confirmation and status notifications',
        ],
        mongoDBConsiderations: [
          'Index on {lastName: 1, dateOfBirth: 1} for duplicate detection',
          'Index on {residentialAddress: 1} for precinct assignment queries',
          'Index on {submittedDate: 1, status: 1} for registration pipeline tracking',
          'Encrypt sensitive fields (SSN, driver\'s license) at rest',
        ],
      },
      seo: {
        metaTitle: 'Voter Registration Form Template | NetPad',
        metaDescription: 'Free voter registration template with eligibility verification, ID capture, and party affiliation. Compliant with state requirements for registration drives.',
        keywords: ['voter registration form', 'voter registration drive', 'register to vote', 'election registration', 'civic engagement'],
        ogDescription: 'Register voters accurately without rejected forms. This template captures complete information with eligibility verification.',
      },
      socialProofAngles: [
        'Higher registration acceptance rate',
        'Complete applications every time',
        'Compliance with state requirements',
        'Increased voter participation',
      ],
    },
  }),

  createTemplate({
    id: 'government-job-application',
    name: 'Government Job Application',
    description: 'Employment application for government and public sector positions',
    category: 'government-public',
    icon: '💼',
    complexity: 'advanced',
    estimatedTime: '15-20 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Position Information'),
      textField('position_title', 'Position Title', true),
      textField('job_posting_number', 'Job Posting Number', true),
      textField('department', 'Department/Division', true),
      sectionHeader('Personal Information'),
      textField('first_name', 'First Name', true),
      textField('middle_name', 'Middle Name', false),
      textField('last_name', 'Last Name', true),
      emailField('email', 'Email Address', true),
      phoneField('phone', 'Phone Number', true),
      phoneField('alt_phone', 'Alternate Phone', false),
      addressField('address', 'Current Address', true),
      sectionHeader('Eligibility'),
      yesNoField('us_work_authorized', 'Are you authorized to work in the United States?', true),
      yesNoField('will_verify', 'Will you submit to required verification?', true),
      yesNoField('veteran', 'Are you a veteran?', false),
      selectField('veteran_status', 'Veteran Status', [
        'Not a Veteran', 'Veteran', 'Disabled Veteran', 'Active Duty Transition'
      ], false),
      yesNoField('former_employee', 'Have you previously worked for this agency?', true),
      textField('former_dates', 'If yes, dates of employment', false),
      sectionHeader('Education'),
      selectField('highest_education', 'Highest Level of Education', [
        'High School/GED', 'Some College', 'Associate Degree', 'Bachelor\'s Degree',
        'Master\'s Degree', 'Doctoral Degree', 'Professional Degree (JD, MD)'
      ], true),
      textField('school_name', 'School/University Name', true),
      textField('major_field', 'Major/Field of Study', false),
      dateField('graduation_date', 'Graduation Date', false),
      sectionHeader('Professional Licenses & Certifications'),
      textareaField('licenses', 'List any professional licenses or certifications', false),
      sectionHeader('Employment History'),
      textareaField('employment_history', 'List your last three employers (name, title, dates, duties)', true),
      sectionHeader('Skills & Qualifications'),
      textareaField('relevant_skills', 'Relevant Skills and Experience', true),
      textareaField('special_qualifications', 'Special Qualifications for this Position', false),
      sectionHeader('References'),
      textareaField('references', 'List 3 professional references (name, title, phone, relationship)', true),
      sectionHeader('Background Information'),
      yesNoField('convicted', 'Have you ever been convicted of a felony?', true),
      textareaField('conviction_details', 'If yes, please explain', false),
      yesNoField('discipline_history', 'Have you been subject to discipline in previous employment?', true),
      textareaField('discipline_details', 'If yes, please explain', false),
      sectionHeader('Documents'),
      fileField('resume', 'Resume/CV', true, '.pdf,.doc,.docx'),
      fileField('cover_letter', 'Cover Letter', false, '.pdf,.doc,.docx'),
      fileField('transcripts', 'Transcripts', false, '.pdf'),
      fileField('licenses_docs', 'License/Certification Documents', false, '.pdf,.jpg,.png'),
      sectionHeader('Certification'),
      yesNoField('accurate_info', 'I certify all information is true and complete', true),
      yesNoField('background_consent', 'I consent to background investigation', true),
      yesNoField('reference_consent', 'I consent to contact my references', true),
      signatureField('signature', 'Signature', true),
      dateField('signature_date', 'Date', true),
    ],
    tags: ['job application', 'government employment', 'public sector', 'career'],
    useCases: ['Government HR departments', 'Civil service', 'Public agencies'],
    enhanced: {
      headline: 'Hire Public Servants Through a Fair, Compliant Process',
      subheadline: 'Collect standardized applications with veteran preferences, background disclosures, and required certifications—score candidates objectively for civil service compliance.',
      longDescription: {
        opening: 'Government hiring isn\'t like private sector hiring. Civil service rules mandate objective scoring. Veteran preferences must be applied consistently. Background checks are mandatory. Union agreements dictate processes. One misstep—an interview question that wasn\'t on the approved list, a veteran preference not applied—and the entire hire can be challenged. Grievances, lawsuits, and failed audits follow when processes aren\'t documented.',
        solution: 'This template captures compliant government job applications: position identification, personal information, work authorization and verification consent, veteran status with preference categories, education and professional licenses, detailed employment history, skills and qualifications, professional references, background disclosures (conviction, discipline history) with explanations, required document uploads (resume, transcripts, certifications), and signed certifications with background check consent. Veteran status enables proper preference application.',
        outcome: 'Score candidates objectively using documented criteria. Apply veteran preferences correctly every time. Document every application for audit defense. Streamline background check consent collection. Reduce time-to-hire by eliminating incomplete applications. Defend hiring decisions with complete application records. Meet civil service compliance requirements.',
      },
      useCases: [
        {
          title: 'Municipal HR Department',
          icon: '🏛️',
          industry: 'Local Government',
          scenario: 'Your city HR department hires for 50+ positions annually across police, fire, public works, administration, and parks. Each department has different requirements. Civil service rules mandate objective scoring. Veteran preferences must be applied. Paper applications create tracking nightmares.',
          painPoint: 'Paper applications difficult to score consistently. Veteran preferences applied inconsistently. No audit trail for hiring decisions. Time-to-hire averages 90 days due to manual processing.',
          keyFields: ['Position Title', 'Are you a veteran?', 'Veteran Status', 'Employment History'],
          exampleOrganization: 'A city HR department with 500 employees, hiring 50+ positions annually with 90-day average time-to-hire.',
        },
        {
          title: 'State Agency Recruitment',
          icon: '📋',
          industry: 'State Government',
          scenario: 'Your state agency uses centralized HR but departments have different position requirements. Some positions require specific certifications or security clearances. Candidates apply for multiple positions. No way to track candidate pipeline across positions.',
          painPoint: 'Candidates resubmit applications for each position. No tracking of candidates across multiple applications. Certification verification done manually. Background check timing inconsistent.',
          keyFields: ['Department/Division', 'Professional Licenses', 'I consent to background investigation', 'Resume/CV'],
          exampleOrganization: 'A state agency with 2,000 employees across 10 divisions, processing 500+ applications annually.',
        },
        {
          title: 'Public Safety Hiring',
          icon: '🚔',
          industry: 'Public Safety',
          scenario: 'Your police or fire department has extensive hiring requirements: physical fitness standards, background investigations, psychological evaluations, polygraphs. Candidates disqualify themselves at various stages. Tracking where candidates fail is essential for process improvement.',
          painPoint: 'Multi-stage process difficult to track. Candidate attrition unclear. Background investigation findings documented separately. No centralized candidate file.',
          keyFields: ['Have you ever been convicted of a felony?', 'Have you been subject to discipline in previous employment?', 'Relevant Skills and Experience', 'References'],
          exampleOrganization: 'A police department hiring 20+ officers annually through 6-month process with 70% candidate attrition.',
        },
        {
          title: 'School District Employment',
          icon: '🏫',
          industry: 'Education',
          scenario: 'Your school district hires teachers, administrators, and support staff. Teaching positions require credential verification. Support staff require background checks. Seasonal hiring creates volume spikes. Candidate pools need to be maintained for future openings.',
          painPoint: 'Credential verification done manually. Background check timing delays start dates. Seasonal hiring creates backlogs. No candidate pool for future openings.',
          keyFields: ['Position Title', 'Highest Level of Education', 'Professional Licenses', 'Transcripts'],
          exampleOrganization: 'A school district with 100 schools hiring 200+ staff annually with credential verification delays.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Veteran Preference Scoring',
          description: 'Based on veteran status, automatically apply preference points per civil service rules. Calculate total score with preferences applied.',
          fieldSuggestion: 'number',
          difficulty: 'medium',
        },
        {
          title: 'Enable Position-Specific Questions',
          description: 'Use conditional logic to show different qualification questions based on position selected. Police applications show different questions than administrative positions.',
          fieldSuggestion: 'textarea',
          difficulty: 'medium',
        },
        {
          title: 'Add Civil Service Scoring',
          description: 'Create scoring rubric based on education, experience, and qualifications. Calculate scores automatically for objective ranking.',
          fieldSuggestion: 'number',
          difficulty: 'advanced',
        },
        {
          title: 'Include EEO Data Collection',
          description: 'Add voluntary Equal Employment Opportunity demographic questions. Store separately from application for compliance reporting.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Reference Auto-Request',
          description: 'When references are provided, automatically email reference request forms. Track which references have responded.',
          fieldSuggestion: 'email',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'application-confirmation',
          title: 'Confirm Application Receipt',
          description: 'Immediately email applicant confirming receipt with application number, position applied for, and next steps in the hiring process.',
          trigger: 'On form submission',
          benefits: ['Applicant knows application received', 'Application number for reference', 'Clear expectations for process'],
        },
        {
          workflowType: 'minimum-qualification-screen',
          title: 'Screen for Minimum Qualifications',
          description: 'Based on position requirements, automatically screen applications for minimum qualifications (education, experience, certifications). Flag those that don\'t meet minimums.',
          trigger: 'On form submission',
          benefits: ['Unqualified applications identified immediately', 'Focus reviewer time on qualified candidates', 'Objective screening documented'],
        },
        {
          workflowType: 'veteran-preference',
          title: 'Apply Veteran Preferences',
          description: 'For applications with veteran status, automatically apply appropriate preference points per civil service rules. Document preference application for audit.',
          trigger: 'On scoring',
          benefits: ['Veteran preferences applied consistently', 'Documented for compliance', 'No manual calculation errors'],
        },
        {
          workflowType: 'background-initiation',
          title: 'Initiate Background Check',
          description: 'When candidate advances to background check stage, automatically send consent documentation to background check vendor. Track status and results.',
          trigger: 'On candidate advancement',
          benefits: ['Background check initiated immediately', 'Consent already captured', 'Status tracking in system'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Veteran status with category enables proper preference point calculation',
          'Background disclosure booleans with conditional explanation text protect agency while giving candidates context',
          'File uploads with type restrictions ensure proper document formats',
          'Signed certifications create legally binding consent record',
        ],
        integrationHints: [
          'Background check vendor API for check initiation and results retrieval',
          'HR information system (Workday, Oracle HCM) for employee record creation',
          'Credential verification service for education and license verification',
        ],
        mongoDBConsiderations: [
          'Index on {position: 1, status: 1} for applicant pipeline queries',
          'Index on {veteranStatus: 1, score: -1} for preference-applied ranking',
          'Index on {submittedDate: 1} for time-to-hire analytics',
          'Encrypt sensitive fields (SSN last 4, background disclosures) at rest',
        ],
      },
      seo: {
        metaTitle: 'Government Job Application Template | NetPad',
        metaDescription: 'Free government job application template with veteran preferences, background disclosures, and civil service compliance. Hire public servants fairly.',
        keywords: ['government job application', 'civil service application', 'public sector employment', 'government hiring', 'municipal job application'],
        ogDescription: 'Hire government employees through a fair, documented process. This template captures everything for civil service compliance.',
      },
      socialProofAngles: [
        'Compliant civil service hiring',
        'Consistent veteran preference application',
        'Documented hiring decisions',
        'Faster time-to-hire',
      ],
    },
  }),

  createTemplate({
    id: 'community-grant-application',
    name: 'Community Grant Application',
    description: 'Apply for government community development or project grants',
    category: 'government-public',
    icon: '💰',
    complexity: 'advanced',
    estimatedTime: '20-30 min',
    formType: 'traditional',
    fields: [
      sectionHeader('Organization Information'),
      textField('org_name', 'Organization Legal Name', true),
      textField('dba_name', 'DBA/Trade Name (if different)', false),
      textField('ein', 'Federal EIN/Tax ID', true),
      selectField('org_type', 'Organization Type', [
        '501(c)(3) Non-Profit', 'Government Entity', 'School/Educational',
        'Faith-Based Organization', 'Community Group', 'Other'
      ], true),
      dateField('established_date', 'Date Established', true),
      addressField('org_address', 'Organization Address', true),
      phoneField('org_phone', 'Organization Phone', true),
      textField('website', 'Website', false),
      sectionHeader('Primary Contact'),
      textField('contact_name', 'Contact Name', true),
      textField('contact_title', 'Title', true),
      emailField('contact_email', 'Email', true),
      phoneField('contact_phone', 'Phone', true),
      sectionHeader('Grant Request Details'),
      textField('project_title', 'Project Title', true),
      selectField('grant_category', 'Grant Category', [
        'Community Development', 'Youth Programs', 'Senior Services', 'Arts & Culture',
        'Public Safety', 'Environmental', 'Economic Development', 'Health & Wellness',
        'Education', 'Housing', 'Infrastructure', 'Other'
      ], true),
      currencyField('amount_requested', 'Amount Requested ($)', true),
      dateField('project_start', 'Project Start Date', true),
      dateField('project_end', 'Project End Date', true),
      sectionHeader('Project Description'),
      textareaField('project_summary', 'Project Summary (250 words max)', true),
      textareaField('need_statement', 'Statement of Need - What problem does this address?', true),
      textareaField('goals_objectives', 'Goals and Measurable Objectives', true),
      textareaField('activities', 'Proposed Activities and Timeline', true),
      textareaField('beneficiaries', 'Who will benefit and how many people will be served?', true),
      sectionHeader('Budget Information'),
      currencyField('total_budget', 'Total Project Budget', true),
      currencyField('other_funding', 'Funding from Other Sources', false),
      textareaField('budget_narrative', 'Budget Narrative - How will funds be used?', true),
      fileField('detailed_budget', 'Detailed Budget Spreadsheet', true, '.xlsx,.pdf'),
      sectionHeader('Organization Capacity'),
      textareaField('org_mission', 'Organization Mission Statement', true),
      textareaField('relevant_experience', 'Relevant Experience Managing Similar Projects', true),
      textareaField('staff_qualifications', 'Key Staff Qualifications', true),
      sectionHeader('Evaluation'),
      textareaField('success_measures', 'How will you measure success?', true),
      textareaField('reporting_plan', 'How will you report progress?', true),
      sectionHeader('Required Documents'),
      fileField('irs_determination', 'IRS Determination Letter (if 501c3)', false, '.pdf'),
      fileField('board_list', 'Board of Directors List', true, '.pdf,.docx'),
      fileField('financial_statements', 'Recent Financial Statements', true, '.pdf'),
      fileField('annual_report', 'Most Recent Annual Report', false, '.pdf'),
      fileField('letters_of_support', 'Letters of Support', false, '.pdf'),
      sectionHeader('Certification'),
      yesNoField('authorized', 'I am authorized to submit on behalf of this organization', true),
      yesNoField('accurate', 'All information provided is accurate and complete', true),
      yesNoField('terms', 'We agree to grant terms and reporting requirements', true),
      textField('authorized_name', 'Authorized Representative Name', true),
      textField('authorized_title', 'Title', true),
      signatureField('signature', 'Signature', true),
      dateField('date', 'Date', true),
    ],
    tags: ['grant', 'funding', 'community development', 'non-profit'],
    useCases: ['Government grant programs', 'Community foundations', 'Public funding agencies'],
    enhanced: {
      headline: 'Fund Community Projects That Actually Deliver',
      subheadline: 'Collect complete grant applications with project details, budgets, and organizational capacity—score and compare proposals objectively.',
      longDescription: {
        opening: 'Grant making should fund impact, but the process often funds whoever writes the best application. Incomplete proposals sit in review limbo. Organizations with grant writers win; grassroots groups with real impact lose. Selection committees argue about subjective criteria. Awards go to organizations that don\'t deliver, while effective programs go unfunded. Funders can\'t demonstrate how their dollars created community benefit.',
        solution: 'This template standardizes grant applications with everything reviewers need: organization information (legal name, EIN, type, history), primary contact, project details (title, category, amount requested, timeline), comprehensive project description (summary, need statement, goals, activities, beneficiaries), detailed budget (total project budget, other funding, budget narrative, spreadsheet upload), organizational capacity (mission, relevant experience, staff qualifications), evaluation plan (success measures, reporting), and required documents (IRS determination, board list, financials). Structured fields enable comparison across applications.',
        outcome: 'Compare applications objectively using consistent criteria. Fund organizations with demonstrated capacity to deliver. Track funded projects from award through completion. Demonstrate community impact with outcome data. Streamline review committee processes with structured applications. Meet funder reporting requirements with documented awards.',
      },
      useCases: [
        {
          title: 'Municipal Community Grants',
          icon: '🏛️',
          industry: 'Local Government',
          scenario: 'Your city offers community grants for neighborhood projects, youth programs, and cultural events. Applications arrive in varying formats—some are 2-page emails, others are 50-page PDFs. Review committee members can\'t compare apples to apples. Award decisions seem arbitrary.',
          painPoint: 'No standardized application format. Review committee can\'t compare applications fairly. Incomplete applications delay review. No tracking of project outcomes after award.',
          keyFields: ['Project Title', 'Amount Requested ($)', 'Statement of Need', 'Goals and Measurable Objectives'],
          exampleOrganization: 'A city community grants program with $500K annual budget, 100+ applications, and no systematic evaluation process.',
        },
        {
          title: 'County Economic Development',
          icon: '📈',
          industry: 'County Government',
          scenario: 'Your county economic development office provides grants and incentives for job creation, small business development, and workforce training. Grants require documentation of jobs created, wages, and economic impact. Past grantees don\'t report outcomes. Can\'t justify program to county commissioners.',
          painPoint: 'Grant agreements don\'t specify outcome requirements. Grantees don\'t report job creation data. Can\'t demonstrate ROI to elected officials. No tracking from application to outcome.',
          keyFields: ['Grant Category', 'Total Project Budget', 'Who will benefit and how many people will be served?', 'How will you measure success?'],
          exampleOrganization: 'A county economic development program with $2M annual grant budget, unable to document job creation outcomes.',
        },
        {
          title: 'State Arts Council',
          icon: '🎨',
          industry: 'State Government',
          scenario: 'Your state arts council funds arts organizations, individual artists, and community arts programs. Applications require artistic merit evaluation alongside organizational capacity. Panels include arts professionals and community members. Subjective criteria need structured evaluation.',
          painPoint: 'Artistic merit hard to evaluate objectively. Panel members have different criteria. Small organizations lack grant writing capacity. No tracking of funded programs\' reach.',
          keyFields: ['Organization Type', 'Relevant Experience Managing Similar Projects', 'Project Summary (250 words max)', 'How will you report progress?'],
          exampleOrganization: 'A state arts council with $5M grant program, panel review, and concerns about equity in award distribution.',
        },
        {
          title: 'Federal Pass-Through Grants',
          icon: '🏦',
          industry: 'State/Local Government',
          scenario: 'Your agency administers federal pass-through grants (CDBG, workforce development, public health). Federal compliance requirements are extensive. Subgrantees must meet eligibility and reporting requirements. Audit findings create risk.',
          painPoint: 'Federal compliance requirements complex. Subgrantee eligibility verification time-consuming. Reporting requirements inconsistently met. Audit findings create liability.',
          keyFields: ['Federal EIN/Tax ID', 'Organization Type', 'IRS Determination Letter', 'Recent Financial Statements'],
          exampleOrganization: 'A state agency administering $50M in federal pass-through grants with 200+ subgrantees and compliance concerns.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Scoring Rubric',
          description: 'Create structured scoring rubric for reviewers: need statement (0-20), goals clarity (0-15), budget reasonableness (0-20), organizational capacity (0-25), evaluation plan (0-20). Calculate total score automatically.',
          fieldSuggestion: 'number',
          difficulty: 'advanced',
        },
        {
          title: 'Enable Eligibility Screening',
          description: 'Based on organization type and project category, automatically verify eligibility before allowing full application. Prevent ineligible organizations from completing lengthy applications.',
          fieldSuggestion: 'yesno',
          difficulty: 'medium',
        },
        {
          title: 'Add Budget Template',
          description: 'Provide structured budget template with line items for personnel, supplies, travel, contractual, indirect costs. Calculate totals automatically. Flag budgets that don\'t balance.',
          fieldSuggestion: 'currency',
          difficulty: 'medium',
        },
        {
          title: 'Include Outcome Tracking',
          description: 'After award, use same system for quarterly/annual progress reports. Track actual vs. proposed outcomes. Flag underperforming grantees.',
          fieldSuggestion: 'textarea',
          difficulty: 'advanced',
        },
        {
          title: 'Enable Reviewer Assignment',
          description: 'Automatically assign applications to review committee members. Prevent conflicts of interest. Track review completion and scores.',
          fieldSuggestion: 'select',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'application-confirmation',
          title: 'Confirm Application Receipt',
          description: 'Immediately email applicant confirming receipt with application number, review timeline, and next steps. List submitted documents for verification.',
          trigger: 'On form submission',
          benefits: ['Applicant knows application received', 'Document checklist confirmation', 'Clear expectations for timeline'],
        },
        {
          workflowType: 'completeness-review',
          title: 'Flag Incomplete Applications',
          description: 'Check submitted application against required fields and documents. Flag missing items and notify applicant within 48 hours with deadline for completion.',
          trigger: 'On form submission',
          benefits: ['Incomplete applications caught early', 'Time for applicants to complete', 'Staff focus on complete applications'],
        },
        {
          workflowType: 'reviewer-distribution',
          title: 'Distribute to Reviewers',
          description: 'When review period opens, automatically distribute applications to assigned reviewers. Provide scoring rubric and deadline. Track review completion.',
          trigger: 'On review period start',
          benefits: ['Fair distribution to reviewers', 'Consistent scoring criteria', 'Review deadline tracking'],
        },
        {
          workflowType: 'award-notification',
          title: 'Notify Award Recipients',
          description: 'When funding decisions are made, automatically email award letters to successful applicants with award amount, terms, and agreement documents. Notify declined applicants with feedback.',
          trigger: 'On funding decisions',
          benefits: ['Immediate notification to all applicants', 'Professional award letters', 'Declined applicants receive feedback'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Grant category enables routing to appropriate review panel and criteria',
          'Currency fields for budgets enable financial analysis across applications',
          'File uploads with type restrictions ensure required documents in proper format',
          'Certification checkboxes create legal record of applicant representations',
        ],
        integrationHints: [
          'Financial system for award tracking and payment processing',
          'IRS API for 501(c)(3) status verification',
          'Document management for application archives and reporting',
        ],
        mongoDBConsiderations: [
          'Index on {grantCategory: 1, status: 1} for application pipeline by category',
          'Index on {amountRequested: -1} for funding analysis',
          'Index on {organizationName: 1} for applicant history queries',
          'Aggregation pipeline for award distribution analysis by category, geography, organization type',
        ],
      },
      seo: {
        metaTitle: 'Grant Application Form Template | NetPad',
        metaDescription: 'Free grant application template for government funders. Collect standardized proposals with budgets, timelines, and organizational capacity for objective review.',
        keywords: ['grant application form', 'funding application', 'community grant', 'nonprofit grant', 'government grant'],
        ogDescription: 'Fund community impact, not just good writing. This template standardizes grant applications for objective evaluation and outcome tracking.',
      },
      socialProofAngles: [
        'Objective grant evaluation',
        'Better funding decisions',
        'Outcome tracking from award to completion',
        'Streamlined review process',
      ],
    },
  }),
];
