/**
 * Legal & Compliance Form Templates
 *
 * Templates for NDAs, contract reviews, compliance audits,
 * and legal documentation.
 */

import { FormTemplate } from '@/types/formTemplate';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  currencyField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  addressField,
  signatureField,
  fileField,
} from '../helpers';

export const legalComplianceTemplates: FormTemplate[] = [
  // 1. NDA Agreement Form
  createTemplate({
    id: 'nda-agreement',
    name: 'NDA Agreement Form',
    shortDescription: 'Non-disclosure agreement submission',
    fullDescription: 'Collect signatures for mutual or one-way non-disclosure agreements. Captures party information and specific terms acknowledgment.',
    category: 'legal-compliance',
    icon: 'FileKey',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 1,
    tags: ['nda', 'confidentiality', 'agreement', 'legal'],
    useCases: [
      'Vendor NDAs',
      'Employee confidentiality',
      'Partnership agreements',
      'Consultant contracts',
    ],
    features: [
      'Party information',
      'Confidential matter definition',
      'Terms acknowledgment',
      'Digital signature',
    ],
    fieldConfigs: [
      sectionHeader('type', 'Agreement Type'),
      selectField('ndaType', 'Type of NDA', [
        'Mutual (Both parties share confidential information)',
        'One-Way (Only disclosing party shares)',
      ], { required: true }),
      sectionHeader('disclosing', 'Disclosing Party'),
      textField('disclosingPartyName', 'Company/Individual Name', { required: true }),
      textField('disclosingPartyContact', 'Contact Person', { required: true }),
      emailField('disclosingPartyEmail', 'Email Address', { required: true }),
      addressField('disclosingPartyAddress', 'Address'),
      sectionHeader('receiving', 'Receiving Party'),
      textField('receivingPartyName', 'Company/Individual Name', { required: true }),
      textField('receivingPartyContact', 'Contact Person', { required: true }),
      emailField('receivingPartyEmail', 'Email Address', { required: true }),
      addressField('receivingPartyAddress', 'Address'),
      sectionHeader('terms', 'Agreement Terms'),
      textareaField('confidentialMatter', 'Description of Confidential Information', {
        required: true,
        placeholder: 'Describe the nature of confidential information being disclosed...',
      }),
      textareaField('purposeOfDisclosure', 'Purpose of Disclosure', {
        required: true,
        placeholder: 'Explain why this information is being shared...',
      }),
      selectField('duration', 'Duration of Confidentiality Obligation', [
        '1 year',
        '2 years',
        '3 years',
        '5 years',
        'Indefinite',
      ], { required: true }),
      dateField('effectiveDate', 'Effective Date', { required: true }),
      sectionHeader('exclusions', 'Exclusions'),
      multiSelectField('standardExclusions', 'Standard Exclusions Apply', [
        'Information already known to receiving party',
        'Information in public domain',
        'Information independently developed',
        'Information disclosed by third party without restriction',
      ]),
      textareaField('additionalExclusions', 'Additional Exclusions (if any)'),
      sectionHeader('acknowledgments', 'Acknowledgments'),
      yesNoField('ackReadTerms', 'I have read and understood all terms of this NDA', { required: true }),
      yesNoField('ackAuthority', 'I have authority to sign on behalf of my organization', { required: true }),
      yesNoField('ackConsequences', 'I understand the consequences of breaching this agreement', { required: true }),
      sectionHeader('signature', 'Signature'),
      textField('signerName', 'Printed Name', { required: true }),
      textField('signerTitle', 'Title', { required: true }),
      signatureField('signature', 'Signature', { required: true }),
      dateField('signatureDate', 'Date', { required: true }),
    ],
  }),

  // 2. Legal Consultation Request
  createTemplate({
    id: 'legal-consultation-request',
    name: 'Legal Consultation Request',
    shortDescription: 'Request a legal consultation',
    fullDescription: 'Allow clients to request legal consultations. Captures case details and urgency for proper attorney matching and scheduling.',
    category: 'legal-compliance',
    icon: 'Scale',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 2,
    tags: ['legal', 'consultation', 'attorney', 'lawyer'],
    useCases: [
      'Initial consultations',
      'Legal advice requests',
      'Case evaluations',
      'Attorney referrals',
    ],
    features: [
      'Case type selection',
      'Detailed matter description',
      'Urgency assessment',
      'Contact preferences',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      addressField('address', 'Address'),
      sectionHeader('matter', 'Legal Matter'),
      selectField('practiceArea', 'Area of Law', [
        'Business/Corporate',
        'Contract Law',
        'Employment Law',
        'Intellectual Property',
        'Real Estate',
        'Family Law',
        'Criminal Defense',
        'Personal Injury',
        'Immigration',
        'Estate Planning',
        'Tax Law',
        'Other',
      ], { required: true }),
      selectField('clientType', 'I am a', [
        'Individual',
        'Small Business',
        'Corporation',
        'Non-Profit',
        'Government Entity',
      ], { required: true }),
      textareaField('matterDescription', 'Describe Your Legal Matter', {
        required: true,
        placeholder: 'Please provide details about your legal issue or question...',
        validation: { minLength: 50 },
      }),
      selectField('urgency', 'Urgency Level', [
        'Emergency - Immediate attention needed',
        'Urgent - Need response within 24-48 hours',
        'Standard - Within 1 week',
        'Planning ahead - No immediate deadline',
      ], { required: true }),
      dateField('relevantDeadline', 'Any Relevant Deadlines (if applicable)'),
      sectionHeader('history', 'Relevant History'),
      yesNoField('previousAttorney', 'Have you worked with an attorney on this matter before?'),
      textareaField('previousAttorneyDetails', 'If yes, please provide details', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'previousAttorney', operator: 'isTrue' }],
        },
      }),
      yesNoField('pendingLitigation', 'Is there any pending litigation?'),
      yesNoField('opposingParty', 'Is there an opposing party involved?'),
      textField('opposingPartyName', 'Opposing Party Name (if known)', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'opposingParty', operator: 'isTrue' }],
        },
      }),
      sectionHeader('preferences', 'Consultation Preferences'),
      selectField('consultationType', 'Preferred Consultation Type', [
        'In-Person',
        'Phone',
        'Video Conference',
        'No Preference',
      ]),
      multiSelectField('availability', 'Availability', [
        'Weekday mornings',
        'Weekday afternoons',
        'Weekday evenings',
        'Weekends',
      ]),
      selectField('referralSource', 'How did you hear about us?', [
        'Search Engine',
        'Referral',
        'Bar Association',
        'Social Media',
        'Advertisement',
        'Previous Client',
        'Other',
      ]),
      fileField('documents', 'Relevant Documents (optional)', {
        validation: { multiple: true, maxFiles: 5 },
      }),
    ],
  }),

  // 3. Data Subject Access Request (DSAR)
  createTemplate({
    id: 'dsar-request',
    name: 'Data Subject Access Request',
    shortDescription: 'GDPR/CCPA data access request',
    fullDescription: 'Enable individuals to submit data subject access requests under GDPR, CCPA, or other privacy regulations. Captures identity verification and request specifics.',
    category: 'legal-compliance',
    icon: 'UserCheck',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 3,
    tags: ['gdpr', 'ccpa', 'privacy', 'dsar', 'data access'],
    useCases: [
      'GDPR compliance',
      'CCPA requests',
      'Privacy rights',
      'Data portability',
    ],
    features: [
      'Identity verification',
      'Request type selection',
      'Specific data identification',
      'Response preferences',
    ],
    fieldConfigs: [
      sectionHeader('identity', 'Identity Verification'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number'),
      addressField('address', 'Mailing Address'),
      dateField('dateOfBirth', 'Date of Birth (for verification)'),
      textField('accountId', 'Account ID/Username (if applicable)'),
      sectionHeader('verification', 'Additional Verification'),
      selectField('verificationType', 'How would you like to verify your identity?', [
        'Email verification',
        'Phone verification',
        'Government ID upload',
        'Answering security questions',
      ], { required: true }),
      fileField('identityDoc', 'Upload Government-Issued ID (if selected above)', {
        validation: { allowedTypes: ['image/*', 'application/pdf'] },
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'verificationType', operator: 'equals', value: 'Government ID upload' }],
        },
      }),
      sectionHeader('request', 'Your Request'),
      selectField('regulation', 'Under which regulation are you making this request?', [
        'GDPR (EU General Data Protection Regulation)',
        'CCPA (California Consumer Privacy Act)',
        'Other privacy regulation',
        'Not sure',
      ], { required: true }),
      multiSelectField('requestType', 'Type of Request (select all that apply)', [
        'Access - Provide a copy of my personal data',
        'Rectification - Correct inaccurate data',
        'Deletion - Delete my personal data',
        'Portability - Provide data in portable format',
        'Restriction - Restrict processing of my data',
        'Object - Object to processing of my data',
        'Opt-out of sale - Do not sell my data (CCPA)',
      ], { required: true }),
      textareaField('specificData', 'Specific Data Requested (if known)', {
        placeholder: 'Describe what specific information you are requesting...',
      }),
      textareaField('additionalDetails', 'Additional Details or Context'),
      sectionHeader('response', 'Response Preferences'),
      selectField('responseFormat', 'Preferred Response Format', [
        'Email (encrypted)',
        'Physical mail',
        'Secure download portal',
        'No preference',
      ]),
      selectField('dataFormat', 'Preferred Data Format (for access/portability requests)', [
        'PDF',
        'CSV',
        'JSON',
        'No preference',
      ]),
      sectionHeader('acknowledgment', 'Acknowledgment'),
      yesNoField('ackAccurate', 'I confirm that the information provided is accurate', { required: true }),
      yesNoField('ackAuthorized', 'I confirm I am the data subject or authorized to act on their behalf', { required: true }),
      yesNoField('ackUnderstand', 'I understand my request will be processed within the legally required timeframe', { required: true }),
    ],
  }),

  // 4. Compliance Audit Checklist
  createTemplate({
    id: 'compliance-audit',
    name: 'Compliance Audit Checklist',
    shortDescription: 'Internal compliance audit form',
    fullDescription: 'Conduct internal compliance audits and assessments. Documents compliance status across various regulatory requirements.',
    category: 'legal-compliance',
    icon: 'ClipboardCheck',
    complexity: 'advanced',
    estimatedTime: 25,
    displayOrder: 4,
    tags: ['compliance', 'audit', 'checklist', 'regulatory'],
    useCases: [
      'Internal audits',
      'Compliance assessments',
      'Pre-audit preparation',
      'Risk management',
    ],
    features: [
      'Multi-area assessment',
      'Evidence documentation',
      'Gap identification',
      'Action item tracking',
    ],
    fieldConfigs: [
      sectionHeader('audit', 'Audit Information'),
      textField('auditTitle', 'Audit Title', { required: true }),
      selectField('auditType', 'Audit Type', [
        'Internal Audit',
        'Pre-external Audit',
        'Periodic Review',
        'Incident Response',
        'New Regulation Assessment',
      ], { required: true }),
      textField('auditorName', 'Auditor Name', { required: true }),
      dateField('auditDate', 'Audit Date', { required: true }),
      textField('department', 'Department/Area Being Audited', { required: true }),
      sectionHeader('dataProtection', 'Data Protection & Privacy'),
      selectField('privacyPolicyStatus', 'Privacy Policy Up to Date', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('dataInventory', 'Data Inventory Maintained', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('consentManagement', 'Consent Management Implemented', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('dataRetention', 'Data Retention Policy Followed', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      textareaField('dataProtectionNotes', 'Data Protection Notes/Findings'),
      sectionHeader('security', 'Information Security'),
      selectField('accessControls', 'Access Controls in Place', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('encryption', 'Encryption Implemented', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('incidentResponse', 'Incident Response Plan', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('securityTraining', 'Security Training Completed', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      textareaField('securityNotes', 'Information Security Notes/Findings'),
      sectionHeader('policies', 'Policies & Procedures'),
      selectField('policiesDocumented', 'Policies Documented', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('policiesAccessible', 'Policies Accessible to Staff', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('policiesReviewed', 'Policies Reviewed Annually', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      textareaField('policyNotes', 'Policy Notes/Findings'),
      sectionHeader('training', 'Training & Awareness'),
      selectField('complianceTraining', 'Compliance Training Completed', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      selectField('trainingRecords', 'Training Records Maintained', ['Compliant', 'Partially Compliant', 'Non-Compliant', 'N/A'], { required: true }),
      textareaField('trainingNotes', 'Training Notes/Findings'),
      sectionHeader('summary', 'Audit Summary'),
      selectField('overallCompliance', 'Overall Compliance Rating', [
        'Fully Compliant',
        'Substantially Compliant',
        'Partially Compliant',
        'Non-Compliant',
      ], { required: true }),
      textareaField('keyFindings', 'Key Findings', { required: true }),
      textareaField('recommendations', 'Recommendations', { required: true }),
      textareaField('actionItems', 'Action Items'),
      dateField('followUpDate', 'Follow-up Date'),
      fileField('evidence', 'Supporting Evidence', {
        validation: { multiple: true, maxFiles: 10 },
      }),
    ],
  }),

  // 5. Incident Disclosure Form
  createTemplate({
    id: 'incident-disclosure',
    name: 'Incident Disclosure Form',
    shortDescription: 'Report compliance or security incidents',
    fullDescription: 'Document and report compliance incidents, data breaches, or policy violations. Enables proper incident tracking and response.',
    category: 'legal-compliance',
    icon: 'AlertCircle',
    complexity: 'moderate',
    estimatedTime: 10,
    displayOrder: 5,
    tags: ['incident', 'breach', 'disclosure', 'security', 'compliance'],
    useCases: [
      'Data breach reporting',
      'Compliance violations',
      'Security incidents',
      'Policy breaches',
    ],
    features: [
      'Incident categorization',
      'Impact assessment',
      'Timeline documentation',
      'Response tracking',
    ],
    fieldConfigs: [
      sectionHeader('reporter', 'Reporter Information'),
      textField('reporterName', 'Your Name', { required: true }),
      textField('reporterDepartment', 'Department', { required: true }),
      emailField('reporterEmail', 'Email', { required: true }),
      phoneField('reporterPhone', 'Phone', { required: true }),
      dateField('reportDate', 'Report Date', { required: true }),
      sectionHeader('incident', 'Incident Details'),
      selectField('incidentType', 'Type of Incident', [
        'Data Breach - Personal Data',
        'Data Breach - Business Data',
        'Security Incident',
        'Policy Violation',
        'Regulatory Non-Compliance',
        'Fraud/Financial',
        'Safety Incident',
        'Other',
      ], { required: true }),
      dateField('incidentDate', 'Date of Incident', { required: true }),
      textField('incidentTime', 'Time of Incident (if known)'),
      dateField('discoveryDate', 'Date Discovered', { required: true }),
      textField('incidentLocation', 'Location/System Affected', { required: true }),
      textareaField('incidentDescription', 'Detailed Description of Incident', {
        required: true,
        placeholder: 'Describe what happened, how it was discovered, and any immediate actions taken...',
        validation: { minLength: 100 },
      }),
      sectionHeader('impact', 'Impact Assessment'),
      selectField('severity', 'Severity Level', [
        'Critical - Major impact, immediate action required',
        'High - Significant impact, urgent action needed',
        'Medium - Moderate impact, action needed',
        'Low - Minor impact, routine handling',
      ], { required: true }),
      yesNoField('dataAffected', 'Was personal/sensitive data affected?', { required: true }),
      textareaField('dataTypes', 'Types of data affected', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'dataAffected', operator: 'isTrue' }],
        },
      }),
      numberField('individualsAffected', 'Estimated number of individuals affected'),
      yesNoField('customersAffected', 'Were customers/external parties affected?'),
      yesNoField('regulatoryReporting', 'Does this require regulatory reporting?'),
      sectionHeader('response', 'Response Actions'),
      textareaField('immediateActions', 'Immediate Actions Taken', {
        required: true,
        placeholder: 'Describe containment measures and immediate response...',
      }),
      textareaField('additionalActions', 'Additional Actions Required'),
      yesNoField('managementNotified', 'Has management been notified?', { required: true }),
      yesNoField('legalNotified', 'Has legal/compliance been notified?'),
      yesNoField('itNotified', 'Has IT/Security been notified?'),
      sectionHeader('evidence', 'Documentation'),
      fileField('supportingDocs', 'Supporting Documentation', {
        validation: { multiple: true, maxFiles: 10 },
      }),
      textareaField('additionalInfo', 'Additional Information'),
    ],
  }),

  // 6. Contract Review Request
  createTemplate({
    id: 'contract-review-request',
    name: 'Contract Review Request',
    shortDescription: 'Request legal review of contracts',
    fullDescription: 'Submit contracts for legal review. Captures contract details, key terms, and specific areas of concern for efficient legal review.',
    category: 'legal-compliance',
    icon: 'FileSearch',
    complexity: 'moderate',
    estimatedTime: 8,
    displayOrder: 6,
    tags: ['contract', 'review', 'legal', 'agreement'],
    useCases: [
      'Vendor contracts',
      'Customer agreements',
      'Partnership contracts',
      'Employment agreements',
    ],
    features: [
      'Contract classification',
      'Key terms summary',
      'Concern areas',
      'Urgency tracking',
    ],
    fieldConfigs: [
      sectionHeader('requester', 'Requester Information'),
      textField('requesterName', 'Your Name', { required: true }),
      textField('department', 'Department', { required: true }),
      emailField('email', 'Email', { required: true }),
      phoneField('phone', 'Phone'),
      sectionHeader('contract', 'Contract Information'),
      textField('contractTitle', 'Contract Title/Name', { required: true }),
      selectField('contractType', 'Type of Contract', [
        'Vendor/Supplier Agreement',
        'Customer Agreement',
        'Service Agreement',
        'License Agreement',
        'NDA/Confidentiality',
        'Employment Contract',
        'Partnership Agreement',
        'Lease Agreement',
        'Amendment/Addendum',
        'Other',
      ], { required: true }),
      textField('counterpartyName', 'Counterparty Name', { required: true }),
      selectField('initiator', 'Who initiated this contract?', [
        'Our company (using our template)',
        'Counterparty (their template)',
        'Third party template',
        'Negotiated from scratch',
      ], { required: true }),
      currencyField('contractValue', 'Contract Value (if applicable)'),
      selectField('contractTerm', 'Contract Term', [
        'One-time transaction',
        'Less than 1 year',
        '1-2 years',
        '2-5 years',
        '5+ years',
        'Ongoing/Perpetual',
      ]),
      dateField('targetSignDate', 'Target Signature Date'),
      sectionHeader('review', 'Review Details'),
      selectField('reviewUrgency', 'Review Urgency', [
        'Critical - Same day',
        'Urgent - Within 24 hours',
        'Standard - Within 3-5 days',
        'Low - Within 1-2 weeks',
      ], { required: true }),
      selectField('reviewType', 'Type of Review Needed', [
        'Full review',
        'Quick review of key terms only',
        'Review of specific sections',
        'Comparison to previous version',
        'Renewal review',
      ], { required: true }),
      multiSelectField('areasOfConcern', 'Areas of Specific Concern', [
        'Payment terms',
        'Liability/Indemnification',
        'Intellectual property',
        'Confidentiality',
        'Termination rights',
        'Data privacy',
        'Compliance requirements',
        'Insurance requirements',
        'Warranty/Guarantees',
        'Governing law/Jurisdiction',
      ]),
      textareaField('specificConcerns', 'Specific Concerns or Questions', {
        placeholder: 'Describe any specific issues you\'d like reviewed...',
      }),
      textareaField('backgroundContext', 'Background/Context', {
        placeholder: 'Provide any relevant context about this contract or relationship...',
      }),
      sectionHeader('documents', 'Documents'),
      fileField('contractDocument', 'Contract Document', {
        required: true,
        validation: { allowedTypes: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] },
      }),
      fileField('supportingDocs', 'Supporting Documents (RFP, previous versions, etc.)', {
        validation: { multiple: true, maxFiles: 5 },
      }),
    ],
  }),
];
