/**
 * Marketing & Research Form Templates
 *
 * Templates for event registration, market research surveys, NPS surveys,
 * and marketing campaign lead capture.
 */

import { FormTemplate, EnhancedTemplateContent } from '@/types/formTemplate';
import {
  createTemplate,
  textField,
  emailField,
  phoneField,
  selectField,
  textareaField,
  dateField,
  numberField,
  yesNoField,
  sectionHeader,
  multiSelectField,
  ratingField,
  scaleField,
} from '../helpers';

export const marketingResearchTemplates: FormTemplate[] = [
  // 1. Event Registration Form
  createTemplate({
    id: 'event-registration',
    name: 'Event Registration Form',
    shortDescription: 'Register attendees for events and webinars',
    fullDescription: 'A comprehensive event registration form for conferences, webinars, and workshops. Captures attendee information, session preferences, and dietary requirements.',
    category: 'marketing-research',
    icon: 'CalendarCheck',
    complexity: 'moderate',
    estimatedTime: 5,
    isFeatured: true,
    displayOrder: 1,
    tags: ['event', 'registration', 'conference', 'webinar', 'workshop'],
    useCases: [
      'Conference registration',
      'Webinar signups',
      'Workshop enrollment',
      'Meetup RSVPs',
    ],
    features: [
      'Attendee information',
      'Session/track selection',
      'Dietary requirements',
      'Networking preferences',
    ],
    fieldConfigs: [
      sectionHeader('attendee', 'Attendee Information'),
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number'),
      textField('company', 'Company/Organization', { fieldWidth: 'half' }),
      textField('jobTitle', 'Job Title', { fieldWidth: 'half' }),
      sectionHeader('event', 'Event Details'),
      selectField('ticketType', 'Ticket Type', [
        'General Admission',
        'VIP',
        'Early Bird',
        'Student',
        'Speaker',
        'Sponsor',
      ], { required: true }),
      multiSelectField('sessions', 'Sessions to Attend (select all that apply)', [
        'Keynote Session',
        'Workshop A - Beginner Track',
        'Workshop B - Advanced Track',
        'Panel Discussion',
        'Networking Lunch',
        'Closing Session',
      ]),
      sectionHeader('requirements', 'Special Requirements'),
      selectField('dietaryRequirements', 'Dietary Requirements', [
        'None',
        'Vegetarian',
        'Vegan',
        'Gluten-Free',
        'Kosher',
        'Halal',
        'Other',
      ]),
      textField('dietaryOther', 'Other Dietary Requirements', {
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'dietaryRequirements', operator: 'equals', value: 'Other' }],
        },
      }),
      textareaField('accessibilityNeeds', 'Accessibility Needs'),
      sectionHeader('networking', 'Networking'),
      yesNoField('interestedInNetworking', 'Interested in networking opportunities?'),
      textareaField('networkingGoals', 'What are you hoping to achieve at this event?'),
      selectField('howHeard', 'How did you hear about this event?', [
        'Email',
        'Social Media',
        'Colleague Referral',
        'Website',
        'Search Engine',
        'Other',
      ]),
    ],
    enhanced: {
      headline: 'Fill Every Seat with Qualified Attendees',
      subheadline: 'Capture attendee details, session preferences, and requirements in one form—so your events run smoothly and participants get exactly what they expect.',
      longDescription: {
        opening: 'Event planning is stressful enough without registration chaos. Spreadsheet signups lead to missing dietary info, overbooking sessions, and last-minute scrambles for accessibility accommodations. Attendees arrive expecting one thing and experience another.',
        solution: 'This template captures everything for smooth event execution: Ticket Type for capacity planning, Session Selection for track management, Dietary Requirements with conditional other field for catering, and Accessibility Needs for venue preparation. Networking preferences help structure activities. Attribution tracking shows which channels drive registrations.',
        outcome: 'Events run smoothly because you planned with complete data. Sessions are appropriately sized, catering is accurate, and accessibility is handled proactively. Attendees get personalized experiences based on their stated goals. Marketing knows which channels to invest in.',
      },
      useCases: [
        {
          title: 'Industry Conference',
          icon: '🎤',
          industry: 'Any',
          scenario: 'A multi-day conference with multiple tracks, meals, and networking events. Attendees need to choose sessions, dietary options, and schedule.',
          painPoint: 'Session rooms over or under capacity; catering counts wrong; attendees missed announcements.',
          keyFields: ['Sessions to Attend', 'Ticket Type', 'Dietary Requirements', 'Networking Goals'],
          exampleOrganization: 'An industry association hosting an annual 500-person conference.',
        },
        {
          title: 'Product Launch Event',
          icon: '🚀',
          industry: 'Technology',
          scenario: 'A company launches a new product with an exclusive event. Lead qualification happens at registration to identify VIPs.',
          painPoint: 'Sales doesn\'t know which registrants are high-value prospects vs. tire kickers.',
          keyFields: ['Company', 'Job Title', 'Ticket Type', 'How did you hear about this event?'],
          exampleOrganization: 'A tech company launching quarterly product updates to 200+ attendees.',
        },
        {
          title: 'Corporate Training Workshop',
          icon: '📚',
          industry: 'Professional Development',
          scenario: 'Internal or external training sessions require tracking who\'s attending, their current skill level, and accommodation needs.',
          painPoint: 'Training materials don\'t match attendee skill levels; no record of who attended.',
          keyFields: ['First Name', 'Last Name', 'Company', 'Sessions to Attend', 'Accessibility Needs'],
          exampleOrganization: 'A training company delivering workshops to 50+ companies annually.',
        },
        {
          title: 'Community Meetup',
          icon: '🍕',
          industry: 'Technology / Community',
          scenario: 'Regular meetups need simple registration with RSVP, dietary info for food ordering, and topic interests.',
          painPoint: 'Ordered too much or too little food; don\'t know what topics attendees want.',
          keyFields: ['Email', 'Dietary Requirements', 'Interested in Networking', 'Networking Goals'],
          exampleOrganization: 'A tech meetup hosting monthly events with 30-100 attendees.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Session Capacity Limits',
          description: 'Show remaining seats for each session. Auto-close options when capacity is reached.',
          difficulty: 'medium',
        },
        {
          title: 'Include Payment Integration',
          description: 'For paid events, integrate with Stripe or PayPal to collect registration fees at signup.',
          difficulty: 'advanced',
        },
        {
          title: 'Enable Group Registration',
          description: 'Add option to register multiple attendees from the same company in one submission.',
          fieldSuggestion: 'number',
          difficulty: 'medium',
        },
        {
          title: 'Add Promo Code Field',
          description: 'Allow discount codes for early birds, speakers, or partners. Validate codes in real-time.',
          fieldSuggestion: 'text',
          difficulty: 'medium',
        },
        {
          title: 'Create Badge PDF Generation',
          description: 'Auto-generate name badges as PDF from registration data for event check-in.',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-confirmation',
          title: 'Send Registration Confirmation',
          description: 'Email attendee with confirmation, calendar invite, session details, and event logistics.',
          trigger: 'On form submission',
          benefits: ['Immediate confirmation', 'Calendar integration'],
        },
        {
          workflowType: 'reminder-sequence',
          title: 'Send Event Reminders',
          description: 'Schedule reminders 1 week, 1 day, and 1 hour before the event with relevant details.',
          trigger: 'Scheduled based on event date',
          benefits: ['Reduced no-shows', 'Prepared attendees'],
        },
        {
          workflowType: 'capacity-management',
          title: 'Track Session Capacity',
          description: 'Update session counts in real-time. Alert organizers when sessions approach capacity.',
          trigger: 'On form submission',
          benefits: ['Capacity planning', 'No overbooking'],
        },
        {
          workflowType: 'check-in-system',
          title: 'Generate QR Check-in',
          description: 'Generate unique QR code for each attendee for fast event-day check-in.',
          trigger: 'On form submission',
          benefits: ['Fast check-in', 'Attendance tracking'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Sessions stored as array for flexible multi-track selection',
          'Dietary requirements with conditional \'other\' field handles all cases',
          'Attribution field (howHeard) enables marketing channel analysis',
        ],
        integrationHints: [
          'Webhook to event platform (Eventbrite, Hopin) for unified attendee management',
          'POST to calendar service (Google, Outlook) to send calendar invites',
          'Connect to email service for automated reminder sequences',
        ],
        mongoDBConsiderations: [
          'Index on {sessions: 1} for session capacity aggregation',
          'Index on {ticketType: 1} for ticket type reporting',
          'Index on {email: 1} for duplicate registration prevention',
        ],
      },
      seo: {
        metaTitle: 'Event Registration Form Template | NetPad',
        metaDescription: 'Free event registration form with session selection, dietary requirements, and attendee management. Fill every seat with qualified attendees.',
        keywords: [
          'event registration form',
          'conference registration',
          'webinar signup',
          'workshop registration',
          'event RSVP form',
          'attendee registration',
          'seminar registration',
        ],
        ogDescription: 'Stop the event planning chaos. This registration form captures sessions, dietary needs, and accessibility requirements—so your event runs smoothly.',
      },
      socialProofAngles: [
        'Smoother event operations',
        'Better attendee experiences',
        'Accurate catering and capacity planning',
        'Higher attendance rates',
      ],
    },
  }),

  // 2. Market Research Survey
  createTemplate({
    id: 'market-research-survey',
    name: 'Market Research Survey',
    shortDescription: 'Conduct comprehensive market research',
    fullDescription: 'Gather insights about market trends, customer preferences, and competitive landscape. Perfect for product development and market analysis.',
    category: 'marketing-research',
    icon: 'PieChart',
    complexity: 'moderate',
    estimatedTime: 8,
    isFeatured: true,
    displayOrder: 2,
    tags: ['research', 'survey', 'market', 'insights', 'analysis'],
    useCases: [
      'Product development research',
      'Market sizing',
      'Competitive analysis',
      'Customer insights',
    ],
    features: [
      'Demographic questions',
      'Behavioral analysis',
      'Preference mapping',
      'Open-ended feedback',
    ],
    fieldConfigs: [
      sectionHeader('demographics', 'About You'),
      selectField('ageRange', 'Age Range', [
        '18-24',
        '25-34',
        '35-44',
        '45-54',
        '55-64',
        '65+',
        'Prefer not to say',
      ], { required: true }),
      selectField('gender', 'Gender', [
        'Male',
        'Female',
        'Non-binary',
        'Prefer not to say',
      ]),
      selectField('income', 'Annual Household Income', [
        'Under $25,000',
        '$25,000 - $49,999',
        '$50,000 - $74,999',
        '$75,000 - $99,999',
        '$100,000 - $149,999',
        '$150,000+',
        'Prefer not to say',
      ]),
      selectField('employment', 'Employment Status', [
        'Employed full-time',
        'Employed part-time',
        'Self-employed',
        'Unemployed',
        'Student',
        'Retired',
      ]),
      selectField('industry', 'Industry', [
        'Technology',
        'Healthcare',
        'Finance',
        'Education',
        'Retail',
        'Manufacturing',
        'Government',
        'Other',
      ]),
      sectionHeader('behavior', 'Purchasing Behavior'),
      selectField('purchaseFrequency', 'How often do you purchase products in this category?', [
        'Weekly',
        'Monthly',
        'Quarterly',
        'Annually',
        'Rarely',
        'Never',
      ], { required: true }),
      selectField('primaryChannel', 'Where do you usually make purchases?', [
        'Online - Company website',
        'Online - Amazon/Marketplace',
        'In-store - Big box retailer',
        'In-store - Specialty store',
        'Direct from manufacturer',
        'Mix of online and in-store',
      ], { required: true }),
      multiSelectField('influencingFactors', 'What factors influence your purchasing decision?', [
        'Price',
        'Quality',
        'Brand reputation',
        'Reviews/Ratings',
        'Recommendations',
        'Convenience',
        'Sustainability',
        'Customer service',
      ]),
      sectionHeader('awareness', 'Brand Awareness'),
      multiSelectField('brandsAware', 'Which brands are you aware of?', [
        'Brand A',
        'Brand B',
        'Brand C',
        'Brand D',
        'None of these',
      ]),
      selectField('currentBrand', 'Which brand do you currently use most?', [
        'Brand A',
        'Brand B',
        'Brand C',
        'Brand D',
        'Other',
        'None',
      ]),
      ratingField('brandSatisfaction', 'Satisfaction with current brand'),
      sectionHeader('preferences', 'Product Preferences'),
      multiSelectField('importantFeatures', 'Which features are most important to you?', [
        'Feature 1',
        'Feature 2',
        'Feature 3',
        'Feature 4',
        'Feature 5',
      ]),
      scaleField('priceImportance', 'How important is price in your decision?', {
        validation: { min: 1, max: 5, lowLabel: 'Not important', highLabel: 'Very important' },
      }),
      selectField('willingToPay', 'How much would you be willing to pay for an ideal product?', [
        'Under $25',
        '$25 - $50',
        '$50 - $100',
        '$100 - $200',
        '$200+',
      ]),
      sectionHeader('feedback', 'Open Feedback'),
      textareaField('unmetNeeds', 'What needs are not being met by current products?'),
      textareaField('idealProduct', 'Describe your ideal product in this category'),
      yesNoField('participateFollowUp', 'Would you be interested in participating in follow-up research?'),
    ],
    enhanced: {
      headline: 'Make Product Decisions Based on Real Market Data',
      subheadline: 'Capture demographics, purchasing behavior, brand perceptions, and unmet needs—so product and marketing teams build on evidence instead of assumptions.',
      longDescription: {
        opening: 'Product decisions based on gut instinct are expensive gambles. Without market research, teams build features nobody wants, price incorrectly, and miss segments with high potential. Competitors with better market intelligence outmaneuver you.',
        solution: 'This template covers the complete market research framework: Demographics for segmentation, Purchasing Behavior for channel and frequency insights, Brand Awareness for competitive positioning, Feature Importance for prioritization, and Open Feedback for discovering unmet needs. Follow-up recruitment builds a research panel.',
        outcome: 'Product roadmaps align with market demand. Pricing reflects willingness to pay. Marketing targets segments most likely to convert. Competitive positioning is based on actual perception data. Opportunities emerge from systematically captured unmet needs.',
      },
      useCases: [
        {
          title: 'New Product Development',
          icon: '💡',
          industry: 'Any',
          scenario: 'Before investing in product development, you need to understand market size, customer preferences, and willingness to pay.',
          painPoint: 'Products launch to lukewarm reception because they don\'t match what customers actually want.',
          keyFields: ['Important Features', 'How much would you be willing to pay?', 'What needs are not being met?', 'Ideal Product Description'],
          exampleOrganization: 'A company validating a new product concept before committing development resources.',
        },
        {
          title: 'Competitive Analysis',
          icon: '🏆',
          industry: 'Any',
          scenario: 'You need to understand how your brand is perceived relative to competitors and where opportunities exist.',
          painPoint: 'Competitive positioning is based on assumptions rather than how customers actually perceive brands.',
          keyFields: ['Which brands are you aware of?', 'Which brand do you currently use?', 'Brand Satisfaction', 'What factors influence your decision?'],
          exampleOrganization: 'A brand repositioning based on actual competitive perception data.',
        },
        {
          title: 'Market Entry Research',
          icon: '🚪',
          industry: 'Any',
          scenario: 'Entering a new market segment requires understanding current behavior, needs, and competitive landscape.',
          painPoint: 'Market entry fails because customer behavior was different than expected.',
          keyFields: ['Age Range', 'Industry', 'Purchase Frequency', 'Primary Channel', 'Current Brand'],
          exampleOrganization: 'A company expanding into a new demographic or geographic segment.',
        },
        {
          title: 'Pricing Research',
          icon: '💰',
          industry: 'Any',
          scenario: 'Determining optimal pricing requires understanding price sensitivity, value perception, and competitive pricing.',
          painPoint: 'Pricing is too high (losing sales) or too low (leaving money on the table).',
          keyFields: ['Income', 'How important is price?', 'How much would you be willing to pay?', 'Value for money rating'],
          exampleOrganization: 'A company optimizing pricing strategy based on willingness-to-pay data.',
        },
      ],
      customizationTips: [
        {
          title: 'Customize Industry Options',
          description: 'Replace generic brand placeholders with actual brands in your category for real competitive insights.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Add Screening Questions',
          description: 'Add early questions to screen out respondents who don\'t match your target market.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Price Sensitivity Questions',
          description: 'Add Van Westendorp price sensitivity questions for detailed pricing analysis.',
          fieldSuggestion: 'number',
          difficulty: 'medium',
        },
        {
          title: 'Enable Conjoint Analysis',
          description: 'Add feature trade-off questions to understand relative importance of different attributes.',
          difficulty: 'advanced',
        },
        {
          title: 'Build Research Panel',
          description: 'Use follow-up consent to build a research panel for ongoing studies.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'data-export',
          title: 'Export to Analytics',
          description: 'Push responses to analytics platform for visualization and statistical analysis.',
          trigger: 'On form submission',
          benefits: ['Real-time insights', 'Professional analysis'],
        },
        {
          workflowType: 'panel-recruitment',
          title: 'Add to Research Panel',
          description: 'When follow-up consent is given, add respondent to research panel for future studies.',
          trigger: 'On form submission where participateFollowUp = true',
          benefits: ['Growing research panel', 'Longitudinal studies'],
        },
        {
          workflowType: 'incentive-fulfillment',
          title: 'Send Survey Incentive',
          description: 'If offering incentives, automatically send gift card or enter respondent in prize drawing.',
          trigger: 'On form submission',
          benefits: ['Higher completion rates', 'Better data quality'],
        },
        {
          workflowType: 'summary-report',
          title: 'Generate Summary Report',
          description: 'Weekly automated summary of key metrics and notable trends for stakeholders.',
          trigger: 'Scheduled weekly',
          benefits: ['Stakeholder updates', 'Trend monitoring'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Demographic fields use consistent enums for cross-survey comparison',
          'Multi-select fields stored as arrays for flexible analysis',
          'Open-ended fields enable qualitative analysis alongside quantitative',
        ],
        integrationHints: [
          'Webhook to research platform (Qualtrics, SurveyMonkey) for advanced analysis',
          'POST to BI tool (Tableau, Looker) for visualization',
          'Connect to incentive platform (Tremendous) for automated gift card delivery',
        ],
        mongoDBConsiderations: [
          'Index on {ageRange: 1, income: 1} for demographic segmentation',
          'Index on {currentBrand: 1} for competitive analysis queries',
          'Text index on open-ended fields for qualitative theme analysis',
        ],
      },
      seo: {
        metaTitle: 'Market Research Survey Template | NetPad',
        metaDescription: 'Free market research survey with demographics, purchasing behavior, and brand perception. Make product decisions based on real market data.',
        keywords: [
          'market research survey',
          'consumer research form',
          'market analysis survey',
          'customer insights survey',
          'competitive research form',
          'product research survey',
          'brand perception survey',
        ],
        ogDescription: 'Stop guessing what the market wants. This survey captures demographics, behavior, and preferences—so you can build products that sell.',
      },
      socialProofAngles: [
        'Data-driven product decisions',
        'Better competitive positioning',
        'Optimized pricing strategies',
        'Reduced product development risk',
      ],
    },
  }),

  // 3. NPS Survey
  createTemplate({
    id: 'nps-survey',
    name: 'NPS Survey',
    shortDescription: 'Net Promoter Score measurement survey',
    fullDescription: 'A focused Net Promoter Score survey to measure customer loyalty. Includes the core NPS question with follow-up questions for deeper insights.',
    category: 'marketing-research',
    icon: 'TrendingUp',
    complexity: 'simple',
    estimatedTime: 2,
    isFeatured: true,
    displayOrder: 3,
    tags: ['nps', 'loyalty', 'promoter', 'survey', 'feedback'],
    useCases: [
      'Customer loyalty tracking',
      'Quarterly NPS measurement',
      'Post-interaction surveys',
      'Brand health monitoring',
    ],
    features: [
      'Standard NPS question',
      'Follow-up reasoning',
      'Improvement suggestions',
      'Contact permission',
    ],
    fieldConfigs: [
      scaleField('npsScore', 'On a scale of 0-10, how likely are you to recommend us to a friend or colleague?', {
        required: true,
        validation: { min: 0, max: 10, lowLabel: 'Not at all likely', highLabel: 'Extremely likely' },
      }),
      textareaField('npsReason', 'What is the primary reason for your score?', {
        required: true,
        placeholder: 'Please share why you gave this rating...',
      }),
      textareaField('improvement', 'What could we do to improve your experience?'),
      textareaField('whatWeLoveDoing', 'What do we do well that we should keep doing?'),
      yesNoField('canContact', 'May we contact you to discuss your feedback?'),
      emailField('email', 'Email Address (optional)', {
        required: false,
        conditionalLogic: {
          action: 'show',
          logicType: 'all',
          conditions: [{ field: 'canContact', operator: 'isTrue' }],
        },
      }),
    ],
    enhanced: {
      headline: 'Track Customer Loyalty with the Industry Standard',
      subheadline: 'A focused NPS survey that measures recommendation likelihood and captures the reasoning behind scores—the essential metric for customer health.',
      longDescription: {
        opening: 'NPS is the most widely used customer loyalty metric, but many implementations fail. Surveys are too long, the follow-up question is missing, and results never drive action. Teams track NPS without understanding why scores change.',
        solution: 'This template implements NPS correctly: the standard 0-10 likelihood question, required reasoning capture, improvement suggestions, and what to keep doing. Conditional email capture enables follow-up with detractors. The focused length maximizes completion rates.',
        outcome: 'Track customer loyalty over time with a benchmarkable metric. Understand the "why" behind scores, not just the number. Identify detractors before they churn. Discover what promoters love so you can double down. Create a closed-loop feedback system.',
      },
      useCases: [
        {
          title: 'Quarterly Pulse Check',
          icon: '📊',
          industry: 'Any',
          scenario: 'Measure customer health quarterly across your entire customer base. Track NPS trends over time.',
          painPoint: 'No systematic way to measure customer loyalty; churn surprises leadership.',
          keyFields: ['NPS Score (0-10)', 'Primary reason for score', 'What could we do to improve?'],
          exampleOrganization: 'A B2B company sending quarterly NPS surveys to 1,000+ customers.',
        },
        {
          title: 'Post-Interaction Survey',
          icon: '🎯',
          industry: 'Customer Service',
          scenario: 'Measure satisfaction after specific interactions—support tickets, onboarding, or purchases.',
          painPoint: 'Interaction quality varies; no way to identify patterns or coach staff.',
          keyFields: ['NPS Score', 'Primary reason for score', 'May we contact you?'],
          exampleOrganization: 'A service company surveying customers after each support interaction.',
        },
        {
          title: 'Account Health Monitoring',
          icon: '💚',
          industry: 'SaaS / Technology',
          scenario: 'Customer Success teams track account health to identify expansion opportunities and churn risks.',
          painPoint: 'CSMs don\'t know which accounts are at risk until renewal conversation.',
          keyFields: ['NPS Score', 'What could we do to improve?', 'What do we do well?'],
          exampleOrganization: 'A SaaS company where Customer Success manages 200+ accounts.',
        },
        {
          title: 'Product Launch Feedback',
          icon: '🚀',
          industry: 'Any',
          scenario: 'Measure reception after launching new features or products. Quick feedback enables iteration.',
          painPoint: 'Product launches with no structured way to measure reception.',
          keyFields: ['NPS Score', 'Primary reason for score', 'What could we improve?'],
          exampleOrganization: 'A product team measuring reception of new features.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Segment Identification',
          description: 'Include hidden fields for customer segment, plan tier, or tenure for cohort analysis.',
          fieldSuggestion: 'hidden',
          difficulty: 'easy',
        },
        {
          title: 'Include Product/Feature Selection',
          description: 'Ask which product or feature the NPS relates to for product-specific insights.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Add Competitive NPS',
          description: 'Ask NPS for a competitor to benchmark your score against alternatives.',
          fieldSuggestion: 'scale',
          difficulty: 'easy',
        },
        {
          title: 'Build Trend Dashboard',
          description: 'Create a real-time dashboard showing NPS trends by segment over time.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Closed-Loop Action',
          description: 'Auto-create support tickets for detractors; send thank-you to promoters.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'detractor-alert',
          title: 'Alert on Low Scores',
          description: 'Immediately notify account manager when NPS is 6 or below (detractor). Include full response.',
          trigger: 'On form submission where npsScore <= 6',
          benefits: ['Rapid intervention', 'Churn prevention'],
        },
        {
          workflowType: 'promoter-engagement',
          title: 'Thank Promoters',
          description: 'Send personalized thank-you to promoters (9-10) with referral program or review invitation.',
          trigger: 'On form submission where npsScore >= 9',
          benefits: ['Referral generation', 'Review collection'],
        },
        {
          workflowType: 'crm-update',
          title: 'Update Account Record',
          description: 'Push NPS score to CRM for account health tracking and renewal forecasting.',
          trigger: 'On form submission',
          benefits: ['Account health visibility', 'Data-driven renewals'],
        },
        {
          workflowType: 'weekly-digest',
          title: 'Send Weekly NPS Report',
          description: 'Compile weekly NPS summary with score, trend, and notable feedback for leadership.',
          trigger: 'Scheduled weekly',
          benefits: ['Executive visibility', 'Trend awareness'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'NPS score as integer (0-10) for accurate mathematical calculations',
          'Reason field captures qualitative context for the score',
          'Conditional email field only shown when follow-up consented',
        ],
        integrationHints: [
          'Webhook to CRM to update customer record with latest NPS',
          'POST to analytics platform for trend visualization',
          'Connect to support system to create tickets for detractors',
        ],
        mongoDBConsiderations: [
          'Index on {npsScore: 1, createdAt: -1} for trend analysis',
          'Aggregation pipeline for calculating NPS percentage (promoters - detractors)',
          'Text index on reason field for theme analysis',
        ],
      },
      seo: {
        metaTitle: 'NPS Survey Template | NetPad',
        metaDescription: 'Free Net Promoter Score survey with score capture, reasoning, and improvement suggestions. Track customer loyalty with the industry standard metric.',
        keywords: [
          'NPS survey',
          'net promoter score',
          'NPS template',
          'customer loyalty survey',
          'NPS form',
          'promoter score survey',
          'customer satisfaction NPS',
        ],
        ogDescription: 'Track customer loyalty the right way. This NPS survey captures the score and the reasoning—so you can act on feedback, not just measure it.',
      },
      socialProofAngles: [
        'Improved customer retention',
        'Early churn identification',
        'More customer referrals',
        'Data-driven customer success',
      ],
    },
  }),

  // 4. Email Newsletter Signup
  createTemplate({
    id: 'email-signup',
    name: 'Email Newsletter Signup',
    shortDescription: 'Simple email list signup form',
    fullDescription: 'A clean, conversion-optimized newsletter signup form. Captures email and preferences for targeted content delivery.',
    category: 'marketing-research',
    icon: 'Mail',
    complexity: 'simple',
    estimatedTime: 1,
    displayOrder: 4,
    tags: ['email', 'newsletter', 'signup', 'subscription', 'lead'],
    useCases: [
      'Newsletter subscriptions',
      'Lead capture',
      'Content updates',
      'Marketing list building',
    ],
    features: [
      'Email capture',
      'Interest selection',
      'Frequency preference',
      'GDPR compliance',
    ],
    fieldConfigs: [
      emailField('email', 'Email Address', { required: true }),
      textField('firstName', 'First Name'),
      multiSelectField('interests', 'What topics interest you?', [
        'Product Updates',
        'Industry News',
        'Tips & Tutorials',
        'Company News',
        'Promotions & Offers',
      ]),
      selectField('frequency', 'How often would you like to hear from us?', [
        'Daily',
        'Weekly',
        'Monthly',
        'Only important updates',
      ]),
      yesNoField('consent', 'I agree to receive marketing emails', {
        required: true,
        validation: { displayStyle: 'checkbox' },
      }),
    ],
    enhanced: {
      headline: 'Build Your Email List with Engaged Subscribers',
      subheadline: 'A simple, high-converting signup form that captures email, preferences, and consent—so you build a list of people who actually want to hear from you.',
      longDescription: {
        opening: 'Most email signups fail at one of two extremes: too simple (just email, no preferences) leads to irrelevant content and unsubscribes; too complex (10 fields) kills conversion. The result is either low engagement or low signups.',
        solution: 'This template finds the right balance: Email capture for the essential contact, optional First Name for personalization, Interest Selection for relevant content, Frequency Preference for respectful communication, and explicit Consent for GDPR compliance. Simple enough for high conversion, rich enough for segmentation.',
        outcome: 'Build an email list of genuinely interested subscribers. Send relevant content based on stated interests. Respect frequency preferences to reduce unsubscribes. Maintain GDPR compliance with documented consent. Higher open rates because content matches expectations.',
      },
      useCases: [
        {
          title: 'Blog Newsletter Signup',
          icon: '📝',
          industry: 'Content / Media',
          scenario: 'Visitors to your blog want to subscribe for new content. Interest selection enables topic-based emails.',
          painPoint: 'Generic newsletter blasts lead to high unsubscribe rates.',
          keyFields: ['Email Address', 'What topics interest you?', 'How often would you like to hear from us?'],
          exampleOrganization: 'A content site building an engaged subscriber base.',
        },
        {
          title: 'Product Updates List',
          icon: '🚀',
          industry: 'Technology / SaaS',
          scenario: 'Users opt in for product updates, feature announcements, and tips. Preference capture prevents notification fatigue.',
          painPoint: 'Users miss important updates or feel spammed by too many emails.',
          keyFields: ['Email Address', 'Interests', 'Frequency'],
          exampleOrganization: 'A SaaS company with 10,000+ users wanting product updates.',
        },
        {
          title: 'E-commerce Marketing List',
          icon: '🛒',
          industry: 'E-commerce / Retail',
          scenario: 'Shoppers opt in for promotions, new arrivals, and sales. Interest-based segmentation increases conversion.',
          painPoint: 'Email blasts have low open rates because content isn\'t relevant.',
          keyFields: ['Email Address', 'First Name', 'Interests (Promotions, New Arrivals)', 'Consent'],
          exampleOrganization: 'An online retailer building a marketing list for targeted campaigns.',
        },
        {
          title: 'Lead Magnet Delivery',
          icon: '🎁',
          industry: 'Any',
          scenario: 'Visitors exchange email for a downloadable resource. The form captures email and consent for follow-up.',
          painPoint: 'Lead magnets capture email but no consent for ongoing communication.',
          keyFields: ['Email Address', 'I agree to receive marketing emails'],
          exampleOrganization: 'A company using ebooks, guides, or tools as lead magnets.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Lead Magnet Delivery',
          description: 'Include a hidden field for which lead magnet they\'re requesting. Trigger appropriate download.',
          fieldSuggestion: 'hidden',
          difficulty: 'easy',
        },
        {
          title: 'Enable Double Opt-In',
          description: 'Send confirmation email requiring click before adding to main list. Improves deliverability.',
          difficulty: 'medium',
        },
        {
          title: 'Include Source Tracking',
          description: 'Add hidden field for signup source (blog post, landing page, popup). Measure content performance.',
          fieldSuggestion: 'hidden',
          difficulty: 'easy',
        },
        {
          title: 'Add Welcome Sequence',
          description: 'Trigger automated welcome email series introducing your brand and best content.',
          difficulty: 'medium',
        },
        {
          title: 'Enable SMS Option',
          description: 'Add phone field with consent for SMS updates. Build multi-channel subscriber list.',
          fieldSuggestion: 'phone',
          difficulty: 'easy',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-service-sync',
          title: 'Add to Email List',
          description: 'Push new subscriber to email service (Mailchimp, ConvertKit, etc.) with interest tags.',
          trigger: 'On form submission',
          benefits: ['Automated list building', 'Proper segmentation'],
        },
        {
          workflowType: 'welcome-email',
          title: 'Send Welcome Email',
          description: 'Immediately send welcome email with promised content and introduction to what they\'ll receive.',
          trigger: 'On form submission',
          benefits: ['Immediate engagement', 'Expectation setting'],
        },
        {
          workflowType: 'double-opt-in',
          title: 'Send Confirmation Email',
          description: 'Send confirmation link email for double opt-in. Only add to main list after confirmation.',
          trigger: 'On form submission',
          benefits: ['Better deliverability', 'GDPR compliance'],
        },
        {
          workflowType: 'lead-magnet-delivery',
          title: 'Deliver Lead Magnet',
          description: 'Email the promised download link or resource immediately after signup.',
          trigger: 'On form submission',
          benefits: ['Instant value delivery', 'Trust building'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Interests as array enables tag-based segmentation in email service',
          'Frequency preference as enum supports different cadence workflows',
          'Consent boolean with required validation ensures GDPR compliance',
        ],
        integrationHints: [
          'Webhook to email service (Mailchimp, ConvertKit, Klaviyo) for list sync',
          'POST to CRM to create/update contact with email preferences',
          'Connect to double opt-in service for confirmation workflow',
        ],
        mongoDBConsiderations: [
          'Unique index on {email: 1} for duplicate prevention',
          'Index on {interests: 1} for segment-based queries',
          'Index on {createdAt: -1} for subscriber growth tracking',
        ],
      },
      seo: {
        metaTitle: 'Email Newsletter Signup Form Template | NetPad',
        metaDescription: 'Free email signup form with preference capture and GDPR consent. Build an engaged email list with relevant subscribers.',
        keywords: [
          'email signup form',
          'newsletter signup',
          'email subscription form',
          'mailing list form',
          'email capture form',
          'newsletter form template',
          'email list signup',
        ],
        ogDescription: 'Build an email list of people who actually want to hear from you. This form captures preferences and consent—so your emails get opened.',
      },
      socialProofAngles: [
        'Higher email open rates',
        'Lower unsubscribe rates',
        'Better email deliverability',
        'GDPR-compliant list building',
      ],
    },
  }),

  // 5. Webinar Registration
  createTemplate({
    id: 'webinar-registration',
    name: 'Webinar Registration',
    shortDescription: 'Register for online webinars',
    fullDescription: 'Capture registrations for live and on-demand webinars. Includes lead qualification questions and reminder preferences.',
    category: 'marketing-research',
    icon: 'Video',
    complexity: 'simple',
    estimatedTime: 3,
    displayOrder: 5,
    tags: ['webinar', 'registration', 'online event', 'lead'],
    useCases: [
      'Live webinars',
      'On-demand content',
      'Product demos',
      'Educational sessions',
    ],
    features: [
      'Registration capture',
      'Reminder preferences',
      'Lead qualification',
      'Question submission',
    ],
    fieldConfigs: [
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      textField('company', 'Company', { fieldWidth: 'half' }),
      textField('jobTitle', 'Job Title', { fieldWidth: 'half' }),
      selectField('companySize', 'Company Size', [
        '1-10',
        '11-50',
        '51-200',
        '201-500',
        '500+',
      ]),
      selectField('role', 'Your Role', [
        'Individual Contributor',
        'Manager',
        'Director',
        'VP/Executive',
        'C-Suite',
        'Consultant',
        'Student',
      ]),
      multiSelectField('reminders', 'Reminder Preferences', [
        'Email 1 day before',
        'Email 1 hour before',
        'SMS reminder',
        'Calendar invite',
      ]),
      textareaField('questions', 'Questions for the presenter (optional)', {
        placeholder: 'Submit questions you\'d like addressed during the webinar...',
      }),
      yesNoField('marketingConsent', 'I agree to receive follow-up emails about related content'),
    ],
    enhanced: {
      headline: 'Convert Webinar Registrations into Qualified Leads',
      subheadline: 'Capture registrant details, qualify leads with company data, and collect questions upfront—so your webinars generate pipeline, not just attendees.',
      longDescription: {
        opening: 'Webinars are one of the most effective B2B lead generation channels, but many underperform. Generic registration forms capture email but no qualification data. Presenters can\'t prepare for audience questions. Follow-up emails are generic because you don\'t know who attended.',
        solution: 'This template goes beyond basic registration: Company and Job Title provide lead qualification, Company Size and Role enable lead scoring, Reminder Preferences reduce no-shows, and pre-submitted Questions help presenters prepare relevant content. Marketing consent enables nurture campaigns.',
        outcome: 'Higher show rates from personalized reminders. Better webinar content because you know who\'s attending and their questions. Qualified leads ready for sales follow-up. Marketing has consent for ongoing nurture. Webinars become a predictable pipeline source.',
      },
      useCases: [
        {
          title: 'B2B Thought Leadership',
          icon: '🎓',
          industry: 'Technology / Professional Services',
          scenario: 'You host webinars on industry topics to build brand authority and generate leads. Registration needs to capture qualification data.',
          painPoint: 'Webinars attract attendees but sales doesn\'t know which are qualified leads.',
          keyFields: ['Company', 'Job Title', 'Company Size', 'Your Role'],
          exampleOrganization: 'A B2B company running monthly thought leadership webinars.',
        },
        {
          title: 'Product Demo Webinars',
          icon: '🖥️',
          industry: 'Technology / SaaS',
          scenario: 'Live product demos for prospects. You need to know their role and company to tailor the demo.',
          painPoint: 'Demo content doesn\'t match audience needs; high dropout during webinar.',
          keyFields: ['Company', 'Company Size', 'Questions for the presenter'],
          exampleOrganization: 'A SaaS company running weekly product demo webinars.',
        },
        {
          title: 'Educational Series',
          icon: '📚',
          industry: 'Education / Training',
          scenario: 'Multi-part educational webinar series. Track who registered for which sessions and their learning goals.',
          painPoint: 'No insight into attendee skill levels or learning objectives.',
          keyFields: ['First Name', 'Last Name', 'Email', 'Your Role', 'Questions'],
          exampleOrganization: 'An organization running a 4-part certification prep series.',
        },
        {
          title: 'Partner Enablement',
          icon: '🤝',
          industry: 'Channel Sales',
          scenario: 'Training webinars for partners. Track partner companies and roles for enablement metrics.',
          painPoint: 'Can\'t track partner enablement progress or identify gaps.',
          keyFields: ['Company', 'Job Title', 'Reminder Preferences'],
          exampleOrganization: 'A company with 100+ partners needing ongoing enablement.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Time Zone Selection',
          description: 'For global webinars, capture timezone to offer the right session time.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Enable Recording Request',
          description: 'Ask if they want the recording if they can\'t attend live. Increases registrations.',
          fieldSuggestion: 'checkbox',
          difficulty: 'easy',
        },
        {
          title: 'Add Lead Scoring Fields',
          description: 'Include budget, timeline, or decision-maker status for more precise lead scoring.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Build Attendance Tracking',
          description: 'Track who actually attended vs. registered. Feed to CRM for accurate lead scoring.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Post-Webinar Survey',
          description: 'Trigger satisfaction survey after webinar ends. Capture feedback while fresh.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'email-confirmation',
          title: 'Send Registration Confirmation',
          description: 'Email registrant with webinar details, calendar invite, and add-to-calendar links.',
          trigger: 'On form submission',
          benefits: ['Calendar blocked', 'Clear expectations'],
        },
        {
          workflowType: 'reminder-sequence',
          title: 'Send Reminder Emails',
          description: 'Based on preferences, send reminders 1 day and 1 hour before with join link.',
          trigger: 'Scheduled based on webinar date and reminders field',
          benefits: ['Higher attendance', 'Lower no-shows'],
        },
        {
          workflowType: 'crm-lead-creation',
          title: 'Create Lead in CRM',
          description: 'Push registration to CRM with company data and lead score. Track webinar source.',
          trigger: 'On form submission',
          benefits: ['Lead tracking', 'Source attribution'],
        },
        {
          workflowType: 'post-webinar-follow-up',
          title: 'Send Recording and Follow-Up',
          description: 'After webinar, send recording, slides, and relevant call-to-action based on attendance.',
          trigger: 'After webinar end time',
          benefits: ['Content delivery', 'Lead nurture'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Company size and role as enums enable lead scoring logic',
          'Reminders as array allows flexible reminder configuration',
          'Questions field captures pre-webinar engagement',
        ],
        integrationHints: [
          'Webhook to webinar platform (Zoom, GoToWebinar) for attendee sync',
          'POST to CRM for lead creation with webinar source',
          'Connect to calendar API for calendar invite generation',
        ],
        mongoDBConsiderations: [
          'Index on {email: 1} for duplicate prevention',
          'Index on {companySize: 1, role: 1} for lead scoring queries',
          'Index on {createdAt: -1} for registration trend analysis',
        ],
      },
      seo: {
        metaTitle: 'Webinar Registration Form Template | NetPad',
        metaDescription: 'Free webinar registration form with lead qualification, reminder preferences, and question collection. Convert registrations into qualified leads.',
        keywords: [
          'webinar registration form',
          'webinar signup form',
          'online event registration',
          'webinar lead capture',
          'virtual event form',
          'webinar registration template',
          'live event signup',
        ],
        ogDescription: 'Fill webinar seats with qualified leads. This registration form captures company data, role info, and questions—so webinars generate pipeline.',
      },
      socialProofAngles: [
        'Higher webinar attendance rates',
        'Better lead qualification',
        'More engaging webinar content',
        'Stronger post-webinar pipeline',
      ],
    },
  }),

  // 6. Contest Entry Form
  createTemplate({
    id: 'contest-entry',
    name: 'Contest Entry Form',
    shortDescription: 'Enter contests and giveaways',
    fullDescription: 'Capture contest and giveaway entries with verification and legal compliance. Perfect for marketing promotions and engagement campaigns.',
    category: 'marketing-research',
    icon: 'Trophy',
    complexity: 'simple',
    estimatedTime: 3,
    displayOrder: 6,
    tags: ['contest', 'giveaway', 'sweepstakes', 'promotion'],
    useCases: [
      'Social media contests',
      'Product giveaways',
      'Promotional campaigns',
      'Brand engagement',
    ],
    features: [
      'Entry capture',
      'Age verification',
      'Legal compliance',
      'Bonus entry options',
    ],
    fieldConfigs: [
      textField('firstName', 'First Name', { required: true, fieldWidth: 'half' }),
      textField('lastName', 'Last Name', { required: true, fieldWidth: 'half' }),
      emailField('email', 'Email Address', { required: true }),
      phoneField('phone', 'Phone Number'),
      dateField('dateOfBirth', 'Date of Birth', { required: true }),
      selectField('country', 'Country', [
        'United States',
        'Canada',
        'United Kingdom',
        'Australia',
        'Other',
      ], { required: true }),
      textField('state', 'State/Province'),
      selectField('howHeard', 'How did you hear about this contest?', [
        'Social Media',
        'Email',
        'Friend/Family',
        'Website',
        'Advertisement',
        'Other',
      ]),
      multiSelectField('bonusEntries', 'Earn bonus entries by:', [
        'Follow us on Instagram',
        'Follow us on Twitter',
        'Share this contest',
        'Tag a friend',
        'Subscribe to newsletter',
      ]),
      yesNoField('ageConfirm', 'I confirm I am 18 years or older', { required: true }),
      yesNoField('rulesAccept', 'I have read and agree to the official rules', { required: true }),
      yesNoField('marketingConsent', 'I agree to receive marketing communications'),
    ],
    enhanced: {
      headline: 'Run Promotions That Build Your List and Brand',
      subheadline: 'Capture contest entries with age verification, legal compliance, and marketing consent—so giveaways grow your audience safely and legally.',
      longDescription: {
        opening: 'Contests and giveaways drive engagement, but legal compliance is tricky. Age verification is often required, official rules acceptance is mandatory, and capturing marketing consent determines the long-term value of entries. Many contests generate entries but few subscribers.',
        solution: 'This template handles promotion compliance: Date of Birth for age verification, Country/State for eligibility, Rules Acceptance for legal protection, Marketing Consent for list building, and Bonus Entry options for social amplification. How Heard tracking measures promotional channel effectiveness.',
        outcome: 'Run promotions confidently with proper compliance. Build your email list with consenting subscribers, not just contest entrants. Amplify reach through structured bonus entry mechanics. Measure which channels drive the most entries.',
      },
      useCases: [
        {
          title: 'Social Media Giveaway',
          icon: '📱',
          industry: 'Any',
          scenario: 'A product giveaway promoted on social media. Bonus entries for follows, shares, and tags drive viral reach.',
          painPoint: 'Giveaways generate entries but no lasting list growth; legal compliance is unclear.',
          keyFields: ['Email Address', 'Date of Birth', 'Bonus entry options', 'I agree to official rules'],
          exampleOrganization: 'A brand running monthly Instagram giveaways to grow followers.',
        },
        {
          title: 'Product Launch Sweepstakes',
          icon: '🎁',
          industry: 'Consumer Products',
          scenario: 'Sweepstakes tied to a product launch generate buzz and capture leads. Prize value attracts broad participation.',
          painPoint: 'Launches lack engagement mechanism; difficult to measure promotional reach.',
          keyFields: ['First Name', 'Last Name', 'Email', 'Country', 'Age confirmation'],
          exampleOrganization: 'A consumer brand launching a new product with a $5,000 prize sweepstakes.',
        },
        {
          title: 'Loyalty Program Reward',
          icon: '⭐',
          industry: 'Retail / E-commerce',
          scenario: 'Existing customers enter contests for exclusive prizes. Rewards loyalty while collecting updated contact information.',
          painPoint: 'Loyalty programs lack engagement; customer data becomes stale.',
          keyFields: ['Email', 'Phone', 'Marketing consent', 'How did you hear about this contest?'],
          exampleOrganization: 'A retailer running quarterly drawings for loyalty program members.',
        },
        {
          title: 'User-Generated Content Contest',
          icon: '📸',
          industry: 'Any',
          scenario: 'Contests requiring photo or video submissions generate authentic content while building community.',
          painPoint: 'UGC campaigns lack proper media rights and release documentation.',
          keyFields: ['Email', 'Rules acceptance', 'Bonus entries (Share, Tag)', 'Marketing consent'],
          exampleOrganization: 'A brand running a photo contest with entries shared as UGC.',
        },
      ],
      customizationTips: [
        {
          title: 'Add File Upload for UGC',
          description: 'For photo or video contests, add file upload field with media release in rules acceptance.',
          fieldSuggestion: 'file',
          difficulty: 'easy',
        },
        {
          title: 'Enable Referral Tracking',
          description: 'Give each entrant a unique referral link. Track bonus entries from their referrals.',
          difficulty: 'advanced',
        },
        {
          title: 'Add Prize Selection',
          description: 'If offering prize choices, let entrants select their preferred prize option.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Build Entry Validation',
          description: 'Verify age eligibility (18+) and location eligibility in real-time before accepting entry.',
          difficulty: 'medium',
        },
        {
          title: 'Create Random Winner Selection',
          description: 'Build workflow to randomly select winners from eligible entries on contest end date.',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'entry-confirmation',
          title: 'Confirm Entry',
          description: 'Email confirmation of entry with contest details and drawing date.',
          trigger: 'On form submission',
          benefits: ['Entry confirmation', 'Engagement maintained'],
        },
        {
          workflowType: 'bonus-entry-tracking',
          title: 'Track Bonus Entries',
          description: 'Verify social actions and add bonus entries to entrant\'s record.',
          trigger: 'On social action completion',
          benefits: ['Viral amplification', 'Verified actions'],
        },
        {
          workflowType: 'list-sync',
          title: 'Add to Marketing List',
          description: 'When marketing consent is given, add entrant to appropriate email list with source tag.',
          trigger: 'On form submission where marketingConsent = true',
          benefits: ['List growth', 'Consent documented'],
        },
        {
          workflowType: 'winner-selection',
          title: 'Select and Notify Winners',
          description: 'On contest end date, randomly select winner(s) from eligible entries and send notification.',
          trigger: 'Scheduled on contest end date',
          benefits: ['Fair selection', 'Automated notification'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Date of birth enables precise age eligibility verification',
          'Bonus entries as array tracks which actions were completed',
          'Country/state fields enable regional eligibility filtering',
        ],
        integrationHints: [
          'Webhook to sweepstakes platform (Gleam, Rafflecopter) for advanced management',
          'POST to email service with marketing consent flag',
          'Connect to social APIs to verify bonus entry actions',
        ],
        mongoDBConsiderations: [
          'Unique index on {email: 1} for duplicate entry prevention',
          'Index on {country: 1, ageConfirm: 1} for eligibility filtering',
          'Index on {createdAt: -1} for entry timeline analysis',
        ],
      },
      seo: {
        metaTitle: 'Contest Entry Form Template | NetPad',
        metaDescription: 'Free contest and giveaway entry form with age verification, legal compliance, and bonus entry tracking. Run promotions that build your list.',
        keywords: [
          'contest entry form',
          'giveaway form',
          'sweepstakes entry',
          'contest registration',
          'promotion entry form',
          'giveaway signup',
          'sweepstakes form',
        ],
        ogDescription: 'Run giveaways the right way. This form handles age verification, rules acceptance, and marketing consent—so contests grow your list legally.',
      },
      socialProofAngles: [
        'Compliant promotion management',
        'List growth from contests',
        'Viral reach from bonus entries',
        'Clear legal protection',
      ],
    },
  }),

  // 7. User Research Screener
  createTemplate({
    id: 'user-research-screener',
    name: 'User Research Screener',
    shortDescription: 'Screen participants for user research',
    fullDescription: 'Qualify participants for user research studies. Screens for demographics, experience levels, and availability to find ideal research candidates.',
    category: 'marketing-research',
    icon: 'Users',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 7,
    tags: ['research', 'user research', 'screener', 'participants', 'ux'],
    useCases: [
      'Usability testing recruitment',
      'Focus group screening',
      'User interview recruitment',
      'Beta tester selection',
    ],
    features: [
      'Demographics collection',
      'Experience level screening',
      'Technology usage assessment',
      'Availability scheduling',
    ],
    fieldConfigs: [
      sectionHeader('contact', 'Contact Information'),
      textField('name', 'Full Name', { required: true }),
      emailField('email', 'Email Address', { required: true, fieldWidth: 'half' }),
      phoneField('phone', 'Phone Number', { required: true, fieldWidth: 'half' }),
      selectField('timezone', 'Timezone', [
        'Eastern',
        'Central',
        'Mountain',
        'Pacific',
        'Other US',
        'International',
      ], { required: true }),
      sectionHeader('demographics', 'Demographics'),
      selectField('age', 'Age Range', [
        '18-24',
        '25-34',
        '35-44',
        '45-54',
        '55-64',
        '65+',
      ], { required: true }),
      selectField('gender', 'Gender', [
        'Male',
        'Female',
        'Non-binary',
        'Prefer not to say',
      ]),
      selectField('occupation', 'Occupation', [
        'Professional/Manager',
        'Technical/IT',
        'Sales/Marketing',
        'Administrative',
        'Student',
        'Retired',
        'Other',
      ]),
      sectionHeader('experience', 'Relevant Experience'),
      selectField('productUsage', 'Do you currently use [Product Category]?', [
        'Yes, daily',
        'Yes, weekly',
        'Yes, occasionally',
        'No, but I have in the past',
        'No, never',
      ], { required: true }),
      multiSelectField('toolsUsed', 'Which similar tools have you used?', [
        'Tool A',
        'Tool B',
        'Tool C',
        'Tool D',
        'None of these',
      ]),
      selectField('techComfort', 'How comfortable are you with technology?', [
        'Very comfortable - I\'m an early adopter',
        'Comfortable - I use tech daily',
        'Somewhat comfortable',
        'Not very comfortable',
      ], { required: true }),
      sectionHeader('availability', 'Availability'),
      multiSelectField('availableDays', 'Which days are you typically available?', [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ]),
      multiSelectField('availableTimes', 'What times work best?', [
        'Morning (9am-12pm)',
        'Afternoon (12pm-5pm)',
        'Evening (5pm-8pm)',
      ]),
      selectField('sessionLength', 'How long can you participate?', [
        '30 minutes',
        '60 minutes',
        '90 minutes',
        '2+ hours',
      ]),
      sectionHeader('final', 'Final Questions'),
      yesNoField('participatedBefore', 'Have you participated in research studies before?'),
      yesNoField('employedByCompetitor', 'Are you employed by a company in our industry?'),
      textareaField('additionalInfo', 'Anything else we should know?'),
    ],
    enhanced: {
      headline: 'Find the Right Research Participants, Fast',
      subheadline: 'Screen candidates for demographics, experience, technology comfort, and availability—so your research studies include participants who match your target profile.',
      longDescription: {
        opening: 'Bad research participants waste time and money. Usability tests with non-target users produce misleading insights. Focus groups with the wrong demographics skew findings. Without proper screening, research quality suffers.',
        solution: 'This template screens for research fit: Demographics ensure target market alignment, Product Usage confirms relevant experience, Tech Comfort matches study requirements, Availability filters for scheduling, and Disqualifiers (competitor employees, past participation) maintain study integrity. Timezone capture enables global research.',
        outcome: 'Research studies include only qualified participants. Usability tests reveal actual user behavior. Focus groups represent your target market. Findings are actionable because they come from the right people. Recruiting becomes efficient instead of hit-or-miss.',
      },
      useCases: [
        {
          title: 'Usability Testing Recruitment',
          icon: '🧪',
          industry: 'Technology / UX',
          scenario: 'Recruit participants for moderated or unmoderated usability tests. Screen for product experience and tech comfort.',
          painPoint: 'Tests include wrong users; insights don\'t represent target market behavior.',
          keyFields: ['Age Range', 'Do you currently use [Product]?', 'Tech comfort level', 'Available days and times'],
          exampleOrganization: 'A product team running monthly usability tests.',
        },
        {
          title: 'Focus Group Screening',
          icon: '👥',
          industry: 'Market Research',
          scenario: 'Qualify participants for in-person or virtual focus groups. Demographics and experience matter.',
          painPoint: 'Focus groups don\'t represent target demographic; findings are skewed.',
          keyFields: ['Demographics', 'Occupation', 'Which tools have you used?', 'Session length availability'],
          exampleOrganization: 'A research agency recruiting for client focus groups.',
        },
        {
          title: 'Beta Tester Selection',
          icon: '🚀',
          industry: 'Technology / SaaS',
          scenario: 'Select beta testers who match your target user profile and have time to provide feedback.',
          painPoint: 'Beta testers don\'t match target users; feedback isn\'t representative.',
          keyFields: ['Product usage experience', 'Tech comfort', 'Available times', 'Timezone'],
          exampleOrganization: 'A software company recruiting beta testers for new features.',
        },
        {
          title: 'Customer Interview Pool',
          icon: '🎙️',
          industry: 'Any',
          scenario: 'Build a pool of customers willing to participate in interviews. Screen for relevant experience and availability.',
          painPoint: 'No pool of willing interview participants; recruitment is ad-hoc.',
          keyFields: ['Email', 'Phone', 'Have you participated before?', 'Available days'],
          exampleOrganization: 'A customer research team building an ongoing interview panel.',
        },
      ],
      customizationTips: [
        {
          title: 'Add Product-Specific Questions',
          description: 'Replace generic product/tool questions with your actual product and competitor names.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Incentive Preference',
          description: 'Ask preferred incentive type (gift card, Amazon, PayPal) for easier fulfillment.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Add Disqualifying Questions',
          description: 'Include questions that screen out ineligible participants (employees, recent participants, etc.).',
          fieldSuggestion: 'yesNo',
          difficulty: 'easy',
        },
        {
          title: 'Build Auto-Qualification',
          description: 'Score responses automatically and only contact qualified participants.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Calendar Integration',
          description: 'Based on availability, offer calendar slots for scheduling research sessions.',
          difficulty: 'advanced',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'qualification-scoring',
          title: 'Score and Qualify',
          description: 'Calculate qualification score based on responses. Flag top candidates for recruitment.',
          trigger: 'On form submission',
          benefits: ['Efficient screening', 'Top candidates identified'],
        },
        {
          workflowType: 'email-notification',
          title: 'Notify Research Team',
          description: 'Alert research team when qualified candidate submits. Include profile summary.',
          trigger: 'On form submission where qualified = true',
          benefits: ['Fast recruitment', 'No missed candidates'],
        },
        {
          workflowType: 'thank-you-email',
          title: 'Send Confirmation',
          description: 'Thank candidate for interest with next steps if qualified or polite rejection if not.',
          trigger: 'On form submission',
          benefits: ['Professional experience', 'Clear expectations'],
        },
        {
          workflowType: 'participant-database',
          title: 'Add to Participant Panel',
          description: 'Store qualified participants in database for future study recruitment.',
          trigger: 'On qualification',
          benefits: ['Growing participant pool', 'Faster future recruiting'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Demographics as enums enable quota management and sampling',
          'Availability stored as arrays for flexible scheduling matching',
          'Disqualifier questions (competitor, past participation) protect study integrity',
        ],
        integrationHints: [
          'Webhook to user research platform (UserTesting, dscout) for panel sync',
          'POST to calendar API to offer available slots based on responses',
          'Connect to incentive platform for automated payment on completion',
        ],
        mongoDBConsiderations: [
          'Index on {productUsage: 1, techComfort: 1} for participant matching',
          'Index on {timezone: 1, availableTimes: 1} for scheduling queries',
          'Index on {email: 1} for duplicate and past participation check',
        ],
      },
      seo: {
        metaTitle: 'User Research Screener Form Template | NetPad',
        metaDescription: 'Free research screener form with demographics, experience levels, and availability capture. Find qualified research participants fast.',
        keywords: [
          'user research screener',
          'participant screening form',
          'research recruitment form',
          'usability testing screener',
          'focus group screener',
          'UX research form',
          'beta tester screening',
        ],
        ogDescription: 'Stop wasting research time on wrong participants. This screener captures demographics, experience, and availability—so studies include the right people.',
      },
      socialProofAngles: [
        'Higher quality research insights',
        'Faster participant recruitment',
        'Better representation of target users',
        'More efficient research operations',
      ],
    },
  }),

  // 8. Brand Awareness Survey
  createTemplate({
    id: 'brand-awareness-survey',
    name: 'Brand Awareness Survey',
    shortDescription: 'Measure brand recognition and perception',
    fullDescription: 'Assess brand awareness, recall, and perception in your target market. Includes unaided and aided awareness questions.',
    category: 'marketing-research',
    icon: 'Sparkles',
    complexity: 'moderate',
    estimatedTime: 6,
    displayOrder: 8,
    tags: ['brand', 'awareness', 'perception', 'research', 'marketing'],
    useCases: [
      'Brand health tracking',
      'Campaign effectiveness',
      'Competitive positioning',
      'Market entry research',
    ],
    features: [
      'Unaided recall',
      'Aided awareness',
      'Brand associations',
      'Competitive comparison',
    ],
    fieldConfigs: [
      sectionHeader('unaided', 'Unaided Awareness'),
      textareaField('topOfMind', 'When you think of [product category], what brands come to mind?', {
        required: true,
        placeholder: 'List all brands you can think of...',
      }),
      sectionHeader('aided', 'Aided Awareness'),
      multiSelectField('brandsRecognized', 'Which of these brands have you heard of?', [
        'Brand A',
        'Brand B',
        'Brand C',
        'Brand D',
        'Brand E',
        'None of these',
      ], { required: true }),
      multiSelectField('brandsConsidered', 'Which would you consider using?', [
        'Brand A',
        'Brand B',
        'Brand C',
        'Brand D',
        'Brand E',
        'None of these',
      ]),
      selectField('brandUsed', 'Which have you actually used?', [
        'Brand A',
        'Brand B',
        'Brand C',
        'Brand D',
        'Brand E',
        'None',
      ]),
      sectionHeader('perception', 'Brand Perception - [Your Brand]'),
      ratingField('overallOpinion', 'Overall opinion of [Your Brand]'),
      multiSelectField('brandAssociations', 'Which words describe [Your Brand]?', [
        'Innovative',
        'Trustworthy',
        'Premium',
        'Value-focused',
        'Modern',
        'Traditional',
        'Customer-friendly',
        'Professional',
      ]),
      scaleField('qualityPerception', 'Perceived quality level', {
        validation: { min: 1, max: 5, lowLabel: 'Low quality', highLabel: 'High quality' },
      }),
      scaleField('valuePerception', 'Perceived value for money', {
        validation: { min: 1, max: 5, lowLabel: 'Poor value', highLabel: 'Excellent value' },
      }),
      sectionHeader('exposure', 'Brand Exposure'),
      multiSelectField('whereEncountered', 'Where have you seen/heard about [Your Brand]?', [
        'TV advertising',
        'Social media',
        'Online ads',
        'Friend/family recommendation',
        'In-store',
        'Search engine',
        'News/articles',
        'Haven\'t encountered',
      ]),
      selectField('adRecall', 'Have you seen any [Your Brand] advertising recently?', [
        'Yes, within the past week',
        'Yes, within the past month',
        'Yes, but not recently',
        'No',
        'Not sure',
      ]),
      textareaField('adDescription', 'If yes, what do you remember about it?'),
    ],
    enhanced: {
      headline: 'Measure How Your Brand Stacks Up in the Market',
      subheadline: 'Capture unaided and aided awareness, brand perception, and competitive positioning—so marketing investments are guided by actual market data.',
      longDescription: {
        opening: 'Brand investments are hard to measure. You spend on advertising, content, and PR but don\'t know if awareness is growing, how perception compares to competitors, or which brand attributes resonate. Marketing budgets are allocated on intuition.',
        solution: 'This template implements brand research methodology: Unaided Awareness (top-of-mind recall), Aided Awareness (recognition from a list), Brand Perception (quality, value associations), and Advertising Recall (campaign effectiveness). Competitive comparison provides context for your brand\'s position.',
        outcome: 'Track brand awareness over time with consistent methodology. Understand competitive positioning from customer perspective. Measure advertising effectiveness through recall. Make marketing investment decisions based on actual awareness and perception data.',
      },
      useCases: [
        {
          title: 'Pre/Post Campaign Measurement',
          icon: '📈',
          industry: 'Any',
          scenario: 'Measure brand awareness before and after major campaigns to quantify marketing impact.',
          painPoint: 'Can\'t prove campaign ROI; brand awareness assumed but not measured.',
          keyFields: ['Unaided awareness', 'Aided awareness', 'Ad recall', 'What do you remember?'],
          exampleOrganization: 'A company investing $500K+ in a brand campaign wanting measurement.',
        },
        {
          title: 'Competitive Positioning Study',
          icon: '🏆',
          industry: 'Any',
          scenario: 'Understand how your brand is perceived relative to competitors. Identify positioning opportunities.',
          painPoint: 'Competitive positioning is based on assumptions, not customer perception.',
          keyFields: ['Brands recognized', 'Brands considered', 'Brand actually used', 'Brand associations'],
          exampleOrganization: 'A brand competing with 5+ alternatives needing positioning data.',
        },
        {
          title: 'Quarterly Brand Health Check',
          icon: '💚',
          industry: 'Consumer / B2B',
          scenario: 'Regular tracking of brand awareness and perception to identify trends and address issues.',
          painPoint: 'No early warning system for brand perception decline.',
          keyFields: ['Overall opinion', 'Quality perception', 'Value perception', 'Where have you encountered brand?'],
          exampleOrganization: 'A brand running quarterly tracking studies across target markets.',
        },
        {
          title: 'Market Entry Assessment',
          icon: '🚪',
          industry: 'Any',
          scenario: 'Assess brand awareness in a new market before and during market entry.',
          painPoint: 'Entering new markets blind to current awareness baseline.',
          keyFields: ['Top-of-mind brands', 'Brands heard of', 'Brands would consider', 'Where have you seen brands?'],
          exampleOrganization: 'A company expanding into a new geographic or demographic market.',
        },
      ],
      customizationTips: [
        {
          title: 'Customize Brand Lists',
          description: 'Replace placeholder brands with your actual brand and real competitors.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Add Demographic Questions',
          description: 'Include age, location, or other demographics for segment-specific analysis.',
          fieldSuggestion: 'select',
          difficulty: 'easy',
        },
        {
          title: 'Include Purchase Intent',
          description: 'Add likelihood to purchase or switch questions for predictive insights.',
          fieldSuggestion: 'scale',
          difficulty: 'easy',
        },
        {
          title: 'Build Tracking Dashboard',
          description: 'Create a dashboard tracking key metrics over time with trend visualization.',
          difficulty: 'medium',
        },
        {
          title: 'Enable Competitive Benchmarking',
          description: 'Add competitor-specific perception questions for side-by-side comparison.',
          fieldSuggestion: 'rating',
          difficulty: 'medium',
        },
      ],
      workflowPairings: [
        {
          workflowType: 'data-export',
          title: 'Export to Analytics',
          description: 'Push responses to analytics platform for visualization and statistical analysis.',
          trigger: 'On form submission',
          benefits: ['Professional analysis', 'Trend visualization'],
        },
        {
          workflowType: 'summary-report',
          title: 'Generate Brand Report',
          description: 'Weekly or monthly automated summary of key brand metrics for marketing team.',
          trigger: 'Scheduled weekly/monthly',
          benefits: ['Regular insights', 'Trend monitoring'],
        },
        {
          workflowType: 'alert-on-change',
          title: 'Alert on Significant Changes',
          description: 'Notify marketing when awareness or perception metrics change significantly.',
          trigger: 'When metric variance exceeds threshold',
          benefits: ['Early warning', 'Rapid response'],
        },
        {
          workflowType: 'incentive-fulfillment',
          title: 'Send Survey Incentive',
          description: 'If offering incentives, automatically process gift card or sweepstakes entry.',
          trigger: 'On form submission',
          benefits: ['Higher completion', 'Better data quality'],
        },
      ],
      developerNotes: {
        schemaHighlights: [
          'Unaided awareness as text captures top-of-mind without prompting',
          'Aided awareness as multi-select enables funnel analysis (aware → consider → use)',
          'Brand associations as multi-select enable attribute mapping',
        ],
        integrationHints: [
          'Webhook to research platform (Qualtrics, Suzy) for panel management',
          'POST to BI tool (Tableau, Looker) for dashboard visualization',
          'Connect to incentive platform for automated reward delivery',
        ],
        mongoDBConsiderations: [
          'Index on {brandsRecognized: 1} for aided awareness calculations',
          'Index on {brandUsed: 1} for usage share analysis',
          'Text index on topOfMind for unaided awareness theme analysis',
        ],
      },
      seo: {
        metaTitle: 'Brand Awareness Survey Template | NetPad',
        metaDescription: 'Free brand awareness survey with unaided and aided recall, perception measurement, and competitive comparison. Track brand health over time.',
        keywords: [
          'brand awareness survey',
          'brand perception survey',
          'brand health survey',
          'brand tracking survey',
          'competitive brand survey',
          'brand recognition form',
          'brand awareness measurement',
        ],
        ogDescription: 'Stop guessing about brand awareness. This survey captures unaided and aided recall, perception, and competitive positioning—so marketing investments are data-driven.',
      },
      socialProofAngles: [
        'Data-driven marketing investment',
        'Measurable campaign impact',
        'Clear competitive positioning',
        'Tracked brand health over time',
      ],
    },
  }),
];
